// Chapter 5 term bank. Morphology first: the parts generate the vocabulary.
// Sources are the standard morphology used throughout the Education Standards
// and the published error-prone abbreviation lists; nothing here is taken from
// a copyrighted textbook.
const SRC_MORPH='Standard medical word-building conventions, as used throughout the NHTSA National EMS Education Standards (2021).';

// [part, kind, meaning, [synonyms]]
const PREFIX=[
  ['a-','prefix','without, absence of',['absence of','without','no']],
  ['an-','prefix','without, absence of',['absence of','without','no']],
  ['brady-','prefix','slow',['slowed','slowly']],
  ['tachy-','prefix','fast, rapid',['rapid','fast','quick']],
  ['dys-','prefix','difficult, painful, abnormal',['difficult','painful','abnormal','labored','labored']],
  ['eu-','prefix','normal, good',['normal','good','well']],
  ['hyper-','prefix','above normal, excessive',['above normal','high','excessive','too much','increased']],
  ['hypo-','prefix','below normal, deficient',['below normal','low','deficient','too little','decreased']],
  ['peri-','prefix','around, surrounding',['around','surrounding','about']],
  ['endo-','prefix','within, inner',['within','inside','inner','internal']],
  ['exo-','prefix','outside, outward',['outside','outward','external']],
  ['epi-','prefix','upon, above, over',['upon','above','over','on top of']],
  ['sub-','prefix','under, below',['under','below','beneath']],
  ['supra-','prefix','above, over',['above','over']],
  ['inter-','prefix','between',['between']],
  ['intra-','prefix','within, inside',['within','inside','into']],
  ['trans-','prefix','across, through',['across','through']],
  ['circum-','prefix','around',['around']],
  ['contra-','prefix','against, opposite',['against','opposite','opposed to']],
  ['anti-','prefix','against',['against','opposing']],
  ['pre-','prefix','before, in front of',['before','prior to','in front of']],
  ['post-','prefix','after, behind',['after','following','behind']],
  ['ante-','prefix','before, in front of',['before','in front of']],
  ['retro-','prefix','backward, behind',['backward','behind','back']],
  ['poly-','prefix','many, much',['many','much','multiple','excessive']],
  ['olig-','prefix','few, scanty',['few','scanty','little','decreased']],
  ['macro-','prefix','large',['large','big','enlarged']],
  ['micro-','prefix','small',['small','tiny']],
  ['mega-','prefix','large, enlarged',['large','enlarged','big']],
  ['neo-','prefix','new',['new']],
  ['pan-','prefix','all, entire',['all','entire','whole']],
  ['para-','prefix','beside, near, abnormal',['beside','near','alongside','abnormal']],
  ['dia-','prefix','through, across, complete',['through','across','complete']],
  ['ec-','prefix','out, outside',['out','outside','away from']],
  ['ex-','prefix','out, away from',['out','away from','outward']],
  ['in-','prefix','in, into, not',['in','into','not']],
  ['de-','prefix','down, from, removal of',['down','removal of','loss of','from']],
  ['re-','prefix','again, back',['again','back']],
  ['syn-','prefix','together, joined',['together','joined','with']],
  ['sym-','prefix','together, joined',['together','joined','with']],
  ['auto-','prefix','self',['self','own']],
  ['iso-','prefix','equal, same',['equal','same','alike']],
  ['hemi-','prefix','half',['half','one side']],
  ['semi-','prefix','half, partial',['half','partial']],
  ['bi-','prefix','two, both',['two','both','double']],
  ['uni-','prefix','one',['one','single']],
  ['mono-','prefix','one, single',['one','single']],
  ['tri-','prefix','three',['three']],
  ['quadri-','prefix','four',['four']],
  ['multi-','prefix','many',['many','multiple']],
  ['nulli-','prefix','none',['none','no','zero']],
  ['primi-','prefix','first',['first']],
  ['ab-','prefix','away from',['away from','from']],
  ['ad-','prefix','toward, near',['toward','to','near']],
  ['dextro-','prefix','right',['right','right-sided']],
  ['sinistro-','prefix','left',['left','left-sided']],
  ['ipsi-','prefix','same side',['same side','same']],
  ['contralateral-','prefix','opposite side',['opposite side','other side']],
  ['normo-','prefix','normal',['normal']],
  ['ortho-','prefix','straight, upright, correct',['straight','upright','correct']]
];

const SUFFIX=[
  ['-itis','suffix','inflammation',['inflammation','inflamed','swelling and irritation']],
  ['-osis','suffix','abnormal condition',['abnormal condition','condition']],
  ['-emia','suffix','blood condition',['blood condition','in the blood','condition of the blood']],
  ['-uria','suffix','urine condition',['urine condition','in the urine','condition of the urine']],
  ['-pnea','suffix','breathing',['breathing','respiration']],
  ['-algia','suffix','pain',['pain','painful']],
  ['-dynia','suffix','pain',['pain','painful']],
  ['-ectomy','suffix','surgical removal',['surgical removal','removal','excision','cutting out']],
  ['-ostomy','suffix','surgical opening',['surgical opening','creating an opening','opening']],
  ['-otomy','suffix','surgical incision',['surgical incision','incision','cutting into']],
  ['-plasty','suffix','surgical repair',['surgical repair','repair','reshaping']],
  ['-pexy','suffix','surgical fixation',['surgical fixation','fixation','securing in place']],
  ['-desis','suffix','surgical fusion',['surgical fusion','fusion','binding together']],
  ['-pathy','suffix','disease',['disease','disorder']],
  ['-megaly','suffix','enlargement',['enlargement','enlarged']],
  ['-sclerosis','suffix','hardening',['hardening','hardened']],
  ['-stenosis','suffix','narrowing',['narrowing','stricture','narrowed']],
  ['-rrhage','suffix','bursting forth, excessive flow',['bursting forth','excessive flow','bleeding']],
  ['-rrhagia','suffix','excessive flow',['excessive flow','bursting forth','heavy bleeding']],
  ['-rrhea','suffix','flow, discharge',['flow','discharge','running']],
  ['-rrhexis','suffix','rupture',['rupture','tearing']],
  ['-plegia','suffix','paralysis',['paralysis','paralyzed','paralysed']],
  ['-paresis','suffix','partial paralysis, weakness',['partial paralysis','weakness','partial weakness']],
  ['-trophy','suffix','development, nourishment',['development','growth','nourishment']],
  ['-plasia','suffix','formation, development',['formation','development','growth']],
  ['-gram','suffix','record, image produced',['record','image','tracing','picture']],
  ['-graphy','suffix','process of recording',['process of recording','recording','imaging']],
  ['-graph','suffix','instrument that records',['instrument that records','recording instrument']],
  ['-scopy','suffix','visual examination',['visual examination','looking into','examination']],
  ['-scope','suffix','instrument for viewing',['instrument for viewing','viewing instrument']],
  ['-metry','suffix','measurement',['measurement','measuring']],
  ['-meter','suffix','instrument that measures',['instrument that measures','measuring instrument']],
  ['-ology','suffix','study of',['study of','the study of']],
  ['-ologist','suffix','specialist in',['specialist','specialist in','one who studies']],
  ['-ism','suffix','condition, state of',['condition','state','state of']],
  ['-ia','suffix','condition of',['condition','condition of','state']],
  ['-ac','suffix','pertaining to',['pertaining to','relating to']],
  ['-al','suffix','pertaining to',['pertaining to','relating to']],
  ['-ar','suffix','pertaining to',['pertaining to','relating to']],
  ['-ic','suffix','pertaining to',['pertaining to','relating to']],
  ['-ous','suffix','pertaining to',['pertaining to','relating to']],
  ['-genic','suffix','producing, causing',['producing','causing','giving rise to']],
  ['-genesis','suffix','formation, origin',['formation','origin','production']],
  ['-lysis','suffix','breakdown, destruction',['breakdown','destruction','separation','dissolving']],
  ['-penia','suffix','deficiency',['deficiency','lack of','too few']],
  ['-cytosis','suffix','increase in cells',['increase in cells','too many cells']],
  ['-oma','suffix','tumour, mass',['tumour','tumor','mass','swelling']],
  ['-phagia','suffix','eating, swallowing',['swallowing','eating']],
  ['-phasia','suffix','speech',['speech','speaking']],
  ['-plasm','suffix','formation, growth',['formation','growth','substance']],
  ['-ptosis','suffix','drooping, downward displacement',['drooping','falling','downward displacement']],
  ['-spasm','suffix','involuntary contraction',['involuntary contraction','sudden contraction','spasm']],
  ['-stasis','suffix','stopping, controlling',['stopping','controlling','standing still']],
  ['-tension','suffix','pressure',['pressure','tension']],
  ['-volemia','suffix','blood volume',['blood volume','volume of blood']],
  ['-centesis','suffix','surgical puncture to remove fluid',['surgical puncture','puncture to remove fluid','tapping']],
  ['-opsy','suffix','view of, examination',['view of','examination','viewing']],
  ['-tripsy','suffix','crushing',['crushing','breaking up']],
  ['-ectasis','suffix','expansion, dilation',['expansion','dilation','stretching']]
];

const ROOT=[
  ['cardi/o','root','heart',['heart','cardiac']],
  ['angi/o','root','vessel',['vessel','blood vessel']],
  ['vas/o','root','vessel, duct',['vessel','duct','blood vessel']],
  ['arteri/o','root','artery',['artery','arterial']],
  ['phleb/o','root','vein',['vein','venous']],
  ['ven/o','root','vein',['vein','venous']],
  ['hem/o','root','blood',['blood']],
  ['hemat/o','root','blood',['blood']],
  ['thromb/o','root','clot',['clot','blood clot','thrombus']],
  ['pneum/o','root','lung, air',['lung','air','lungs']],
  ['pulmon/o','root','lung',['lung','lungs','pulmonary']],
  ['bronch/o','root','airway, bronchus',['bronchus','airway','bronchial tube']],
  ['thorac/o','root','chest',['chest','thorax']],
  ['laryng/o','root','voice box, larynx',['larynx','voice box']],
  ['trache/o','root','windpipe, trachea',['trachea','windpipe']],
  ['rhin/o','root','nose',['nose','nasal']],
  ['ox/i','root','oxygen',['oxygen']],
  ['capn/o','root','carbon dioxide',['carbon dioxide','CO2']],
  ['neur/o','root','nerve',['nerve','nervous','nerves']],
  ['encephal/o','root','brain',['brain']],
  ['cerebr/o','root','cerebrum, brain',['cerebrum','brain']],
  ['mening/o','root','membranes around the brain and cord',['meninges','membranes around the brain']],
  ['myel/o','root','spinal cord, bone marrow',['spinal cord','bone marrow']],
  ['gastr/o','root','stomach',['stomach','gastric']],
  ['enter/o','root','intestine',['intestine','bowel','small intestine']],
  ['col/o','root','colon, large intestine',['colon','large intestine','large bowel']],
  ['hepat/o','root','liver',['liver','hepatic']],
  ['chol/e','root','bile, gall',['bile','gall']],
  ['pancreat/o','root','pancreas',['pancreas']],
  ['nephr/o','root','kidney',['kidney','renal']],
  ['ren/o','root','kidney',['kidney','renal']],
  ['cyst/o','root','bladder, sac',['bladder','sac','urinary bladder']],
  ['ur/o','root','urine, urinary tract',['urine','urinary tract']],
  ['hyster/o','root','uterus',['uterus','womb']],
  ['oste/o','root','bone',['bone','bones']],
  ['arthr/o','root','joint',['joint','joints']],
  ['my/o','root','muscle',['muscle','muscular']],
  ['cost/o','root','rib',['rib','ribs']],
  ['crani/o','root','skull',['skull','cranium']],
  ['cephal/o','root','head',['head']],
  ['derm/o','root','skin',['skin']],
  ['dermat/o','root','skin',['skin']],
  ['cyan/o','root','blue',['blue','bluish']],
  ['erythr/o','root','red',['red']],
  ['leuk/o','root','white',['white']],
  ['melan/o','root','black, dark',['black','dark']],
  ['glyc/o','root','sugar, glucose',['sugar','glucose']],
  ['lip/o','root','fat',['fat','lipid']],
  ['aden/o','root','gland',['gland','glandular']],
  ['carcin/o','root','cancer',['cancer','cancerous']],
  ['path/o','root','disease',['disease','illness']],
  ['pyr/o','root','fever, heat',['fever','heat']],
  ['tox/o','root','poison',['poison','toxin','toxic']],
  ['esthes/i','root','sensation, feeling',['sensation','feeling','sensory']],
  ['aer/o','root','air',['air','gas']],
  ['hydr/o','root','water, fluid',['water','fluid']],
  ['nat/o','root','birth',['birth','born']],
  ['ped/o','root','child',['child','children']],
  ['ger/o','root','old age',['old age','elderly','aging']],
  ['ophthalm/o','root','eye',['eye','ocular']],
  ['ot/o','root','ear',['ear','aural']]
];

// The combining vowel is its own idea, so it is its own card.
const VOWEL=[['/o','vowel','the combining vowel that joins a root to another part',
  ['combining vowel','joining vowel','links a root to the next part']]];

// Whole terms carried because they are irregular, high-frequency, or
// dangerous to confuse. Each decomposes into parts already in the bank.
const TERMS=[
  ['bradycardia','slow heart rate',[['brady','prefix','slow'],['card','root','heart'],['ia','suffix','condition of']],
   ['slow heart rate','abnormally slow heart rate','slow pulse'],true],
  ['tachycardia','fast heart rate',[['tachy','prefix','fast'],['card','root','heart'],['ia','suffix','condition of']],
   ['fast heart rate','rapid heart rate','rapid pulse'],true],
  ['bradypnea','slow breathing',[['brady','prefix','slow'],['pnea','suffix','breathing']],
   ['slow breathing','slow respiratory rate'],true],
  ['tachypnea','rapid breathing',[['tachy','prefix','fast'],['pnea','suffix','breathing']],
   ['fast breathing','rapid breathing','rapid respiratory rate'],true],
  ['apnea','absence of breathing',[['a','prefix','without'],['pnea','suffix','breathing']],
   ['not breathing','absence of breathing','no breathing'],true],
  ['dyspnea','difficult or labored breathing',[['dys','prefix','difficult'],['pnea','suffix','breathing']],
   ['shortness of breath','difficulty breathing','labored breathing','labored breathing'],true],
  ['orthopnea','breathlessness when lying flat',[['ortho','prefix','straight, upright'],['pnea','suffix','breathing']],
   ['breathless lying flat','difficulty breathing when lying down'],true],
  ['hypoxia','too little oxygen in the tissues',[['hyp','prefix','below normal (hypo- before a vowel)'],['ox','root','oxygen'],['ia','suffix','condition of']],
   ['low oxygen','too little oxygen','oxygen deficiency'],true],
  ['hypoxemia','too little oxygen in the blood',[['hyp','prefix','below normal (hypo- before a vowel)'],['ox','root','oxygen'],['emia','suffix','blood condition']],
   ['low blood oxygen','low oxygen in the blood'],true],
  ['hypercapnia','too much carbon dioxide in the blood',[['hyper','prefix','above normal'],['capn','root','carbon dioxide'],['ia','suffix','condition of']],
   ['high carbon dioxide','too much CO2','raised carbon dioxide'],true],
  ['hypoglycemia','low blood sugar',[['hypo','prefix','below normal'],['glyc','root','sugar'],['emia','suffix','blood condition']],
   ['low blood sugar','low blood glucose'],true],
  ['hyperglycemia','high blood sugar',[['hyper','prefix','above normal'],['glyc','root','sugar'],['emia','suffix','blood condition']],
   ['high blood sugar','high blood glucose','raised blood glucose'],true],
  ['hypotension','low blood pressure',[['hypo','prefix','below normal'],['tension','suffix','pressure']],
   ['low blood pressure','low BP'],true],
  ['hypertension','high blood pressure',[['hyper','prefix','above normal'],['tension','suffix','pressure']],
   ['high blood pressure','high BP'],true],
  ['hypovolemia','low circulating blood volume',[['hypo','prefix','below normal'],['volemia','suffix','blood volume']],
   ['low blood volume','low circulating volume','volume depletion'],true],
  ['hemothorax','blood in the chest cavity',[['hemo','root','blood'],['thorax','root','chest']],
   ['blood in the chest','blood in the pleural space'],false],
  ['pneumothorax','air in the chest cavity',[['pneumo','root','air'],['thorax','root','chest']],
   ['air in the chest','collapsed lung','air in the pleural space'],true],
  ['cyanosis','bluish discolouration from poor oxygenation',[['cyan','root','blue'],['osis','suffix','abnormal condition']],
   ['blue discolouration','bluish skin','blue discoloration'],false],
  ['tachyarrhythmia','a fast, irregular heart rhythm',[['tachy','prefix','fast'],['a','prefix','without'],['rrhythm','root','rhythm'],['ia','suffix','condition of']],
   ['fast irregular rhythm','rapid irregular heartbeat'],false],
  ['bradyarrhythmia','a slow, irregular heart rhythm',[['brady','prefix','slow'],['a','prefix','without'],['rrhythm','root','rhythm'],['ia','suffix','condition of']],
   ['slow irregular rhythm','slow irregular heartbeat'],false],
  ['hemorrhage','bursting forth of blood; heavy bleeding',[['hemo','root','blood'],['rrhage','suffix','bursting forth']],
   ['heavy bleeding','severe bleeding','hemorrhage'],true],
  ['hematemesis','vomiting blood',[['hemat','root','blood'],['emesis','suffix','vomiting']],
   ['vomiting blood','blood in vomit'],true],
  ['hemoptysis','coughing up blood',[['hemo','root','blood'],['ptysis','suffix','spitting']],
   ['coughing up blood','blood in sputum'],true],
  ['hematuria','blood in the urine',[['hemat','root','blood'],['uria','suffix','urine condition']],
   ['blood in the urine','blood in urine'],false],
  ['melena','black, tarry stool from digested blood',[],
   ['black tarry stool','digested blood in stool'],true],
  ['hemiplegia','paralysis of one side of the body',[['hemi','prefix','half'],['plegia','suffix','paralysis']],
   ['one-sided paralysis','paralysis of one side'],true],
  ['hemiparesis','weakness of one side of the body',[['hemi','prefix','half'],['paresis','suffix','partial paralysis']],
   ['one-sided weakness','weakness of one side'],true],
  ['paraplegia','paralysis of both legs',[['para','prefix','beside, abnormal'],['plegia','suffix','paralysis']],
   ['paralysis of the legs','paralysed legs','both legs paralysed'],false],
  ['quadriplegia','paralysis of all four limbs',[['quadri','prefix','four'],['plegia','suffix','paralysis']],
   ['paralysis of all four limbs','tetraplegia','all four limbs paralysed'],false],
  ['aphasia','loss of the ability to speak or understand speech',[['a','prefix','without'],['phasia','suffix','speech']],
   ['loss of speech','cannot speak','unable to speak or understand'],true],
  ['dysphagia','difficulty swallowing',[['dys','prefix','difficult'],['phagia','suffix','swallowing']],
   ['difficulty swallowing','trouble swallowing'],true],
  ['dysphasia','difficulty with speech',[['dys','prefix','difficult'],['phasia','suffix','speech']],
   ['difficulty speaking','impaired speech'],true],
  ['syncope','a transient loss of consciousness from reduced brain perfusion',[],
   ['fainting','passing out','transient loss of consciousness'],true],
  ['ischemia','reduced blood supply to tissue',[['isch','root','holding back'],['emia','suffix','blood condition']],
   ['reduced blood supply','restricted blood flow','poor perfusion of tissue'],true],
  ['infarction','tissue death from loss of blood supply',[],
   ['tissue death from loss of blood supply','death of tissue'],true],
  ['necrosis','tissue death',[['necr','root','death'],['osis','suffix','abnormal condition']],
   ['tissue death','dead tissue'],false],
  ['edema','swelling from fluid in the tissues',[],
   ['swelling','fluid in the tissues','edema'],false],
  ['diaphoresis','profuse sweating',[['dia','prefix','through'],['phoresis','suffix','carrying']],
   ['profuse sweating','heavy sweating','sweating'],true],
  ['epistaxis','nosebleed',[],['nosebleed','bleeding from the nose'],false],
  ['anaphylaxis','a severe, life-threatening allergic reaction',[],
   ['severe allergic reaction','life-threatening allergic reaction'],true],
  ['bronchospasm','sudden narrowing of the airways',[['broncho','root','airway'],['spasm','suffix','involuntary contraction']],
   ['airway narrowing','narrowing of the airways','airway spasm'],true],
  ['angina','chest pain from reduced blood flow to the heart',[],
   ['chest pain from reduced blood flow','cardiac chest pain'],true],
  ['arrhythmia','an abnormal heart rhythm',[['a','prefix','without'],['rrhythm','root','rhythm'],['ia','suffix','condition of']],
   ['abnormal heart rhythm','irregular heart rhythm','dysrhythmia'],false],
  ['pericarditis','inflammation of the sac around the heart',[['peri','prefix','around'],['card','root','heart'],['itis','suffix','inflammation']],
   ['inflammation of the pericardium','inflammation around the heart'],false],
  ['peritonitis','inflammation of the abdominal lining',[['periton','root','peritoneum'],['itis','suffix','inflammation']],
   ['inflammation of the peritoneum','inflammation of the abdominal lining'],false],
  ['meningitis','inflammation of the membranes around the brain and cord',[['mening','root','meninges'],['itis','suffix','inflammation']],
   ['inflammation of the meninges','inflammation around the brain'],true],
  ['nephrolithiasis','kidney stones',[['nephro','root','kidney'],['lith','root','stone'],['iasis','suffix','condition']],
   ['kidney stones','renal stones','kidney stone'],false],
  ['cholecystitis','inflammation of the gallbladder',[['chole','root','bile'],['cyst','root','sac'],['itis','suffix','inflammation']],
   ['inflammation of the gallbladder','gallbladder inflammation'],false],
  ['gastroenteritis','inflammation of the stomach and intestine',[['gastro','root','stomach'],['enter','root','intestine'],['itis','suffix','inflammation']],
   ['inflammation of the stomach and intestine','stomach and bowel inflammation'],false],
  ['cardiomyopathy','disease of the heart muscle',[['cardi','root','heart'],['o','vowel','combining vowel'],['my','root','muscle'],['o','vowel','combining vowel'],['pathy','suffix','disease']],
   ['disease of the heart muscle','heart muscle disease'],false],
  ['cardiomegaly','enlargement of the heart',[['cardio','root','heart'],['megaly','suffix','enlargement']],
   ['enlarged heart','enlargement of the heart'],false],
  ['atelectasis','collapse of part of the lung',[['atel','root','incomplete'],['ectasis','suffix','expansion']],
   ['collapsed lung tissue','lung collapse','partial lung collapse'],false],
  ['thrombosis','formation of a clot in a vessel',[['thromb','root','clot'],['osis','suffix','abnormal condition']],
   ['clot formation','blood clot in a vessel'],false],
  ['embolism','blockage of a vessel by material carried in the blood',[],
   ['blockage of a vessel','vessel blockage by a traveling clot'],true],
  ['polyuria','passing large volumes of urine',[['poly','prefix','many, much'],['uria','suffix','urine condition']],
   ['excessive urination','passing a lot of urine','large volumes of urine'],false],
  ['oliguria','passing very little urine',[['olig','prefix','few, scanty'],['uria','suffix','urine condition']],
   ['low urine output','passing very little urine','reduced urine output'],true],
  ['anuria','producing no urine',[['an','prefix','without'],['uria','suffix','urine condition']],
   ['no urine output','not producing urine'],true],
  ['polydipsia','excessive thirst',[['poly','prefix','many, much'],['dipsia','suffix','thirst']],
   ['excessive thirst','very thirsty','increased thirst'],false],
  ['hyperkalemia','too much potassium in the blood',[['hyper','prefix','above normal'],['kal','root','potassium'],['emia','suffix','blood condition']],
   ['high potassium','raised potassium'],true],
  ['hypokalemia','too little potassium in the blood',[['hypo','prefix','below normal'],['kal','root','potassium'],['emia','suffix','blood condition']],
   ['low potassium'],true],
  ['epigastric','pertaining to the region above the stomach',[['epi','prefix','upon, above'],['gastr','root','stomach'],['ic','suffix','pertaining to']],
   ['above the stomach','upper central abdomen'],false],
  ['subcutaneous','beneath the skin',[['sub','prefix','under'],['cutane','root','skin'],['ous','suffix','pertaining to']],
   ['under the skin','beneath the skin']  ,false],
  ['intraosseous','within the bone',[['intra','prefix','within'],['osse','root','bone'],['ous','suffix','pertaining to']],
   ['into the bone','within the bone']  ,true],
  ['intramuscular','within the muscle',[['intra','prefix','within'],['muscul','root','muscle'],['ar','suffix','pertaining to']],
   ['into the muscle','within the muscle'],true],
  ['sublingual','under the tongue',[['sub','prefix','under'],['lingu','root','tongue'],['al','suffix','pertaining to']],
   ['under the tongue'],true]
];

export function buildBank(){
  const cards=[];
  const partId=(t)=>'trm-p-'+t.replace(/[^a-z]/gi,'').toLowerCase();
  const all=[...PREFIX,...SUFFIX,...ROOT,...VOWEL];
  const kindLabel={prefix:'prefix',suffix:'suffix',root:'root',vowel:'combining vowel'};
  all.forEach(([text,kind,meaning,syn])=>{
    cards.push({
      id:partId(text)+'-'+kind.slice(0,3),
      card_type:'term', card_kind:'part',
      chapter:5, part_kind:kind,
      term:text, definition:meaning,
      synonyms:syn||[],
      prompt:'Which '+kindLabel[kind]+' means this?',
      source_ref:SRC_MORPH
    });
  });
  TERMS.forEach(([term,def,parts,syn,hs])=>{
    const bank=all.map(([t])=>t.replace(/[-\/]/g,''));
    const own=parts.map(p=>p[0]);
    const distract=[];
    for(const b of bank){ if(distract.length>=4) break;
      if(own.indexOf(b)===-1 && b.length>1 && !distract.includes(b)) distract.push(b); }
    cards.push({
      id:'trm-'+term.replace(/[^a-z]/gi,'').toLowerCase(),
      card_type:'term', card_kind:'term',
      chapter:5,
      term, definition:def,
      parts:parts.map(([text,kind,meaning])=>({text,kind,meaning})),
      synonyms:syn||[],
      distractor_parts:distract,
      high_stakes:!!hs,
      source_ref:SRC_MORPH
    });
  });
  // build and decompose both require the parts to spell the term. A card that
  // fails this is not gradeable, so it fails the build instead of the learner.
  const broken=cards.filter(function(c){
    return c.card_kind==='term' && c.parts && c.parts.length &&
           c.parts.map(function(p){return p.text;}).join('')!==c.term;
  });
  if(broken.length){
    throw new Error('term parts do not spell the term: '+
      broken.map(function(b){ return b.term+' -> '+b.parts.map(function(p){return p.text;}).join(''); }).join(', '));
  }
  return cards;
}
