// Chapter 5 — Medical Terminology. Blocks and items.
// Every item traces to a source in v1.0 §11.1. Nothing is drawn from the
// Jones & Bartlett text: its table of contents set the sequence, nothing else.
const STD='NHTSA National EMS Education Standards (2021) — Preparatory: Medical Terminology.';
const ISMP='ISMP List of Error-Prone Abbreviations, Symbols and Dose Designations.';
const TJC='The Joint Commission Official "Do Not Use" List.';
const ANAT='Standard anatomical position and directional terminology, as used throughout the NHTSA National EMS Education Standards (2021).';

const opt=(id,text,correct,rationale)=>({id,text,correct,rationale});
const base=(o)=>({
  stimulus:{kind:'none',ref:null}, bloom:'apply', nremt_domain:'ems_operations',
  cj_step:null, difficulty_seed:0.5, high_stakes:false,
  version:'1.0.0', ...o
});

export const objectives=[
  {id:'obj-5.1.a',chapter:5,tier:'core',text:'Decompose a term into prefix, root, suffix and combining vowel',
   enables:'Read a term you have never seen in a handoff or on a chart, instead of guessing or asking'},
  {id:'obj-5.2.a',chapter:5,tier:'core',text:'Apply common suffixes to determine meaning',
   enables:'Tell from the word ending whether a note describes inflammation, a blood condition or a surgical procedure'},
  {id:'obj-5.3.a',chapter:5,tier:'core',text:'Apply common prefixes including position, direction, negation and number',
   enables:'Catch the difference between hypo- and hyper- in a handoff, where it decides treatment'},
  {id:'obj-5.4.a',chapter:5,tier:'core',text:'Map roots to body systems',
   enables:'Place an unfamiliar term in the right body system and narrow what the problem can be'},
  {id:'obj-5.5.a',chapter:5,tier:'core',text:'Apply anatomic planes, directional terms, positions and body cavities',
   enables:'Describe where an injury is in a PCR narrative so a reader two years later locates it exactly'},
  {id:'obj-5.6.a',chapter:5,tier:'core',text:'Use approved abbreviations and identify prohibited or error-prone ones',
   enables:'Write a chart entry that cannot be misread as a tenfold dose or the wrong drug'},
  {id:'obj-5.INT.a',chapter:5,tier:'core',text:'Decode unfamiliar terms encountered in a hospital handoff',
   enables:'Follow a receiving physician’s handoff in real time without stopping them to ask'}
];

export const items=[
// ── 5.1 Words are built, not memorized ─────────────────────────────────── 8
base({id:'itm-5.1.001',type:'mc',chapter:5,block:'5.1',objective:'obj-5.1.a',bloom:'understand',
  stem:'In the term pericarditis, which part carries the core meaning the rest are built around?',
  options:[opt('a','card, the root',true,'The root carries the core meaning — here, heart. Everything else modifies it.'),
    opt('b','peri-, the prefix',false,'A prefix modifies the root. Peri- means around, which tells you where, not what.'),
    opt('c','-itis, the suffix',false,'A suffix tells you what kind of condition. -itis means inflammation, but of what is carried by the root.'),
    opt('d','The combining vowel',false,'A combining vowel only joins parts so the word can be said. It carries no meaning.')],
  explanation_md:'Peri- (around) + card (heart) + -itis (inflammation) = inflammation around the heart. The root names the subject; prefix and suffix modify it.',
  source_ref:STD}),
base({id:'itm-5.1.002',type:'build_list',chapter:5,block:'5.1',objective:'obj-5.1.a',
  stem:'Put the parts of a medical term in the order they normally appear.',
  options:[opt('a','Prefix',true,'A prefix comes first and modifies what follows.'),
    opt('b','Root',true,'The root carries the core meaning and sits in the middle.'),
    opt('c','Combining vowel',true,'A combining vowel sits between a root and the next part, so the word can be said.'),
    opt('d','Suffix',true,'A suffix comes last and states what kind of condition, procedure or quality.')],
  explanation_md:'Prefix, root, combining vowel, suffix. Not every term has all four — but when they appear, this is the order.',
  source_ref:STD}),
base({id:'itm-5.1.003',type:'mc',chapter:5,block:'5.1',objective:'obj-5.1.a',bloom:'understand',
  stem:'Why does cardiomyopathy contain an "o" between cardi and my?',
  options:[opt('a','It is a combining vowel joining two roots so the word can be pronounced',true,'That is exactly its job — it carries no meaning of its own.'),
    opt('b','It is a prefix meaning heart',false,'Cardi is the root meaning heart. The o is not a prefix and has no meaning.'),
    opt('c','It marks the term as plural',false,'Medical plurals are formed at the end of a word, not in the middle.'),
    opt('d','It indicates the condition is chronic',false,'Nothing about duration is encoded by a combining vowel.')],
  explanation_md:'Cardi + o + my + o + pathy. The combining vowel — usually o — appears between a root and a following part when the join would otherwise be unsayable.',
  source_ref:STD}),
base({id:'itm-5.1.004',type:'drag_drop',chapter:5,block:'5.1',objective:'obj-5.1.a',
  stem:'Sort each word part by what kind of part it is.',
  categories:[{id:'prefix',label:'Prefix'},{id:'root',label:'Root'},{id:'suffix',label:'Suffix'}],
  options:[opt('a','brady-',true,'A prefix. It modifies what follows — here, slow.'),
    opt('b','-itis',true,'A suffix. It states the kind of condition — inflammation.'),
    opt('c','nephr',true,'A root. It names the subject — kidney.'),
    opt('d','hyper-',true,'A prefix, meaning above normal.')],
  answer_map:{a:'prefix',b:'suffix',c:'root',d:'prefix'},
  explanation_md:'Prefixes attach to the front and modify. Roots name the subject. Suffixes attach to the end and state the kind of condition or procedure.',
  source_ref:STD}),
base({id:'itm-5.1.005',type:'mc',chapter:5,block:'5.1',objective:'obj-5.1.a',
  stem:'A receiving nurse says a patient has nephromegaly. Without having met the word, what can you say it means?',
  options:[opt('a','An enlarged kidney',true,'Nephr (kidney) + -megaly (enlargement). The parts give you the whole.'),
    opt('b','Inflammation of the kidney',false,'That would be nephritis. -megaly is enlargement, not inflammation.'),
    opt('c','Surgical removal of a kidney',false,'That would be nephrectomy. -ectomy is removal.'),
    opt('d','Kidney stones',false,'That would be nephrolithiasis, which carries the root lith, meaning stone.')],
  explanation_md:'This is the whole point of the chapter: you decode a term you have never seen rather than recalling it.',
  source_ref:STD}),
base({id:'itm-5.1.006',type:'mr',chapter:5,block:'5.1',objective:'obj-5.1.a',select_count:[2,3],
  bloom:'understand',
  stem:'Select every statement about word parts that is true.',
  options:[opt('a','A root carries the core meaning of the term',true,'The root names the subject; the other parts modify it.'),
    opt('b','A combining vowel carries no meaning of its own',true,'Its only job is to make the join pronounceable.'),
    opt('c','A term must contain a prefix',false,'Many terms have none — nephritis is root plus suffix.'),
    opt('d','A suffix changes which body part is being described',false,'The root does that. A suffix states the kind of condition, procedure or quality.'),
    opt('e','Every term contains exactly one root',false,'Terms such as gastroenteritis carry two.')],
  explanation_md:'Roots name, prefixes and suffixes modify, combining vowels only join. Not every term carries every kind of part.',
  source_ref:STD}),
base({id:'itm-5.1.007',type:'mc',chapter:5,block:'5.1',objective:'obj-5.1.a',
  stem:'Which term is built from two roots rather than a prefix and a root?',
  options:[opt('a','Gastroenteritis',true,'Gastr (stomach) + enter (intestine) + -itis. Two roots, joined by a combining vowel.'),
    opt('b','Bradycardia',false,'Brady- is a prefix meaning slow; card is the only root.'),
    opt('c','Hypertension',false,'Hyper- is a prefix; -tension is the suffix. There is no second root.'),
    opt('d','Pericarditis',false,'Peri- is a prefix meaning around; card is the only root.')],
  explanation_md:'A term can carry more than one root when it describes more than one structure.',
  source_ref:STD}),
base({id:'itm-5.1.008',type:'mc',chapter:5,block:'5.1',objective:'obj-5.1.a',bloom:'analyze',
  stem:'Roughly 120 word parts generate several thousand medical terms. What follows for how you should study this chapter?',
  options:[opt('a','Learn the parts; the vocabulary follows from them',true,'Learning the generative system lets you read terms that were never on any list.'),
    opt('b','Memorize a list of the most common whole terms',false,'A finite list leaves you stuck the first time a term is not on it.'),
    opt('c','Learn only the terms in your own protocols',false,'Handoffs come from hospital staff who are not working from your protocols.'),
    opt('d','Look each term up when you meet it',false,'Reasonable at a desk. Not while a receiving physician is talking.')],
  explanation_md:'This is why the term bank drills parts rather than a vocabulary list, and why it asks you to produce rather than recognize.',
  source_ref:STD}),

// ── 5.2 Suffixes ───────────────────────────────────────────────────────── 8
base({id:'itm-5.2.001',type:'options_box',chapter:5,block:'5.2',objective:'obj-5.2.a',
  bloom:'remember',
  stem:'Classify each suffix by what kind of thing it describes.',
  columns:[{id:'cond',label:'A condition'},{id:'proc',label:'A procedure'}],
  rows:[{id:'r1',label:'-itis',answer:'cond'},{id:'r2',label:'-ectomy',answer:'proc'},
        {id:'r3',label:'-emia',answer:'cond'},{id:'r4',label:'-ostomy',answer:'proc'},
        {id:'r5',label:'-osis',answer:'cond'}],
  options:[],
  explanation_md:'Condition suffixes describe what is wrong. Procedure suffixes describe what was done about it — -ectomy removal, -ostomy an opening, -otomy an incision.',
  source_ref:STD}),
base({id:'itm-5.2.002',type:'mc',chapter:5,block:'5.2',objective:'obj-5.2.a',
  stem:'A chart records a past appendectomy. What happened?',
  options:[opt('a','The appendix was surgically removed',true,'-ectomy is surgical removal.'),
    opt('b','An opening was made into the appendix',false,'That would be -ostomy, a surgical opening.'),
    opt('c','The appendix was examined with a scope',false,'That would be -scopy, visual examination.'),
    opt('d','The appendix was repaired',false,'That would be -plasty, surgical repair.')],
  explanation_md:'The three surgical suffixes worth knowing cold: -ectomy removal, -ostomy opening, -otomy incision.',
  source_ref:STD}),
base({id:'itm-5.2.003',type:'mc',chapter:5,block:'5.2',objective:'obj-5.2.a',high_stakes:true,
  stem:'A handoff mentions hemoptysis. Which suffix tells you this concerns something being brought up from the airway?',
  options:[opt('a','-ptysis, spitting',true,'Hemo (blood) + -ptysis (spitting) — coughing up blood.'),
    opt('b','-emesis, vomiting',false,'That would be hematemesis, vomiting blood, which comes from the gut rather than the airway.'),
    opt('c','-rrhage, bursting forth',false,'That names heavy bleeding without saying from where.'),
    opt('d','-uria, urine condition',false,'That would be hematuria, blood in the urine.')],
  explanation_md:'Hemoptysis and hematemesis both mean blood is coming out, from two different places, and the suffix is the only thing telling you which.',
  source_ref:STD}),
base({id:'itm-5.2.004',type:'mr',chapter:5,block:'5.2',objective:'obj-5.2.a',select_count:[2,3],
  bloom:'remember',
  stem:'Select every suffix that tells you something is being measured, recorded or viewed.',
  options:[opt('a','-graphy',true,'The process of recording — as in angiography.'),
    opt('b','-scopy',true,'Visual examination — as in bronchoscopy.'),
    opt('c','-metry',true,'Measurement — as in spirometry.'),
    opt('d','-plasty',false,'Surgical repair. Nothing is being recorded.'),
    opt('e','-penia',false,'A deficiency — a condition, not an examination.')],
  explanation_md:'-graphy records, -graph is the instrument, -gram is the result. -scopy views, -scope is the instrument. -metry measures, -meter is the instrument.',
  source_ref:STD}),
base({id:'itm-5.2.005',type:'mc',chapter:5,block:'5.2',objective:'obj-5.2.a',
  bloom:'understand',
  stem:'What is the difference between a cardiogram and cardiography?',
  options:[opt('a','The gram is the record produced; the graphy is the process of producing it',true,'-gram is the result, -graphy the process, -graph the instrument.'),
    opt('b','The gram is the instrument; the graphy is the record',false,'The instrument is the -graph. The record is the -gram.'),
    opt('c','They describe the same thing',false,'They describe the record and the act of making it, which are different.'),
    opt('d','The gram is diagnostic; the graphy is therapeutic',false,'Neither is therapeutic. Both concern recording.')],
  explanation_md:'Instrument, process, result: -graph, -graphy, -gram.',
  source_ref:STD}),
base({id:'itm-5.2.006',type:'mc',chapter:5,block:'5.2',objective:'obj-5.2.a',high_stakes:true,
  stem:'A patient has thrombocytopenia. What does the suffix tell you about the platelet count?',
  options:[opt('a','It is deficient',true,'-penia is a deficiency, so there are too few platelets — which matters for bleeding.'),
    opt('b','It is raised',false,'That would be -cytosis, an increase in cells.'),
    opt('c','It is normal',false,'A suffix naming a deficiency does not describe a normal value.'),
    opt('d','It is unmeasurable',false,'No suffix carries that meaning.')],
  explanation_md:'-penia deficiency, -cytosis increase. In a bleeding patient, which one appears in the history changes what you expect.',
  source_ref:STD}),
base({id:'itm-5.2.007',type:'mc',chapter:5,block:'5.2',objective:'obj-5.2.a',
  bloom:'remember',
  stem:'Which suffix would you expect in a term describing a narrowed heart valve?',
  options:[opt('a','-stenosis',true,'-stenosis is narrowing — aortic stenosis is a narrowed aortic valve.'),
    opt('b','-sclerosis',false,'Hardening. Related, and often the cause, but not the same word.'),
    opt('c','-ectasis',false,'Expansion or dilation — the opposite.'),
    opt('d','-lysis',false,'Breakdown or destruction.')],
  explanation_md:'-stenosis narrows, -ectasis widens, -sclerosis hardens. Confusing narrowing with widening reverses the physiology.',
  source_ref:STD}),
base({id:'itm-5.2.008',type:'mc',chapter:5,block:'5.2',objective:'obj-5.2.a',bloom:'analyze',
  stem:'A note reads "hepatomegaly, no hepatitis". What does this tell you?',
  options:[opt('a','The liver is enlarged but not inflamed',true,'-megaly enlargement, -itis inflammation. The two are separate findings.'),
    opt('b','The liver is inflamed but not enlarged',false,'That reverses both suffixes.'),
    opt('c','The liver has been partly removed',false,'That would carry -ectomy.'),
    opt('d','The liver is hardened',false,'That would be -sclerosis, or cirrhosis.')],
  explanation_md:'Two suffixes on the same root describe two different findings, and a chart can record one without the other.',
  source_ref:STD}),

// ── 5.3 Prefixes ───────────────────────────────────────────────────────── 8
base({id:'itm-5.3.001',type:'mc',chapter:5,block:'5.3',objective:'obj-5.3.a',high_stakes:true,
  cj_step:'analyze_cues',
  stem:'A handoff is rushed and you hear "...glycemia" clearly but the prefix only partly. Why can you not proceed on the root alone?',
  options:[opt('a','Hypo- and hyper- reverse the meaning, and the treatments are opposite',true,'Low blood sugar may need dextrose; high blood sugar does not. The prefix is the whole clinical difference.'),
    opt('b','Glyc is an uncommon root',false,'It is common. The problem is not the root.'),
    opt('c','The suffix -emia is ambiguous',false,'-emia reliably means a blood condition. It is not the ambiguous part.'),
    opt('d','Blood sugar is not an EMS concern',false,'It is one of the most frequent reversible causes of altered mental status.')],
  explanation_md:'Hypo- and hyper- differ by two letters and invert the treatment. When you have not heard the prefix, ask — do not infer.',
  source_ref:STD}),
base({id:'itm-5.3.002',type:'drag_drop',chapter:5,block:'5.3',objective:'obj-5.3.a',high_stakes:true,
  stem:'Sort each prefix by whether it means more than normal or less than normal.',
  categories:[{id:'more',label:'More than normal'},{id:'less',label:'Less than normal'}],
  options:[opt('a','hyper-',true,'Above normal or excessive.'),opt('b','hypo-',true,'Below normal or deficient.'),
    opt('c','poly-',true,'Many or much — as in polyuria, passing large volumes.'),
    opt('d','olig-',true,'Few or scanty — as in oliguria, passing very little.')],
  answer_map:{a:'more',b:'less',c:'more',d:'less'},
  explanation_md:'Two pairs that reverse meaning: hyper/hypo and poly/olig. Both appear in handoffs about the same patient.',
  source_ref:STD}),
base({id:'itm-5.3.003',type:'mc',chapter:5,block:'5.3',objective:'obj-5.3.a',
  bloom:'apply',
  stem:'What does the prefix in "peritonsillar abscess" tell you about where the abscess is?',
  options:[opt('a','Around the tonsil',true,'Peri- means around or surrounding.'),
    opt('b','Inside the tonsil',false,'That would be intra-, within.'),
    opt('c','Below the tonsil',false,'That would be sub- or infra-.'),
    opt('d','Instead of the tonsil',false,'No prefix carries that meaning.')],
  explanation_md:'Position prefixes — peri- around, intra- within, sub- under, supra- above, inter- between — place the finding.',
  source_ref:STD}),
base({id:'itm-5.3.004',type:'mr',chapter:5,block:'5.3',objective:'obj-5.3.a',select_count:[2,3],
  bloom:'remember',
  stem:'Select every prefix that negates or removes what follows it.',
  options:[opt('a','a-',true,'Without — as in apnea, not breathing.'),
    opt('b','an-',true,'Without — the form used before a vowel, as in anuria.'),
    opt('c','de-',true,'Removal or loss of — as in dehydration.'),
    opt('d','dys-',false,'Difficult, painful or abnormal — not absent. Dyspnea is hard breathing, not no breathing.'),
    opt('e','poly-',false,'Many or much. The opposite of a negation.')],
  explanation_md:'The distinction that matters most on this list is a- against dys-. Apnea and dyspnea describe very different patients.',
  source_ref:STD}),
base({id:'itm-5.3.005',type:'mc',chapter:5,block:'5.3',objective:'obj-5.3.a',high_stakes:true,
  stem:'A partner reports the patient is apneic. Another says dyspneic. What is the difference?',
  options:[opt('a','Apneic is not breathing; dyspneic is breathing with difficulty',true,'a- means without, dys- means difficult. One needs ventilation now; the other needs assessment.'),
    opt('b','They mean the same thing',false,'They differ by the prefix, and the prefix is the whole difference.'),
    opt('c','Apneic is slow breathing; dyspneic is fast breathing',false,'Those are bradypnea and tachypnea.'),
    opt('d','Apneic refers to adults; dyspneic to children',false,'Neither prefix says anything about age.')],
  explanation_md:'One word apart, and one of them means you are ventilating.',
  source_ref:STD}),
base({id:'itm-5.3.006',type:'options_box',chapter:5,block:'5.3',objective:'obj-5.3.a',
  bloom:'remember',
  stem:'How many of each does the numerical prefix indicate?',
  columns:[{id:'1',label:'One'},{id:'2',label:'Two'},{id:'4',label:'Four'}],
  rows:[{id:'r1',label:'hemi- / uni- / mono-',answer:'1'},{id:'r2',label:'bi-',answer:'2'},
        {id:'r3',label:'quadri-',answer:'4'}],
  options:[],
  explanation_md:'Hemi- is strictly half, but in hemiplegia it describes one side. Quadriplegia is all four limbs.',
  source_ref:STD}),
base({id:'itm-5.3.007',type:'mc',chapter:5,block:'5.3',objective:'obj-5.3.a',
  stem:'Which prefix would you expect in a term for a medication given between two structures?',
  options:[opt('a','inter-',true,'Between — as in intercostal, between the ribs.'),
    opt('b','intra-',false,'Within — as in intramuscular, into the muscle itself.'),
    opt('c','infra-',false,'Below.'),
    opt('d','extra-',false,'Outside.')],
  explanation_md:'Inter- and intra- differ by one letter and describe different places. Intercostal is between the ribs; intramuscular is into the muscle.',
  source_ref:STD}),
base({id:'itm-5.3.008',type:'mc',chapter:5,block:'5.3',objective:'obj-5.3.a',bloom:'analyze',
  stem:'A chart records "post-ictal". What does the prefix establish about timing?',
  options:[opt('a','The state described follows the event',true,'Post- means after. The patient is in the period after a seizure.'),
    opt('b','The state described precedes the event',false,'That would be pre- or ante-.'),
    opt('c','The state described is ongoing',false,'No prefix here says the event is continuing.'),
    opt('d','The state described recurs',false,'That would be re-.')],
  explanation_md:'Pre-, post-, ante- and retro- all fix a finding in time, which is often what separates a resolved problem from a current one.',
  source_ref:STD}),

// ── 5.4 Roots and combining forms ──────────────────────────────────────── 8
base({id:'itm-5.4.001',type:'drag_drop',chapter:5,block:'5.4',objective:'obj-5.4.a',
  bloom:'remember',
  stem:'Sort each root into the body system it names.',
  categories:[{id:'cv',label:'Cardiovascular'},{id:'resp',label:'Respiratory'},{id:'neuro',label:'Nervous'}],
  options:[opt('a','cardi/o',true,'Heart — cardiovascular.'),opt('b','pneum/o',true,'Lung or air — respiratory.'),
    opt('c','encephal/o',true,'Brain — nervous system.'),opt('d','angi/o',true,'Vessel — cardiovascular.')],
  answer_map:{a:'cv',b:'resp',c:'neuro',d:'cv'},
  explanation_md:'Placing a root in a system narrows an unfamiliar term to a body region before you know anything else about it.',
  source_ref:STD}),
base({id:'itm-5.4.002',type:'mc',chapter:5,block:'5.4',objective:'obj-5.4.a',
  stem:'Nephr/o and ren/o both name the same organ. What is the practical consequence?',
  options:[opt('a','The same organ generates two families of terms, and you need both',true,'Nephrology and renal failure describe the same organ through different roots — one Greek, one Latin.'),
    opt('b','One of them is obsolete',false,'Both are in current use, often in the same chart.'),
    opt('c','They describe different parts of the kidney',false,'They name the same organ.'),
    opt('d','One is used for adults and one for children',false,'Neither root carries an age meaning.')],
  explanation_md:'Several organs carry a Greek and a Latin root. Heart is cardi/o only, but kidney, vein and skin each have two.',
  source_ref:STD}),
base({id:'itm-5.4.003',type:'mr',chapter:5,block:'5.4',objective:'obj-5.4.a',select_count:[2,3],
  bloom:'remember',
  stem:'Select every root that names a blood vessel or blood itself.',
  options:[opt('a','angi/o',true,'Vessel.'),opt('b','phleb/o',true,'Vein — as in phlebotomy.'),
    opt('c','hem/o',true,'Blood.'),opt('d','my/o',false,'Muscle.'),opt('e','oste/o',false,'Bone.')],
  explanation_md:'Vessel roots: angi/o and vas/o generally, arteri/o for artery, phleb/o and ven/o for vein.',
  source_ref:STD}),
base({id:'itm-5.4.004',type:'mc',chapter:5,block:'5.4',objective:'obj-5.4.a',
  stem:'A note records a cholecystectomy. Which organ was removed?',
  options:[opt('a','The gallbladder',true,'Chol/e (bile) + cyst (sac) + -ectomy (removal).'),
    opt('b','The bladder',false,'Cyst alone can mean bladder, but chol/e places it in the biliary system.'),
    opt('c','The colon',false,'That root is col/o, and the term would be colectomy.'),
    opt('d','The kidney',false,'That would be nephrectomy.')],
  explanation_md:'Cyst means sac. Which sac is settled by the root in front of it.',
  source_ref:STD}),
base({id:'itm-5.4.005',type:'mc',chapter:5,block:'5.4',objective:'obj-5.4.a',high_stakes:true,
  stem:'What does the root in "capnography" refer to?',
  options:[opt('a','Carbon dioxide',true,'Capn/o is carbon dioxide — capnography records it.'),
    opt('b','Oxygen',false,'That root is ox/i, as in hypoxia.'),
    opt('c','Breathing rate',false,'Breathing is the suffix -pnea, not a root here.'),
    opt('d','Blood',false,'That is hem/o or hemat/o.')],
  explanation_md:'Ox/i and capn/o name the two gases you monitor, and they are measured by different devices for different reasons.',
  source_ref:STD}),
base({id:'itm-5.4.006',type:'mc',chapter:5,block:'5.4',objective:'obj-5.4.a',
  bloom:'remember',
  stem:'Which root appears in terms about the membranes covering the brain and spinal cord?',
  options:[opt('a','mening/o',true,'Meninges — as in meningitis.'),
    opt('b','myel/o',false,'Spinal cord or bone marrow, not the covering membranes.'),
    opt('c','encephal/o',false,'The brain itself.'),
    opt('d','crani/o',false,'The skull.')],
  explanation_md:'Four roots sit close together anatomically — crani/o the skull, mening/o the membranes, encephal/o the brain, myel/o the cord.',
  source_ref:STD}),
base({id:'itm-5.4.007',type:'options_box',chapter:5,block:'5.4',objective:'obj-5.4.a',
  bloom:'remember',
  stem:'Which color does each root name?',
  columns:[{id:'blue',label:'Blue'},{id:'red',label:'Red'},{id:'white',label:'White'}],
  rows:[{id:'r1',label:'cyan/o',answer:'blue'},{id:'r2',label:'erythr/o',answer:'red'},
        {id:'r3',label:'leuk/o',answer:'white'}],
  options:[],
  explanation_md:'Color roots describe findings you can see — cyanosis — and cells you cannot — erythrocytes, leukocytes.',
  source_ref:STD}),
base({id:'itm-5.4.008',type:'mc',chapter:5,block:'5.4',objective:'obj-5.4.a',bloom:'analyze',
  stem:'A term you have never seen reads "myocarditis". Which system is it in, and what is wrong?',
  options:[opt('a','Cardiovascular — inflammation of the heart muscle',true,'My (muscle) + card (heart) + -itis (inflammation).'),
    opt('b','Musculoskeletal — inflammation of a skeletal muscle',false,'The root card places it in the heart, not the skeleton.'),
    opt('c','Cardiovascular — enlargement of the heart',false,'That would be -megaly.'),
    opt('d','Respiratory — inflammation of the diaphragm',false,'Neither root names the diaphragm or the respiratory system.')],
  explanation_md:'Two roots and a suffix, none of which you had to memorize as a whole word.',
  source_ref:STD}),

// ── 5.5 Where you are on the body ──────────────────────────────────────── 10
base({id:'itm-5.5.001',type:'mc',chapter:5,block:'5.5',objective:'obj-5.5.a',high_stakes:true,
  bloom:'remember',
  stem:'What does the anatomical position assume about the patient, regardless of how you found them?',
  options:[opt('a','Standing, facing forward, arms at the sides with palms forward',true,'All directional terms are stated against this reference position.'),
    opt('b','Lying supine with arms at the sides',false,'That is the supine position, not the reference position for directional terms.'),
    opt('c','However the patient was found',false,'If terms depended on how you found them, no two narratives would agree.'),
    opt('d','Seated upright at 90 degrees',false,'That is Fowler’s position.')],
  explanation_md:'Directional terms only mean one thing because they are all referred to the same assumed position. That is what makes a narrative readable by someone who was not there.',
  source_ref:ANAT}),
base({id:'itm-5.5.002',type:'hotspot',chapter:5,block:'5.5',objective:'obj-5.5.a',high_stakes:true,
  stimulus:{kind:'image',ref:'aemt/fig-abdominal-quadrants.svg',
    alt:'Outline of a torso divided into four abdominal quadrants by a vertical and a horizontal line through the navel.',
    asset_license:'Original schematic drawn for this module. AMR Kansas City, 2026. No third-party source.'},
  stem:'Tap the quadrant where the appendix is usually found.',
  regions:[{id:'ruq',label:'Right upper quadrant',polygon:[[50,18],[86,18],[86,50],[50,50]]},
    {id:'luq',label:'Left upper quadrant',polygon:[[14,18],[50,18],[50,50],[14,50]]},
    {id:'rlq',label:'Right lower quadrant',polygon:[[50,50],[86,50],[86,84],[50,84]]},
    {id:'llq',label:'Left lower quadrant',polygon:[[14,50],[50,50],[50,84],[14,84]]}],
  answer_region:'rlq',
  options:[],
  explanation_md:'The appendix sits in the right lower quadrant. Note that the patient’s right appears on the left of the diagram — quadrants are named from the patient’s perspective, never yours.',
  source_ref:ANAT}),
base({id:'itm-5.5.003',type:'mc',chapter:5,block:'5.5',objective:'obj-5.5.a',high_stakes:true,
  stem:'You write "laceration to the left forearm". Whose left?',
  options:[opt('a','The patient’s left, always',true,'Left and right in a clinical record are always the patient’s, not the writer’s.'),
    opt('b','Yours, as the person facing them',false,'That reverses the side for every reader who was not standing where you were.'),
    opt('c','Whichever is clearer in context',false,'A record that depends on context is a record that can be read two ways.'),
    opt('d','The side nearest the door',false,'Nothing in a narrative is oriented to the room.')],
  explanation_md:'This is the single most consequential convention in the chapter. A side recorded from the writer’s point of view sends the next clinician to the wrong limb.',
  source_ref:ANAT}),
base({id:'itm-5.5.004',type:'drag_drop',chapter:5,block:'5.5',objective:'obj-5.5.a',
  stem:'Sort each term by what it describes.',
  categories:[{id:'dir',label:'A direction'},{id:'pos',label:'A patient position'}],
  options:[opt('a','Proximal',true,'A direction — nearer to the trunk.'),
    opt('b','Supine',true,'A position — lying face up.'),
    opt('c','Lateral',true,'A direction — away from the midline.'),
    opt('d','Fowler’s',true,'A position — seated upright.')],
  answer_map:{a:'dir',b:'pos',c:'dir',d:'pos'},
  explanation_md:'Directions describe where something is on the body. Positions describe how the whole body is arranged.',
  source_ref:ANAT}),
base({id:'itm-5.5.005',type:'mc',chapter:5,block:'5.5',objective:'obj-5.5.a',high_stakes:true,
  stem:'An open fracture is described as distal to the elbow. Where is it?',
  options:[opt('a','Further from the trunk than the elbow — in the forearm, wrist or hand',true,'Distal means further from the point of attachment; proximal means nearer.'),
    opt('b','Nearer the trunk than the elbow',false,'That is proximal.'),
    opt('c','On the outer side of the elbow',false,'That is lateral.'),
    opt('d','Below the elbow when the patient is standing',false,'Below is inferior, and it is not interchangeable with distal — distal is measured along the limb, not against gravity.')],
  explanation_md:'Proximal and distal apply along a limb. Superior and inferior apply to the body as a whole. They are not synonyms.',
  source_ref:ANAT}),
base({id:'itm-5.5.006',type:'options_box',chapter:5,block:'5.5',objective:'obj-5.5.a',
  bloom:'remember',
  stem:'Which plane does each division describe?',
  columns:[{id:'sag',label:'Sagittal'},{id:'front',label:'Frontal / coronal'},{id:'trans',label:'Transverse'}],
  rows:[{id:'r1',label:'Divides the body into left and right',answer:'sag'},
        {id:'r2',label:'Divides the body into front and back',answer:'front'},
        {id:'r3',label:'Divides the body into top and bottom',answer:'trans'}],
  options:[],
  explanation_md:'Three planes, three divisions. A midsagittal plane is the sagittal plane taken exactly down the midline.',
  source_ref:ANAT}),
base({id:'itm-5.5.007',type:'mc',chapter:5,block:'5.5',objective:'obj-5.5.a',
  bloom:'remember',
  stem:'A patient is found face down. How is that recorded?',
  options:[opt('a','Prone',true,'Prone is face down; supine is face up.'),
    opt('b','Supine',false,'That is face up.'),
    opt('c','Lateral recumbent',false,'That is lying on one side.'),
    opt('d','Trendelenburg',false,'That is supine with the feet elevated above the head.')],
  explanation_md:'Prone and supine are the pair most often written the wrong way round, and both appear in the same narratives.',
  source_ref:ANAT}),
base({id:'itm-5.5.008',type:'mr',chapter:5,block:'5.5',objective:'obj-5.5.a',select_count:[2,3],
  bloom:'remember',
  stem:'Select every term that places a finding nearer the midline or the surface.',
  options:[opt('a','Medial',true,'Nearer the midline.'),
    opt('b','Superficial',true,'Nearer the surface.'),
    opt('c','Lateral',false,'Away from the midline — the opposite of medial.'),
    opt('d','Deep',false,'Further from the surface — the opposite of superficial.'),
    opt('e','Posterior',false,'Toward the back, which is neither midline nor surface.')],
  explanation_md:'Three pairs worth holding: medial/lateral, superficial/deep, anterior/posterior.',
  source_ref:ANAT}),
base({id:'itm-5.5.009',type:'mc',chapter:5,block:'5.5',objective:'obj-5.5.a',
  bloom:'remember',
  stem:'Which body cavity contains the heart and lungs?',
  options:[opt('a','The thoracic cavity',true,'The thoracic cavity holds the heart, lungs and great vessels.'),
    opt('b','The abdominal cavity',false,'That holds most of the digestive organs, below the diaphragm.'),
    opt('c','The cranial cavity',false,'That holds the brain.'),
    opt('d','The pelvic cavity',false,'That holds the bladder and reproductive organs.')],
  explanation_md:'The diaphragm separates thoracic from abdominal, which is why penetrating trauma near it may involve either.',
  source_ref:ANAT}),
base({id:'itm-5.5.010',type:'mc',chapter:5,block:'5.5',objective:'obj-5.5.a',bloom:'analyze',high_stakes:true,
  stem:'Which narrative line would let a reader two years later locate the wound exactly?',
  options:[opt('a','"A 3 cm laceration to the anterior aspect of the left forearm, 5 cm proximal to the wrist"',true,'Surface, side, and a measured distance from a fixed landmark. Nothing depends on where the writer stood.'),
    opt('b','"A cut on the arm"',false,'No side, no surface, no landmark, no size.'),
    opt('c','"A laceration on the inside of the arm nearest me"',false,'Oriented to the writer, which no later reader can reconstruct.'),
    opt('d','"A laceration below the elbow"',false,'Better, but below is ambiguous on a limb and no side is given.')],
  explanation_md:'The point of directional terms is that a narrative survives being read by someone who was not there.',
  source_ref:ANAT}),

// ── 5.6 Abbreviations and the error-prone list ─────────────────────────── 9
base({id:'itm-5.6.001',type:'mc',chapter:5,block:'5.6',objective:'obj-5.6.a',high_stakes:true,
  cj_step:'take_action',
  stem:'Why is "U" prohibited as an abbreviation for unit?',
  options:[opt('a','It can be misread as a zero or a four, multiplying the dose',true,'A handwritten U next to a number reads as another digit — 4U becomes 40.'),
    opt('b','It is ambiguous between units and micrograms',false,'That confusion belongs to µg, which is also discouraged.'),
    opt('c','It is not recognized internationally',false,'Recognition is not the issue; misreading is.'),
    opt('d','It is too short to be legible',false,'Length is not the problem. The shape is.')],
  explanation_md:'Write "unit" in full. This appears on the Joint Commission Do Not Use list precisely because the failure mode is a tenfold overdose.',
  source_ref:TJC}),
base({id:'itm-5.6.002',type:'mr',chapter:5,block:'5.6',objective:'obj-5.6.a',high_stakes:true,select_count:[2,3],
  bloom:'remember',
  stem:'Select every abbreviation that appears on the Joint Commission Do Not Use list.',
  options:[opt('a','U for unit',true,'Prohibited — write "unit".'),
    opt('b','IU for International Unit',true,'Prohibited — it can be read as IV or as the number 10.'),
    opt('c','MS for morphine sulfate',true,'Prohibited — it can mean morphine sulfate or magnesium sulfate.'),
    opt('d','mg for milligram',false,'Standard and accepted.'),
    opt('e','mL for millilitre',false,'Standard and accepted.')],
  explanation_md:'The list exists because each entry has an established record of being misread in a way that changed a dose or a drug.',
  source_ref:TJC}),
base({id:'itm-5.6.003',type:'options_box',chapter:5,block:'5.6',objective:'obj-5.6.a',high_stakes:true,
  stem:'Is each way of writing a dose acceptable?',
  columns:[{id:'ok',label:'Acceptable'},{id:'no',label:'Do not write'}],
  rows:[{id:'r1',label:'0.5 mg',answer:'ok'},{id:'r2',label:'.5 mg',answer:'no'},
        {id:'r3',label:'5 mg',answer:'ok'},{id:'r4',label:'5.0 mg',answer:'no'}],
  options:[],
  explanation_md:'Always use a leading zero before a decimal point; never use a trailing zero after one. A missed decimal in ".5" reads as 5 — tenfold. A "5.0" misread as 50 is tenfold the other way.',
  source_ref:TJC}),
base({id:'itm-5.6.004',type:'mc',chapter:5,block:'5.6',objective:'obj-5.6.a',high_stakes:true,
  stem:'A chart reads "MS 4 mg IV". What is the problem?',
  options:[opt('a','MS can mean morphine sulfate or magnesium sulfate',true,'Two different drugs, and the abbreviation does not distinguish them. Write the drug name in full.'),
    opt('b','The route should be written before the dose',false,'Order is a style matter, not a safety one.'),
    opt('c','4 mg is not a valid dose',false,'It may well be valid. The drug is what is unclear.'),
    opt('d','IV should be written in full',false,'IV is widely accepted and unambiguous.')],
  explanation_md:'MS, MSO4 and MgSO4 are all on the Do Not Use list for this reason. Spell the drug out.',
  source_ref:TJC}),
base({id:'itm-5.6.005',type:'mc',chapter:5,block:'5.6',objective:'obj-5.6.a',high_stakes:true,
  bloom:'understand',
  stem:'Why are q.d. and q.o.d. both prohibited?',
  options:[opt('a','They are mistaken for each other, and the period after q can look like an i',true,'Daily and every other day differ by one letter, and misreading either changes the frequency.'),
    opt('b','They are Latin and Latin is no longer used',false,'Plenty of accepted abbreviations are Latin. Ambiguity is the issue, not origin.'),
    opt('c','They apply only to oral medication',false,'Neither is route-specific.'),
    opt('d','They are too long to write',false,'Length is not the problem.')],
  explanation_md:'Write "daily" and "every other day". The prohibition is about the failure mode, not the language.',
  source_ref:TJC}),
base({id:'itm-5.6.006',type:'mc',chapter:5,block:'5.6',objective:'obj-5.6.a',
  stem:'When is a trailing zero acceptable?',
  options:[opt('a','To show precision in a reported value such as a lesion size or a tube size',true,'It is permitted where the zero conveys the precision of a measurement — not in medication orders.'),
    opt('b','Never, in any context',false,'Close, but too strong — there is a defined exception for reported values.'),
    opt('c','Whenever the dose is a whole number',false,'That is exactly where it is prohibited.'),
    opt('d','Whenever the value is under 1 mg',false,'Under 1 mg the issue is the leading zero, which is required.')],
  explanation_md:'The exception is narrow and it is about measurement precision. In anything medication-related, no trailing zero.',
  source_ref:TJC}),
base({id:'itm-5.6.007',type:'mc',chapter:5,block:'5.6',objective:'obj-5.6.a',high_stakes:true,
  cj_step:'take_action',
  stem:'You are reviewing your own chart before submitting and find an abbreviation you are unsure of. What is the safest action?',
  options:[opt('a','Write the term out in full',true,'An unambiguous chart costs you seconds. A misread one costs someone else more.'),
    opt('b','Leave it — the receiving facility will know',false,'The reader may be a biller, a lawyer or a clinician two years later, none of whom can ask you.'),
    opt('c','Add a note explaining the abbreviation',false,'Better than nothing, but the abbreviation is still there to be misread.'),
    opt('d','Use a more common abbreviation instead',false,'Substituting one abbreviation for another does not remove the ambiguity.')],
  explanation_md:'The whole point of this block is that the record is read by people who cannot ask you what you meant.',
  source_ref:ISMP}),
base({id:'itm-5.6.008',type:'mr',chapter:5,block:'5.6',objective:'obj-5.6.a',select_count:[2,3],
  bloom:'remember',
  stem:'Select every symbol or abbreviation identified as error-prone.',
  options:[opt('a','@ for at',true,'It is read as the number 2. Write "at".'),
    opt('b','cc for cubic centimetre',true,'It is read as U. Write mL.'),
    opt('c','µg for microgram',true,'It is read as mg — a thousandfold error. Write mcg.'),
    opt('d','kg for kilogram',false,'Standard and accepted.'),
    opt('e','mmHg for millimetres of mercury',false,'Standard and accepted.')],
  explanation_md:'Each of these has a documented misreading. µg read as mg is the one with the largest multiplier.',
  source_ref:ISMP}),
base({id:'itm-5.6.009',type:'mc',chapter:5,block:'5.6',objective:'obj-5.6.a',bloom:'analyze',high_stakes:true,
  stem:'Your agency ePCR permits an abbreviation that appears on a national error-prone list. Which governs your charting?',
  options:[opt('a','Follow the stricter of the two and write it out',true,'Nothing is lost by being unambiguous, and the national list exists because that abbreviation has already caused harm somewhere.'),
    opt('b','The agency list, because it is the local rule',false,'Local permission does not make a documented misreading less likely.'),
    opt('c','The national list, because it overrides local policy',false,'It does not formally override local policy — but you can exceed it, which is the point.'),
    opt('d','Whichever the receiving facility prefers',false,'You will not know, and the record outlives the handoff.')],
  explanation_md:'Where the two differ, write it out. This is one to raise with your clinical education team rather than resolve silently in a narrative.',
  source_ref:ISMP}),

// ── 5.INT Integration: a hospital handoff ──────────────────────────────── 8
base({id:'itm-5.INT.000',type:'scenario',chapter:5,block:'5.INT',objective:'obj-5.INT.a',
  stimulus:{kind:'scenario',ref:null,
    text:'You are at the bedside as the receiving physician takes report from a transferring nurse:\n\n"Sixty-eight-year-old, three days post cholecystectomy, now with tachypnea and new hypoxemia. Denies hemoptysis. Mild epigastric tenderness, no peritonitis. Oliguric overnight. We are treating for a possible pulmonary embolism."'},
  children:['itm-5.INT.001','itm-5.INT.002','itm-5.INT.003','itm-5.INT.004',
            'itm-5.INT.005','itm-5.INT.006','itm-5.INT.007'],
  stem:'', options:[], explanation_md:'', source_ref:STD}),
base({id:'itm-5.INT.001',type:'mc',chapter:5,block:'5.INT',objective:'obj-5.INT.a',parent:'itm-5.INT.000',
  stem:'What operation did this patient have three days ago?',
  options:[opt('a','Removal of the gallbladder',true,'Chol/e (bile) + cyst (sac) + -ectomy (removal).'),
    opt('b','Removal of the appendix',false,'That would be appendectomy.'),
    opt('c','An opening made into the colon',false,'That would be colostomy.'),
    opt('d','Repair of a hernia',false,'No part of the term names a hernia or a repair.')],
  explanation_md:'Recent abdominal surgery is a risk factor for the diagnosis the team is treating.',
  source_ref:STD}),
base({id:'itm-5.INT.002',type:'mc',chapter:5,block:'5.INT',objective:'obj-5.INT.a',high_stakes:true,
  parent:'itm-5.INT.000', cj_step:'recognize_cues',
  stem:'Tachypnea and hypoxemia together describe what?',
  options:[opt('a','Rapid breathing with too little oxygen in the blood',true,'Tachy- (fast) + -pnea (breathing); hyp- (below normal) + ox (oxygen) + -emia (blood condition).'),
    opt('b','Slow breathing with too little oxygen in the tissues',false,'Slow would be brady-, and tissue oxygen would be hypoxia rather than hypoxemia.'),
    opt('c','Rapid breathing with too much carbon dioxide',false,'That would be hypercapnia.'),
    opt('d','Absent breathing with low blood pressure',false,'Those would be apnea and hypotension.')],
  explanation_md:'Two terms, four word parts, and between them they describe the presentation the team is acting on.',
  source_ref:STD}),
base({id:'itm-5.INT.003',type:'mc',chapter:5,block:'5.INT',objective:'obj-5.INT.a',parent:'itm-5.INT.000',
  stem:'"Denies hemoptysis" rules out what?',
  options:[opt('a','Coughing up blood',true,'Hemo (blood) + -ptysis (spitting).'),
    opt('b','Vomiting blood',false,'That is hematemesis.'),
    opt('c','Blood in the urine',false,'That is hematuria.'),
    opt('d','Heavy bleeding from any site',false,'That would be hemorrhage, which names no site.')],
  explanation_md:'Four terms share the root for blood and differ only in the suffix, which is what names the route.',
  source_ref:STD}),
base({id:'itm-5.INT.004',type:'mc',chapter:5,block:'5.INT',objective:'obj-5.INT.a',parent:'itm-5.INT.000',
  stem:'Where is the epigastric tenderness?',
  options:[opt('a','In the upper central abdomen, above the stomach',true,'Epi- (above) + gastr (stomach) + -ic (pertaining to).'),
    opt('b','In the right lower quadrant',false,'No part of the term names a quadrant.'),
    opt('c','Behind the stomach',false,'That would be retro-, not epi-.'),
    opt('d','Throughout the abdomen',false,'That would be generalised, and would not carry the root gastr.')],
  explanation_md:'A position prefix on an organ root gives you a region without a diagram.',
  source_ref:STD}),
base({id:'itm-5.INT.005',type:'mc',chapter:5,block:'5.INT',objective:'obj-5.INT.a',high_stakes:true,
  parent:'itm-5.INT.000',
  stem:'"No peritonitis" means the team has not found what?',
  options:[opt('a','Inflammation of the lining of the abdominal cavity',true,'Periton (peritoneum) + -itis (inflammation).'),
    opt('b','Inflammation around the heart',false,'That is pericarditis — a different root, one letter apart in speech.'),
    opt('c','A perforated bowel',false,'Peritonitis may follow one, but the term names the inflammation, not the perforation.'),
    opt('d','Fluid in the abdomen',false,'That would be ascites.')],
  explanation_md:'Pericarditis and peritonitis sound alike in a fast handoff and describe entirely different cavities. The root is the only thing separating them.',
  source_ref:STD}),
base({id:'itm-5.INT.006',type:'mc',chapter:5,block:'5.INT',objective:'obj-5.INT.a',high_stakes:true,
  parent:'itm-5.INT.000', cj_step:'analyze_cues',
  stem:'"Oliguric overnight" tells you what about urine output?',
  options:[opt('a','It was low',true,'Olig- (few, scanty) + -uria (urine condition).'),
    opt('b','It was high',false,'That would be polyuric.'),
    opt('c','There was none at all',false,'That would be anuric.'),
    opt('d','It contained blood',false,'That would be hematuria.')],
  explanation_md:'Three prefixes on one suffix describe three different degrees of a finding that tracks perfusion.',
  source_ref:STD}),
base({id:'itm-5.INT.007',type:'mr',chapter:5,block:'5.INT',objective:'obj-5.INT.a',parent:'itm-5.INT.000',
  select_count:[2,3], cj_step:'define_hypothesis',
  stem:'Which findings in this handoff would you carry into your own report as directly relevant?',
  options:[opt('a','Recent abdominal surgery three days ago',true,'It is a recognized risk factor for the diagnosis being treated.'),
    opt('b','New rapid breathing with low blood oxygen',true,'The presentation that prompted the working diagnosis.'),
    opt('c','Low urine output overnight',true,'It speaks to perfusion, and it changes what you watch on the way.'),
    opt('d','The absence of coughing up blood',false,'Worth recording, but a negative finding is not what you lead with.'),
    opt('e','That the gallbladder was removed rather than the appendix',false,'Which organ matters less here than the fact of recent surgery.')],
  explanation_md:'Decoding the words is step one. Deciding which of them travel with the patient is the reason it was worth doing.',
  source_ref:STD})
];

export const blocks=[
{id:'5.1',chapter:5,title:'Words are built, not memorized',learner_title:'Words are built',
 objectives:['obj-5.1.a'],est_minutes:7,
 cold_open:{text:'The receiving nurse says your patient is "bradycardic with a hemothorax, no hemoptysis". You have never seen any of those three words written down. Nobody is going to spell them for you, and in about ninety seconds you will repeat them back on the radio to your own medical control.',
   decision_point:'Do you have to know these words, or can you work them out?'},
 pretest_item:'itm-5.1.001',
 screens:[
  {id:'scr-5.1.1',body_md:'**A medical term is a machine, not a memory.** Around 120 word parts generate several thousand terms. Learn the parts and you can read a word you have never met.\n\nFour kinds of part do all the work. A **prefix** goes on the front and modifies. A **root** carries the core meaning. A **suffix** goes on the end and says what kind of condition, procedure or quality. A **combining vowel** — nearly always *o* — sits between parts so the word can be said.',figure:null},
  {id:'scr-5.1.2',body_md:'Take **pericarditis** apart:\n\n*peri-* (around) + *card* (heart) + *-itis* (inflammation) = inflammation around the heart.\n\nNow change one part at a time. *Myo*carditis is inflammation of the heart **muscle**. Cardio*megaly* is an **enlarged** heart. Cardi*ectomy* would be its **removal**.\n\nOne root, three different words, none of which you memorized.',figure:null},
  {id:'scr-5.1.3',body_md:'**The combining vowel has no meaning.** It exists only so the join can be pronounced.\n\n*Cardiomyopathy* is cardi + **o** + my + **o** + pathy. Without the vowels it would be *cardimypathy*, which nobody can say.\n\nA useful habit: read a term back to front. The suffix tells you what kind of thing it is, then the root tells you where, then the prefix tells you how much or which way.',figure:null},
  {id:'scr-5.1.4',body_md:'**Not every term has every part.** *Nephritis* is root plus suffix. *Gastroenteritis* carries two roots. *Melena* and *syncope* have no usable parts at all and simply have to be learned.\n\nThose irregular ones are the minority, and they are the reason the term bank in this app carries some whole words alongside the parts.',figure:null},
  {id:'scr-5.1.5',body_md:'**Where this pays off is a handoff you cannot pause.** A receiving clinician will not stop and define *hepatomegaly* for you, and asking twice costs credibility you would rather keep.\n\nThe term bank in this app drills the parts rather than a word list, and it asks you to **produce** them rather than pick them from four options. Recognizing a definition you have just been shown feels like learning and is not. Building the word yourself, from nothing, is the part that sticks.',figure:null}],
 inline_checks:['itm-5.1.003','itm-5.1.005'],
 quiz:['itm-5.1.002','itm-5.1.004','itm-5.1.006','itm-5.1.007','itm-5.1.008'],
 callback_md:'**Bradycardic**: brady (slow) + card (heart) + -ic = a slow heart rate. **Hemothorax**: hemo (blood) + thorax (chest) = blood in the chest cavity. **Hemoptysis**: hemo (blood) + -ptysis (spitting) = coughing up blood, which the nurse is telling you is absent.\n\nYou did not memorize any of the three. You took them apart.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'5.2',chapter:5,title:'Suffixes',learner_title:'The ending tells you what kind',
 objectives:['obj-5.2.a'],est_minutes:7,
 cold_open:{text:'A transfer packet lists, under past surgical history: appendectomy, colostomy, cholecystectomy. Three words, three endings, and only one of them left an opening in the abdominal wall. You are about to lift the sheet and see it, and knowing which one before you look changes how you react.',
   decision_point:'Which one?'},
 pretest_item:'itm-5.2.002',
 screens:[
  {id:'scr-5.2.1',body_md:'**Read the end of the word first.** The suffix tells you what *kind* of thing you are dealing with before you know which body part is involved. That is usually enough to know whether a note is describing a problem or a past operation.\n\nCondition endings: **-itis** inflammation, **-osis** an abnormal condition, **-emia** a blood condition, **-uria** a urine condition, **-algia** pain, **-megaly** enlargement, **-pathy** disease. Four of those seven appear in a typical discharge summary.',figure:null},
  {id:'scr-5.2.2',body_md:'**Three surgical endings are worth knowing cold**, because they fill transfer paperwork and they describe very different things.\n\n**-ectomy** — surgical removal. *Appendectomy.*\n**-ostomy** — a surgical opening. *Colostomy.*\n**-otomy** — a surgical incision. *Thoracotomy.*\n\nOne letter separates the second from the third, and only one of the three leaves a stoma you will see when you lift the sheet.',figure:null},
  {id:'scr-5.2.3',body_md:'**Instrument, process, result** is a pattern rather than three separate facts to hold.\n\n**-graph** is the instrument, **-graphy** is the process, **-gram** is the record it produces.\n\nThe same shape repeats elsewhere. **-scope** the instrument, **-scopy** the examination. **-meter** the instrument, **-metry** the measurement. Learn the shape once and it gives you nine words.',figure:null},
  {id:'scr-5.2.4',body_md:'**Some suffixes are direct opposites**, and reversing them reverses the physiology.\n\n**-stenosis** narrowing against **-ectasis** expansion. **-penia** too few against **-cytosis** too many.\n\nIn a history, *aortic stenosis* and *bronchiectasis* describe problems moving in opposite directions. Read the ending carelessly and you have the pathology backwards — which is worse than not knowing the word at all.',figure:null},
  {id:'scr-5.2.5',body_md:'**Two endings about movement** turn up constantly in stroke and spinal patients.\n\n**-plegia** is paralysis. **-paresis** is partial paralysis, or weakness.\n\n*Hemiplegia* is one side paralysed; *hemiparesis* is one side weak. And a family of endings describes flow: **-rrhea** a discharge, **-rrhage** and **-rrhagia** heavy bleeding, **-rrhexis** rupture. They look alike and they are not the same order of problem.',figure:null}],
 inline_checks:['itm-5.2.003','itm-5.2.005'],
 quiz:['itm-5.2.001','itm-5.2.004','itm-5.2.006','itm-5.2.007','itm-5.2.008'],
 callback_md:'**Colostomy.** The *-ostomy* ending is a surgical opening — col (colon) + -ostomy = an opening from the colon to the abdominal wall. The appendectomy and the cholecystectomy both used *-ectomy*: something was removed, and nothing was left open.\n\nYou did not need to know what a colon is, or where the gallbladder sits, to get that right. You needed three endings and the confidence to read them.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'5.3',chapter:5,title:'Prefixes and numerical prefixes',learner_title:'The front changes everything',
 objectives:['obj-5.3.a'],est_minutes:7,
 cold_open:{text:'Bad radio, busy bay. You catch "...glycemia" and the crew is already moving. You have the root and you have the suffix. What you are missing is the four letters on the front, and those four letters decide the treatment.',
   decision_point:'Can you act on what you heard?'},
 pretest_item:'itm-5.3.001',
 screens:[
  {id:'scr-5.3.1',body_md:'**The prefix is where meaning reverses.** Two pairs matter more than all the others put together, because both turn up in handoffs about the same patient and both invert the treatment.\n\n**hypo-** below normal against **hyper-** above normal.\n**olig-** few or scanty against **poly-** many or much.\n\n*Hypoglycemia* may need dextrose. *Hyperglycemia* does not. Four letters, opposite actions.',figure:null},
  {id:'scr-5.3.2',body_md:'**Negation prefixes are not interchangeable.**\n\n**a-** and **an-** mean *without*. Apnea is not breathing at all.\n**dys-** means *difficult, painful or abnormal*. Dyspnea is breathing that is hard work.\n\nOne of those patients is being ventilated and the other is being assessed. The difference between them is two letters on the front of one word, spoken quickly, in a noisy bay.',figure:null},
  {id:'scr-5.3.3',body_md:'**Position prefixes place the finding on the body.**\n\n**peri-** around · **intra-** within · **inter-** between · **sub-** under · **supra-** above · **epi-** upon · **retro-** behind\n\n*Intercostal* is between the ribs. *Intramuscular* is into the muscle itself. One letter apart and two different places — one of which is a drug route you will use.',figure:null},
  {id:'scr-5.3.4',body_md:'**Timing and number prefixes** finish the set.\n\nTiming: **pre-** before, **post-** after, **ante-** before, **retro-** behind or backward, **re-** again. *Post-ictal* is the period after a seizure, which is a different patient from one who is *pre*-ictal.\n\nNumber: **mono-** and **uni-** one, **bi-** two, **tri-** three, **quadri-** four, **hemi-** half or one side.',figure:null},
  {id:'scr-5.3.5',body_md:'**Direction prefixes** show up in drug routes and in movement. **ab-** away from · **ad-** toward · **ex-** out · **trans-** across · **circum-** around.\n\nAbduction moves a limb away from the midline; adduction brings it back.\n\nAnd one prefix is reassuring rather than alarming: **eu-** means normal. A handoff saying the patient is *euvolemic* is telling you something has been excluded, not found.',figure:null}],
 inline_checks:['itm-5.3.005','itm-5.3.007'],
 quiz:['itm-5.3.002','itm-5.3.003','itm-5.3.004','itm-5.3.006','itm-5.3.008'],
 callback_md:'**No.** The root tells you it concerns blood sugar and the suffix tells you it is a blood condition, but *hypo-* and *hyper-* point in opposite directions and the treatment differs accordingly.\n\nWhen the prefix is the part you missed, ask. This is the one place in the chapter where working it out from context is the wrong instinct — everywhere else, decoding is exactly what you should do.\n\nThe cost of asking is four seconds and mild embarrassment. The cost of guessing wrong is a drug the patient did not need.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'5.4',chapter:5,title:'Roots and combining forms',learner_title:'Roots put it in a system',
 objectives:['obj-5.4.a'],est_minutes:7,
 cold_open:{text:'A discharge summary lists "myocarditis, nephrolithiasis, cholecystitis". You are not expected to treat any of them. You are expected to know, in roughly two seconds of scanning the page, which body systems this patient has already had trouble with.',
   decision_point:'Which three?'},
 pretest_item:'itm-5.4.008',
 screens:[
  {id:'scr-5.4.1',body_md:'**The root places a term in a body system**, which narrows an unfamiliar word before you know anything else about it.\n\nCardiovascular: **cardi/o** heart, **angi/o** and **vas/o** vessel, **arteri/o** artery, **phleb/o** and **ven/o** vein, **hem/o** blood.\n\nRespiratory: **pneum/o** lung or air, **pulmon/o** lung, **bronch/o** airway, **thorac/o** chest, **laryng/o** larynx, **trache/o** trachea.',figure:null},
  {id:'scr-5.4.2',body_md:'Nervous system: **neur/o** nerve, **encephal/o** brain, **mening/o** the membranes around brain and cord, **myel/o** spinal cord or bone marrow, **crani/o** skull.\n\nThose five structures sit within centimetres of each other and are not interchangeable. *Meningitis* and *encephalitis* are different diagnoses with different courses, and the only thing separating the words is the root.',figure:null},
  {id:'scr-5.4.3',body_md:'Abdomen and urinary: **gastr/o** stomach, **enter/o** intestine, **col/o** colon, **hepat/o** liver, **chol/e** bile, **pancreat/o** pancreas, **nephr/o** and **ren/o** kidney, **cyst/o** bladder or sac, **ur/o** urine.\n\n**Some organs carry two roots**, one Greek and one Latin, and both stay in use. The kidney gives you *nephrology* and *renal failure* in the same chart.',figure:null},
  {id:'scr-5.4.4',body_md:'A few roots are not organs at all and turn up everywhere:\n\n**cyan/o** blue · **erythr/o** red · **leuk/o** white · **glyc/o** sugar · **lip/o** fat · **ox/i** oxygen · **capn/o** carbon dioxide · **tox/o** poison · **path/o** disease\n\n*Ox/i* and *capn/o* name the two gases you monitor, on two different devices, for two different reasons.',figure:null},
  {id:'scr-5.4.5',body_md:'Musculoskeletal roots fill every trauma narrative: **oste/o** bone · **arthr/o** joint · **my/o** muscle · **cost/o** rib · **crani/o** skull · **derm/o** skin.\n\n**A root plus a suffix you already have is a finished term.** *Nephr* + *-itis*. *Arthr* + *-algia*. *Hepat* + *-megaly*. None of those three had to be learned as a word — you already had both halves of each.',figure:null}],
 inline_checks:['itm-5.4.002','itm-5.4.005'],
 quiz:['itm-5.4.001','itm-5.4.003','itm-5.4.004','itm-5.4.006','itm-5.4.007'],
 callback_md:'**Cardiovascular, urinary, and biliary.** *My/o* + *card* places the first in the heart. *Nephr/o* + *lith* places the second in the kidney. *Chol/e* + *cyst* places the third in the gallbladder.\n\nThree systems, from three roots, without knowing a thing about the conditions themselves.\n\nThat is what roots are for. They will not tell you how sick someone is, but they place every unfamiliar word in a region of the body, and that is usually enough to know whether it matters to you today, or is simply history.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'5.5',chapter:5,title:'Where you are on the body',learner_title:'Saying where, exactly',
 objectives:['obj-5.5.a'],est_minutes:9,
 cold_open:{text:'Two years from now a lawyer reads your narrative aloud in a deposition. It says "laceration on the inside of the arm, nearest me". Nobody in the room, including you by then, can tell which arm it was, which surface of it, or where you had been standing.',
   decision_point:'What should it have said?'},
 pretest_item:'itm-5.5.003',
 screens:[
  {id:'scr-5.5.1',body_md:'**Everything is stated against the anatomical position**: standing, facing forward, arms at the sides, palms forward. It does not matter how you found the patient. The reference never moves, which is the only reason two people describe the same wound the same way.\n\n**Left and right are always the patient’s.** Not yours, whichever way you were facing.',figure:null},
  {id:'scr-5.5.2',body_md:'**Three pairs of directions** carry most of the load:\n\n**anterior / posterior** — front and back\n**medial / lateral** — toward and away from the midline\n**superficial / deep** — nearer and further from the surface\n\nAnd along a limb, **proximal / distal** — nearer and further from the trunk. Proximal and distal are not the same as superior and inferior: one runs along the limb, the other against gravity.',figure:null},
  {id:'scr-5.5.3',body_md:'**Positions describe the whole body**, not a location on it.\n\n**Supine** face up · **prone** face down · **lateral recumbent** on one side · **Fowler’s** seated upright · **semi-Fowler’s** partly reclined · **Trendelenburg** supine with the feet raised above the head.\n\nSupine and prone are the pair most often written the wrong way round.',figure:null},
  {id:'scr-5.5.4',body_md:'**Planes and cavities** finish the vocabulary.\n\nPlanes: **sagittal** divides left from right, **frontal** (coronal) front from back, **transverse** top from bottom.\n\nCavities: **cranial** brain · **thoracic** heart and lungs · **abdominal** digestive organs · **pelvic** bladder and reproductive organs. The diaphragm separates thoracic from abdominal — which is why a wound near it may have entered either.',figure:null},
  {id:'scr-5.5.5',body_md:'**The abdomen is divided into four quadrants** by a vertical and a horizontal line through the navel: right upper, left upper, right lower, left lower.\n\nThey are named from the **patient’s** perspective. On a diagram facing you, the patient’s right appears on your left. Getting this backwards puts the appendix on the wrong side of the chart.',figure:null}],
 inline_checks:['itm-5.5.001','itm-5.5.005'],
 quiz:['itm-5.5.002','itm-5.5.004','itm-5.5.006','itm-5.5.007','itm-5.5.008','itm-5.5.009','itm-5.5.010'],
 callback_md:'Something closer to: **"A 3 cm laceration to the anterior aspect of the left forearm, 5 cm proximal to the wrist."**\n\nSide, surface, size, and a measured distance from a fixed landmark. Nothing in that sentence depends on where you were standing, which is the entire point.\n\nWrite every location as though the reader will be someone who was not there, because sooner or later it will be. That reader may be a surgeon, a biller, or a lawyer, and none of them can ask you what you meant.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'5.6',chapter:5,title:'Abbreviations and the error-prone list',learner_title:'What not to write',
 objectives:['obj-5.6.a'],est_minutes:8,
 cold_open:{text:'A handwritten order reads "morphine 4U IV". The U is a little open at the top. The nurse who picks that chart up next has never met you, is not on your shift, and has no way to ask what you meant before she draws it up.',
   decision_point:'What could she reasonably read that as?'},
 pretest_item:'itm-5.6.001',
 screens:[
  {id:'scr-5.6.1',body_md:'**This is a safety block, not a vocabulary block.** Every entry on the prohibited lists is there because that abbreviation has already been misread somewhere, and the misreading changed a dose or a drug.\n\nThe Joint Commission list is short enough to know outright: **U**, **IU**, **q.d.**, **q.o.d.**, trailing zeros, missing leading zeros, and **MS / MSO4 / MgSO4**. Seven entries, all of them with a body count behind them.',figure:null},
  {id:'scr-5.6.2',body_md:'**Two of them are about zeros**, and both fail by a factor of ten.\n\n**Always use a leading zero**: write 0.5 mg, never .5 mg. A decimal point that does not reproduce turns .5 into 5.\n\n**Never use a trailing zero**: write 5 mg, never 5.0 mg. A 5.0 read without its point becomes 50.\n\nThe one exception is a reported measurement where the zero shows precision — a lesion size, a tube size. Never in a medication.',figure:null},
  {id:'scr-5.6.3',body_md:'**Some are about the drug itself.** **MS** can mean morphine sulfate or magnesium sulfate. **MSO4** and **MgSO4** look alike written quickly. All three are prohibited; write the drug name out.\n\n**U** for unit is read as a zero or a four — 4U becomes 40. **IU** is read as IV, or as the number 10. **q.d.** and **q.o.d.** are read as each other, which changes a daily drug into an alternate-day one.',figure:null},
  {id:'scr-5.6.4',body_md:'**Others are flagged as error-prone** rather than prohibited outright, and are worth avoiding anyway.\n\n**@** is read as the number 2 — write *at*.\n**cc** is read as U — write *mL*.\n**\u00b5g** is read as mg — write *mcg*. That one is a thousandfold error.\n**>** and **<** are read as each other, and as the number 7.',figure:null},
  {id:'scr-5.6.5',body_md:'**Your agency list is the operative rule for your ePCR**, and it may permit something a national list flags. Where the two disagree, write it out — nothing is lost by being unambiguous.\n\nOne habit covers most of this. Before a chart leaves you, read the numbers back the way a stranger would: tired, at three in the morning, never having met you. Any point that could vanish? Any letter that could be a digit?\n\n*Your service’s own abbreviation list belongs here. It has not been added yet.*',figure:null}],
 inline_checks:['itm-5.6.003','itm-5.6.005'],
 quiz:['itm-5.6.002','itm-5.6.004','itm-5.6.006','itm-5.6.007','itm-5.6.008','itm-5.6.009'],
 callback_md:'**Morphine 40 units intravenously** — which is both a tenfold overdose and a unit that morphine is not measured in.\n\nWrite *unit* in full, and write the number so it cannot gain a digit. That is the whole of this block.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'5.INT',chapter:5,title:'Integration — decoding a handoff',learner_title:'A handoff, in real time',
 objectives:['obj-5.INT.a'],est_minutes:8,
 cold_open:{text:'You are at the bedside for a transfer. The physician and the sending nurse are talking to each other, quickly, and not slowing down for you. Everything you need in order to take this patient safely is somewhere in what they are saying to each other.',
   decision_point:'How much of it can you follow?'},
 pretest_item:null,
 screens:[
  {id:'scr-5.INT.1',body_md:'**Nobody is going to slow down for you.** A handoff between two clinicians runs at their pace, and stopping it to ask what a word means costs time and credibility.\n\nWhat follows is one report. Take each term apart as it arrives.',figure:null},
  {id:'scr-5.INT.2',body_md:'**Work back to front, one term at a time.**\n\nThe suffix first · what kind of thing is this? A condition, a procedure, a measurement? Then the root · where in the body? Then the prefix · how much, which direction, when?\n\nThree questions in that order, and most terms fall open in about a second.',figure:null},
  {id:'scr-5.INT.3',body_md:'**You are not listening for every word.** You are listening for the handful that change what you do on the way in.\n\nA risk factor. A current abnormality. A trend overnight. A negative finding that rules something out.\n\nThe rest is context you can read off the paperwork later. What follows is one report. Take each term apart as it arrives.',figure:null}],
 inline_checks:[],
 quiz:['itm-5.INT.000'],
 callback_md:'Every term in that report came apart into parts you already had. Three days post **cholecystectomy** — gallbladder removed. **Tachypnea** and **hypoxemia** — breathing fast, low blood oxygen. No **hemoptysis** — not coughing blood. **Epigastric** tenderness, no **peritonitis**. **Oliguric** — passing little urine.\n\nYou were not told what any of those meant. You read them.',
 local_overlay:'ks-amr-kc',version:'1.0.0'}
];
