// Chapter 3 — Medical, Legal and Ethical Issues.
// This is the chapter where state law does most of the work, and state law is
// exactly what a portable module cannot assert. Consent ages, refusal
// documentation, mandatory reporting and the name and design of the portable
// medical order form all vary. Every one of those is marked for the local
// overlay rather than guessed at here.
const STD='NHTSA National EMS Education Standards (2021) — Preparatory: Medical/Legal and Ethical Issues.';
const CAP='Appelbaum PS. Assessment of patients’ competence to consent to treatment. N Engl J Med 2007;357:1834–40.';
const HIPAA='HIPAA Privacy Rule, 45 CFR Parts 160 and 164.';
const POLST='National POLST — portable medical orders: form structure and completion standards.';
const EMTALA='Emergency Medical Treatment and Labor Act, 42 U.S.C. §1395dd; 42 CFR 489.24.';

const opt=(id,text,correct,rationale)=>({id,text,correct,rationale});
const base=(o)=>({stimulus:{kind:'none',ref:null},bloom:'apply',nremt_domain:'ems_operations',
  cj_step:null,difficulty_seed:0.5,high_stakes:false,reviewed_by:null,
  review_status:'unreviewed',version:'1.0.0',...o});

export const objectives=[
 {id:'obj-3.1.a',chapter:3,tier:'core',text:'Explain duty to act, abandonment and the point at which care may be transferred',
  enables:'Know when your responsibility for a patient begins and the only ways it properly ends'},
 {id:'obj-3.2.a',chapter:3,tier:'core',text:'Differentiate expressed, informed and implied consent, and apply each',
  enables:'Get consent that is worth something, rather than a signature on a page'},
 {id:'obj-3.3.a',chapter:3,tier:'core',text:'Assess decision-making capacity using the four abilities, and handle minors',
  enables:'Decide whether this patient’s answer is a decision or a symptom'},
 {id:'obj-3.4.a',chapter:3,tier:'core',text:'Identify the four elements of negligence and what establishes each',
  enables:'Understand what a claim would actually have to prove about a call you ran'},
 {id:'obj-3.5.a',chapter:3,tier:'core',text:'Manage a refusal of care safely, and document what makes it defensible',
  enables:'Handle the highest-risk call type at this level without leaving a patient or yourself exposed'},
 {id:'obj-3.6.a',chapter:3,tier:'core',text:'Apply advance directives and portable medical orders, including an incomplete form',
  enables:'Follow a standing instruction about resuscitation correctly, in a room, at speed'},
 {id:'obj-3.7.a',chapter:3,tier:'core',text:'Apply confidentiality rules to handover, records, family and social media',
  enables:'Share what care requires and nothing else, which is where most breaches happen'},
 {id:'obj-3.8.a',chapter:3,tier:'context',text:'Apply ethical reasoning, mandatory reporting duties, crime scene and donation considerations',
  enables:'Act on an obligation that is not clinical, without losing the patient in front of you'},
 {id:'obj-3.INT.a',chapter:3,tier:'core',text:'Integrate capacity, refusal, advance directives and documentation on one call',
  enables:'Hold a refusal, a form and a family in the same room without any of them deciding for you'}
];

export const items=[
// ── 3.1 Duty, abandonment, transfer of care ───────────────────────────── 8
base({id:'itm-3.1.001',type:'mc',chapter:3,block:'3.1',objective:'obj-3.1.a',bloom:'understand',
 stem:'What creates a duty to act on a dispatched call?',
 options:[opt('a','Being on duty and dispatched — the service has contracted to respond and you are its crew',true,'The duty comes from the employment and the dispatch, not from proximity.'),
  opt('b','Being the nearest trained person',false,'Nearness alone does not create a legal duty in most jurisdictions.'),
  opt('c','Holding a current certification',false,'Certification establishes competence, not an obligation to any particular patient.'),
  opt('d','The patient asking for help',false,'A request does not by itself create the duty; the dispatch and your role do.')],
 explanation_md:'Duty to act is the first element a negligence claim has to establish, and on a dispatched call it is rarely in dispute. Off duty it usually is.',source_ref:STD}),
base({id:'itm-3.1.002',type:'mc',chapter:3,block:'3.1',objective:'obj-3.1.a',high_stakes:true,
 stem:'You hand your patient to a nurse in a corridor who says they will "get to them shortly" and walks away. What have you got?',
 options:[opt('a','An incomplete transfer — you remain responsible until someone of equal or higher level accepts the patient',true,'Leaving now is abandonment, whatever the corridor looks like.'),
  opt('b','A completed transfer, because you handed over in the hospital',false,'The building does not accept the patient. A person does.'),
  opt('c','A completed transfer once you have written your report',false,'Documentation records the transfer; it does not perform it.'),
  opt('d','A transfer completed by the dispatch clearing you',false,'Dispatch status has nothing to do with clinical responsibility.')],
 explanation_md:'Abandonment is ending care without a proper handover to someone able to continue it. A busy department is the commonest place it nearly happens.',source_ref:STD}),
base({id:'itm-3.1.003',type:'mc',chapter:3,block:'3.1',objective:'obj-3.1.a',bloom:'remember',
 stem:'What does abandonment mean in this context?',
 options:[opt('a','Ending care without transferring the patient to someone of equal or higher training',true,'The definition turns on who receives the patient, not on how long you stayed.'),
  opt('b','Refusing to respond to a dispatch',false,'That is a different failure, and it is not abandonment.'),
  opt('c','Transporting to the wrong hospital',false,'A destination error is not abandonment.'),
  opt('d','Leaving a scene before police arrive',false,'Not in itself abandonment.')],
 explanation_md:'Equal or higher level, and they have to actually accept. Handing to a lower level ends your care in name only.',source_ref:STD}),
base({id:'itm-3.1.004',type:'mr',chapter:3,block:'3.1',objective:'obj-3.1.a',bloom:'remember',select_count:[2,3],
 stem:'Select what must be true for a transfer of care to be complete.',
 options:[opt('a','The receiving provider is of equal or higher training',true,'Handing down the chain does not discharge the responsibility.'),
  opt('b','The receiving provider has accepted the patient',true,'Acceptance is an act, not an assumption.'),
  opt('c','A verbal report of the patient’s condition and what you did has been given',true,'Without it, the patient arrives without a history.'),
  opt('d','The patient has been moved onto a hospital bed',false,'Useful and not what completes the transfer.'),
  opt('e','Your written report has been submitted',false,'The written record can follow; the handover cannot.')],
 explanation_md:'Equal or higher, accepted, and told what they need. Three things, and the second is the one that gets skipped in a full corridor.',source_ref:STD}),
base({id:'itm-3.1.005',type:'mc',chapter:3,block:'3.1',objective:'obj-3.1.a',
 stem:'Off duty, you stop at a collision and begin care. What generally follows?',
 options:[opt('a','Having begun, you are expected to continue until someone equal or higher takes over',true,'Starting voluntarily creates an expectation of continuing reasonably.'),
  opt('b','You may stop at any time for any reason',false,'Beginning care changes the position, which is why the decision to start matters.'),
  opt('c','You automatically have the same duties as when on duty',false,'The off-duty position differs, and it is state-specific.'),
  opt('d','You have no legal exposure of any kind',false,'Protections vary by state and are not absolute.')],
 explanation_md:'Good Samaritan statutes exist in every state and differ in what they cover; most do not protect someone acting within their paid employment. The detail belongs to your state.',source_ref:STD}),
base({id:'itm-3.1.006',type:'options_box',chapter:3,block:'3.1',objective:'obj-3.1.a',bloom:'analyze',
 stem:'Abandonment, or not?',
 columns:[{id:'yes',label:'Abandonment'},{id:'no',label:'Not abandonment'}],
 rows:[{id:'r1',label:'Leaving a patient on a corridor trolley with no one having accepted them',answer:'yes'},
  {id:'r2',label:'Handing an AEMT-level patient to a receiving paramedic with a full report',answer:'no'},
  {id:'r3',label:'Leaving an intoxicated patient with a police officer and no clinical handover',answer:'yes'},
  {id:'r4',label:'Transferring care to an arriving paramedic crew on scene',answer:'no'}],
 options:[],
 explanation_md:'Two of these involve someone being physically present. Presence is not acceptance, and a police officer is not a clinical handover.',source_ref:STD}),
base({id:'itm-3.1.007',type:'mc',chapter:3,block:'3.1',objective:'obj-3.1.a',bloom:'analyze',
 stem:'Why does the law treat starting care as changing your position?',
 options:[opt('a','Because others stop helping once someone has taken charge, so stopping leaves the patient worse off than if you had not begun',true,'Reliance is the reasoning, and it is why beginning is the decision point.'),
  opt('b','Because starting care creates a contract with the patient',false,'That is not the mechanism.'),
  opt('c','Because it transfers liability from the service to you',false,'It does not work that way.'),
  opt('d','Because certification requires it',false,'Certification is not the source of the obligation.')],
 explanation_md:'Bystanders stand back. Another vehicle passes. The patient is now relying on you, and that reliance is what makes walking away different from never having stopped.',source_ref:STD}),
base({id:'itm-3.1.008',type:'mc',chapter:3,block:'3.1',objective:'obj-3.1.a',
 stem:'A hospital tells you to take a patient elsewhere because they are on diversion, and the patient is unstable. What governs?',
 options:[opt('a','A hospital with an emergency department must provide a medical screening examination to anyone who presents, regardless of diversion',true,'Federal law requires screening and stabilisation once a patient presents.'),
  opt('b','Diversion is binding and you must go elsewhere',false,'Diversion is a resource signal, and it does not override the screening obligation for a patient who presents.'),
  opt('c','The patient’s insurance decides',false,'Insurance status may not be used to decide whether the patient is screened.'),
  opt('d','Whichever hospital is nearest must be used',false,'That is not what the obligation says.')],
 explanation_md:'The law aimed at patients being turned away is worth knowing by name. Diversion requests still deserve cooperation where the patient can safely go elsewhere — but they are not a legal wall.',source_ref:EMTALA}),

// ── 3.2 Consent ───────────────────────────────────────────────────────── 8
base({id:'itm-3.2.001',type:'mc',chapter:3,block:'3.2',objective:'obj-3.2.a',bloom:'understand',
 stem:'What makes consent informed rather than merely given?',
 options:[opt('a','The patient was told what you propose, why, the risks, and what happens if they decline',true,'Information about the alternative — including refusing — is the part most often left out.'),
  opt('b','The patient signed a form',false,'A signature records consent. It does not create it.'),
  opt('c','The patient did not object',false,'Silence is not informed consent.'),
  opt('d','A family member agreed',false,'Family agreement is not the patient’s consent.')],
 explanation_md:'Informed means the patient could weigh it: what you want to do, why, what could go wrong, and what happens if they say no.',source_ref:STD}),
base({id:'itm-3.2.002',type:'drag_drop',chapter:3,block:'3.2',objective:'obj-3.2.a',high_stakes:true,
 stem:'Sort each situation by the type of consent it relies on.',
 categories:[{id:'exp',label:'Expressed consent'},{id:'imp',label:'Implied consent'},{id:'sub',label:'Consent by another'}],
 options:[opt('a','An alert adult agrees to an intravenous line after you explain it',true,'Expressed, and informed if you explained it properly.'),
  opt('b','An unconscious adult in cardiac arrest',true,'Implied: a reasonable person would consent to lifesaving care.'),
  opt('c','A parent agrees to treatment for their seven-year-old',true,'Consent given by someone legally authorised for the patient.'),
  opt('d','A patient rolls up a sleeve and holds out an arm for a blood pressure',true,'Expressed by conduct — still the patient’s own consent.')],
 answer_map:{a:'exp',b:'imp',c:'sub',d:'exp'},
 explanation_md:'Implied consent is a legal presumption for someone who cannot consent and needs emergency care. It is not a general fallback for a patient who is simply difficult.',source_ref:STD}),
base({id:'itm-3.2.003',type:'mc',chapter:3,block:'3.2',objective:'obj-3.2.a',high_stakes:true,
 stem:'An unconscious adult needs emergency care and no family is present. On what basis do you treat?',
 options:[opt('a','Implied consent — the law presumes a reasonable person would consent to emergency care',true,'It applies because the patient cannot consent and the care is needed now.'),
  opt('b','You may not treat without written consent',false,'That reading would let people die for want of a signature.'),
  opt('c','Consent from the police officer on scene',false,'A police officer cannot consent for a patient.'),
  opt('d','Medical control can consent on the patient’s behalf',false,'Medical direction authorises the care; it does not consent for the patient.')],
 explanation_md:'Implied consent covers the emergency and no more. It does not extend to whatever else you would like to do while they cannot object.',source_ref:STD}),
base({id:'itm-3.2.004',type:'mr',chapter:3,block:'3.2',objective:'obj-3.2.a',bloom:'remember',select_count:[3,4],
 stem:'Select what informed consent requires you to tell the patient.',
 options:[opt('a','What you propose to do',true,'The intervention itself, in words they use.'),
  opt('b','Why you are proposing it',true,'The reason is what makes the risk worth taking.'),
  opt('c','The significant risks',true,'Not every risk — the ones that would matter to a reasonable person.'),
  opt('d','What is likely to happen if they decline',true,'The most frequently omitted part, and the one that matters most in a refusal.'),
  opt('e','The cost of the transport',false,'It may concern the patient and it is not part of clinical informed consent.')],
 explanation_md:'Propose, why, risks, and what happens if they say no. The fourth is the one that turns a refusal into an informed refusal.',source_ref:STD}),
base({id:'itm-3.2.005',type:'mc',chapter:3,block:'3.2',objective:'obj-3.2.a',high_stakes:true,
 stem:'A 16-year-old is injured at school, is alert, and no parent can be reached. What is the general position?',
 options:[opt('a','Treat what needs treating, keep trying to reach a parent, and check your state’s rules on minors — they vary',true,'Emergency care is not withheld while you search for a parent, and the consent rules themselves are state law.'),
  opt('b','Do nothing until a parent consents',false,'Withholding emergency care while you telephone is not defensible.'),
  opt('c','The school principal consents on the parent’s behalf',false,'Sometimes arranged in writing, and not something to assume.'),
  opt('d','A 16-year-old may always consent for themselves',false,'Some states allow this in some circumstances. It is not a general rule.')],
 explanation_md:'Emancipation, mature minor provisions and consent for specific care all vary by state. Treat the emergency, keep trying for the parent, and get your state’s rule into the local layer.',source_ref:STD}),
base({id:'itm-3.2.006',type:'options_box',chapter:3,block:'3.2',objective:'obj-3.2.a',
 stem:'Does this count as consent to the procedure?',
 columns:[{id:'yes',label:'Consent'},{id:'no',label:'Not consent'}],
 rows:[{id:'r1',label:'An alert patient says yes after you explain the line and why you want it',answer:'yes'},
  {id:'r2',label:'A patient signs a form nobody read to them',answer:'no'},
  {id:'r3',label:'A patient holds out an arm when you ask for one',answer:'yes'},
  {id:'r4',label:'A confused patient does not resist',answer:'no'}],
 options:[],
 explanation_md:'Not resisting is not consenting, and a signature without an explanation is a record of nothing. Both are extremely common.',source_ref:STD}),
base({id:'itm-3.2.007',type:'mc',chapter:3,block:'3.2',objective:'obj-3.2.a',bloom:'analyze',
 stem:'Why is touching a patient who has refused a serious matter, beyond being poor practice?',
 options:[opt('a','Unconsented touching can be a battery, and consent is what makes lawful care lawful',true,'Consent is the legal basis for touching someone at all.'),
  opt('b','It breaches the patient’s privacy',false,'Privacy is a separate issue.'),
  opt('c','It is a protocol violation only',false,'It is more than an internal matter.'),
  opt('d','It only matters if the patient is injured by it',false,'Injury affects damages, not whether the touching was permitted.')],
 explanation_md:'This is why consent sits at the front of this chapter. Everything you do to a patient is permitted by it, and without it the same act has a different name.',source_ref:STD}),
base({id:'itm-3.2.008',type:'mc',chapter:3,block:'3.2',objective:'obj-3.2.a',
 stem:'A patient consented to a blood glucose check and now says stop as you approach with the lancet. What do you do?',
 options:[opt('a','Stop — consent can be withdrawn at any point, including part-way through',true,'Consent is continuing permission, not a one-time gate.'),
  opt('b','Continue, since they already agreed',false,'Prior agreement does not authorise continuing after a withdrawal.'),
  opt('c','Continue if it is nearly done',false,'Nearly done is not a legal category.'),
  opt('d','Ask a family member to overrule them',false,'Family cannot overrule a patient with capacity.')],
 explanation_md:'Consent is a running state, not a signature at the start. When it stops, you stop, and then you find out what changed.',source_ref:STD}),
// ── 3.3 Capacity, and the four abilities ──────────────────────────────── 8
base({id:'itm-3.3.001',type:'mc',chapter:3,block:'3.3',objective:'obj-3.3.a',bloom:'understand',high_stakes:true,
 stem:'What does assessing decision-making capacity actually involve?',
 options:[opt('a','Testing four abilities: understanding, appreciating it applies to them, reasoning, and expressing a choice',true,'These four are the standard framework and they can be assessed in a few minutes.'),
  opt('b','Checking whether the patient agrees with your recommendation',false,'Disagreeing with you is not evidence of incapacity, and treating it that way is the core error.'),
  opt('c','Asking the patient their name, the date and the place',false,'Orientation is a screen for something else. It does not establish capacity for this decision.'),
  opt('d','Obtaining a doctor’s opinion in every case',false,'You assess it at the bedside; that is what the framework is for.')],
 explanation_md:'Understand, appreciate, reason, express a choice. Capacity is decision-specific and time-specific, which is why it is assessed rather than looked up.',source_ref:CAP}),
base({id:'itm-3.3.002',type:'mr',chapter:3,block:'3.3',objective:'obj-3.3.a',bloom:'remember',select_count:[4,4],
 stem:'Select the four abilities that make up decision-making capacity.',
 options:[opt('a','Understanding the information relevant to the decision',true,'Can they take in what you told them?'),
  opt('b','Appreciating that it applies to their own situation',true,'Understanding in the abstract while denying it applies is the classic gap.'),
  opt('c','Reasoning — weighing the options against each other',true,'Not whether the reasoning matches yours, but whether there is any.'),
  opt('d','Expressing a choice',true,'A choice that can be communicated and is reasonably stable.'),
  opt('e','Agreeing with the clinician’s recommendation',false,'This is not part of it, and treating it as if it were is how refusals go wrong.')],
 explanation_md:'The fifth option is the trap and it is the common failure. A patient with capacity is allowed to make a decision you think is wrong.',source_ref:CAP}),
base({id:'itm-3.3.003',type:'mc',chapter:3,block:'3.3',objective:'obj-3.3.a',high_stakes:true,
 stem:'A patient with chest pain refuses transport, answers everything correctly, and can explain what could happen. Does he have capacity?',
 options:[opt('a','Yes — capacity is about the process of deciding, not the wisdom of the decision',true,'He understands, appreciates, can reason and has expressed a choice.'),
  opt('b','No — refusing transport for chest pain is itself evidence of incapacity',false,'This is the error the framework exists to prevent.'),
  opt('c','No, unless a physician confirms it',false,'You assess it; a physician conversation may still help him decide.'),
  opt('d','Only if he signs the refusal form',false,'A signature documents a refusal; it does not create capacity.')],
 explanation_md:'A capable adult may make a decision that harms them. Your job is to make sure it is genuinely informed, not to make it come out right.',source_ref:CAP}),
base({id:'itm-3.3.004',type:'options_box',chapter:3,block:'3.3',objective:'obj-3.3.a',bloom:'analyze',
 stem:'Does this cast real doubt on capacity?',
 columns:[{id:'yes',label:'Casts doubt'},{id:'no',label:'Does not'}],
 rows:[{id:'r1',label:'The patient cannot repeat back what you just explained',answer:'yes'},
  {id:'r2',label:'The patient disagrees with your recommendation',answer:'no'},
  {id:'r3',label:'The patient denies the injury is theirs despite seeing it',answer:'yes'},
  {id:'r4',label:'The patient is frightened and tearful but answers clearly',answer:'no'}],
 options:[],
 explanation_md:'Two of these are failures of understanding or appreciation. The other two are a patient exercising a right while upset, which is not the same thing at all.',source_ref:CAP}),
base({id:'itm-3.3.005',type:'mc',chapter:3,block:'3.3',objective:'obj-3.3.a',high_stakes:true,
 stem:'A head-injured patient who smells of alcohol wants to refuse. What is the safest reading?',
 options:[opt('a','Both the head injury and the intoxication can impair capacity, so the threshold for accepting a refusal is high',true,'Two plausible causes of impairment, and the injury itself can worsen.'),
  opt('b','Intoxication always removes capacity',false,'It can impair it. It does not automatically abolish it, and treating it as automatic is also wrong.'),
  opt('c','If he can walk and talk, he has capacity',false,'Walking and talking is not the test.'),
  opt('d','A signed refusal resolves it',false,'A signature from someone without capacity resolves nothing.')],
 explanation_md:'Assess against the four abilities, involve medical control, try hard to persuade, and do not treat the form as the point of the exercise.',source_ref:CAP}),
base({id:'itm-3.3.006',type:'mc',chapter:3,block:'3.3',objective:'obj-3.3.a',bloom:'analyze',
 stem:'Why is capacity described as decision-specific rather than as a property of a person?',
 options:[opt('a','Someone may have capacity for a simple decision and not for a complex one, and it can change within an hour',true,'It is assessed for this decision, now.'),
  opt('b','Because it is recorded on a legal document',false,'Capacity is clinical; competence is the legal determination.'),
  opt('c','Because it is decided by a physician',false,'Any assessing clinician can evaluate it.'),
  opt('d','Because it varies by state',false,'The framework does not change at a state line.')],
 explanation_md:'A hypoglycaemic patient may lack capacity at 0800 and have it at 0815. Documenting *when* you assessed it, and against what decision, is what makes the note useful.',source_ref:CAP}),
base({id:'itm-3.3.007',type:'mc',chapter:3,block:'3.3',objective:'obj-3.3.a',bloom:'remember',
 stem:'What is the difference between capacity and competence?',
 options:[opt('a','Capacity is a clinical assessment at the bedside; competence is a legal determination by a court',true,'You assess capacity. A court determines competence.'),
  opt('b','They are the same thing',false,'They are used interchangeably in conversation and are not the same.'),
  opt('c','Capacity applies to minors only',false,'It applies to any patient making a decision.'),
  opt('d','Competence is assessed by the medical director',false,'It is a judicial determination.')],
 explanation_md:'Worth keeping straight because the words get swapped constantly, including in charts. What you write about is capacity.',source_ref:CAP}),
base({id:'itm-3.3.008',type:'mc',chapter:3,block:'3.3',objective:'obj-3.3.a',
 stem:'A patient in police custody wants to refuse care. Who decides?',
 options:[opt('a','It depends on the custody status and state law — the patient may no longer be free to refuse, and this belongs in your local protocol',true,'Custody changes the position, and how it changes is jurisdictional.'),
  opt('b','The patient always decides, custody changes nothing',false,'Custody can change who may consent or refuse.'),
  opt('c','The officer always decides',false,'Not a general rule either.'),
  opt('d','You decide on clinical grounds',false,'The decision is not yours to make on those grounds.')],
 explanation_md:'One of several places in this chapter where the honest answer is that your state and your protocol settle it. Find out before the call, not during it.',source_ref:STD}),

// ── 3.4 Negligence ────────────────────────────────────────────────────── 8
base({id:'itm-3.4.001',type:'build_list',chapter:3,block:'3.4',objective:'obj-3.4.a',bloom:'remember',high_stakes:true,
 stem:'Place the four elements of negligence in the order a claim must establish them.',
 options:[opt('a','Duty to act',true,'Nothing else matters unless a duty existed.'),
  opt('b','Breach of duty',true,'The care fell below the standard of care.'),
  opt('c','Causation',true,'The breach caused the harm, rather than merely preceding it.'),
  opt('d','Damages',true,'Actual harm resulted. Without harm there is no negligence claim.')],
 explanation_md:'Duty, breach, causation, damages. All four, or the claim fails — which is why a bad call that harms nobody is not negligence, however uncomfortable it was.',source_ref:STD}),
base({id:'itm-3.4.002',type:'mc',chapter:3,block:'3.4',objective:'obj-3.4.a',high_stakes:true,
 stem:'You depart from protocol and the patient is unharmed. What has a negligence claim lost?',
 options:[opt('a','Damages — without actual harm, the claim does not stand',true,'The other three may be arguable. Damages is the one missing.'),
  opt('b','Duty',false,'The duty existed throughout.'),
  opt('c','Breach',false,'A departure from protocol is exactly what a breach argument is built on.'),
  opt('d','Nothing — the claim is complete',false,'All four elements are needed.')],
 explanation_md:'This is not permission. It is the reason a near miss goes to quality improvement rather than to court, and why reporting it costs you less than you think.',source_ref:STD}),
base({id:'itm-3.4.003',type:'mc',chapter:3,block:'3.4',objective:'obj-3.4.a',bloom:'understand',
 stem:'Against what is breach of duty measured?',
 options:[opt('a','What a reasonable provider of the same level would have done in the same circumstances',true,'The standard of care, judged on the situation as it was, not with hindsight.'),
  opt('b','What the best provider in the service would have done',false,'The standard is reasonable, not optimal.'),
  opt('c','What a physician would have done',false,'You are judged against your own level.'),
  opt('d','What the patient expected',false,'Expectation is not the standard.')],
 explanation_md:'Protocol is strong evidence of what reasonable looks like, which is why departing from it needs a reason you can state.',source_ref:STD}),
base({id:'itm-3.4.004',type:'options_box',chapter:3,block:'3.4',objective:'obj-3.4.a',bloom:'analyze',
 stem:'Which element does each fact go to?',
 columns:[{id:'duty',label:'Duty'},{id:'breach',label:'Breach'},{id:'cause',label:'Causation'},{id:'dmg',label:'Damages'}],
 rows:[{id:'r1',label:'The crew was dispatched and on duty',answer:'duty'},
  {id:'r2',label:'The protocol required a glucose check and none was done',answer:'breach'},
  {id:'r3',label:'The missed hypoglycaemia led to a prolonged seizure',answer:'cause'},
  {id:'r4',label:'The patient sustained a permanent deficit',answer:'dmg'}],
 options:[],
 explanation_md:'Laid out this way it is a chain, and the weakest link decides it. Causation is usually the contested one.',source_ref:STD}),
base({id:'itm-3.4.005',type:'mc',chapter:3,block:'3.4',objective:'obj-3.4.a',bloom:'analyze',
 stem:'Why is causation the element most often argued over?',
 options:[opt('a','Because a patient may have deteriorated for reasons unrelated to the breach, and separating the two is genuinely hard',true,'Sequence is easy to show. Cause is not.'),
  opt('b','Because duty is always disputed',false,'On a dispatched call it rarely is.'),
  opt('c','Because damages are impossible to measure',false,'Damages are difficult to quantify, not to establish.'),
  opt('d','Because the standard of care is never written down',false,'It is evidenced by protocol, guidelines and expert testimony.')],
 explanation_md:'Something happening after an error is not the same as the error having caused it. That gap is where these cases are decided.',source_ref:STD}),
base({id:'itm-3.4.006',type:'mc',chapter:3,block:'3.4',objective:'obj-3.4.a',
 stem:'How does thorough documentation affect a negligence claim?',
 options:[opt('a','It is the record of what was assessed and done, and what you did not write is treated as not done',true,'The chart is usually the only contemporaneous account left.'),
  opt('b','It prevents claims being brought',false,'It does not prevent a claim; it decides how one goes.'),
  opt('c','It transfers liability to the service',false,'Documentation does not move liability.'),
  opt('d','It matters only in criminal cases',false,'It matters most in civil ones.')],
 explanation_md:'Two years later nobody remembers the call. The note is the witness, and a gap in it reads as an omission rather than as forgetfulness.',source_ref:STD}),
base({id:'itm-3.4.007',type:'mc',chapter:3,block:'3.4',objective:'obj-3.4.a',bloom:'understand',
 stem:'What is gross negligence, as distinct from ordinary negligence?',
 options:[opt('a','Conduct showing a reckless disregard for the patient’s safety, beyond a failure to meet the standard',true,'The difference is in degree and state of mind, and it matters for what protections apply.'),
  opt('b','Negligence causing death',false,'The outcome does not define the category.'),
  opt('c','Negligence by more than one provider',false,'Number of providers is irrelevant.'),
  opt('d','Any deliberate act',false,'Deliberate harm is a different category again.')],
 explanation_md:'Most legal protections, including Good Samaritan statutes, stop at gross negligence. That is where the line is usually drawn.',source_ref:STD}),
base({id:'itm-3.4.008',type:'mc',chapter:3,block:'3.4',objective:'obj-3.4.a',
 stem:'Your protocol says one thing and you did another, for a reason you can explain. What follows?',
 options:[opt('a','You will have to justify the departure, and a stated clinical reason recorded at the time is what makes that possible',true,'Departures are sometimes right; unexplained departures are not defensible.'),
  opt('b','A departure from protocol is automatically negligence',false,'It is evidence of breach, not proof of it.'),
  opt('c','Protocol has no legal weight at all',false,'It is strong evidence of the standard of care.'),
  opt('d','Nothing, provided the patient recovered',false,'Outcome does not retrospectively authorise the decision.')],
 explanation_md:'Write the reasoning, not just the action. "Deviated from protocol because..." is a very different note from a blank where the protocol step should be.',source_ref:STD}),
// ── 3.5 Refusal of care — the highest-risk call you run ───────────────── 9
base({id:'itm-3.5.001',type:'mc',chapter:3,block:'3.5',objective:'obj-3.5.a',bloom:'understand',high_stakes:true,
 stem:'What has to be established before a refusal of transport is a refusal at all?',
 options:[opt('a','That the patient has capacity and has been informed of the risks of declining',true,'Without both, there is no valid refusal — only a patient who was left behind.'),
  opt('b','That the patient has signed the refusal form',false,'The signature records it. It does not validate it.'),
  opt('c','That a family member agrees with the decision',false,'Family agreement is not required and does not substitute for capacity.'),
  opt('d','That medical control has authorised the release',false,'Contact is often required by protocol and it is not what makes the refusal valid.')],
 explanation_md:'Capacity, plus information about what declining risks. Everything else on the form is documentation of those two things.',source_ref:STD}),
base({id:'itm-3.5.002',type:'mr',chapter:3,block:'3.5',objective:'obj-3.5.a',bloom:'remember',select_count:[4,5],
 stem:'Select what a defensible refusal record contains.',
 options:[opt('a','The capacity assessment — what you asked and what they said, not a conclusion alone',true,'"Alert and oriented" is not a capacity assessment.'),
  opt('b','The specific risks you explained, including the possibility of death where that is real',true,'Named, not summarised as "risks explained".'),
  opt('c','That the patient could repeat the risks back in their own words',true,'The strongest single line in the record.'),
  opt('d','That they were told they may call again at any time, with no penalty',true,'It keeps the door open, and it belongs in the note.'),
  opt('e','Your opinion that the patient was being unreasonable',false,'It adds nothing and reads badly two years later.')],
 explanation_md:'The note that holds up describes a conversation. The one that does not holds a signature and the phrase "refused, AMA".',source_ref:STD}),
base({id:'itm-3.5.003',type:'mc',chapter:3,block:'3.5',objective:'obj-3.5.a',high_stakes:true,
 stem:'A hypoglycaemic patient treated with glucose is now alert and refuses transport. What is the concern?',
 options:[opt('a','He may become hypoglycaemic again — the refusal needs a plan for eating, a responsible adult, and what would make him call back',true,'Capacity has returned. The risk has not gone away with it.'),
  opt('b','He cannot refuse, because he was hypoglycaemic earlier',false,'Capacity is assessed now, and it has returned.'),
  opt('c','A signature on the form resolves it',false,'It resolves nothing about what happens in two hours.'),
  opt('d','Nothing — the treatment worked',false,'The treatment worked and the underlying cause is unchanged.')],
 explanation_md:'One of the most common refusals at this level and one of the most often documented badly. What goes in the note is the plan, not the fact of the refusal.',source_ref:STD}),
base({id:'itm-3.5.004',type:'options_box',chapter:3,block:'3.5',objective:'obj-3.5.a',bloom:'analyze',high_stakes:true,
 stem:'Can this refusal be accepted as it stands?',
 columns:[{id:'yes',label:'Can be accepted'},{id:'no',label:'Cannot, as it stands'}],
 rows:[{id:'r1',label:'Alert adult with an ankle injury who can state the risks of not going',answer:'yes'},
  {id:'r2',label:'Head-injured patient who cannot recall the conversation you just had',answer:'no'},
  {id:'r3',label:'Patient with chest pain who repeats back that he could die and still declines',answer:'yes'},
  {id:'r4',label:'A parent refusing transport for a child with an altered level of consciousness',answer:'no'}],
 options:[],
 explanation_md:'Two turn on capacity that is not there. The third is a capable adult making a decision you do not like, which is his to make.',source_ref:CAP}),
base({id:'itm-3.5.005',type:'mc',chapter:3,block:'3.5',objective:'obj-3.5.a',
 stem:'What should you do before leaving a patient who has refused?',
 options:[opt('a','Offer again, say plainly that they can call back at any time, and leave a way to do it',true,'People change their minds, and the offer has to be genuinely open.'),
  opt('b','Warn them that calling again may be refused',false,'Untrue and it deters the call you most want them to make.'),
  opt('c','Have them sign and leave promptly',false,'The signature is not the objective.'),
  opt('d','Ask a neighbour to take responsibility for them',false,'Not yours to delegate, and it does not make anyone accountable.')],
 explanation_md:'The most useful sentence in a refusal is that calling back costs nothing. Some of these patients call at three in the morning, and you want them to.',source_ref:STD}),
base({id:'itm-3.5.006',type:'mc',chapter:3,block:'3.5',objective:'obj-3.5.a',high_stakes:true,bloom:'analyze',
 stem:'Why is refusal the highest-risk call type at this level?',
 options:[opt('a','A patient with an unrecognised serious condition is left at the scene, and the record is often too thin to show what was assessed',true,'The clinical risk and the documentation risk arrive together.'),
  opt('b','Because the paperwork is long',false,'The paperwork is usually too short, which is the problem.'),
  opt('c','Because refusals are rare',false,'They are common, which is part of why they are treated casually.'),
  opt('d','Because the patient is always intoxicated',false,'Some are. Most are not.')],
 explanation_md:'You leave, and nobody sees the patient again until something has happened. That is the shape of the risk, and thin documentation is what makes it indefensible afterwards.',source_ref:STD}),
base({id:'itm-3.5.007',type:'drag_drop',chapter:3,block:'3.5',objective:'obj-3.5.a',high_stakes:true,
 stem:'Sort each line by whether it belongs in a refusal record.',
 categories:[{id:'in',label:'Belongs in the record'},{id:'out',label:'Does not'}],
 options:[opt('a','Patient stated the risks back in his own words, including possible death',true,'The strongest line you can write.'),
  opt('b','Refused, AMA, signed',true,'It records the outcome and nothing about how it was reached.'),
  opt('c','Told he may call 911 again at any time; he acknowledged this',true,'Keeps the door open and shows you left it open.'),
  opt('d','Patient was being difficult and would not listen',true,'An opinion, unhelpful, and it reads badly in a deposition.')],
 answer_map:{a:'in',b:'out',c:'in',d:'out'},
 explanation_md:'Two describe what happened in the room. Two describe how you felt about it, or nothing at all.',source_ref:STD}),
base({id:'itm-3.5.008',type:'mc',chapter:3,block:'3.5',objective:'obj-3.5.a',
 stem:'The patient will not sign the refusal form. What now?',
 options:[opt('a','Document the refusal to sign, ideally with a witness, and record the conversation in full',true,'The refusal is still valid; the signature was only ever evidence of it.'),
  opt('b','You may not leave until they sign',false,'You cannot detain a patient with capacity over a form.'),
  opt('c','Treat them against their will',false,'That is a serious escalation with no basis here.'),
  opt('d','Sign it on their behalf',false,'Never. That is falsification of a record.')],
 explanation_md:'The form is evidence. A well-written narrative with a witness is better evidence than a signature on a page nobody read.',source_ref:STD}),
base({id:'itm-3.5.009',type:'mc',chapter:3,block:'3.5',objective:'obj-3.5.a',bloom:'analyze',
 stem:'What does the phrase "alert and oriented ×4" establish about capacity?',
 options:[opt('a','Very little on its own — orientation is not one of the four abilities capacity is assessed against',true,'It is a screen, and it is routinely written as though it settled the question.'),
  opt('b','That the patient has capacity',false,'Orientation and capacity are different things.'),
  opt('c','That the patient understood the risks',false,'Understanding has to be demonstrated, not inferred from orientation.'),
  opt('d','That the refusal is valid',false,'It is not enough to make a refusal valid.')],
 explanation_md:'An oriented patient can still fail to appreciate that a warning applies to them. Write what they understood and what they said back — that is the assessment.',source_ref:CAP}),

// ── 3.6 Advance directives and portable medical orders ────────────────── 8
base({id:'itm-3.6.001',type:'mc',chapter:3,block:'3.6',objective:'obj-3.6.a',bloom:'understand',
 stem:'What distinguishes a portable medical order from an advance directive such as a living will?',
 options:[opt('a','It is a signed clinician order, actionable immediately; a living will states wishes for others to interpret',true,'An order can be followed. A statement of wishes has to be interpreted.'),
  opt('b','It is written by the patient rather than a clinician',false,'The clinician signature is what makes it an order.'),
  opt('c','It applies only in hospital',false,'Portability out of hospital is the whole point of it.'),
  opt('d','It expires after 30 days',false,'No such general rule.')],
 explanation_md:'The names differ by state — POLST, MOST, POST, TPOPP and others. The structure is the same, and so is the reason it exists.',source_ref:POLST}),
base({id:'itm-3.6.002',type:'graphical',chapter:3,block:'3.6',objective:'obj-3.6.a',high_stakes:true,
 stimulus:{kind:'image',ref:'aemt/fig-portable-medical-order.svg',
  alt:'Schematic of a portable medical order form. Section A, cardiopulmonary resuscitation, has both boxes unmarked. Section B has selective treatment ticked. Section C has no artificial nutrition ticked. Section D has a clinician signature line signed and a patient line blank.',
  asset_license:'Original schematic drawn for this module. AMR Kansas City, 2026. Not a reproduction of any state form.'},
 stem:'Section A of this form has been left completely unmarked. What does that mean for resuscitation?',
 options:[opt('a','Full treatment for that section — an unmarked section is not a limitation',true,'An incomplete section defaults to full treatment for that section.'),
  opt('b','The whole form is void',false,'The completed sections still stand; a blank does not invalidate them.'),
  opt('c','Comfort measures only',false,'A limitation has to be affirmatively marked, never inferred from a blank.'),
  opt('d','You must contact the signing clinician before acting',false,'The default resolves it, and a patient in arrest cannot wait for a phone call.')],
 explanation_md:'The default runs one way for a reason: a blank must never be read as permission to withhold. If nothing is marked in Section A, you resuscitate.',source_ref:POLST}),
base({id:'itm-3.6.003',type:'mc',chapter:3,block:'3.6',objective:'obj-3.6.a',high_stakes:true,
 stem:'A patient with a valid do-not-resuscitate order is choking and in severe respiratory distress, but has a pulse. What do you do?',
 options:[opt('a','Treat the obstruction — a DNR order addresses resuscitation from arrest, not all care',true,'DNR is not "do not treat", and this patient is not in arrest.'),
  opt('b','Withhold all intervention',false,'That is the most consequential misreading of a DNR there is.'),
  opt('c','Provide comfort measures only',false,'Not what the order says, and not what the patient needs.'),
  opt('d','Contact medical control before any intervention',false,'An airway obstruction does not wait for a radio conversation.')],
 explanation_md:'This misunderstanding kills people who were never meant to die of it. Read what the order actually limits, and treat everything it does not.',source_ref:POLST}),
base({id:'itm-3.6.004',type:'mr',chapter:3,block:'3.6',objective:'obj-3.6.a',bloom:'remember',select_count:[3,4],
 stem:'Select what you should check before acting on a portable medical order form.',
 options:[opt('a','That it identifies this patient',true,'A form on the fridge may belong to a former resident.'),
  opt('b','That it carries the required clinician signature',true,'Without it, it is not an order.'),
  opt('c','Which sections are marked, and which are blank',true,'Blanks default to full treatment for that section.'),
  opt('d','Whether the patient or family is now revoking it',true,'A patient with capacity may revoke at any time.'),
  opt('e','Whether you personally agree with the decision',false,'Not a factor, and not yours.')],
 explanation_md:'Identity, signature, sections, and whether it still stands. Four checks, and in an arrest you make them in about fifteen seconds.',source_ref:POLST}),
base({id:'itm-3.6.005',type:'mc',chapter:3,block:'3.6',objective:'obj-3.6.a',high_stakes:true,
 stem:'The family produces a DNR order and then says they have changed their mind and want everything done. The patient cannot speak. What governs?',
 options:[opt('a','Follow your protocol and contact medical control — a family dispute at the bedside is exactly what online direction is for',true,'This is contested, time-critical and jurisdiction-specific. Do not resolve it alone.'),
  opt('b','The family’s wish overrides the order automatically',false,'Who may revoke, and how, is set by state law.'),
  opt('c','The order is binding and the family may be ignored',false,'Also too simple, and it leaves you arguing in a living room.'),
  opt('d','Begin resuscitation and ignore the form entirely',false,'Discarding a valid order is not a neutral act.')],
 explanation_md:'Who may revoke a portable medical order varies by state. The defensible move is the radio, and the local layer should tell you the answer before this happens.',source_ref:POLST}),
base({id:'itm-3.6.006',type:'options_box',chapter:3,block:'3.6',objective:'obj-3.6.a',bloom:'analyze',
 stem:'Does a do-not-resuscitate order withhold this?',
 columns:[{id:'with',label:'Withheld'},{id:'give',label:'Still given'}],
 rows:[{id:'r1',label:'Chest compressions in cardiac arrest',answer:'with'},
  {id:'r2',label:'Oxygen for breathlessness',answer:'give'},
  {id:'r3',label:'Pain relief within your protocol',answer:'give'},
  {id:'r4',label:'Relief of an airway obstruction in a patient with a pulse',answer:'give'}],
 options:[],
 explanation_md:'One row is withheld. Everything else continues, and reading the order more broadly than it is written is the error to guard against.',source_ref:POLST}),
base({id:'itm-3.6.007',type:'mc',chapter:3,block:'3.6',objective:'obj-3.6.a',
 stem:'You cannot find any documentation, and the family say the patient "did not want any of this". What is the safe default?',
 options:[opt('a','Begin resuscitation — you can stop later, but you cannot restart a window that has closed',true,'Where the order cannot be verified, the reversible choice is to treat.'),
  opt('b','Withhold resuscitation on the family’s word',false,'A recollection is not an order, and this decision is not reversible.'),
  opt('c','Wait for documentation to be found',false,'Waiting is a decision to withhold, made passively.'),
  opt('d','Ask the family to sign a statement, then withhold',false,'A family signature does not create a medical order.')],
 explanation_md:'Treat, contact medical control, and let the documentation catch up. Of the two errors available, only one can be undone.',source_ref:POLST}),
base({id:'itm-3.6.008',type:'mc',chapter:3,block:'3.6',objective:'obj-3.6.a',bloom:'analyze',
 stem:'Why is the blank-section default on these forms deliberately biased toward treatment?',
 options:[opt('a','Because an omission must never be read as an instruction to withhold — the error would be irreversible',true,'The asymmetry in the consequences sets the direction of the default.'),
  opt('b','Because most patients want full treatment',false,'Not the reason, and not necessarily true of people who complete these forms.'),
  opt('c','Because it reduces the service’s liability',false,'Liability is not the design principle here.'),
  opt('d','Because the form is usually filled in wrongly',false,'The default is not an assumption about competence.')],
 explanation_md:'The two mistakes are not equivalent. Resuscitating someone who did not want it is a serious harm; withholding from someone who did want it cannot be corrected at all.',source_ref:POLST}),
// ── 3.7 Confidentiality and the record ────────────────────────────────── 8
base({id:'itm-3.7.001',type:'mc',chapter:3,block:'3.7',objective:'obj-3.7.a',bloom:'understand',
 stem:'Does the privacy rule prevent you giving a full verbal report to the receiving nurse?',
 options:[opt('a','No — disclosure for treatment is permitted, and the handover is treatment',true,'The rule was never intended to obstruct care.'),
  opt('b','Yes, unless the patient signs an authorisation first',false,'Treatment disclosures do not require a separate authorisation.'),
  opt('c','Yes, unless the nurse works for the same organisation',false,'Organisational boundaries do not block treatment disclosures.'),
  opt('d','Only if the patient is conscious',false,'Consciousness is not the test.')],
 explanation_md:'"HIPAA says I can’t tell you" is almost always wrong at a handover, and it is dangerous when it is wrong. Treatment disclosures are permitted.',source_ref:HIPAA}),
base({id:'itm-3.7.002',type:'mc',chapter:3,block:'3.7',objective:'obj-3.7.a',high_stakes:true,
 stem:'You post a photograph of an unusual extrication online with no name attached. What is wrong with it?',
 options:[opt('a','The patient may still be identifiable from the scene, the vehicle or the timing — and there was no permitted purpose for the disclosure',true,'De-identification is harder than removing a name, and posting is not a treatment purpose.'),
  opt('b','Nothing, since no name was used',false,'Identifiability is broader than naming.'),
  opt('c','Only wrong if a family member sees it',false,'The breach does not depend on who happens to see it.'),
  opt('d','Only wrong if the service has a policy against it',false,'The obligation does not begin with the policy.')],
 explanation_md:'Social media posts have ended EMS careers repeatedly, usually on details the poster thought were anonymous. A vehicle and a time are often enough.',source_ref:HIPAA}),
base({id:'itm-3.7.003',type:'mr',chapter:3,block:'3.7',objective:'obj-3.7.a',bloom:'remember',select_count:[3,4],
 stem:'Select the disclosures that are generally permitted without the patient’s authorisation.',
 options:[opt('a','To the receiving hospital for treatment',true,'Treatment is a permitted purpose.'),
  opt('b','To your medical director for quality review',true,'Healthcare operations, which includes quality improvement.'),
  opt('c','For billing the transport',true,'Payment is a permitted purpose.'),
  opt('d','As required by a state mandatory reporting law',true,'Required-by-law disclosures are provided for.'),
  opt('e','To a neighbour who asks how the patient is',false,'No permitted purpose, however kindly meant.')],
 explanation_md:'Treatment, payment, operations, and what the law requires. Everything outside those four needs authorisation or a specific exception.',source_ref:HIPAA}),
base({id:'itm-3.7.004',type:'options_box',chapter:3,block:'3.7',objective:'obj-3.7.a',bloom:'analyze',
 stem:'Permitted, or a breach?',
 columns:[{id:'ok',label:'Permitted'},{id:'no',label:'Breach'}],
 rows:[{id:'r1',label:'Full clinical handover to the receiving nurse',answer:'ok'},
  {id:'r2',label:'Telling your partner’s spouse about an unusual call, with names',answer:'no'},
  {id:'r3',label:'Discussing the call in a quality review with your medical director',answer:'ok'},
  {id:'r4',label:'Describing a recognisable patient in a public social media post',answer:'no'}],
 options:[],
 explanation_md:'The two breaches have something in common: neither had a purpose connected to the patient’s care. That is usually the test worth applying.',source_ref:HIPAA}),
base({id:'itm-3.7.005',type:'mc',chapter:3,block:'3.7',objective:'obj-3.7.a',high_stakes:true,
 stem:'You realise after the call that you charted a vital sign you did not actually take. What do you do?',
 options:[opt('a','Correct the record openly — an amendment that shows the original entry and the reason for the change',true,'Correcting is expected. Concealing is the serious act.'),
  opt('b','Leave it, since no harm resulted',false,'It leaves a false record that others will rely on.'),
  opt('c','Delete the entry so the record is clean',false,'Altering a record to conceal is a separate and far more serious problem.'),
  opt('d','Tell your partner and take no further action',false,'It does not correct the record anyone else will read.')],
 explanation_md:'Everyone makes charting errors. What ends careers is the correction that hides rather than shows — and audit trails generally make that visible anyway.',source_ref:STD}),
base({id:'itm-3.7.006',type:'mc',chapter:3,block:'3.7',objective:'obj-3.7.a',bloom:'analyze',
 stem:'Why is "minimum necessary" not applied to a clinical handover?',
 options:[opt('a','Because the minimum necessary for treatment is everything relevant to the patient’s care',true,'The standard does not restrict treatment disclosures in that way.'),
  opt('b','Because handovers are exempt from privacy rules entirely',false,'They are not exempt; they are permitted.'),
  opt('c','Because the receiving nurse has already consented',false,'Not the mechanism.'),
  opt('d','Because verbal disclosures are not covered',false,'Verbal disclosures are covered.')],
 explanation_md:'Withholding clinically relevant information in the name of privacy is the failure mode here, and it is far more common than over-disclosure at a bedside.',source_ref:HIPAA}),
base({id:'itm-3.7.007',type:'mc',chapter:3,block:'3.7',objective:'obj-3.7.a',
 stem:'A police officer asks you for details of a patient’s condition at a scene. What is the position?',
 options:[opt('a','Disclose what a specific legal requirement or exception permits, and check your protocol — it is not an unlimited request',true,'Some disclosures to law enforcement are permitted, and they are specific rather than general.'),
  opt('b','Disclose everything — police are exempt from privacy rules',false,'They are not, and the exceptions are narrower than people assume.'),
  opt('c','Disclose nothing under any circumstances',false,'Several permitted disclosures exist, including required reporting.'),
  opt('d','Ask the patient to authorise it in writing first, always',false,'Not required for disclosures that are already permitted.')],
 explanation_md:'Another place where the honest answer is that the specifics are jurisdictional. Know your protocol before somebody in uniform asks you at two in the morning.',source_ref:HIPAA}),
base({id:'itm-3.7.008',type:'mc',chapter:3,block:'3.7',objective:'obj-3.7.a',
 stem:'What is the practical status of something you left out of the patient care record?',
 options:[opt('a','It is generally treated as not having been done',true,'The record is the evidence, and a gap reads as an omission.'),
  opt('b','It can be added from memory at any later date without note',false,'Late entries must be identified as such.'),
  opt('c','It is covered by your verbal handover',false,'A verbal report does not survive as a record.'),
  opt('d','It matters only if the patient complains',false,'The record is read in quality review, billing and litigation alike.')],
 explanation_md:'This is the whole reason documentation is a clinical skill rather than an administrative one, and Chapter 4 takes it up in detail.',source_ref:STD}),

// ── 3.8 Ethics, reporting, crime scenes, donation ─────────────────────── 8
base({id:'itm-3.8.001',type:'mc',chapter:3,block:'3.8',objective:'obj-3.8.a',bloom:'understand',
 stem:'What is the difference between an ethical obligation and a legal one?',
 options:[opt('a','Law sets the minimum that is enforceable; ethics asks what you ought to do, and can require more',true,'Something can be lawful and still be the wrong thing to do.'),
  opt('b','They are the same in healthcare',false,'They overlap and they are not the same.'),
  opt('c','Ethics applies only to physicians',false,'It applies at every level.'),
  opt('d','Ethics is whatever the protocol says',false,'Protocol is an instruction, not an ethical framework.')],
 explanation_md:'Most difficult calls are not legally unclear. They are legally settled and still hard, and that is the space ethics occupies.',source_ref:STD}),
base({id:'itm-3.8.002',type:'mc',chapter:3,block:'3.8',objective:'obj-3.8.a',high_stakes:true,
 stem:'You suspect a child in the home is being abused. What is your obligation?',
 options:[opt('a','Report it through the route your state requires — suspicion is the threshold, not proof',true,'EMS providers are mandatory reporters in every state, and you are not required to be sure.'),
  opt('b','Investigate until you are certain, then report',false,'Investigation is not your role, and waiting for certainty defeats the purpose.'),
  opt('c','Tell the receiving nurse and consider it discharged',false,'Telling the hospital may be part of it and is not the report.'),
  opt('d','Report only if the child discloses abuse',false,'Disclosure is not required to trigger the duty.')],
 explanation_md:'Who must report, what, to whom and by when is set by your state. The threshold being suspicion rather than proof is the part that is consistent.',source_ref:STD}),
base({id:'itm-3.8.003',type:'mr',chapter:3,block:'3.8',objective:'obj-3.8.a',bloom:'remember',select_count:[2,3],
 stem:'Select what generally holds for mandatory reporting by EMS providers.',
 options:[opt('a','Suspicion, not proof, is the threshold for reporting',true,'You are not investigating; you are reporting a concern.'),
  opt('b','What must be reported, and to whom, is set by state law',true,'Which is why this belongs in your local layer rather than here.'),
  opt('c','Reporting in good faith is generally protected',true,'Statutes commonly provide protection for good-faith reports.'),
  opt('d','Reporting requires the patient’s consent',false,'Required reports do not depend on consent.'),
  opt('e','A single national list of reportable conditions applies',false,'There is no single national list.')],
 explanation_md:'Suspicion is enough, the list is local, and good-faith reports are usually protected. Those three carry you a long way.',source_ref:STD}),
base({id:'itm-3.8.004',type:'options_box',chapter:3,block:'3.8',objective:'obj-3.8.a',bloom:'analyze',
 stem:'At a scene that is also a crime scene, does patient care yield?',
 columns:[{id:'care',label:'Care comes first'},{id:'scene',label:'Preserve the scene'}],
 rows:[{id:'r1',label:'Moving a patient to perform compressions',answer:'care'},
  {id:'r2',label:'Cutting clothing through an existing bullet hole',answer:'scene'},
  {id:'r3',label:'Choosing where to put used packaging and sharps',answer:'scene'},
  {id:'r4',label:'Entering before the scene is secured, to reach a patient',answer:'scene'}],
 options:[],
 explanation_md:'Care wins wherever the two genuinely conflict. Most of the time they do not: you can avoid cutting through a defect and still work fast.',source_ref:STD}),
base({id:'itm-3.8.005',type:'mc',chapter:3,block:'3.8',objective:'obj-3.8.a',high_stakes:true,
 stem:'Working a shooting victim in a room where the shooting happened, what should you do about the scene?',
 options:[opt('a','Treat, and disturb only what care requires — avoid cutting through defects in clothing, note what you moved',true,'Both things are achievable at once, and what you moved is worth telling the investigator.'),
  opt('b','Preserve everything and delay care until investigators arrive',false,'Evidence does not outrank a living patient.'),
  opt('c','Disregard the scene entirely',false,'Avoidable destruction of evidence is not necessary to good care.'),
  opt('d','Move the patient outside before assessing',false,'A move for its own sake helps nobody.')],
 explanation_md:'The realistic standard is minimal necessary disturbance, and telling somebody what you changed. Both take almost no time.',source_ref:STD}),
base({id:'itm-3.8.006',type:'mc',chapter:3,block:'3.8',objective:'obj-3.8.a',
 stem:'A patient carries an organ donor designation. How should that affect your care?',
 options:[opt('a','Not at all — you provide the same resuscitation and treatment as for any other patient',true,'Donation is considered after care has been provided, and only by those responsible for it.'),
  opt('b','Resuscitation should be less aggressive',false,'The designation does not change the care owed.'),
  opt('c','You should contact the donation organisation from the scene',false,'Not your task, and not at the expense of the patient.'),
  opt('d','It functions as a do-not-resuscitate order',false,'It is nothing of the kind.')],
 explanation_md:'A donor card is a statement about what happens after death, not a limit on trying to prevent it.',source_ref:STD}),
base({id:'itm-3.8.007',type:'mc',chapter:3,block:'3.8',objective:'obj-3.8.a',bloom:'analyze',
 stem:'How should you handle a call where the lawful action and the compassionate action pull apart?',
 options:[opt('a','Meet the legal obligation, look for the most humane way of meeting it, and say plainly what you are doing and why',true,'The obligation is not optional; how it is carried out usually is.'),
  opt('b','Follow your conscience and disregard the requirement',false,'That is not available to you, whatever the motive.'),
  opt('c','Meet the requirement without explanation',false,'Explaining costs nothing and changes how it is experienced.'),
  opt('d','Refer the whole matter to your supervisor and take no action',false,'Deferring is itself a decision, and it usually leaves the patient waiting.')],
 explanation_md:'Most of the room for ethical judgement at this level is in how an obligation is carried out, not whether it is. That room is real and it matters to people.',source_ref:STD}),
base({id:'itm-3.8.008',type:'mc',chapter:3,block:'3.8',objective:'obj-3.8.a',bloom:'remember',
 stem:'Which of these is settled by your state rather than by anything in this module?',
 options:[opt('a','The age at which a minor may consent, and what must be reported to whom',true,'Both are state law, and both vary considerably.'),
  opt('b','The four elements of negligence',false,'The elements are common to the doctrine.'),
  opt('c','The four abilities that make up capacity',false,'That framework does not change at a state line.'),
  opt('d','Whether a blank section on a portable order means full treatment',false,'That default is a feature of the form standard.')],
 explanation_md:'Knowing which parts of this chapter are portable and which are local is itself part of the content. Everything local belongs in the overlay, not in memory.',source_ref:STD}),
// ── 3.INT Integration ─────────────────────────────────────────────────── 9
base({id:'itm-3.INT.000',type:'scenario',chapter:3,block:'3.INT',objective:'obj-3.INT.a',
 stimulus:{kind:'scenario',ref:null,
  text:'2210. An 81-year-old man at home, called by his daughter for "not acting right". He is pale and clammy, with a blood glucose of 39 mg/dL. He is drowsy and will not answer questions.\n\nOn the refrigerator is a portable medical order form in his name. Section A — cardiopulmonary resuscitation — is completely unmarked. Section B is ticked for selective treatment. The clinician has signed it.\n\nYou give glucose. Ten minutes later he is alert, oriented, arguing, and says he is not going anywhere. His daughter tells you to take him whether he likes it or not, and that the form on the fridge means he does not want treatment.'},
 children:['itm-3.INT.001','itm-3.INT.002','itm-3.INT.003','itm-3.INT.004',
  'itm-3.INT.005','itm-3.INT.006','itm-3.INT.007','itm-3.INT.008'],
 stem:'',options:[],explanation_md:'',source_ref:STD}),
base({id:'itm-3.INT.001',type:'mc',chapter:3,block:'3.INT',objective:'obj-3.INT.a',parent:'itm-3.INT.000',high_stakes:true,
 stem:'On arrival he is drowsy and will not answer. On what basis do you treat the hypoglycaemia?',
 options:[opt('a','Implied consent — he cannot consent and the care is needed now',true,'A reasonable person would consent to treatment for symptomatic hypoglycaemia.'),
  opt('b','His daughter’s consent',false,'An adult daughter does not automatically have authority to consent for her father.'),
  opt('c','The portable medical order form',false,'The form limits certain treatments; it does not consent to this one.'),
  opt('d','You may not treat until he is alert enough to agree',false,'That reading would require the hypoglycaemia to be left untreated.')],
 explanation_md:'Implied consent covers the emergency in front of you and nothing beyond it.',source_ref:STD}),
base({id:'itm-3.INT.002',type:'mc',chapter:3,block:'3.INT',objective:'obj-3.INT.a',parent:'itm-3.INT.000',high_stakes:true,
 stem:'The daughter says the form means he does not want treatment. Is she right?',
 options:[opt('a','No — Section B permits selective treatment, and an unmarked Section A defaults to full resuscitation',true,'The form limits nothing that is relevant to giving him glucose.'),
  opt('b','Yes — any portable medical order means comfort measures only',false,'That is a serious and common misreading.'),
  opt('c','Yes, because Section A is blank',false,'A blank is never read as a limitation.'),
  opt('d','It cannot be determined without contacting the signing clinician',false,'The form is readable as it stands, and he is not in arrest.')],
 explanation_md:'Read what the form actually says. It was not written to stop anyone treating a hypoglycaemic man at home, and it does not.',source_ref:POLST}),
base({id:'itm-3.INT.003',type:'mc',chapter:3,block:'3.INT',objective:'obj-3.INT.a',parent:'itm-3.INT.000',
 stem:'He is now alert and refusing. What has changed legally?',
 options:[opt('a','He may now have capacity, so implied consent no longer applies and his own decision governs',true,'Capacity is assessed now, not from how he was fifteen minutes ago.'),
  opt('b','Nothing — he was incapacitated on arrival, so you may still transport him',false,'Capacity is time-specific and it has plausibly returned.'),
  opt('c','His daughter now decides, as she called the ambulance',false,'Calling an ambulance confers no authority over another adult.'),
  opt('d','The form now governs the decision',false,'The form is about resuscitation preferences, not about this refusal.')],
 explanation_md:'The same patient, half an hour apart, under two different legal frameworks. That is what "decision-specific and time-specific" means in practice.',source_ref:CAP}),
base({id:'itm-3.INT.004',type:'mr',chapter:3,block:'3.INT',objective:'obj-3.INT.a',parent:'itm-3.INT.000',bloom:'remember',select_count:[4,4],
 stem:'Which four abilities do you assess before accepting his refusal?',
 options:[opt('a','That he understands what you have told him',true,'Can he take in the information?'),
  opt('b','That he appreciates it applies to him',true,'Not to hypoglycaemic patients generally — to him, tonight.'),
  opt('c','That he can reason about the options',true,'Some weighing, whether or not it matches yours.'),
  opt('d','That he can express a choice',true,'Communicated, and reasonably stable.'),
  opt('e','That he agrees with your recommendation',false,'The trap. He is allowed to decide against you.')],
 explanation_md:'Four abilities, assessed in a couple of minutes, and written down as what he said rather than as a conclusion.',source_ref:CAP}),
base({id:'itm-3.INT.005',type:'mc',chapter:3,block:'3.INT',objective:'obj-3.INT.a',parent:'itm-3.INT.000',high_stakes:true,
 stem:'He has capacity and refuses. His daughter insists you take him anyway. What do you do?',
 options:[opt('a','Decline to transport him against his will, and say to them both why',true,'Transporting a capable adult who refuses is not something a relative can authorise.'),
  opt('b','Transport him, since the daughter is next of kin',false,'Next of kin does not override a capable adult.'),
  opt('c','Transport him because hypoglycaemia may recur',false,'A real risk, and it does not remove his right to decide.'),
  opt('d','Ask the daughter to sign a consent form on his behalf',false,'She cannot consent for a capable adult, and a form does not change that.')],
 explanation_md:'Being right about the medicine does not give you authority over an adult who has capacity. It gives you an obligation to explain it well.',source_ref:STD}),
base({id:'itm-3.INT.006',type:'mr',chapter:3,block:'3.INT',objective:'obj-3.INT.a',parent:'itm-3.INT.000',select_count:[4,5],
 stem:'What belongs in the record of this refusal?',
 options:[opt('a','The capacity assessment as a conversation — what you asked, what he said',true,'Not "alert and oriented ×4" standing in for an assessment.'),
  opt('b','The specific risk of recurrent hypoglycaemia, and that you named it',true,'Including what could happen if nobody is there.'),
  opt('c','That he repeated the risks back in his own words',true,'The strongest single line available to you.'),
  opt('d','The plan agreed — that he eats, and that someone stays with him',true,'What makes the refusal safer rather than merely documented.'),
  opt('e','That his daughter disagreed and you sided with the patient',false,'Record the disagreement factually; the editorial is not useful.')],
 explanation_md:'A refusal note that describes a conversation and a plan is defensible. One that records a signature is not.',source_ref:STD}),
base({id:'itm-3.INT.007',type:'mc',chapter:3,block:'3.INT',objective:'obj-3.INT.a',parent:'itm-3.INT.000',
 stem:'What is the single most useful thing you can say to him before leaving?',
 options:[opt('a','That he can call again at any time, for any reason, and nobody will hold it against him',true,'It keeps the door open for the call you actually want him to make.'),
  opt('b','That he is making a serious mistake',false,'He has heard it, and repeating it does not help now.'),
  opt('c','That his daughter will be responsible for him',false,'Not something you can assign to her.'),
  opt('d','That you will return in an hour to check',false,'Do not promise something the system will not deliver.')],
 explanation_md:'You want the second call to happen early. Everything in the last sixty seconds should make that easier rather than harder.',source_ref:STD}),
base({id:'itm-3.INT.008',type:'mc',chapter:3,block:'3.INT',objective:'obj-3.INT.a',parent:'itm-3.INT.000',bloom:'analyze',
 stem:'Reviewing this call, which three decisions would you have to defend, and on what?',
 options:[opt('a','Treating on implied consent, reading the form correctly, and accepting a refusal from a patient whose capacity you assessed and recorded',true,'Three distinct frameworks, each with its own evidence in the chart.'),
  opt('b','Only the decision not to transport',false,'The other two would be examined just as closely.'),
  opt('c','Only the reading of the form',false,'It is one of three.'),
  opt('d','None — the patient refused, so the call ends there',false,'A refusal is the beginning of the scrutiny, not the end of it.')],
 explanation_md:'One call, three frameworks, and the record is the only thing that will still exist when someone asks. That is the whole chapter in one living room.',source_ref:STD}),
];

export const blocks=[
{id:'3.1',chapter:3,title:'Duty, abandonment and transfer of care',learner_title:'When the patient becomes yours',
 objectives:['obj-3.1.a'],est_minutes:7,
 cold_open:{text:'A full emergency department. You wheel your patient into a corridor and a nurse says, without stopping, that she will get to them shortly. Your radio is asking for your status and there is another call holding. Your patient is on your trolley, and nobody has taken them.',
  decision_point:'Can you leave?'},
 pretest_item:'itm-3.1.001',
 screens:[
  {id:'scr-3.1.1',body_md:'**Duty to act comes from the arrangement, not from proximity.** On duty and dispatched, the duty is rarely in dispute — your service contracted to respond and you are its crew.\n\nOff duty it is different, and it is state law. Good Samaritan statutes exist everywhere, differ everywhere, and generally do not cover someone acting inside their paid employment.',figure:null},
  {id:'scr-3.1.2',body_md:'**Beginning care changes your position.** Once you start, people stop helping, another vehicle drives past, and the patient is relying on you.\n\nThat reliance is the reason walking away part-way through is treated differently from never having stopped. It is also why the decision to begin is a real decision, off duty.\n\nOn duty there is no such decision to make. You were sent, and the duty arrived with the dispatch.',figure:null},
  {id:'scr-3.1.3',body_md:'**Abandonment is ending care without a proper handover** — to someone of equal or higher training, who has actually accepted the patient, having been told what they need to know.\n\nThree conditions. The second is the one that gets skipped, because a person being physically present feels like acceptance and is not.',figure:null},
  {id:'scr-3.1.4',body_md:'**A corridor is where this nearly happens.** The department is full, your next call is holding, and nobody has said the words.\n\nGet an acceptance. Give the report. If the delay is a system problem — and it usually is — that belongs in a report afterwards, not in a decision to leave a patient on a trolley.',figure:null},
  {id:'scr-3.1.5',body_md:'**One thing worth knowing by name.** Federal law requires a hospital with an emergency department to provide a medical screening examination to anyone who presents, regardless of diversion status or ability to pay.\n\nDiversion is a resource signal worth cooperating with. It is not a legal wall against a patient who is already there and unstable.',figure:null}],
 inline_checks:['itm-3.1.003','itm-3.1.005'],
 quiz:['itm-3.1.002','itm-3.1.004','itm-3.1.006','itm-3.1.007','itm-3.1.008'],
 callback_md:'Not yet. Nobody has accepted the patient, so the transfer is incomplete and leaving now is abandonment — however busy the department is and however loud the radio gets.\n\nFind someone of equal or higher level, get an acceptance, give the report. **The building does not accept patients. A person does**, and "I’ll get to them shortly" is not that person saying yes.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'3.2',chapter:3,title:'Consent',learner_title:'What makes touching someone lawful',
 objectives:['obj-3.2.a'],est_minutes:7,
 cold_open:{text:'You explain the intravenous line, he nods, and you start cleaning the skin. As you pick up the cannula he says "actually, no". The line is half set up, your partner is holding the tape, and the hospital is expecting you.',
  decision_point:'Does the nod still count?'},
 pretest_item:'itm-3.2.001',
 screens:[
  {id:'scr-3.2.1',body_md:'**Consent is what makes touching a patient lawful.** Without it, the same act has a different name — battery — and that is not a figure of speech.\n\nThis is why consent sits at the front of the chapter. Everything else you do to a patient is permitted by it, and nothing else substitutes.\n\nIt is also why a signature on a form proves very little on its own. What matters is the conversation the signature is supposed to be recording, and whether it happened at all.',figure:null},
  {id:'scr-3.2.2',body_md:'**Expressed consent** is the patient agreeing — in words, or by conduct, like holding out an arm.\n\n**Informed** means they could actually weigh it: what you propose, why, the significant risks, and what is likely to happen if they decline. The last of those is the one most often left out, and it is the one that matters in a refusal.',figure:null},
  {id:'scr-3.2.3',body_md:'**Implied consent is a legal presumption**, not a convenience. It applies when the patient cannot consent and needs emergency care: the law presumes a reasonable person would have agreed.\n\nIt covers the emergency and no further. It is not a fallback for a patient who is simply difficult, or awkward, or saying no.',figure:null},
  {id:'scr-3.2.4',body_md:'**Minors are state law.** Who may consent, at what age, in what circumstances, and what emancipation or mature-minor provisions exist — all of it varies.\n\nWhat does not vary: you treat the emergency while you keep trying to reach a parent. Nobody is left untreated because a telephone is not being answered.',figure:null},
  {id:'scr-3.2.5',body_md:'**Consent is a running state, not a gate at the start.** It can be withdrawn at any moment, including part-way through a procedure, and when it is, you stop.\n\nThen you find out what changed — because most withdrawals are about fear or pain, and they are often recoverable by asking rather than by continuing.',figure:null}],
 inline_checks:['itm-3.2.003','itm-3.2.005'],
 quiz:['itm-3.2.002','itm-3.2.004','itm-3.2.006','itm-3.2.007','itm-3.2.008'],
 callback_md:'No. Consent is continuing permission, and he has just withdrawn it. Stop — with the tape in your partner’s hand and the hospital waiting.\n\n**Then ask what changed.** Usually it is the needle, or a bad memory of one, and it is often recoverable in a sentence. What is not recoverable is having carried on because you were nearly finished.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'3.3',chapter:3,title:'Capacity',learner_title:'Decision, or symptom?',
 objectives:['obj-3.3.a'],est_minutes:8,
 cold_open:{text:'Crushing chest pain, grey, sweating, and he will not go. He answers every question correctly, tells you exactly what a heart attack is, and says he is staying. Your partner says he is obviously not thinking straight.',
  decision_point:'Is your partner right?'},
 pretest_item:'itm-3.3.001',
 screens:[
  {id:'scr-3.3.1',body_md:'**Capacity is assessed against four abilities.** Does the patient **understand** the information? Do they **appreciate** that it applies to them? Can they **reason** — weigh one option against another? Can they **express a choice**?\n\nFour questions, a couple of minutes, and they can all be asked conversationally.\n\nNone of them is a memory test. You are not checking what the patient knows in general — only whether they can work with what you have just told them.',figure:null},
  {id:'scr-3.3.2',body_md:'**Agreeing with you is not on the list.** A patient with capacity may make a decision you believe is dangerous, and it remains theirs.\n\nThis is the single most common error in the chapter: treating disagreement as evidence of incapacity. It is also the error that ends up in court, because it looks exactly like deciding for someone.',figure:null},
  {id:'scr-3.3.3',body_md:'**Capacity is decision-specific and time-specific.** Someone may have it for a simple decision and not a complex one, and it can change inside a quarter of an hour.\n\nA hypoglycaemic patient may lack capacity at 0800 and have it at 0815. So the record has to say *when* you assessed it, and *about what*.',figure:null},
  {id:'scr-3.3.4',body_md:'**Capacity is not competence.** You assess capacity at the bedside; competence is determined by a court.\n\nThe words are swapped constantly, including in charts. What you are writing about, every time, is capacity — and writing the right word costs nothing.\n\nNo court is going to be convened in this living room. The assessment is yours to make and yours to record.',figure:null},
  {id:'scr-3.3.5',body_md:'**Head injury, intoxication and custody are the hard ones.** Intoxication can impair capacity and does not automatically abolish it. A head injury can impair it and can also worsen while you argue.\n\nWhen two plausible causes of impairment are in the room, the threshold for accepting a refusal goes up, and medical control is a reasonable call.',figure:null}],
 inline_checks:['itm-3.3.005','itm-3.3.007'],
 quiz:['itm-3.3.002','itm-3.3.003','itm-3.3.004','itm-3.3.006','itm-3.3.008'],
 callback_md:'No. He understands, he appreciates it applies to him, he can reason about it, and he has expressed a choice. That is capacity, and the decision is his.\n\n**What your partner has described is a decision he disagrees with**, which is a different thing entirely. Your job now is to make the refusal genuinely informed — and to document the four abilities as a conversation, not as a conclusion.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'3.4',chapter:3,title:'Negligence',learner_title:'What a claim has to prove',
 objectives:['obj-3.4.a'],est_minutes:7,
 cold_open:{text:'Two years after a call you barely remember, a letter arrives. Somebody is going to have to reconstruct what you assessed, what you did, and why, from a report you wrote in nine minutes at the end of a night shift.',
  decision_point:'What would that claim actually have to establish?'},
 pretest_item:'itm-3.4.003',
 screens:[
  {id:'scr-3.4.1',body_md:'**Four elements, and all four are needed.**\n\n**Duty** — you were obliged to act. **Breach** — the care fell below the standard. **Causation** — the breach caused the harm. **Damages** — actual harm resulted.\n\nMiss one and the claim fails, which is why a frightening call that harmed nobody is not negligence.\n\nThat is not permission. It is the reason a near miss belongs in quality improvement rather than in a courtroom, and why reporting one costs you less than people assume.',figure:null},
  {id:'scr-3.4.2',body_md:'**Breach is measured against the standard of care**: what a reasonable provider of your level would have done, in the same circumstances, with what was known at the time.\n\nNot the best provider. Not with hindsight. Protocol is strong evidence of what reasonable looks like, which is why a departure needs a reason you can say out loud.',figure:null},
  {id:'scr-3.4.3',body_md:'**Causation is where these cases are decided.** Showing that something happened after an error is easy. Showing that the error caused it is genuinely hard, because patients deteriorate for reasons of their own.\n\nThat gap is real, and it cuts both ways — it protects providers, and it also makes some real harms impossible to prove.\n\nWhich is why the element is argued over at such length: sequence is easy to establish, and cause is not.',figure:null},
  {id:'scr-3.4.4',body_md:'**Gross negligence is a different category** — reckless disregard for safety, beyond falling short of a standard.\n\nIt matters because most legal protections stop there. Good Samaritan statutes, immunity provisions and similar shields are generally written to end where recklessness begins.',figure:null},
  {id:'scr-3.4.5',body_md:'**The record is the witness.** Two years on, nobody remembers the call, and what is not written is treated as not done.\n\nWrite the reasoning as well as the action. "Departed from protocol because..." is a completely different document from a blank where the protocol step should have been.',figure:null}],
 inline_checks:['itm-3.4.006','itm-3.4.007'],
 quiz:['itm-3.4.001','itm-3.4.002','itm-3.4.004','itm-3.4.005','itm-3.4.008'],
 callback_md:'Duty — established the moment you were dispatched. Breach — measured against a reasonable AEMT in the same circumstances, with protocol as strong evidence. Causation — the contested one, and the hardest. Damages — actual harm, without which there is no claim.\n\n**And all of it reconstructed from those nine minutes.** That is the honest reason documentation is a clinical skill, and it is what Chapter 4 is for.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'3.5',chapter:3,title:'Refusal of care',learner_title:'The call that ends careers',
 objectives:['obj-3.5.a'],est_minutes:9,
 cold_open:{text:'Blood glucose was 39. You gave glucose, he woke up, and now he is sitting on the edge of the bed telling you he is fine and you can go. He is right that he is fine. He was not fine twenty minutes ago, and nothing has changed about why.',
  decision_point:'What has to happen before you leave?'},
 pretest_item:'itm-3.5.001',
 screens:[
  {id:'scr-3.5.1',body_md:'**Two things make a refusal a refusal**: the patient has capacity, and they have been told what declining risks.\n\nWithout both, nobody has refused anything — a patient has simply been left at the scene. The form, the signature and the box you tick are documentation of those two facts, and nothing more.',figure:null},
  {id:'scr-3.5.2',body_md:'**This is the highest-risk call type at this level**, and the reason is structural. A patient with an unrecognised serious condition stays where they are, nobody sees them again until something has happened, and the record is usually too thin to show what was assessed.\n\nClinical risk and documentation risk, arriving together.',figure:null},
  {id:'scr-3.5.3',body_md:'**"Alert and oriented ×4" is not a capacity assessment.** Orientation is not one of the four abilities, and an oriented patient can still fail to appreciate that a warning applies to them.\n\nWrite what you asked and what they said. The strongest single line you can put in a chart is that the patient stated the risks back in their own words.',figure:null},
  {id:'scr-3.5.4',body_md:'**Name the risk, including death where that is real.** Vague warnings do not make a refusal informed, and they read as vague afterwards.\n\nThen make the refusal safer: what will they eat, who is staying with them, what would make them call back. A refusal with a plan is a different clinical event from a refusal with a signature.',figure:null},
  {id:'scr-3.5.5',body_md:'**Leave the door open, out loud.** Tell them they can call again at any time, for any reason, and that nobody will hold it against them.\n\nIf they will not sign, document the refusal to sign with a witness. The signature was only ever evidence, and a narrative describing the conversation is better evidence than a name on a line.',figure:null}],
 inline_checks:['itm-3.5.003','itm-3.5.009'],
 quiz:['itm-3.5.002','itm-3.5.004','itm-3.5.005','itm-3.5.006','itm-3.5.007','itm-3.5.008'],
 callback_md:'Assess capacity against the four abilities, now that he has it back. Name the specific risk — that it can recur, that it can happen while he is asleep, and that people have died of exactly this. Get him to say it back.\n\n**Then make the refusal safer rather than merely legal**: something to eat, somebody with him, and what would make him call. And say the last sentence plainly — call again, any time, no penalty. That is the one that brings him back at 0300 while there is still time.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'3.6',chapter:3,title:'Advance directives and portable medical orders',learner_title:'The form on the fridge',
 objectives:['obj-3.6.a'],est_minutes:8,
 cold_open:{text:'Cardiac arrest in a bedroom, and a form is taped to the refrigerator with the patient’s name on it. Section A, the resuscitation section, has neither box marked. The clinician has signed at the bottom. Your partner is already opening the airway bag.',
  decision_point:'Do you start?'},
 pretest_item:'itm-3.6.001',
 screens:[
  {id:'scr-3.6.1',body_md:'**A portable medical order is a signed clinician order**, actionable immediately. An advance directive such as a living will states wishes for somebody else to interpret later.\n\nThat difference is the whole point. The names vary by state — POLST, MOST, POST, TPOPP and others — and the structure does not.',figure:null},
  {id:'scr-3.6.2',body_md:'**An unmarked section defaults to full treatment for that section.** A blank is never a limitation.\n\nThe asymmetry is deliberate. Resuscitating someone who did not want it is a serious harm. Withholding from someone who did want it cannot be undone at all — so the default runs toward treatment.',figure:null},
  {id:'scr-3.6.3',body_md:'**"Do not resuscitate" is not "do not treat".** It addresses resuscitation from arrest.\n\nA patient with a valid DNR who is choking, breathless or in pain still gets the airway cleared, the oxygen, and the analgesia your protocol allows. Reading the order more broadly than it is written has killed people who were never meant to die of it.',figure:null},
  {id:'scr-3.6.4',body_md:'**Four checks, in about fifteen seconds.** Does it identify *this* patient? Does it carry the required signature? Which sections are marked, and which are blank? And is anyone with authority revoking it now?\n\nA form on a refrigerator can belong to a previous resident. It happens.\n\nThe check that gets skipped is the first one. A name at the top is quick to read and worth the two seconds.',figure:null},
  {id:'scr-3.6.5',body_md:'**When it cannot be verified, treat.** No documentation and a family recollection is not an order, and the choice to withhold is the one you cannot take back.\n\nBegin, contact medical control, and let the paperwork catch up. Who may revoke one of these forms is state law, which is exactly the kind of thing to know before the night it matters.',figure:null}],
 inline_checks:['itm-3.6.003','itm-3.6.007'],
 quiz:['itm-3.6.002','itm-3.6.004','itm-3.6.005','itm-3.6.006','itm-3.6.008'],
 callback_md:'Yes. Start.\n\nSection A is unmarked, and an unmarked section means full treatment for that section. The form is valid, the signature is there, and none of that changes the answer — **a blank is never read as permission to withhold.**\n\nThe rest of the form may well limit other things, and you can read it properly once compressions are running. What you do not do is stand in a bedroom interpreting a blank while somebody is in arrest.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'3.7',chapter:3,title:'Confidentiality and the record',learner_title:'Who gets told what',
 objectives:['obj-3.7.a'],est_minutes:7,
 cold_open:{text:'A crew member tells you they could not give the receiving nurse the patient’s psychiatric history "because of HIPAA". An hour later the same person posts a photograph of the wreck, with the street sign in frame, and says nothing identifying was in it.',
  decision_point:'Which of those two was the breach?'},
 pretest_item:'itm-3.7.001',
 screens:[
  {id:'scr-3.7.1',body_md:'**Disclosure for treatment is permitted, and a handover is treatment.** "HIPAA says I can’t tell you" is almost always wrong at a bedside, and it is dangerous when it is wrong.\n\nThe rule permits disclosure for treatment, for payment, for healthcare operations such as quality review, and where the law requires it.',figure:null},
  {id:'scr-3.7.2',body_md:'**Minimum necessary does not shrink a clinical handover.** The minimum necessary for treatment is everything relevant to the patient’s care.\n\nWithholding a psychiatric history, a medication or a mechanism because it feels sensitive is the common failure here — and it is far more frequent than over-disclosure at a bedside.\n\nIf a piece of information would change what the receiving team does in the next hour, it belongs in the handover, whatever it is about.',figure:null},
  {id:'scr-3.7.3',body_md:'**Identifiability is broader than a name.** A vehicle, a street, a time and an unusual mechanism can identify someone completely.\n\nSocial media posts have ended EMS careers repeatedly, almost always on details the poster believed were anonymous. And a post is not a treatment purpose, so there is no permitted basis for it in the first place.',figure:null},
  {id:'scr-3.7.4',body_md:'**Law enforcement requests are narrower than people assume.** Some disclosures are permitted, some are required, and it is specific rather than general.\n\nThe details are jurisdictional, so this is a protocol question — worth knowing before somebody in uniform asks you at two in the morning and everyone is waiting.',figure:null},
  {id:'scr-3.7.5',body_md:'**Correct errors openly.** An amendment that shows the original entry and the reason for the change is expected and unremarkable.\n\nDeleting an entry to conceal it is a different act entirely, audit trails usually reveal it, and that is the version that ends careers — not the charting mistake underneath.',figure:null}],
 inline_checks:['itm-3.7.005','itm-3.7.008'],
 quiz:['itm-3.7.002','itm-3.7.003','itm-3.7.004','itm-3.7.006','itm-3.7.007'],
 callback_md:'The photograph. Withholding the psychiatric history at handover was the wrong call for the patient and was not required by anything — treatment disclosures are permitted, and the minimum necessary for treatment is everything relevant.\n\nThe post had **no permitted purpose at all**, and the street sign makes the patient identifiable to anyone who knows the road. **The rule almost never stops you telling the nurse. It has plenty to say about telling the internet.**',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'3.8',chapter:3,title:'Ethics, reporting, crime scenes',learner_title:'Obligations that are not clinical',
 objectives:['obj-3.8.a'],est_minutes:7,
 cold_open:{text:'A shooting in a small apartment. Your patient is alive and needs work. There is a firearm on the floor, shell casings by the door, and an officer telling you not to move anything. There is also a child in the next room with a bruise pattern you have already noticed.',
  decision_point:'How many obligations are in this room?'},
 pretest_item:'itm-3.8.001',
 screens:[
  {id:'scr-3.8.1',body_md:'**Law sets the enforceable minimum; ethics asks what you ought to do.** Something can be entirely lawful and still be the wrong way to treat a person.\n\nMost genuinely difficult calls are not legally unclear. They are legally settled and still hard, and that is the space where judgement actually lives.',figure:null},
  {id:'scr-3.8.2',body_md:'**Mandatory reporting: suspicion is the threshold, not proof.** EMS providers are mandatory reporters in every state, and you are not required to be sure, or to investigate.\n\nWhat must be reported, to whom, and by when is state law. Good-faith reports are generally protected. The specifics belong in your local layer.',figure:null},
  {id:'scr-3.8.3',body_md:'**Care wins where it genuinely conflicts with a scene.** Move the patient if compressions require it.\n\nMost of the time there is no conflict at all: you can avoid cutting through a bullet hole in clothing, choose where packaging and sharps land, and note what you moved. All of it costs seconds.',figure:null},
  {id:'scr-3.8.4',body_md:'**A donor designation changes nothing about your care.** It is a statement about what happens after death, not a limit on trying to prevent it.\n\nThe same care, the same aggression, the same everything. Donation is considered afterwards, by the people whose job that is.\n\nIf you find yourself treating a donor differently, that is the moment to notice it and stop.',figure:null},
  {id:'scr-3.8.5',body_md:'**Know which parts of this chapter are portable and which are local.** Consent ages, reporting lists, who may revoke a portable order, and what may be disclosed to police are all state law.\n\nThe frameworks — the four elements, the four abilities, the blank-section default — travel. Everything else has to be looked up where you work.',figure:null}],
 inline_checks:['itm-3.8.002','itm-3.8.006'],
 quiz:['itm-3.8.003','itm-3.8.004','itm-3.8.005','itm-3.8.007','itm-3.8.008'],
 callback_md:'Three, and they do not conflict as much as the room suggests.\n\nThe patient comes first — move what care requires. The scene costs you almost nothing: avoid the defects in the clothing, choose where your packaging lands, tell the officer what you moved. And the child is a mandatory report on suspicion alone, through the route your state sets, whether or not anyone says a word about it tonight.\n\n**The bruise is the obligation you could most easily leave in that apartment.**',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'3.INT',chapter:3,title:'Integration — one living room, three frameworks',learner_title:'All of it at once',
 objectives:['obj-3.INT.a'],est_minutes:10,
 cold_open:{text:'Consent, capacity and a portable medical order rarely arrive one at a time. They turn up in the same living room, in the wrong order, with a relative in the doorway who has a firm view about all three and is not wrong to have one.',
  decision_point:'Whose decision is it, and when?'},
 pretest_item:null,
 screens:[
  {id:'scr-3.INT.1',body_md:'**Three questions, and the answers change during the call.**\n\nWho is deciding right now — the patient, the law on their behalf, or nobody yet? What does the paperwork in this room actually say, as opposed to what it is assumed to say? And what will the record show if somebody asks in two years?\n\nWhat follows is one call. Every answer moves at least once.',figure:null}],
 inline_checks:[],
 quiz:['itm-3.INT.000'],
 callback_md:'Implied consent when he could not decide. His own decision fifteen minutes later, because capacity is assessed now and not from how he was on arrival. The form limited nothing relevant, because an unmarked section is never a limitation. And his daughter, who is frightened and means well, has no authority over a capable adult.\n\nFour calls inside one, each under a different framework. **The only thing that will still exist in two years is what you wrote about the conversation** — which is why the last ten minutes of this call matter as much as the first ten.',
 local_overlay:'ks-amr-kc',version:'1.0.0'}
];
