// Chapter 2 — Workforce Safety and Wellness.
// Sourced to OSHA, CDC/HICPAC, NIOSH, the Education Standards, and the primary
// literature where the textbook position and the current evidence diverge —
// which in this chapter they do twice, in 2.5 and 2.8.
const STD='NHTSA National EMS Education Standards (2021) — Preparatory: Workforce Safety and Wellness.';
const OSHA='OSHA Bloodborne Pathogens Standard, 29 CFR 1910.1030.';
const CDC='CDC/HICPAC Guideline for Isolation Precautions (2007, with subsequent updates).';
const PEP='CDC/USPHS guidance on occupational post-exposure management of HBV, HCV and HIV.';
const RW='Ryan White HIV/AIDS Treatment Extension Act of 2009, Part G — notification of possible exposure for emergency response employees.';
const ROAD='NIOSH and NHTSA data on EMS worker fatalities and roadway operations; 23 CFR 634 (high-visibility apparel).';
const FAT='Patterson PD et al., Evidence-Based Guidelines for Fatigue Risk Management in EMS. Prehosp Emerg Care 2018;22(sup1):89–101.';
const DEB='Rose S et al., Psychological debriefing for preventing PTSD (Cochrane, 2002); NICE NG116 (2018); WHO mhGAP guidance.';
const FAM='Jabre P et al., Family presence during cardiopulmonary resuscitation. N Engl J Med 2013;368:1008–18.';
const IARC='IARC Monographs Volume 124 (2020) — night shift work.';

const opt=(id,text,correct,rationale)=>({id,text,correct,rationale});
const base=(o)=>({stimulus:{kind:'none',ref:null},bloom:'apply',nremt_domain:'ems_operations',
  cj_step:null,difficulty_seed:0.5,high_stakes:false,reviewed_by:null,
  review_status:'unreviewed',version:'1.0.0',...o});

export const objectives=[
 {id:'obj-2.1.a',chapter:2,tier:'core',text:'Apply standard precautions and select personal protective equipment by route of transmission',
  enables:'Decide what goes on your face before you touch the patient, not after'},
 {id:'obj-2.2.a',chapter:2,tier:'core',text:'Manage a blood or body fluid exposure, and state what the employer is required to provide',
  enables:'Protect yourself in the minutes after an exposure, when the decisions are time-limited'},
 {id:'obj-2.3.a',chapter:2,tier:'core',text:'Assess and manage scene risk, with particular attention to roadway and vehicle hazards',
  enables:'Guard against what actually kills EMS providers, rather than what feels dangerous'},
 {id:'obj-2.4.a',chapter:2,tier:'core',text:'Recognise acute, cumulative and traumatic stress responses in yourself and in colleagues',
  enables:'Tell an expected reaction from one that needs assessment, in yourself and in a partner'},
 {id:'obj-2.5.a',chapter:2,tier:'context',text:'Communicate a death and support a grieving family without relying on the stage model',
  enables:'Say the thing that has to be said, once, clearly, to someone who will remember it for years'},
 {id:'obj-2.6.a',chapter:2,tier:'context',text:'Apply the sleep, caffeine and activity practices that the evidence actually supports',
  enables:'Spend your effort on the habits that change alertness rather than the ones that sound healthy'},
 {id:'obj-2.7.a',chapter:2,tier:'core',text:'Apply fatigue risk management, and state how strong the evidence behind it is',
  enables:'Act on the guideline, and describe honestly what it does and does not rest on'},
 {id:'obj-2.8.a',chapter:2,tier:'core',text:'Distinguish what the evidence supports after a critical incident from what is traditionally offered',
  enables:'Choose a response after a bad call that is supported, and decline one that is not'},
 {id:'obj-2.INT.a',chapter:2,tier:'core',text:'Integrate hazard recognition, exposure management and post-incident response on one call',
  enables:'Handle a call that threatens you three different ways in the same hour'}
];

export const items=[
// ── 2.1 Standard precautions and PPE ──────────────────────────────────── 8
base({id:'itm-2.1.001',type:'mc',chapter:2,block:'2.1',objective:'obj-2.1.a',bloom:'understand',
 stem:'What do standard precautions require?',
 options:[opt('a','Treating every patient’s blood and body fluids as infectious, regardless of what you know about them',true,'The point is that you cannot tell by looking, and the patient often does not know either.'),
  opt('b','Full protective equipment on every patient',false,'The level is matched to the exposure expected, not fixed at maximum.'),
  opt('c','Precautions only for patients with a known infection',false,'That is the practice standard precautions replaced, and it failed precisely on the unknown cases.'),
  opt('d','Precautions only where blood is visible',false,'Body fluids other than visible blood transmit infection too.')],
 explanation_md:'Standard precautions assume infectiousness rather than trying to identify it. The older idea of protecting yourself only from known carriers failed on everyone who had not been diagnosed yet.',source_ref:CDC}),
base({id:'itm-2.1.002',type:'drag_drop',chapter:2,block:'2.1',objective:'obj-2.1.a',high_stakes:true,
 stem:'Sort each patient by the transmission-based precautions they need.',
 categories:[{id:'contact',label:'Contact'},{id:'droplet',label:'Droplet'},{id:'air',label:'Airborne'}],
 options:[opt('a','A three-week productive cough with night sweats and weight loss',true,'That presentation raises tuberculosis, which is airborne and needs a fit-tested respirator.'),
  opt('b','Suspected influenza with a wet cough',true,'Influenza is spread by droplets; a surgical mask and eye protection.'),
  opt('c','An open draining wound with a resistant organism',true,'Contact precautions: gloves and gown.'),
  opt('d','Suspected measles rash and fever',true,'Measles is airborne, and it is one of the most transmissible infections there is.')],
 answer_map:{a:'air',b:'droplet',c:'contact',d:'air'},
 explanation_md:'The route decides the equipment. Contact means gloves and gown, droplet means a surgical mask and eye protection, airborne means a fit-tested N95 or better — and, where possible, a surgical mask on the patient.',source_ref:CDC}),
base({id:'itm-2.1.003',type:'mc',chapter:2,block:'2.1',objective:'obj-2.1.a',high_stakes:true,
 stem:'You are called to a patient with a long productive cough, night sweats and weight loss. What do you wear?',
 options:[opt('a','A fit-tested N95 or better, with eye protection and gloves',true,'The presentation raises tuberculosis, and TB is airborne.'),
  opt('b','A surgical mask',false,'A surgical mask does not protect you from airborne particles.'),
  opt('c','Gloves alone',false,'Gloves do nothing against an airborne route.'),
  opt('d','Nothing beyond routine, unless the patient says they have TB',false,'Most people with undiagnosed TB cannot tell you they have it. That is the whole problem.')],
 explanation_md:'A respirator only protects you if it fits, which is why fit testing is not a formality. Put a surgical mask on the patient as well — it reduces what they put into the air.',source_ref:CDC}),
base({id:'itm-2.1.004',type:'mr',chapter:2,block:'2.1',objective:'obj-2.1.a',select_count:[3,4],
 stem:'Select every situation where eye protection should be on before you start.',
 options:[opt('a','Suctioning an airway',true,'Suctioning generates splash and spray directly toward your face.'),
  opt('b','Assisting at a delivery',true,'Childbirth is one of the highest-splash events in prehospital care.'),
  opt('c','Controlling an arterial bleed',true,'Arterial bleeding sprays, and it does not warn you first.'),
  opt('d','Assisting a ventilation with a bag-mask',true,'Bag-mask ventilation aerosolises and leaks around the seal.'),
  opt('e','Taking a blood pressure',false,'No splash risk, and routine precautions are enough.')],
 explanation_md:'Eyes are mucous membrane and the most commonly skipped protection. Every high-splash task in prehospital care points at your face.',source_ref:CDC}),
base({id:'itm-2.1.005',type:'options_box',chapter:2,block:'2.1',objective:'obj-2.1.a',bloom:'analyze',
 stem:'Is alcohol hand rub adequate, or are soap and running water needed?',
 columns:[{id:'rub',label:'Alcohol rub is adequate'},{id:'soap',label:'Soap and water needed'}],
 rows:[{id:'r1',label:'Hands are visibly soiled',answer:'soap'},
  {id:'r2',label:'Routine hand hygiene between clean patient contacts',answer:'rub'},
  {id:'r3',label:'Care of a patient with suspected C. difficile',answer:'soap'},
  {id:'r4',label:'After removing gloves, hands not visibly soiled',answer:'rub'}],
 options:[],
 explanation_md:'Alcohol does not kill spores and does not work through visible soil. Those are the two exceptions worth memorising; the rest of the time the rub is faster, and faster means it actually happens.',source_ref:CDC}),
base({id:'itm-2.1.006',type:'mc',chapter:2,block:'2.1',objective:'obj-2.1.a',bloom:'remember',
 stem:'Which single measure does most to prevent transmission of infection in healthcare?',
 options:[opt('a','Hand hygiene',true,'It is the most effective single measure, and the most frequently omitted.'),
  opt('b','Gowns',false,'Useful for contact precautions, but narrower in effect.'),
  opt('c','Respirators',false,'Essential for airborne routes, but they address one route.'),
  opt('d','Surface disinfection',false,'It matters, and it does less than hands.')],
 explanation_md:'The finding is old, consistent and still ignored daily. Gloves do not replace it: hands get contaminated during removal.',source_ref:CDC}),
base({id:'itm-2.1.007',type:'build_list',chapter:2,block:'2.1',objective:'obj-2.1.a',
 stem:'Put the removal of protective equipment in the order that keeps contamination off you.',
 options:[opt('a','Gloves',true,'Gloves are the most contaminated item and come off first.'),
  opt('b','Eye protection',true,'Removed next, handling it by the strap or arms.'),
  opt('c','Gown',true,'Rolled away from you, contaminated surface inward.'),
  opt('d','Mask or respirator',true,'Last, and by the ties or straps — the front is contaminated.')],
 explanation_md:'Doffing is when most self-contamination happens. Hand hygiene follows, and again after anything you touch on the way out.',source_ref:CDC}),
base({id:'itm-2.1.008',type:'mc',chapter:2,block:'2.1',objective:'obj-2.1.a',bloom:'analyze',
 stem:'Why is the order of removal of protective equipment taught as a sequence at all?',
 options:[opt('a','Because most self-contamination happens during removal, not during care',true,'The outside of everything you are wearing is the contaminated part, and removal is when you touch it.'),
  opt('b','Because it is faster',false,'It is not chosen for speed.'),
  opt('c','Because equipment is damaged in the wrong order',false,'Damage is not the concern.'),
  opt('d','Because regulations require a specific order for its own sake',false,'The sequence exists for a physical reason, not a formal one.')],
 explanation_md:'You protected yourself for twenty minutes and then wiped a contaminated glove across your own face. The sequence exists to stop exactly that.',source_ref:CDC}),

// ── 2.2 Exposure: what you do in the first hour ───────────────────────── 8
base({id:'itm-2.2.001',type:'mc',chapter:2,block:'2.2',objective:'obj-2.2.a',bloom:'understand',high_stakes:true,
 stem:'A used catheter needle punctures your hand. What is the first thing you do?',
 options:[opt('a','Wash the site with soap and running water',true,'Immediate washing is the first step, and it is the only one you can do straight away.'),
  opt('b','Squeeze the wound to express blood',false,'There is no evidence squeezing reduces transmission, and it damages tissue.'),
  opt('c','Apply bleach or a caustic antiseptic',false,'Not supported, and it injures the wound.'),
  opt('d','Finish the call and report at the end of shift',false,'The delay is the problem: some decisions after an exposure are measured in hours.')],
 explanation_md:'Wash, then report immediately. Squeezing and caustic agents are traditional, untested, and can make the wound worse.',source_ref:PEP}),
base({id:'itm-2.2.002',type:'mc',chapter:2,block:'2.2',objective:'obj-2.2.a',high_stakes:true,
 stem:'Why does an exposure have to be reported immediately rather than at the end of the shift?',
 options:[opt('a','Post-exposure prophylaxis for HIV works best started as soon as possible and is not recommended after 72 hours',true,'The window is real and it is short. Hours matter within it.'),
  opt('b','The paperwork is easier',false,'True and irrelevant.'),
  opt('c','The patient may be discharged',false,'Source testing is arranged through the process; it is not the reason for the urgency.'),
  opt('d','It is a disciplinary requirement',false,'There may be a policy, but the reason is pharmacological.')],
 explanation_md:'Prophylaxis is started on a clock. Waiting until the end of a shift can cost the whole benefit of it.',source_ref:PEP}),
base({id:'itm-2.2.003',type:'mr',chapter:2,block:'2.2',objective:'obj-2.2.a',bloom:'remember',select_count:[3,4],
 stem:'Select everything your employer must provide under the bloodborne pathogens standard.',
 options:[opt('a','Hepatitis B vaccination at no cost to you',true,'Offered at no cost, and you may decline it in writing.'),
  opt('b','A written exposure control plan, reviewed annually',true,'Required, and it names who does what after an exposure.'),
  opt('c','Post-exposure evaluation and follow-up by a healthcare professional',true,'Confidential, and at no cost to you.'),
  opt('d','Protective equipment appropriate to the task',true,'Provided, maintained and replaced by the employer.'),
  opt('e','Payment for time lost during follow-up appointments',false,'Not part of the standard, whatever local policy says.')],
 explanation_md:'These are obligations, not benefits. A service that asks you to pay for hepatitis B vaccination is not complying with the standard.',source_ref:OSHA}),
base({id:'itm-2.2.004',type:'options_box',chapter:2,block:'2.2',objective:'obj-2.2.a',bloom:'analyze',
 stem:'For each bloodborne pathogen, is there a vaccine, and is there post-exposure prophylaxis?',
 columns:[{id:'both',label:'Vaccine and PEP'},{id:'pep',label:'PEP but no vaccine'},{id:'neither',label:'Neither'}],
 rows:[{id:'r1',label:'Hepatitis B',answer:'both'},
  {id:'r2',label:'HIV',answer:'pep'},
  {id:'r3',label:'Hepatitis C',answer:'neither'}],
 options:[],
 explanation_md:'Hepatitis B is the one vaccination essentially solves, which is why declining it is a real decision. Hepatitis C has neither, and is managed by testing and treating infection if it develops.',source_ref:PEP}),
base({id:'itm-2.2.005',type:'mc',chapter:2,block:'2.2',objective:'obj-2.2.a',bloom:'remember',
 stem:'Which of these carries the highest risk of transmission from a single needlestick from a positive source?',
 options:[opt('a','Hepatitis B in an unvaccinated person',true,'By a wide margin — which is exactly why the vaccine is offered.'),
  opt('b','Hepatitis C',false,'Roughly two in a hundred, well below hepatitis B.'),
  opt('c','HIV',false,'Roughly three in a thousand for a percutaneous exposure.'),
  opt('d','All three are about equal',false,'They differ by more than an order of magnitude.')],
 explanation_md:'The ranking is worth knowing because it explains the countermeasures: a vaccine for the highest risk, prophylaxis for the one without a vaccine, and surveillance for the third.',source_ref:PEP}),
base({id:'itm-2.2.006',type:'mc',chapter:2,block:'2.2',objective:'obj-2.2.a',
 stem:'You transported a patient later diagnosed with an airborne infectious disease. How are you meant to find out?',
 options:[opt('a','Through your service’s designated officer, who receives and passes on the notification',true,'Federal law provides this route precisely because you leave before the diagnosis is made.'),
  opt('b','By calling the hospital and asking about the patient',false,'That is a privacy problem and an unreliable one.'),
  opt('c','You are not entitled to know',false,'Emergency response employees have a notification route in law.'),
  opt('d','By checking the patient care record',false,'The diagnosis was made after your record was closed.')],
 explanation_md:'You hand over and go. The designated officer exists so the information can come back to you afterwards without anyone breaching the patient’s privacy.',source_ref:RW}),
base({id:'itm-2.2.007',type:'drag_drop',chapter:2,block:'2.2',objective:'obj-2.2.a',
 stem:'Sort each action by when it happens after an exposure.',
 categories:[{id:'now',label:'Immediately'},{id:'hours',label:'Within hours'},{id:'later',label:'Over the following months'}],
 options:[opt('a','Wash the site with soap and water',true,'The first action, at the moment it happens.'),
  opt('b','Report to your supervisor and start the exposure process',true,'Immediately — it is what starts everything else.'),
  opt('c','Medical evaluation and a decision about prophylaxis',true,'Within hours, because of the prophylaxis window.'),
  opt('d','Follow-up serological testing',true,'Repeated over months, because seroconversion is not immediate.')],
 answer_map:{a:'now',b:'now',c:'hours',d:'later'},
 explanation_md:'Two things happen in the first minutes, one in the first hours, and one over the next six months. Only the first is in your hands alone.',source_ref:PEP}),
base({id:'itm-2.2.008',type:'mc',chapter:2,block:'2.2',objective:'obj-2.2.a',bloom:'analyze',
 stem:'Your service asks you to pay for your own hepatitis B vaccination. What is wrong with that?',
 options:[opt('a','The standard requires the employer to offer it at no cost to the employee',true,'Cost is the employer’s, and the offer must be made within the first weeks of assignment.'),
  opt('b','Nothing — vaccination is a personal choice',false,'Declining is your choice. Paying is not the arrangement the standard sets.'),
  opt('c','Only the first dose must be free',false,'The series and the titre are covered.'),
  opt('d','It is wrong only if you have already been exposed',false,'The obligation is not conditional on an exposure.')],
 explanation_md:'You can decline, in writing, and change your mind later at no cost. What cannot happen is the cost being moved onto you.',source_ref:OSHA}),
// ── 2.3 Scene safety, and what actually kills providers ───────────────── 8
base({id:'itm-2.3.001',type:'mc',chapter:2,block:'2.3',objective:'obj-2.3.a',bloom:'remember',
 stem:'What causes the largest share of on-duty EMS provider deaths?',
 options:[opt('a','Transportation-related events — ambulance crashes and being struck on the roadway',true,'Consistently the leading category in national fatality data.'),
  opt('b','Assault by patients or bystanders',false,'Assault is common and injuries are frequent, but it is not the leading cause of death.'),
  opt('c','Infectious disease acquired at work',false,'A real risk, and a small fraction of occupational deaths.'),
  opt('d','Lifting and moving injuries',false,'The leading cause of injury and lost time — not of death.')],
 explanation_md:'The thing most likely to kill you at work is a vehicle: yours, or somebody else’s coming past the scene. That is not where most people direct their attention.',source_ref:ROAD}),
base({id:'itm-2.3.002',type:'mc',chapter:2,block:'2.3',objective:'obj-2.3.a',high_stakes:true,
 stem:'Night, interstate shoulder. Your partner steps out into the live lane side without high-visibility apparel. What do you do?',
 options:[opt('a','Stop them, get the vest on, and work from the protected side of the apparatus',true,'Being struck is one of the two ways this job kills people, and it takes seconds to prevent.'),
  opt('b','Say nothing — they are experienced',false,'Experience does not make you visible at night.'),
  opt('c','Mention it afterwards',false,'Afterwards is too late for the only minute that mattered.'),
  opt('d','Move the ambulance closer to them',false,'Position matters, and it does not substitute for being seen.')],
 explanation_md:'High-visibility apparel meeting the national standard is required for workers on federal-aid highways. The rule exists because of a specific and repeated way people die.',source_ref:ROAD}),
base({id:'itm-2.3.003',type:'mr',chapter:2,block:'2.3',objective:'obj-2.3.a',bloom:'remember',select_count:[3,4],
 stem:'Select every measure that reduces your risk while working a roadway incident.',
 options:[opt('a','Positioning the apparatus to block the work area from oncoming traffic',true,'The vehicle is the barrier; the crew works behind it.'),
  opt('b','Wearing high-visibility apparel meeting the national standard',true,'Required on federal-aid highways, and sensible everywhere else.'),
  opt('c','Working from the side away from live traffic wherever possible',true,'Keeps you out of the lane that hurts people.'),
  opt('d','Keeping the number of people in the roadway to the minimum needed',true,'Fewer people exposed is fewer people at risk.'),
  opt('e','Facing away from traffic so you are not distracted',false,'You want to see what is coming toward you, not less of it.')],
 explanation_md:'Block, be seen, work on the protected side, and keep the exposure short. None of it is complicated, and all of it is skipped when a scene feels urgent.',source_ref:ROAD}),
base({id:'itm-2.3.004',type:'options_box',chapter:2,block:'2.3',objective:'obj-2.3.a',high_stakes:true,
 stem:'Enter now, or stage and wait?',
 columns:[{id:'enter',label:'Enter'},{id:'stage',label:'Stage and wait'}],
 rows:[{id:'r1',label:'Reported assault, the assailant is unaccounted for, police not yet on scene',answer:'stage'},
  {id:'r2',label:'Elderly fall, family at the door, scene quiet',answer:'enter'},
  {id:'r3',label:'Two workers unresponsive inside a grain bin',answer:'stage'},
  {id:'r4',label:'Chest pain at a supermarket, staff directing you in',answer:'enter'}],
 options:[],
 explanation_md:'Two patients down in an enclosed space is a chemical or oxygen-deficient atmosphere until proven otherwise. Walking in makes you the third.',source_ref:STD}),
base({id:'itm-2.3.005',type:'mc',chapter:2,block:'2.3',objective:'obj-2.3.a',high_stakes:true,bloom:'analyze',
 stem:'Why does more than one unresponsive person in an enclosed space change your approach entirely?',
 options:[opt('a','It points to an atmosphere that will do the same to you, so entry needs specialist protection',true,'Carbon monoxide, hydrogen sulfide and oxygen displacement all present exactly this way.'),
  opt('b','It means a mass-casualty declaration is required first',false,'The declaration is not what stops you being harmed.'),
  opt('c','It means the patients are more likely to be dead',false,'That is not the reasoning, and it would not change your protection.'),
  opt('d','It changes nothing if you move quickly',false,'Speed is exactly how rescuers become patients in confined spaces.')],
 explanation_md:'Rescuers make up a substantial share of confined-space deaths, and almost all of them entered to help. The pattern — more than one down, no obvious trauma — is the warning.',source_ref:STD}),
base({id:'itm-2.3.006',type:'drag_drop',chapter:2,block:'2.3',objective:'obj-2.3.a',
 stem:'Sort each hazard by the kind of control that addresses it.',
 categories:[{id:'traffic',label:'Traffic control'},{id:'security',label:'Law enforcement'},{id:'hazmat',label:'Specialist hazard team'}],
 options:[opt('a','A crash scene on a live interstate at night',true,'Blocking, apparatus position and high-visibility apparel.'),
  opt('b','A domestic assault with the assailant still unaccounted for',true,'Staging until the scene is secured is the control.'),
  opt('c','Unresponsive workers in a below-ground vault',true,'Confined space with an unknown atmosphere — specialist entry.'),
  opt('d','A tanker leaking an unidentified liquid',true,'Identify from a distance, upwind and uphill, and wait for the team.')],
 answer_map:{a:'traffic',b:'security',c:'hazmat',d:'hazmat'},
 explanation_md:'Each of these has a control, and none of the controls is you being careful. Recognising which one you need is the skill.',source_ref:STD}),
base({id:'itm-2.3.007',type:'mc',chapter:2,block:'2.3',objective:'obj-2.3.a',bloom:'analyze',
 stem:'What does the evidence show about running lights and siren on a typical urban transport?',
 options:[opt('a','It saves a small amount of time — commonly a few minutes — while raising crash risk',true,'Repeated studies find time savings of roughly one to four minutes, with measurably higher crash risk.'),
  opt('b','It saves no time at all',false,'It does save some; the point is how little, against the risk.'),
  opt('c','It reliably saves ten minutes or more',false,'Not what the studies find on typical urban transports.'),
  opt('d','It has no effect on crash risk',false,'Emergency operation carries a higher crash rate.')],
 explanation_md:'The honest summary: a few minutes, bought with a real increase in risk to you, your patient and everyone at the junction. Worth it for some patients, and for far fewer than it is used on.',source_ref:ROAD}),
base({id:'itm-2.3.008',type:'mc',chapter:2,block:'2.3',objective:'obj-2.3.a',
 stem:'Why does loose equipment in the patient compartment matter in a crash?',
 options:[opt('a','It becomes a projectile, and the patient compartment is where occupants are least protected',true,'Unrestrained equipment and unrestrained people are the two reasons that space is dangerous.'),
  opt('b','It is a licensing violation',false,'There may be a rule; the reason for the rule is physics.'),
  opt('c','It damages the equipment',false,'True and trivial by comparison.'),
  opt('d','It only matters at high speed',false,'Objects do not need highway speeds to injure someone.')],
 explanation_md:'You cannot always be belted while caring for a patient. You can always secure the monitor, the oxygen cylinder and the drug bag, and those are what strike people.',source_ref:ROAD}),

// ── 2.4 Stress: acute, cumulative, traumatic ──────────────────────────── 8
base({id:'itm-2.4.001',type:'mc',chapter:2,block:'2.4',objective:'obj-2.4.a',bloom:'understand',
 stem:'Which set of findings describes the acute stress response during a critical call?',
 options:[opt('a','Tachycardia, tunnel vision, reduced hearing of peripheral sound, distorted sense of time',true,'Sympathetic activation, with the perceptual narrowing that comes with it.'),
  opt('b','Emotional exhaustion, cynicism about patients, a sense of ineffectiveness',false,'Those describe burnout, which builds over months.'),
  opt('c','Intrusive memories and avoidance persisting beyond a month',false,'That pattern points toward a traumatic stress disorder, not the acute response.'),
  opt('d','Low mood and loss of interest over several weeks',false,'That describes depressive symptoms.')],
 explanation_md:'The acute response is adaptive in the moment and unhelpful for anything requiring precision — which is most of what you are doing.',source_ref:STD}),
base({id:'itm-2.4.002',type:'mr',chapter:2,block:'2.4',objective:'obj-2.4.a',select_count:[3,4],
 stem:'Select the features that describe burnout rather than a single bad shift.',
 options:[opt('a','Emotional exhaustion that does not lift with days off',true,'Exhaustion is the core feature and the earliest one.'),
  opt('b','Cynicism or detachment toward patients',true,'Depersonalisation: patients become cases, then obstacles.'),
  opt('c','A sense that nothing you do makes a difference',true,'Reduced personal accomplishment, the third dimension.'),
  opt('d','Building over months rather than hours',true,'Burnout is cumulative by definition.'),
  opt('e','Resolving fully after a good night’s sleep',false,'That describes acute fatigue, which is a different problem.')],
 explanation_md:'Burnout is classified as an occupational phenomenon rather than a medical condition. That does not make it minor — it locates the cause in the work.',source_ref:STD}),
base({id:'itm-2.4.003',type:'mc',chapter:2,block:'2.4',objective:'obj-2.4.a',high_stakes:true,
 stem:'A colleague has withdrawn, is drinking more, and said last week that there is no way out. What do you do?',
 options:[opt('a','Ask them directly whether they are thinking about suicide, and stay with the answer',true,'Asking directly does not plant the idea; the evidence does not support that fear.'),
  opt('b','Avoid the subject so as not to put the idea in their head',false,'This belief is common and not supported by evidence. Not asking is what leaves someone alone with it.'),
  opt('c','Tell a supervisor and leave it there',false,'Telling someone may be right as well, and it is not a substitute for asking the person.'),
  opt('d','Wait to see whether it passes',false,'The signs listed are not the ones to wait out.')],
 explanation_md:'The worry that asking about suicide increases risk has been examined and is not supported. Asking plainly, and then listening, is the intervention available to you.',source_ref:STD}),
base({id:'itm-2.4.004',type:'options_box',chapter:2,block:'2.4',objective:'obj-2.4.a',bloom:'analyze',
 stem:'Expected early reaction, or a reason to seek assessment?',
 columns:[{id:'expected',label:'Expected early reaction'},{id:'assess',label:'Seek assessment'}],
 rows:[{id:'r1',label:'Broken sleep and intrusive images for a few days after a paediatric arrest',answer:'expected'},
  {id:'r2',label:'The same symptoms, unchanged, two months later',answer:'assess'},
  {id:'r3',label:'Avoiding a whole district, and calling in sick to do it',answer:'assess'},
  {id:'r4',label:'Feeling shaken and tearful the evening after a bad call',answer:'expected'}],
 options:[],
 explanation_md:'Most people exposed to a traumatic event do not develop a disorder, and early distress usually settles. Persistence beyond about a month, or a real dent in functioning, is the line worth watching.',source_ref:DEB}),
base({id:'itm-2.4.005',type:'mc',chapter:2,block:'2.4',objective:'obj-2.4.a',bloom:'analyze',
 stem:'Why does perceptual narrowing under acute stress matter clinically rather than only personally?',
 options:[opt('a','It makes you miss information that is in front of you, which is what read-backs and checklists are for',true,'The countermeasure is procedural, because the narrowing itself is not under your control.'),
  opt('b','It makes you slower',false,'Reaction time changes, but missing information is the larger clinical problem.'),
  opt('c','It causes long-term memory loss',false,'Not the mechanism in question.'),
  opt('d','It only affects inexperienced providers',false,'It affects everyone; experience changes what you do about it.')],
 explanation_md:'This is why Chapter 1 put read-backs where it did. You cannot decide not to tunnel. You can build a step that catches what tunnelling loses.',source_ref:STD}),
base({id:'itm-2.4.006',type:'mc',chapter:2,block:'2.4',objective:'obj-2.4.a',bloom:'remember',
 stem:'How is burnout formally classified?',
 options:[opt('a','As an occupational phenomenon resulting from unmanaged chronic workplace stress',true,'Classified in relation to work, not as a medical diagnosis.'),
  opt('b','As an anxiety disorder',false,'It is not classified as a mental disorder.'),
  opt('c','As a form of depression',false,'The two overlap and are not the same construct.'),
  opt('d','As a personality trait',false,'It is a response to conditions, not a trait.')],
 explanation_md:'The classification matters practically: it points the remedy at workload, control and recovery rather than only at the individual.',source_ref:STD}),
base({id:'itm-2.4.007',type:'drag_drop',chapter:2,block:'2.4',objective:'obj-2.4.a',
 stem:'Sort each presentation by the pattern it fits.',
 categories:[{id:'acute',label:'Acute stress response'},{id:'cumulative',label:'Cumulative stress'},{id:'traumatic',label:'Traumatic stress'}],
 options:[opt('a','Hands shaking and time slowing during a first paediatric arrest',true,'The sympathetic response, in the moment.'),
  opt('b','Cynicism about patients and exhaustion that days off do not fix',true,'Cumulative, and the classic burnout pattern.'),
  opt('c','Intrusive images and avoidance of the district, three months on',true,'Persistent and impairing — the pattern that needs assessment.'),
  opt('d','Auditory exclusion while working an entrapment',true,'Acute, and entirely expected.')],
 answer_map:{a:'acute',b:'cumulative',c:'traumatic',d:'acute'},
 explanation_md:'The three have different time courses and different responses. Treating a normal acute reaction as a disorder is its own kind of harm.',source_ref:STD}),
base({id:'itm-2.4.008',type:'mc',chapter:2,block:'2.4',objective:'obj-2.4.a',bloom:'remember',
 stem:'What proportion of people exposed to a traumatic event go on to develop PTSD?',
 options:[opt('a','A minority — most recover without developing a disorder',true,'Early distress is common; persistent disorder is not the usual outcome.'),
  opt('b','Most of them',false,'This overestimate is common and it drives unnecessary intervention.'),
  opt('c','Almost none, so distress afterwards is abnormal',false,'Early distress is very common and expected.'),
  opt('d','It cannot be estimated',false,'It has been studied extensively across populations.')],
 explanation_md:'Holding both facts matters: early distress is normal, and a minority go on to a disorder. Getting this wrong in either direction leads to the wrong response, which is what 2.8 is about.',source_ref:DEB}),
// ── 2.5 Death, dying, and the family in the room ──────────────────────── 8
base({id:'itm-2.5.001',type:'mc',chapter:2,block:'2.5',objective:'obj-2.5.a',bloom:'understand',high_stakes:true,
 stem:'Resuscitation has been stopped. How do you tell the patient’s wife?',
 options:[opt('a','Use the word died, once, plainly, and then stop talking',true,'Plain language is understood the first time. The silence afterwards is part of it.'),
  opt('b','Say he has passed on',false,'Euphemisms are heard as ambiguous, and people ask again because they are not sure.'),
  opt('c','Say we lost him',false,'Same problem — it can be heard as a description of the search for a pulse.'),
  opt('d','Explain the resuscitation in detail first',false,'The detail matters later. It buries the one sentence she needs now.')],
 explanation_md:'People remember this sentence for the rest of their lives. Say it clearly, once, and then let the silence do its work rather than filling it.',source_ref:STD}),
base({id:'itm-2.5.002',type:'mc',chapter:2,block:'2.5',objective:'obj-2.5.a',high_stakes:true,
 stem:'A six-year-old asks what happened to their grandfather. What do you say?',
 options:[opt('a','That he died, using the word, in short concrete sentences',true,'Concrete language is what children can work with.'),
  opt('b','That he has gone to sleep',false,'Sleep euphemisms are associated with children becoming frightened of going to sleep.'),
  opt('c','That we lost him',false,'A young child may take this literally and ask where to look.'),
  opt('d','Nothing — a parent should tell them',false,'A parent should be there, and saying nothing while the child stands in the room is not neutral.')],
 explanation_md:'Below about five, death is often understood as reversible. Softening the language makes it more confusing, not less frightening.',source_ref:STD}),
base({id:'itm-2.5.003',type:'mr',chapter:2,block:'2.5',objective:'obj-2.5.a',bloom:'remember',select_count:[3,4],
 stem:'Select what is supported practice when telling a family someone has died.',
 options:[opt('a','Use the word died or dead rather than a euphemism',true,'Unambiguous language is understood the first time.'),
  opt('b','Say it early rather than after a long preamble',true,'The family is waiting for one piece of information.'),
  opt('c','Allow silence rather than filling it',true,'Silence gives the news somewhere to land.'),
  opt('d','Offer the family the chance to be with the body',true,'Where it is safe and practical, this matters to people.'),
  opt('e','Reassure them that you know how they feel',false,'You do not, and it moves the focus onto you.')],
 explanation_md:'Plain, early, quiet, and then present. Almost everything that goes wrong in a death notification is an attempt to soften it.',source_ref:STD}),
base({id:'itm-2.5.004',type:'options_box',chapter:2,block:'2.5',objective:'obj-2.5.a',bloom:'analyze',
 stem:'Supported by current evidence, or traditionally taught without support?',
 columns:[{id:'ev',label:'Supported by evidence'},{id:'trad',label:'Taught, not supported'}],
 rows:[{id:'r1',label:'Offering family the option to be present during resuscitation',answer:'ev'},
  {id:'r2',label:'Grief passing through five stages in order',answer:'trad'},
  {id:'r3',label:'Using the word died rather than a euphemism',answer:'ev'},
  {id:'r4',label:'Family presence interfering with resuscitation performance',answer:'trad'}],
 options:[],
 explanation_md:'A randomised trial of family presence during out-of-hospital resuscitation found fewer PTSD-related symptoms in relatives at 90 days, with no effect on resuscitation performance and no increase in medicolegal claims.',source_ref:FAM}),
base({id:'itm-2.5.005',type:'mc',chapter:2,block:'2.5',objective:'obj-2.5.a',bloom:'analyze',
 stem:'Why does a euphemism so often produce a second question from the family?',
 options:[opt('a','Because it is genuinely ambiguous, and under shock people take the least final reading',true,'"We lost him" can be heard as a description of a search rather than a death.'),
  opt('b','Because families are not listening',false,'They are listening intently. The sentence is the problem.'),
  opt('c','Because it is said too quietly',false,'Volume is not what makes it unclear.'),
  opt('d','Because families expect medical terminology',false,'Plain words are what is needed, not technical ones.')],
 explanation_md:'The kindness intended by softening the words is spent making the family ask again. Say the clear thing, then be gentle in everything that follows.',source_ref:STD}),
base({id:'itm-2.5.006',type:'mc',chapter:2,block:'2.5',objective:'obj-2.5.a',bloom:'remember',
 stem:'What did the randomised trial of family presence during out-of-hospital resuscitation find?',
 options:[opt('a','Relatives offered the chance to be present had fewer PTSD-related symptoms at 90 days',true,'With no measured harm to the resuscitation and no increase in claims.'),
  opt('b','Relatives present were more distressed at 90 days',false,'The result went the other way.'),
  opt('c','Resuscitation quality fell when relatives were present',false,'No such effect was found.'),
  opt('d','Medicolegal claims increased',false,'They did not.')],
 explanation_md:'This is one of the clearer reversals in prehospital practice: what was assumed to harm relatives appears to help them, provided someone is assigned to support them.',source_ref:FAM}),
base({id:'itm-2.5.007',type:'drag_drop',chapter:2,block:'2.5',objective:'obj-2.5.a',
 stem:'Sort each sentence by whether it belongs in a death notification.',
 categories:[{id:'say',label:'Say this'},{id:'avoid',label:'Avoid this'}],
 options:[opt('a','I am sorry. He died.',true,'Plain, and it is the sentence they are waiting for.'),
  opt('b','We did everything we could and he has passed on.',true,'The euphemism undoes the clarity of the first half.'),
  opt('c','Would you like to sit with him?',true,'Offering presence is supported and it is often what people want.'),
  opt('d','I know exactly how you feel.',true,'You do not, and it turns the moment toward you.')],
 answer_map:{a:'say',b:'avoid',c:'say',d:'avoid'},
 explanation_md:'Clear, then quiet, then available. Everything on the avoid side is an attempt to make the moment easier for the person speaking.',source_ref:STD}),
base({id:'itm-2.5.008',type:'mc',chapter:2,block:'2.5',objective:'obj-2.5.a',bloom:'analyze',
 stem:'What is the status of the five stages of grief as a model?',
 options:[opt('a','Widely taught, and not supported as a sequence people actually pass through',true,'Grief does not follow a fixed order, and most people do not show all five.'),
  opt('b','Well supported, and the expected course of normal grief',false,'The staged sequence has not held up when tested.'),
  opt('c','Supported for sudden death only',false,'The model was not derived from, or validated in, that setting.'),
  opt('d','Abandoned and no longer taught anywhere',false,'It is still taught almost everywhere, which is why it is worth knowing its status.')],
 explanation_md:'Use the five as a vocabulary for reactions you may see, not as a map. Expecting a sequence leads you to treat a normal reaction as a problem, or to wait for a stage that never comes.',source_ref:STD}),

// ── 2.6 Sleep, caffeine, food, movement ───────────────────────────────── 8
base({id:'itm-2.6.001',type:'mc',chapter:2,block:'2.6',objective:'obj-2.6.a',bloom:'understand',
 stem:'You drink coffee at 0400 on a night shift and plan to sleep at 0900. What is the problem?',
 options:[opt('a','Caffeine has a half-life of roughly five hours, so a substantial amount is still active at 0900',true,'Half of that dose is still on board when you lie down.'),
  opt('b','Caffeine does not affect alertness',false,'It does — that is why the timing matters.'),
  opt('c','Caffeine causes dehydration severe enough to disturb sleep',false,'The diuretic effect is modest and is not the mechanism here.'),
  opt('d','There is no problem; tolerance removes the effect',false,'Tolerance develops to some effects and does not clear the drug faster.')],
 explanation_md:'Caffeine works, and it is a tool with a clock on it. Front-load it in the shift; the cup near the end is the one that costs you the sleep afterwards.',source_ref:FAT}),
base({id:'itm-2.6.002',type:'mc',chapter:2,block:'2.6',objective:'obj-2.6.a',bloom:'understand',
 stem:'What does alcohol actually do to sleep?',
 options:[opt('a','It shortens the time to fall asleep and then fragments the second half of the night',true,'Net sleep quality is worse, even though getting to sleep feels easier.'),
  opt('b','It improves sleep quality throughout the night',false,'The second half of the night is disrupted.'),
  opt('c','It has no measurable effect on sleep architecture',false,'The effects on sleep structure are well described.'),
  opt('d','It is an effective long-term treatment for shift-work sleep problems',false,'It worsens them, and carries its own risks in this profession.')],
 explanation_md:'This is why it is such an easy habit to acquire on nights: the part you notice works, and the part that does the damage happens while you are asleep.',source_ref:STD}),
base({id:'itm-2.6.003',type:'mr',chapter:2,block:'2.6',objective:'obj-2.6.a',bloom:'remember',select_count:[3,4],
 stem:'Select the practices supported for sleeping around shift work.',
 options:[opt('a','A dark, cool and quiet sleep environment',true,'The most reliable environmental levers there are.'),
  opt('b','Keeping sleep timing as consistent as the roster allows',true,'Consistency helps the circadian system more than total hours alone.'),
  opt('c','Taking a planned nap when the shift allows one',true,'Napping is one of the fatigue guideline’s recommendations.'),
  opt('d','Managing light exposure — bright while working, dim on the way home',true,'Light is the strongest signal the circadian clock takes.'),
  opt('e','Using alcohol to fall asleep after a night shift',false,'It fragments the sleep it helped you start.')],
 explanation_md:'Dark, cool, quiet, consistent, and light used deliberately. Unglamorous, and it is what the evidence actually points at.',source_ref:FAT}),
base({id:'itm-2.6.004',type:'options_box',chapter:2,block:'2.6',objective:'obj-2.6.a',bloom:'analyze',
 stem:'Supported, or not supported?',
 columns:[{id:'yes',label:'Supported'},{id:'no',label:'Not supported'}],
 rows:[{id:'r1',label:'A planned nap on shift improves alertness',answer:'yes'},
  {id:'r2',label:'One long weekend sleep fully repays a week of restriction',answer:'no'},
  {id:'r3',label:'Bright light while working helps maintain alertness at night',answer:'yes'},
  {id:'r4',label:'A large meal at the end of a night shift improves recovery',answer:'no'}],
 options:[],
 explanation_md:'Recovery sleep restores alertness partially. Performance deficits from repeated restriction persist after a single long sleep, which is why "catching up on Sunday" does less than it feels like it does.',source_ref:FAT}),
base({id:'itm-2.6.005',type:'mc',chapter:2,block:'2.6',objective:'obj-2.6.a',bloom:'analyze',
 stem:'Why does one long weekend sleep not clear a week of restricted sleep?',
 options:[opt('a','Recovery is partial — alertness improves while measurable performance deficits persist',true,'Sleep debt is not repaid hour for hour by one long night.'),
  opt('b','Sleep debt cannot be reduced at all',false,'It can be reduced. It is not cleared in one go.'),
  opt('c','Long sleeps are harmful in themselves',false,'That is not the finding.'),
  opt('d','The effect is entirely psychological',false,'The deficits are measurable on objective testing.')],
 explanation_md:'The dangerous part is that subjective alertness recovers faster than performance does. You feel restored before you are, and then you drive.',source_ref:FAT}),
base({id:'itm-2.6.006',type:'mc',chapter:2,block:'2.6',objective:'obj-2.6.a',bloom:'remember',
 stem:'How is night shift work involving circadian disruption classified for cancer risk?',
 options:[opt('a','Probably carcinogenic to humans',true,'Classified in Group 2A on the basis of limited human and sufficient animal evidence.'),
  opt('b','Carcinogenic to humans',false,'That is the higher category; shift work sits one below it.'),
  opt('c','Not classifiable',false,'It has been evaluated and classified.'),
  opt('d','Probably not carcinogenic',false,'The evaluation went the other way.')],
 explanation_md:'This is not a reason to leave the job. It is a reason to take the countermeasures seriously rather than treating night work as neutral.',source_ref:IARC}),
base({id:'itm-2.6.007',type:'drag_drop',chapter:2,block:'2.6',objective:'obj-2.6.a',
 stem:'Sort each action by what it is actually for.',
 categories:[{id:'now',label:'Alertness during this shift'},{id:'later',label:'Sleep after this shift'}],
 options:[opt('a','Caffeine in the first half of the shift',true,'Alertness now, and early enough not to cost you sleep later.'),
  opt('b','Sunglasses on the drive home at dawn',true,'Reduces the light signal that would tell your clock to wake up.'),
  opt('c','A planned nap during a quiet period',true,'Alertness for the rest of the shift.'),
  opt('d','Blackout blinds and a cool bedroom',true,'Entirely about the sleep that follows.')],
 answer_map:{a:'now',b:'later',c:'now',d:'later'},
 explanation_md:'Two separate problems: staying functional tonight, and sleeping tomorrow. Most people work on the first and neglect the second, which is what makes the next shift worse.',source_ref:FAT}),
base({id:'itm-2.6.008',type:'mc',chapter:2,block:'2.6',objective:'obj-2.6.a',
 stem:'What can honestly be said about diet and exercise advice for EMS providers?',
 options:[opt('a','There is no EMS-specific regimen with good evidence; general activity and regular eating are what hold up',true,'The specifics marketed to shift workers are largely unsupported.'),
  opt('b','A specific shift-worker diet has strong evidence behind it',false,'No such regimen has good supporting evidence.'),
  opt('c','Exercise before a night shift is proven to prevent fatigue',false,'Not established, though activity is broadly beneficial.'),
  opt('d','Diet has no measurable relationship to health in shift workers',false,'That overstates it in the other direction.')],
 explanation_md:'Being straight about weak evidence is part of the skill. Regular activity and not eating one enormous meal at 0700 are defensible; the branded shift-worker protocol is not.',source_ref:STD}),
// ── 2.7 Fatigue risk management ───────────────────────────────────────── 8
base({id:'itm-2.7.001',type:'mc',chapter:2,block:'2.7',objective:'obj-2.7.a',bloom:'understand',
 stem:'What does the 2018 EMS fatigue risk management guideline recommend about shift length?',
 options:[opt('a','Shifts shorter than 24 hours',true,'One of five recommendations in the guideline.'),
  opt('b','Shifts of any length, provided naps are allowed',false,'Nap opportunity is a separate recommendation, not a substitute.'),
  opt('c','Shifts no longer than 8 hours',false,'The guideline does not set that threshold.'),
  opt('d','No recommendation is made about shift length',false,'One is made, and this is it.')],
 explanation_md:'Under 24 hours is a low bar, and it is where the evidence supported a recommendation. Do not read it as an endorsement of 23.',source_ref:FAT}),
base({id:'itm-2.7.002',type:'mr',chapter:2,block:'2.7',objective:'obj-2.7.a',bloom:'remember',select_count:[4,5],
 stem:'Select the recommendations made by the 2018 EMS fatigue risk management guideline.',
 options:[opt('a','Use validated survey instruments to measure and monitor fatigue',true,'Measuring it is the first recommendation.'),
  opt('b','Shifts shorter than 24 hours',true,'Recommended, conditionally.'),
  opt('c','Access to caffeine as a countermeasure',true,'Recommended, with the best of a weak evidence base.'),
  opt('d','The opportunity to nap while on duty',true,'Recommended, conditionally.'),
  opt('e','Mandatory annual fitness testing',false,'Not part of this guideline.')],
 explanation_md:'Five recommendations: measure fatigue, keep shifts under 24 hours, allow caffeine, allow napping, and train people in fatigue risk management.',source_ref:FAT}),
base({id:'itm-2.7.003',type:'mc',chapter:2,block:'2.7',objective:'obj-2.7.a',high_stakes:true,
 stem:'Hour 20 of a 24-hour shift, and you are not sure you are safe to drive. What is the professional action?',
 options:[opt('a','Say so, and ask for the driving to be handed over or the crew stood down',true,'Naming it is the act. The alternative is finding out on the road.'),
  opt('b','Drink coffee and continue driving',false,'Caffeine helps and it does not restore an impaired driver to baseline.'),
  opt('c','Continue, since the shift is nearly over',false,'The last hours of a long shift are the highest-risk ones.'),
  opt('d','Continue but drive more slowly',false,'Slower does not fix a lapse in attention.')],
 explanation_md:'This is 1.7 again in a different costume: saying what you cannot currently do safely is the professional act, not the embarrassing one.',source_ref:FAT}),
base({id:'itm-2.7.004',type:'options_box',chapter:2,block:'2.7',objective:'obj-2.7.a',bloom:'analyze',
 stem:'Is this within your control, or the system’s?',
 columns:[{id:'you',label:'Yours'},{id:'system',label:'The system’s'}],
 rows:[{id:'r1',label:'Sleep obtained before the shift starts',answer:'you'},
  {id:'r2',label:'Whether shifts run to 24 hours',answer:'system'},
  {id:'r3',label:'When in the shift you take caffeine',answer:'you'},
  {id:'r4',label:'Whether there is a policy permitting naps on duty',answer:'system'}],
 options:[],
 explanation_md:'Two of these change tonight and two change only if someone raises them. Knowing which is which stops you carrying a rostering problem as a personal failing.',source_ref:FAT}),
base({id:'itm-2.7.005',type:'mc',chapter:2,block:'2.7',objective:'obj-2.7.a',bloom:'analyze',high_stakes:true,
 stem:'Why is asking a tired provider how fatigued they feel an unreliable way to measure it?',
 options:[opt('a','Self-rating underestimates impairment — subjective alertness recovers faster than performance does',true,'The gap between how you feel and how you perform is the dangerous part.'),
  opt('b','People deliberately conceal fatigue',false,'Some do, and the measurement problem exists even among people answering honestly.'),
  opt('c','Fatigue cannot be measured at all',false,'Validated instruments exist; the guideline recommends using them.'),
  opt('d','Fatigue does not affect performance',false,'It affects vigilance, reaction time and decision quality.')],
 explanation_md:'This is precisely why the guideline recommends an instrument rather than a question. You are the least reliable judge of your own state at the moment it matters most.',source_ref:FAT}),
base({id:'itm-2.7.006',type:'mc',chapter:2,block:'2.7',objective:'obj-2.7.a',bloom:'analyze',
 stem:'How strong is the evidence underlying the 2018 fatigue guideline?',
 options:[opt('a','Weak — the recommendations are conditional, graded on low to very low quality evidence',true,'That is what the guideline itself reports, and it says so plainly.'),
  opt('b','Strong — based on multiple large randomised trials',false,'No such trial base exists in this field.'),
  opt('c','It is expert opinion with no systematic review',false,'A systematic process was followed; the underlying studies were weak.'),
  opt('d','The guideline does not report the strength of its evidence',false,'It reports it explicitly, which is one of its virtues.')],
 explanation_md:'Best available is not the same as strong. Acting on it is reasonable; quoting it as established fact is not, and the guideline is more honest about this than most of what it competes with.',source_ref:FAT}),
base({id:'itm-2.7.007',type:'drag_drop',chapter:2,block:'2.7',objective:'obj-2.7.a',
 stem:'Sort each measure by whether the fatigue guideline recommends it.',
 categories:[{id:'rec',label:'Recommended'},{id:'not',label:'Not part of the guideline'}],
 options:[opt('a','Napping opportunity during duty',true,'One of the five recommendations.'),
  opt('b','Fatigue education and training for personnel',true,'Also recommended.'),
  opt('c','Mandatory overtime to cover shortfalls',true,'Not recommended, and it works against everything else on the list.'),
  opt('d','Routine prescription of stimulant medication',true,'Not part of the guideline at all.')],
 answer_map:{a:'rec',b:'rec',c:'not',d:'not'},
 explanation_md:'The guideline is short and specific. Anything presented as "the fatigue guideline says" that is not one of the five is somebody adding their own view to it.',source_ref:FAT}),
base({id:'itm-2.7.008',type:'mc',chapter:2,block:'2.7',objective:'obj-2.7.a',
 stem:'What is the effect of fatigue on clinical performance?',
 options:[opt('a','Reduced vigilance, slower reaction time and poorer decision quality',true,'The same profile measured in other safety-critical industries.'),
  opt('b','It affects driving only',false,'Driving is the most studied, and it is not the only domain affected.'),
  opt('c','It affects mood without affecting performance',false,'Performance is measurably affected.'),
  opt('d','Experienced providers are unaffected',false,'Experience changes what you do about it, not whether it happens.')],
 explanation_md:'Fatigue does not announce itself as an error. It shows up as the dose you cannot remember giving and the sign you did not register.',source_ref:FAT}),

// ── 2.8 After a critical incident ─────────────────────────────────────── 8
base({id:'itm-2.8.001',type:'mc',chapter:2,block:'2.8',objective:'obj-2.8.a',bloom:'understand',high_stakes:true,
 stem:'What did the Cochrane review of single-session psychological debriefing find?',
 options:[opt('a','No reduction in psychological distress and no prevention of PTSD, with one trial showing increased symptoms at a year',true,'That is the finding, and it surprised the field.'),
  opt('b','A clear reduction in PTSD',false,'No such effect was found.'),
  opt('c','Benefit only in emergency workers',false,'No subgroup benefit of that kind was demonstrated.'),
  opt('d','Too few studies to say anything',false,'There were enough to reach a conclusion.')],
 explanation_md:'This is the clearest example in the chapter of a practice adopted widely, on strong intuition, that did not survive being tested.',source_ref:DEB}),
base({id:'itm-2.8.002',type:'mc',chapter:2,block:'2.8',objective:'obj-2.8.a',high_stakes:true,
 stem:'Your supervisor books a mandatory debriefing for the whole crew after a paediatric drowning. What is the defensible position?',
 options:[opt('a','Offer it, and do not compel attendance — the evidence does not support requiring it of everyone exposed',true,'Offered and voluntary is defensible; mandatory for all is not supported.'),
  opt('b','Require everyone to attend, since some will not come otherwise',false,'Compelling everyone is the part the evidence does not support.'),
  opt('c','Cancel it and offer nothing',false,'Doing nothing is not the alternative. Support, screening and access to care are.'),
  opt('d','Require attendance only for the crew who touched the patient',false,'The problem is compulsion, not who is compelled.')],
 explanation_md:'Guidance in the UK and from the WHO recommends against routine single-session debriefing for everyone exposed. Offering support, and making real care reachable, is what replaces it.',source_ref:DEB}),
base({id:'itm-2.8.003',type:'mr',chapter:2,block:'2.8',objective:'obj-2.8.a',bloom:'remember',select_count:[3,4],
 stem:'Select the responses after a critical incident that current evidence supports.',
 options:[opt('a','Practical support, safety, information and reconnection with people',true,'The psychological first aid principles.'),
  opt('b','Watchful waiting through the first month, with a route back if symptoms persist',true,'Recommended where symptoms are mild and recent.'),
  opt('c','Screening, and access to trauma-focused therapy for those who develop persistent symptoms',true,'Trauma-focused CBT and EMDR have the strongest treatment evidence.'),
  opt('d','Peer support that connects people to care rather than substituting for it',true,'Useful as a route in, not as the treatment.'),
  opt('e','A compulsory group session for everyone present within 72 hours',false,'This is the practice the evidence does not support.')],
 explanation_md:'Support, wait, screen, and treat those who need it with something that works. Less dramatic than a mandated session, and it is what holds up.',source_ref:DEB}),
base({id:'itm-2.8.004',type:'options_box',chapter:2,block:'2.8',objective:'obj-2.8.a',bloom:'analyze',
 stem:'Supported by current evidence, or not?',
 columns:[{id:'yes',label:'Supported'},{id:'no',label:'Not supported'}],
 rows:[{id:'r1',label:'Trauma-focused CBT for established PTSD',answer:'yes'},
  {id:'r2',label:'Mandatory single-session debriefing for everyone exposed',answer:'no'},
  {id:'r3',label:'Watchful waiting for mild symptoms in the first month',answer:'yes'},
  {id:'r4',label:'Debriefing reliably prevents PTSD',answer:'no'}],
 options:[],
 explanation_md:'The treatments with the strongest evidence are for people who have developed symptoms. There is no well-supported way to prevent PTSD by processing the event for everybody at once.',source_ref:DEB}),
base({id:'itm-2.8.005',type:'mc',chapter:2,block:'2.8',objective:'obj-2.8.a',bloom:'analyze',
 stem:'Why does it matter that the strongest debriefing evidence examined individual rather than group sessions?',
 options:[opt('a','It limits how far the finding stretches — group models are less well studied, with no good evidence they prevent PTSD either',true,'Stating the limit is more honest than claiming the review settles every format.'),
  opt('b','It means group debriefing has been shown to work',false,'It has not been shown to work; it has been studied less.'),
  opt('c','It makes the review irrelevant to EMS',false,'It is directly relevant, and it is not the last word on every format.'),
  opt('d','It means the review was poorly conducted',false,'The scope of a review is not a flaw in it.')],
 explanation_md:'Getting this right is the skill Chapter 1 was pointing at: say what the evidence shows, and say where it stops, without rounding either up.',source_ref:DEB}),
base({id:'itm-2.8.006',type:'mc',chapter:2,block:'2.8',objective:'obj-2.8.a',bloom:'remember',
 stem:'Which treatments have the strongest evidence for established PTSD?',
 options:[opt('a','Trauma-focused cognitive behavioural therapy and EMDR',true,'These are the first-line recommendations in major guidelines.'),
  opt('b','A single debriefing session',false,'Debriefing is a prevention attempt, and it does not work as one.'),
  opt('c','Rest and time off alone',false,'Time helps many people and is not a treatment for established disorder.'),
  opt('d','Peer support alone',false,'Valuable as a route to care, not as the care.')],
 explanation_md:'Knowing the answer matters because you may one day be the person telling a colleague that there is something that works, and that it is reachable.',source_ref:DEB}),
base({id:'itm-2.8.007',type:'drag_drop',chapter:2,block:'2.8',objective:'obj-2.8.a',
 stem:'Sort each response by when it belongs.',
 categories:[{id:'early',label:'First days and weeks'},{id:'persist',label:'If symptoms persist'}],
 options:[opt('a','Practical support, rest, information and contact with people',true,'Psychological first aid, in the early period.'),
  opt('b','Watchful waiting with a route back into care',true,'Also early, and it requires the route to actually exist.'),
  opt('c','Formal screening and assessment',true,'Once symptoms have not settled.'),
  opt('d','Trauma-focused CBT or EMDR',true,'Treatment for established symptoms, not prevention.')],
 answer_map:{a:'early',b:'early',c:'persist',d:'persist'},
 explanation_md:'Two things early, two things later. The mistake the evidence keeps finding is doing the later things to everybody, early, whether or not they need them.',source_ref:DEB}),
base({id:'itm-2.8.008',type:'mc',chapter:2,block:'2.8',objective:'obj-2.8.a',
 stem:'What does watchful waiting mean in the first month after a traumatic event?',
 options:[opt('a','Active monitoring with a planned review, not simply hoping it resolves',true,'Someone is checking, a date is set, and the route into care stays open.'),
  opt('b','Taking no action of any kind',false,'That is neglect wearing the name.'),
  opt('c','Starting therapy immediately for everyone',false,'That is the opposite approach, and it is not recommended for mild recent symptoms.'),
  opt('d','Removing the provider from duty for a month',false,'Not part of what the term means.')],
 explanation_md:'The waiting is the deliberate part. Most early symptoms settle; the plan exists so that the people whose symptoms do not settle are actually found.',source_ref:DEB}),

// ── 2.INT Integration ─────────────────────────────────────────────────── 8
base({id:'itm-2.INT.000',type:'scenario',chapter:2,block:'2.INT',objective:'obj-2.INT.a',
 stimulus:{kind:'scenario',ref:null,
  text:'0340. Hour 18 of a 24-hour shift. A single-storey house fire, knocked down. Two firefighters went into the basement to check for extension; one is now being carried out unresponsive, and command wants him in your truck immediately.\n\nYou are parked on a narrow street. A second engine is manoeuvring past you and a crowd has come out to watch.\n\nEn route, securing an intravenous line in a moving ambulance, the patient moves and the used catheter needle catches the back of your hand through the glove.\n\nHe is pronounced in the emergency department forty minutes later. Your supervisor meets you in the corridor, tells you a mandatory debriefing is booked for the whole crew at 0900, and asks whether you can pick up the next shift because somebody has called in sick.'},
 children:['itm-2.INT.001','itm-2.INT.002','itm-2.INT.003','itm-2.INT.004',
  'itm-2.INT.005','itm-2.INT.006','itm-2.INT.007'],
 stem:'',options:[],explanation_md:'',source_ref:STD}),
base({id:'itm-2.INT.001',type:'mc',chapter:2,block:'2.INT',objective:'obj-2.INT.a',parent:'itm-2.INT.000',high_stakes:true,
 stem:'An unresponsive firefighter carried out of a basement. What should that raise before you touch him?',
 options:[opt('a','An atmosphere that is still dangerous — carbon monoxide, other products of combustion, or oxygen displacement',true,'The basement did this to a firefighter in protective equipment. It has not stopped.'),
  opt('b','That he has had a cardiac event unrelated to the fire',false,'Possible, and not the thing that changes anyone’s safety in the next minute.'),
  opt('c','That he was struck by falling material',false,'It would not explain an unresponsive patient with no obvious injury.'),
  opt('d','Nothing in particular — treat as an unresponsive adult',false,'The location is the single most informative finding you have.')],
 explanation_md:'The environment that produced the patient is the first piece of the history, and on this call it is the part that protects you.',source_ref:STD}),
base({id:'itm-2.INT.002',type:'mc',chapter:2,block:'2.INT',objective:'obj-2.INT.a',parent:'itm-2.INT.000',
 stem:'A second engine is manoeuvring past you on a narrow street with a crowd out. What matters most?',
 options:[opt('a','Where you stand while loading — a moving apparatus in a tight street is the immediate physical risk',true,'Being struck by a vehicle is one of the two ways this job kills people.'),
  opt('b','Crowd control for the onlookers',false,'It matters and it is not the thing most likely to injure you in the next two minutes.'),
  opt('c','Repositioning your ambulance for a faster exit',false,'Useful later; it does not address where your feet are now.'),
  opt('d','Nothing — the scene is under fire command',false,'Command does not stand where you are standing.')],
 explanation_md:'The fire is out and the vehicles are still moving. That is the point in these calls at which people get hurt, because everyone has relaxed.',source_ref:ROAD}),
base({id:'itm-2.INT.003',type:'mc',chapter:2,block:'2.INT',objective:'obj-2.INT.a',parent:'itm-2.INT.000',high_stakes:true,
 stem:'The needle catches the back of your hand. What do you do about it, and when?',
 options:[opt('a','Wash it with soap and water as soon as the patient is safe, and report it before the end of this call',true,'Washing first, reporting immediately — the prophylaxis window is measured in hours.'),
  opt('b','Squeeze the site to express blood, then continue',false,'No evidence supports squeezing, and it damages tissue.'),
  opt('c','Report it at the end of the shift with the rest of the paperwork',false,'That delay can cost the entire benefit of post-exposure prophylaxis.'),
  opt('d','Nothing — it went through a glove',false,'A glove reduces inoculum. It does not make this a non-event.')],
 explanation_md:'The patient is still your responsibility, and this does not wait until the shift ends. Hand over, wash, report, and let the process start.',source_ref:PEP}),
base({id:'itm-2.INT.004',type:'mr',chapter:2,block:'2.INT',objective:'obj-2.INT.a',parent:'itm-2.INT.000',select_count:[3,4],
 stem:'What must your employer provide following this exposure?',
 options:[opt('a','A confidential medical evaluation at no cost to you',true,'Required under the bloodborne pathogens standard.'),
  opt('b','Post-exposure follow-up, including serological testing over time',true,'Part of the required follow-up.'),
  opt('c','Hepatitis B vaccination at no cost, if you are not already immune',true,'Offered at no cost, and you may have declined it earlier and changed your mind.'),
  opt('d','Access to the written exposure control plan',true,'It must exist and be available to you.'),
  opt('e','A guarantee of the source patient’s test results',false,'Source testing is sought through the process, and it is not something you are guaranteed.')],
 explanation_md:'These are obligations under the standard, not favours. Knowing them is what lets you ask for the right thing at 0500 when nobody is keen to start paperwork.',source_ref:OSHA}),
base({id:'itm-2.INT.005',type:'mc',chapter:2,block:'2.INT',objective:'obj-2.INT.a',parent:'itm-2.INT.000',high_stakes:true,
 stem:'You are asked to pick up the next shift at hour 18 of 24. What is the defensible answer?',
 options:[opt('a','Decline, and say plainly that you are not fit to work it safely',true,'Naming it is the professional act, and it is the one the guideline exists to make possible.'),
  opt('b','Accept, and manage it with caffeine',false,'Caffeine helps and does not return an impaired provider to baseline.'),
  opt('c','Accept, since refusing leaves the service short',false,'The shortfall is the roster’s problem, and it is not solved by an unfit crew.'),
  opt('d','Accept, but ask not to drive',false,'Not driving reduces one risk, and you are still delivering clinical care impaired.')],
 explanation_md:'Shifts shorter than 24 hours is a guideline recommendation. Being asked to extend one past 30, straight after this call, is exactly the situation it was written about.',source_ref:FAT}),
base({id:'itm-2.INT.006',type:'mc',chapter:2,block:'2.INT',objective:'obj-2.INT.a',parent:'itm-2.INT.000',
 stem:'A mandatory debriefing is booked for the whole crew at 0900. What is the evidence-based objection?',
 options:[opt('a','Compelling everyone exposed to a single session is not supported, and one trial found worse symptoms a year on',true,'Offer it. Requiring it is the part the evidence does not support.'),
  opt('b','Debriefing is harmful in every form and should never be offered',false,'That overstates the finding in the other direction.'),
  opt('c','It should be held sooner, within an hour',false,'Timing is not what the objection rests on.'),
  opt('d','There is no objection — mandatory sessions are standard practice',false,'Widespread practice is not evidence, which is the point of 1.6.')],
 explanation_md:'Two things can be true: people need support after this call, and compelling all of them into one session is not the way to give it.',source_ref:DEB}),
base({id:'itm-2.INT.007',type:'options_box',chapter:2,block:'2.INT',objective:'obj-2.INT.a',parent:'itm-2.INT.000',bloom:'analyze',
 stem:'Over the month after this call, is each response supported?',
 columns:[{id:'yes',label:'Supported'},{id:'no',label:'Not supported'}],
 rows:[{id:'r1',label:'Practical support, rest, and contact with people you trust',answer:'yes'},
  {id:'r2',label:'A planned check-in, with a route into care if symptoms persist',answer:'yes'},
  {id:'r3',label:'A compulsory session for everyone on the crew tomorrow morning',answer:'no'},
  {id:'r4',label:'Alcohol to get to sleep after the night shifts',answer:'no'}],
 options:[],
 explanation_md:'Everything on the supported side is unremarkable and reachable. That is usually what the evidence turns out to favour.',source_ref:DEB}),
];

export const blocks=[
{id:'2.1',chapter:2,title:'Standard precautions and PPE',learner_title:'What goes on your face',
 objectives:['obj-2.1.a'],est_minutes:7,
 cold_open:{text:'Three calls into the shift: a nosebleed, a three-week productive cough with night sweats and weight loss, and an open fracture. You have gloves, surgical masks, a fit-tested N95 and eye protection on the truck. One of those three calls needs something the other two do not.',
  decision_point:'Which one, and what?'},
 pretest_item:'itm-2.1.001',
 screens:[
  {id:'scr-2.1.1',body_md:'**Standard precautions assume infectiousness rather than trying to identify it.** Every patient’s blood and body fluids are treated as infectious, whatever you have been told.\n\nThis replaced the older idea of protecting yourself from known carriers, which failed for an obvious reason: it protected you from everybody except the people who had not been diagnosed yet.',figure:null},
  {id:'scr-2.1.2',body_md:'**The route decides the equipment.**\n\n**Contact** — gloves, and a gown where contamination is likely.\n**Droplet** — a surgical mask and eye protection.\n**Airborne** — a fit-tested respirator, N95 or better, and a surgical mask on the patient where you can.\n\nTuberculosis, measles and varicella are the airborne ones you will meet.',figure:null},
  {id:'scr-2.1.3',body_md:'**Hand hygiene is the highest-value single act**, and the most frequently skipped. Alcohol rub is faster, and faster means it happens.\n\nTwo exceptions where soap and running water are needed: hands that are visibly soiled, and organisms alcohol does not kill — *C. difficile* among them. Gloves do not replace any of this, because hands get contaminated during removal.',figure:null},
  {id:'scr-2.1.4',body_md:'**Eye protection is mucous membrane protection**, and it is the one most often left in the bag.\n\nSuctioning, bag-mask ventilation, childbirth and arterial bleeding all spray toward your face and none of them warn you first. If you are doing one of those four, it should already be on.',figure:null},
  {id:'scr-2.1.5',body_md:'**Most self-contamination happens during removal.** The outside of everything you are wearing is the dirty part, and taking it off is when you touch it.\n\nGloves, then eye protection, then gown, then the mask or respirator — by the straps, away from the front. Then hand hygiene. Twenty minutes of protection is undone by one careless glove across a face.',figure:null}],
 inline_checks:['itm-2.1.003','itm-2.1.006'],
 quiz:['itm-2.1.002','itm-2.1.004','itm-2.1.005','itm-2.1.007','itm-2.1.008'],
 callback_md:'The cough. Three weeks, night sweats and weight loss raises tuberculosis, and TB is airborne — a fit-tested respirator for you, a surgical mask on the patient.\n\nThe nosebleed and the open fracture are splash risks: gloves and eye protection, and a gown if you are going to be in it. **The decision is made before contact, not after**, because the exposure you are protecting against has already happened by the time you think to reach for the bag.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'2.2',chapter:2,title:'Exposure: the first hour',learner_title:'When it happens to you',
 objectives:['obj-2.2.a'],est_minutes:8,
 cold_open:{text:'Securing an intravenous line in a moving ambulance, the patient moves, and the used catheter needle catches the back of your hand through the glove. The patient is still your patient. The hospital is fifteen minutes away. Nobody saw it.',
  decision_point:'What happens now, and how fast?'},
 pretest_item:'itm-2.2.001',
 screens:[
  {id:'scr-2.2.1',body_md:'**Wash it.** Soap and running water for skin; water or saline for a splash to the eye or mouth.\n\nSqueezing the wound and applying bleach or a caustic antiseptic are traditional, untested, and damage tissue. Neither is recommended. Wash, and move on to the part that has a clock on it.\n\nA glove reduces how much blood reaches you, which is worth having. It does not turn a needlestick into a non-event, and it is not a reason to skip anything below.',figure:null},
  {id:'scr-2.2.2',body_md:'**Report immediately — not at the end of the shift.** The reason is pharmacological, not administrative.\n\nPost-exposure prophylaxis for HIV works best started as soon as possible and is not recommended beyond 72 hours. A shift you finish quietly can spend most of that window before anyone knows an exposure happened.\n\nReporting is also what starts source testing and the medical evaluation. None of that begins until somebody is told.',figure:null},
  {id:'scr-2.2.3',body_md:'**Your employer has obligations, and they are not favours.** A written exposure control plan. Hepatitis B vaccination at no cost. Protective equipment. Sharps engineering controls.\n\nAnd after an exposure: a confidential medical evaluation and follow-up by a healthcare professional, at no cost to you. If you are asked to pay, something is wrong.',figure:null},
  {id:'scr-2.2.4',body_md:'**Three pathogens, three different answers.**\n\n**Hepatitis B** — highest transmission risk of the three, and a vaccine that essentially solves it.\n**HIV** — roughly three per thousand from a percutaneous exposure, and prophylaxis exists.\n**Hepatitis C** — around two per hundred, no vaccine, no prophylaxis; monitored, and treated if infection develops.',figure:null},
  {id:'scr-2.2.5',body_md:'**You leave before the diagnosis is made.** That is what the designated officer is for: federal law provides a route for notification when a patient you transported turns out to have a reportable infectious disease.\n\nIt runs through your service, not through you telephoning the hospital — which would be both unreliable and a privacy problem.',figure:null}],
 inline_checks:['itm-2.2.005','itm-2.2.006'],
 quiz:['itm-2.2.002','itm-2.2.003','itm-2.2.004','itm-2.2.007','itm-2.2.008'],
 callback_md:'Wash it now. Report it before this call is finished, not at 0700 — the prophylaxis window is measured in hours and you have already spent some of it.\n\nThen a confidential medical evaluation, at no cost to you, and follow-up testing over the months that follow. **Nobody saw it is not a reason to absorb it.** The only person the silence protects is the one who does not have to open a file.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'2.3',chapter:2,title:'Scene safety and the roadway',learner_title:'What actually kills people here',
 objectives:['obj-2.3.a'],est_minutes:8,
 cold_open:{text:'Night, interstate shoulder, a car on its roof and traffic that is not slowing down. Your partner steps out of the ambulance on the live lane side, without a vest, and walks toward the wreck. You are looking at the car.',
  decision_point:'Are you looking at the right thing?'},
 pretest_item:'itm-2.3.001',
 screens:[
  {id:'scr-2.3.1',body_md:'**Transportation events cause the largest share of on-duty EMS deaths.** Two forms: the ambulance crashing, and providers being struck while working a roadway.\n\nLifting injuries are more common. Assaults are more frequent than either. But the thing most likely to kill you at work is a vehicle, and it is usually not the one you are looking at.',figure:null},
  {id:'scr-2.3.2',body_md:'**Four things reduce roadway risk**, and none of them is being careful.\n\nBlock the work area with the apparatus. Wear high-visibility apparel meeting the national standard — it is required on federal-aid highways. Work from the protected side. Keep the number of people in the roadway to the minimum the job needs.\n\nDo all four before you look at the patient, because afterwards you will not remember to.',figure:null},
  {id:'scr-2.3.3',body_md:'**The patient compartment is the least protected space in the vehicle.** You cannot always be belted while treating someone, so the equipment has to be.\n\nAn unsecured monitor or oxygen cylinder is what injures people in a crash. And the evidence on lights and siren is unglamorous: commonly one to four minutes saved on an urban transport, with measurably higher crash risk.',figure:null},
  {id:'scr-2.3.4',body_md:'**Violence: staging is a clinical decision, not cowardice.** If the scene is not secure, you wait, however long it feels.\n\nA crew that enters early and is injured has removed the only ambulance the patient had. Assess continuously — scenes change after you arrive, and the reassuring first impression is not a guarantee for the next ten minutes.',figure:null},
  {id:'scr-2.3.5',body_md:'**More than one person down in an enclosed space is an atmosphere until proven otherwise.** Carbon monoxide, hydrogen sulfide, oxygen displacement — all present exactly like that.\n\nRescuers make up a large share of confined-space deaths, and nearly all of them entered to help. The pattern is the warning: several down, no obvious injury, nothing visible in the air.',figure:null}],
 inline_checks:['itm-2.3.002','itm-2.3.005'],
 quiz:['itm-2.3.003','itm-2.3.004','itm-2.3.006','itm-2.3.007','itm-2.3.008'],
 callback_md:'No. The car has already done what it is going to do. The traffic behind you has not.\n\nStop your partner, get the vest on, block with the apparatus and work from the protected side. **The hazard that kills EMS providers is almost never the one everyone on scene is staring at** — it is moving past at seventy miles an hour while you crouch beside a door.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'2.4',chapter:2,title:'Stress: acute, cumulative, traumatic',learner_title:'Three different things',
 objectives:['obj-2.4.a'],est_minutes:7,
 cold_open:{text:'Three weeks after a paediatric arrest you are sleeping badly, snapping at your partner, and checking on your own child twice a night. Nothing is dramatic. Everything is slightly off, and you have not mentioned it to anyone because it sounds like nothing when you say it out loud.',
  decision_point:'Is this a normal reaction, or a problem?'},
 pretest_item:'itm-2.4.001',
 screens:[
  {id:'scr-2.4.1',body_md:'**The acute response is sympathetic activation**: tachycardia, tunnel vision, loss of peripheral sound, a distorted sense of time.\n\nUseful for running away from something. Actively unhelpful for drawing up a dose correctly, which is why the countermeasure is procedural — read-backs and checklists — rather than a decision to concentrate harder.',figure:null},
  {id:'scr-2.4.2',body_md:'**Cumulative stress builds over months** and has three recognised features: emotional exhaustion, cynicism or detachment toward patients, and a sense that nothing you do makes a difference.\n\nBurnout is classified as an occupational phenomenon rather than a medical condition. That is not a demotion — it points the remedy at workload, control and recovery rather than only at you.',figure:null},
  {id:'scr-2.4.3',body_md:'**Traumatic stress is a third thing, and the numbers matter in both directions.** Early distress after a bad call is common and usually settles. A minority of people exposed go on to a persistent disorder.\n\nThe line worth watching is persistence past about a month, or a real dent in how you function — avoiding a district, calling in sick to avoid it.',figure:null},
  {id:'scr-2.4.4',body_md:'**In a colleague, the signs are unspectacular.** Withdrawal. Drinking more. Irritability that is new. Absence. Talking about being trapped, or about there being no way out.\n\nAsk them directly whether they are thinking about suicide. The fear that asking puts the idea there has been examined and is not supported — and not asking is what leaves someone alone with it.',figure:null},
  {id:'scr-2.4.5',body_md:'**What helps is unremarkable**: sleep, routine, staying connected to people, and a route into actual care when it is needed.\n\nWhat is not supported is compelling everyone exposed into a single session to process it. That is a whole block of its own, and it is 2.8 — because it is the clearest case in this chapter of a good intention that did not survive testing.',figure:null}],
 inline_checks:['itm-2.4.003','itm-2.4.006'],
 quiz:['itm-2.4.002','itm-2.4.004','itm-2.4.005','itm-2.4.007','itm-2.4.008'],
 callback_md:'Three weeks is inside the window where this is a common reaction, and the shape of it — sleep, irritability, checking your own child — is recognisably about the call.\n\n**What decides it is what happens next.** Settling over the following weeks is the usual course. Still there at two months, or starting to change what you will do and where you will go, is the point to get it assessed. Say it out loud to somebody now, precisely because it sounds like nothing.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'2.5',chapter:2,title:'Death, dying and the family',learner_title:'The sentence they will remember',
 objectives:['obj-2.5.a'],est_minutes:7,
 cold_open:{text:'You have stopped the resuscitation in the living room. His wife is standing by the sofa and asks whether he is gone. A six-year-old is in the doorway behind her, and nobody has moved the child.',
  decision_point:'What do you say, and what do you not say?'},
 pretest_item:'itm-2.5.001',
 screens:[
  {id:'scr-2.5.1',body_md:'**Use the word.** "I am sorry. He died." Once, plainly, early — and then stop.\n\nPassed on, gone, we lost him: each is genuinely ambiguous, and under shock people take the least final reading available. The softening is spent making the family ask a second time, which is harder on them than the plain sentence was.',figure:null},
  {id:'scr-2.5.2',body_md:'**Then be quiet.** The silence after is not an awkward gap to fill with an account of the resuscitation.\n\nThe detail matters later and some of it they will ask for. Right now one piece of information has to land, and talking over it is the most common way a death notification goes wrong.',figure:null},
  {id:'scr-2.5.3',body_md:'**Children need the concrete word more than adults do.** Below about five, death is often understood as reversible, and "gone to sleep" is associated with children becoming frightened of sleeping.\n\nShort sentences. The real word. A parent present if one can be. Saying nothing while a child stands in the doorway is not a neutral act.',figure:null},
  {id:'scr-2.5.4',body_md:'**Family presence during resuscitation is supported.** A randomised trial of relatives offered the chance to be present during out-of-hospital resuscitation found fewer PTSD-related symptoms at 90 days.\n\nNo measured harm to the resuscitation, and no increase in medicolegal claims. It works when someone is assigned to stay with them — not when they are simply left at the edge of the room.',figure:null},
  {id:'scr-2.5.5',body_md:'**The five stages are taught everywhere and are not supported as a sequence.** Grief does not arrive in order, and most people do not show all five.\n\nUse them as a vocabulary for reactions you may see, never as a map. Expecting a stage that does not come, or treating a normal reaction as the wrong one, is what the model costs when it is taken literally.',figure:null}],
 inline_checks:['itm-2.5.002','itm-2.5.006'],
 quiz:['itm-2.5.003','itm-2.5.004','itm-2.5.005','itm-2.5.007','itm-2.5.008'],
 callback_md:'"I am sorry. He died." Then nothing, for as long as it takes.\n\nTo the child, in the doorway, the same word in shorter sentences — not asleep, not lost. Offer them both the chance to sit with him.\n\n**What you do not say is the part people get wrong**: no euphemism, no account of the resuscitation before the sentence, and never that you know how they feel. You do not, and it moves the room onto you at the one moment it should not be.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'2.6',chapter:2,title:'Sleep, caffeine, food, movement',learner_title:'What actually works',
 objectives:['obj-2.6.a'],est_minutes:7,
 cold_open:{text:'0400 on a night shift, second coffee of the hour, a garage sandwich in your hand, and a plan to catch up on sleep properly on Sunday. Every part of that plan feels reasonable at the time, and most of it is working against the thing you want.',
  decision_point:'Which part of it actually works?'},
 pretest_item:'itm-2.6.001',
 screens:[
  {id:'scr-2.6.1',body_md:'**Caffeine works, and it has a clock on it.** The half-life is roughly five hours, so a cup at 0400 is still half present at 0900, when you are trying to sleep.\n\nFront-load it. The cup that gets you through the last hour of the shift is the one that costs you the sleep after it, and the next shift pays.',figure:null},
  {id:'scr-2.6.2',body_md:'**Recovery sleep is partial.** One long weekend night improves how alert you feel more than it restores measurable performance, and deficits from a week of restriction persist.\n\nThat gap is the dangerous part: you feel recovered before you are, and then you get in a vehicle. Catching up on Sunday helps, and it does not reset the week.',figure:null},
  {id:'scr-2.6.3',body_md:'**The levers that hold up are dull.** Dark, cool and quiet. Sleep timing as consistent as the roster allows. A planned nap when the shift permits one. Light used deliberately — bright while working, dimmed on the drive home at dawn.\n\nLight is the strongest signal your circadian system takes, which makes sunglasses at 0700 a clinical intervention rather than an affectation.',figure:null},
  {id:'scr-2.6.4',body_md:'**Alcohol is the trap.** It shortens the time to fall asleep and fragments the second half of the night, so the part you notice works and the part that does the damage happens while you are unconscious.\n\nIt is an easy habit to acquire on nights, for exactly that reason, and it makes the underlying sleep problem worse rather than better.',figure:null},
  {id:'scr-2.6.5',body_md:'**Be honest about the rest.** There is no EMS-specific diet with good evidence behind it. What holds up is regular eating rather than one enormous meal at the end of a shift, hydration, and any regular activity you will actually keep doing.\n\nNight shift work involving circadian disruption is classified as probably carcinogenic — a reason to take the countermeasures seriously, not a reason to leave.',figure:null}],
 inline_checks:['itm-2.6.002','itm-2.6.006'],
 quiz:['itm-2.6.003','itm-2.6.004','itm-2.6.005','itm-2.6.007','itm-2.6.008'],
 callback_md:'The coffee works — four hours ago. At 0400 it is mostly buying tomorrow’s bad sleep.\n\nThe sandwich is close to irrelevant either way. The Sunday plan helps and does not clear the week: alertness comes back faster than performance does, which is precisely why people drive home feeling fine.\n\n**What would actually change the next shift** is the nap you did not take, the sunglasses on the way home, and the room being dark enough.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'2.7',chapter:2,title:'Fatigue risk management',learner_title:'Hour twenty of twenty-four',
 objectives:['obj-2.7.a'],est_minutes:7,
 cold_open:{text:'Hour twenty of a twenty-four. Second cardiac arrest of the night. You are holding a syringe and you genuinely cannot remember whether you gave that dose or only drew it up. Your partner is looking at you and the monitor is alarming.',
  decision_point:'Whose problem is this — yours, or the roster’s?'},
 pretest_item:'itm-2.7.001',
 screens:[
  {id:'scr-2.7.1',body_md:'**Fatigue degrades vigilance, reaction time and decision quality**, and it does not announce itself as an error. It shows up as a dose you cannot account for and a sign you never registered.\n\nWorse: the fatigued person is a poor judge of how fatigued they are. Subjective alertness recovers before performance does, so you feel adequate while measurably not being it.',figure:null},
  {id:'scr-2.7.2',body_md:'**There is a guideline, and it is short.** Five recommendations, published in 2018:\n\nMeasure fatigue with validated survey instruments. Keep shifts shorter than 24 hours. Allow access to caffeine. Give the opportunity to nap on duty. Train personnel in fatigue risk management.\n\nThat is the whole list.',figure:null},
  {id:'scr-2.7.3',body_md:'**Now the honest part.** Every one of those five is a *conditional* recommendation, and the underlying evidence was graded low to very low quality.\n\nThat is not a reason to ignore it — it is the best synthesis the field has, arrived at by a proper process. It is a reason not to quote it as established fact, and the guideline says so itself, which is more than most of what competes with it.',figure:null},
  {id:'scr-2.7.4',body_md:'**Separate what you control from what you do not.** Yours: sleep before the shift, when you take caffeine, whether you take the nap when it is offered, and whether you say you are unfit.\n\nThe system’s: shift length, rostering, and whether a nap policy exists at all. Carrying a rostering problem as a personal failing helps nobody and changes nothing.',figure:null},
  {id:'scr-2.7.5',body_md:'**Naming it is the professional act.** Exactly like saying you have not done a skill in a year — uncomfortable once, defensible forever.\n\nThe alternative is discovering where your limit was on the way back, at four in the morning, with a patient in the back. That is the version of this conversation nobody gets to have twice.',figure:null}],
 inline_checks:['itm-2.7.003','itm-2.7.008'],
 quiz:['itm-2.7.002','itm-2.7.004','itm-2.7.005','itm-2.7.006','itm-2.7.007'],
 callback_md:'Both, and they are not the same problem. Right now: say it out loud, get your partner to verify the dose, and use the read-back rather than your memory.\n\n**Afterwards it is the roster’s.** A twenty-four hour shift is longer than the guideline recommends, and the fifth recommendation exists so that a crew can say so. Treat the lapse as evidence about the schedule, not as evidence about you — that is what it is.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'2.8',chapter:2,title:'After a critical incident',learner_title:'What the evidence supports',
 objectives:['obj-2.8.a'],est_minutes:8,
 cold_open:{text:'A paediatric drowning. Back at the station the supervisor books a mandatory debriefing for the whole crew at 0900 tomorrow, so that everyone gets it out. Nobody in the room objects, and two people quietly do not want to go.',
  decision_point:'Does that session help?'},
 pretest_item:'itm-2.8.001',
 screens:[
  {id:'scr-2.8.1',body_md:'**What is taught:** a structured group session within 24 to 72 hours of a critical incident, adopted widely across EMS and fire, on the reasonable intuition that talking it through early prevents lasting harm.\n\nIt is one of the most confidently taught interventions in this profession, and it is worth knowing what happened when it was tested.',figure:null},
  {id:'scr-2.8.2',body_md:'**What the evidence found:** a Cochrane review of single-session psychological debriefing reported no reduction in psychological distress and no prevention of PTSD — and one trial found a significantly *increased* risk of symptoms at one year.\n\nMajor guidance now recommends against routine single-session debriefing for everyone exposed.',figure:null},
  {id:'scr-2.8.3',body_md:'**The honest limit on that claim.** The strongest evidence examined individual debriefing. Group models of the kind EMS uses have been studied less well.\n\nSo the accurate statement is narrower than "debriefing is harmful": there is no good evidence that it prevents PTSD in any format, and the evidence does not support compelling people into it. Offered, never mandatory, is defensible.',figure:null},
  {id:'scr-2.8.4',body_md:'**What is supported instead.** Practical support, safety, information and reconnection — the psychological first aid principles. Watchful waiting through the first month, which means active monitoring with a planned review, not hoping.\n\nThen screening, and trauma-focused CBT or EMDR for anyone whose symptoms persist. Those two have the strongest treatment evidence there is.',figure:null},
  {id:'scr-2.8.5',body_md:'**Peer support belongs here as a route, not as the treatment.** Its value is getting somebody through a door they would not have opened alone.\n\nAnd the wider point is 1.6 arriving on a night you will remember: *we have always done it this way* is not evidence. This is what it costs when a confident practice is never tested against the thing it claims to prevent.',figure:null}],
 inline_checks:['itm-2.8.002','itm-2.8.008'],
 quiz:['itm-2.8.003','itm-2.8.004','itm-2.8.005','itm-2.8.006','itm-2.8.007'],
 callback_md:'Not as booked. Compelling everyone exposed into a single session is the part the evidence does not support, and one trial found worse symptoms a year later.\n\n**Offer it instead.** Then do the things that hold up: practical support tonight, a planned check-in rather than hoping, and a real route into trauma-focused therapy for anyone whose symptoms have not settled in a month.\n\nThe two people who quietly did not want to go should not have to explain themselves.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'2.INT',chapter:2,title:'Integration — one hour, four threats',learner_title:'All of it at once',
 objectives:['obj-2.INT.a'],est_minutes:9,
 cold_open:{text:'This chapter does not arrive one topic at a time. An atmosphere, a roadway, an exposure and a system making poor decisions on your behalf can all land inside the same hour, and each one is easier to miss because you are dealing with the others.',
  decision_point:'Can you catch all four?'},
 pretest_item:null,
 screens:[
  {id:'scr-2.INT.1',body_md:'**Four questions, running at once.**\n\nWhat produced this patient, and is it still there? Where am I standing? Has anything got into me? And who is making decisions about my next twelve hours?\n\nWhat follows is one call. Every one of the four comes up, three of them inside forty minutes, and the last one is asked in a corridor when you are too tired to argue.',figure:null}],
 inline_checks:[],
 quiz:['itm-2.INT.000'],
 callback_md:'The basement is the history — an atmosphere that did this to a firefighter in protective equipment. The street is where you are most likely to be hurt, after the fire is out and everyone has relaxed.\n\nThe needlestick is washed and reported before the call ends, because the window is hours. The extra shift is declined, and the mandatory session is offered rather than required.\n\n**Four threats, four different answers, and not one of them is being more careful.**',
 local_overlay:'ks-amr-kc',version:'1.0.0'}
];
