// Chapter 1 — EMS Systems.
// Sourced to the National EMS Scope of Practice Model and the Education
// Standards. Kansas scope and AMR KC standing orders are deliberately NOT
// here: they belong in local_overlay so the base module stays portable.
const SOP='National EMS Scope of Practice Model (NHTSA, 2019; 2021 update) — AEMT.';
const STD='NHTSA National EMS Education Standards (2021) — Preparatory: EMS Systems.';
const NR='NREMT Advanced EMT Examination Specifications, effective 1 July 2024.';

const opt=(id,text,correct,rationale)=>({id,text,correct,rationale});
const base=(o)=>({stimulus:{kind:'none',ref:null},bloom:'apply',nremt_domain:'ems_operations',
  cj_step:null,difficulty_seed:0.5,high_stakes:false,reviewed_by:null,
  review_status:'unreviewed',version:'1.0.0',...o});

export const objectives=[
 {id:'obj-1.1.a',chapter:1,tier:'core',text:'Distinguish EMR, EMT, AEMT and Paramedic by scope, and state what AEMT adds',
  enables:'Know before you act whether a skill is yours to perform or one you must call for'},
 {id:'obj-1.2.a',chapter:1,tier:'core',text:'Differentiate scope of practice, standard of care, protocol, and licensure, certification and credentialing',
  enables:'Recognise when an instruction you have been given would take you outside your scope'},
 {id:'obj-1.3.a',chapter:1,tier:'core',text:'Identify the components of an EMS system and how a call moves through them',
  enables:'Know who to ask for what when something on a call is not going to plan'},
 {id:'obj-1.4.a',chapter:1,tier:'core',text:'Differentiate online from offline medical direction and apply standing orders',
  enables:'Act on a standing order without delay, and know the point at which you must call'},
 {id:'obj-1.5.a',chapter:1,tier:'core',text:'Apply destination logic using specialty centre capability and transfer requirements',
  enables:'Choose a destination that can actually treat the problem, rather than the nearest door'},
 {id:'obj-1.6.a',chapter:1,tier:'core',text:'Explain continuous quality improvement and how evidence changes practice',
  enables:'Read a practice change and judge what it rests on, instead of taking it on authority'},
 {id:'obj-1.7.a',chapter:1,tier:'context',text:'Describe professional attributes and define mobile integrated healthcare',
  enables:'Recognise the conduct that keeps a licence, and what MIH asks of a crew'},
 {id:'obj-1.INT.a',chapter:1,tier:'core',text:'Integrate scope, medical direction and destination on a single call',
  enables:'Hold all three together under time pressure, which is when they conflict'}
];

export const items=[
// ── 1.1 What an AEMT actually is ──────────────────────────────────────── 8
base({id:'itm-1.1.001',type:'mc',chapter:1,block:'1.1',objective:'obj-1.1.a',bloom:'understand',
 stem:'What most clearly distinguishes the AEMT level from the EMT level?',
 options:[opt('a','A limited set of advanced skills, including IV access and selected medications',true,'AEMT adds a defined set of advanced skills on top of the EMT foundation.'),
  opt('b','The ability to work without medical direction',false,'Every level works under medical direction. AEMT does not change that.'),
  opt('c','Authority to determine a patient’s diagnosis',false,'No prehospital level diagnoses. Providers form impressions and treat findings.'),
  opt('d','Supervision of EMTs on scene',false,'Crew roles are set by the agency, not by the certification level.')],
 explanation_md:'The Scope of Practice Model builds each level on the one below it. AEMT is the EMT scope plus a limited advanced set — not a different kind of practice.',source_ref:SOP}),
base({id:'itm-1.1.002',type:'drag_drop',chapter:1,block:'1.1',objective:'obj-1.1.a',high_stakes:true,
 stem:'Sort each skill by the lowest level licensed to perform it.',
 categories:[{id:'emt',label:'EMT'},{id:'aemt',label:'AEMT'},{id:'para',label:'Paramedic'}],
 options:[opt('a','Automated external defibrillation',true,'AED use is within the EMT scope.'),
  opt('b','Peripheral IV access',true,'IV access is one of the skills AEMT adds.'),
  opt('c','Cardiac rhythm interpretation and manual defibrillation',true,'Manual defibrillation and rhythm interpretation are paramedic-level.'),
  opt('d','Oral glucose for a conscious hypoglycaemic patient',true,'Oral glucose is an EMT skill.')],
 answer_map:{a:'emt',b:'aemt',c:'para',d:'emt'},
 explanation_md:'Each level includes everything below it. A skill being within your scope is separate from whether your protocol authorises it today.',source_ref:SOP}),
base({id:'itm-1.1.003',type:'mc',chapter:1,block:'1.1',objective:'obj-1.1.a',bloom:'remember',
 stem:'Which level is the entry point of the national licensure structure?',
 options:[opt('a','Emergency Medical Responder',true,'EMR is the first level, intended for those who arrive before an ambulance.'),
  opt('b','Emergency Medical Technician',false,'EMT is the second level, built on EMR.'),
  opt('c','Advanced EMT',false,'AEMT is the third level.'),
  opt('d','Paramedic',false,'Paramedic is the highest of the four.')],
 explanation_md:'Four levels: EMR, EMT, AEMT, Paramedic. Each is a superset of the one before it.',source_ref:SOP}),
base({id:'itm-1.1.004',type:'mr',chapter:1,block:'1.1',objective:'obj-1.1.a',select_count:[2,3],
 stem:'Select everything the AEMT level typically adds to the EMT scope.',
 options:[opt('a','Establishing peripheral intravenous access',true,'IV access is a defining AEMT addition.'),
  opt('b','Administering a limited set of medications by additional routes',true,'AEMT widens both the drug list and the routes available.'),
  opt('c','Supraglottic airway placement',true,'Advanced airway adjuncts short of intubation sit at AEMT.'),
  opt('d','Interpreting a 12-lead electrocardiogram',false,'That is paramedic-level.'),
  opt('e','Performing needle decompression of the chest',false,'Needle thoracostomy is a paramedic skill.')],
 explanation_md:'The pattern is access and a limited drug set, not independent diagnosis or invasive procedures.',source_ref:SOP}),
base({id:'itm-1.1.005',type:'mc',chapter:1,block:'1.1',objective:'obj-1.1.a',high_stakes:true,
 cj_step:'take_action',
 stem:'A paramedic asks you, an AEMT, to push a drug that is outside your scope while they manage the airway. What do you do?',
 options:[opt('a','Decline, and offer to take over the airway so they can give it',true,'Scope is a legal limit on you. A colleague cannot widen it, and swapping tasks solves the problem.'),
  opt('b','Give it, since a paramedic directed you',false,'A verbal instruction does not extend your licence. You would be acting outside scope.'),
  opt('c','Give it and document that the paramedic ordered it',false,'Documenting an out-of-scope act does not make it lawful.'),
  opt('d','Call medical control for permission',false,'Medical control cannot authorise a skill your licence does not include.')],
 explanation_md:'Scope is set by the state and is not negotiable on scene. Neither a partner nor a physician can extend it.',source_ref:SOP}),
base({id:'itm-1.1.006',type:'mc',chapter:1,block:'1.1',objective:'obj-1.1.a',bloom:'understand',
 stem:'An EMR arrives first at a cardiac arrest. What should you expect them to have done?',
 options:[opt('a','Started compressions and applied an AED',true,'EMR scope covers immediate lifesaving care with minimal equipment.'),
  opt('b','Established an IV and given epinephrine',false,'Both are beyond EMR scope.'),
  opt('c','Placed a supraglottic airway',false,'Advanced airway adjuncts are above EMR.'),
  opt('d','Interpreted the rhythm and defibrillated manually',false,'Manual defibrillation is paramedic-level.')],
 explanation_md:'EMR exists to close the gap before the ambulance. Knowing what they can do tells you what you are walking into.',source_ref:SOP}),
base({id:'itm-1.1.007',type:'options_box',chapter:1,block:'1.1',objective:'obj-1.1.a',bloom:'remember',
 stem:'Is each skill within the AEMT scope?',
 columns:[{id:'in',label:'Within AEMT scope'},{id:'out',label:'Above AEMT scope'}],
 rows:[{id:'r1',label:'Intravenous access',answer:'in'},{id:'r2',label:'Endotracheal intubation',answer:'out'},
  {id:'r3',label:'Supraglottic airway',answer:'in'},{id:'r4',label:'Manual defibrillation',answer:'out'},
  {id:'r5',label:'Blood glucose measurement',answer:'in'}],
 options:[],
 explanation_md:'The national model sets the ceiling. Your state may sit below it, and your protocol may sit below that again.',source_ref:SOP}),
base({id:'itm-1.1.008',type:'mc',chapter:1,block:'1.1',objective:'obj-1.1.a',bloom:'analyze',
 stem:'Why does the national model describe levels as building on one another rather than as separate jobs?',
 options:[opt('a','Because every level keeps the whole scope beneath it, so a higher level never loses a lower skill',true,'A paramedic still performs EMT care. The levels are cumulative.'),
  opt('b','Because each level replaces the one below it',false,'Nothing is given up on moving up a level.'),
  opt('c','Because the levels are interchangeable on scene',false,'They are not. Each has a defined ceiling.'),
  opt('d','Because states are required to license all four',false,'States decide which levels they license.')],
 explanation_md:'Cumulative scope is why a crew of mixed levels works: the higher level can do everything the lower one can, and more.',source_ref:SOP}),

// ── 1.2 Scope, protocol, licensure ────────────────────────────────────── 9
base({id:'itm-1.2.001',type:'mc',chapter:1,block:'1.2',objective:'obj-1.2.a',bloom:'understand',high_stakes:true,
 stem:'Which of these is set by the state rather than by your employer or medical director?',
 options:[opt('a','Scope of practice',true,'Scope is defined in state law and regulation.'),
  opt('b','Protocol',false,'Protocol is written by the medical director, inside the state scope.'),
  opt('c','Credentialing',false,'Credentialing is an agency verifying an individual may practise there.'),
  opt('d','Shift assignment',false,'An operational matter, not a legal one.')],
 explanation_md:'Scope comes from the state. Protocol narrows it. Credentialing decides which individuals may work under it.',source_ref:SOP}),
base({id:'itm-1.2.002',type:'drag_drop',chapter:1,block:'1.2',objective:'obj-1.2.a',high_stakes:true,
 stem:'Sort each statement by which concept it describes.',
 categories:[{id:'scope',label:'Scope of practice'},{id:'standard',label:'Standard of care'},{id:'protocol',label:'Protocol'}],
 options:[opt('a','The skills state law permits at your level',true,'That is the definition of scope.'),
  opt('b','What a reasonable provider of your level would do in the same situation',true,'That is the standard of care, and it is a negligence concept.'),
  opt('c','Your medical director’s written instruction for a presentation',true,'That is protocol.'),
  opt('d','The legal ceiling on what you may perform at all',true,'Also scope — it is a ceiling, not a checklist.')],
 answer_map:{a:'scope',b:'standard',c:'protocol',d:'scope'},
 explanation_md:'Scope is a legal ceiling. Protocol is an instruction inside it. Standard of care is how your conduct is judged afterwards.',source_ref:STD}),
base({id:'itm-1.2.003',type:'mc',chapter:1,block:'1.2',objective:'obj-1.2.a',high_stakes:true,
 stem:'A skill is within your state scope but your agency protocol does not include it. May you perform it?',
 options:[opt('a','No — protocol may narrow scope, and you practise under your protocol',true,'You may do what is in both. Protocol narrowing scope is normal and binding.'),
  opt('b','Yes — state scope overrides agency protocol',false,'Scope permits; it does not require. Your medical director decides what you actually do.'),
  opt('c','Yes, if a paramedic agrees',false,'A colleague cannot authorise you outside your protocol.'),
  opt('d','Only if you document the reason',false,'Documentation does not authorise an act.')],
 explanation_md:'Think of it as two circles. You practise in the overlap, and the overlap is always the smaller of the two.',source_ref:SOP}),
base({id:'itm-1.2.004',type:'options_box',chapter:1,block:'1.2',objective:'obj-1.2.a',bloom:'remember',
 stem:'Who confers each of these?',
 columns:[{id:'state',label:'The state'},{id:'agency',label:'Your agency'},{id:'national',label:'A national body'}],
 rows:[{id:'r1',label:'Licensure to practise',answer:'state'},
  {id:'r2',label:'Certification of competence by examination',answer:'national'},
  {id:'r3',label:'Credentialing to work at this service',answer:'agency'}],
 options:[],
 explanation_md:'Certification says you passed. Licensure says the state permits you. Credentialing says this employer permits you. All three are needed.',source_ref:STD}),
base({id:'itm-1.2.005',type:'mc',chapter:1,block:'1.2',objective:'obj-1.2.a',
 stem:'You move to another state holding a current national certification. What do you still need?',
 options:[opt('a','A licence from the new state, and credentialing by the new employer',true,'Certification travels; the authority to practise does not.'),
  opt('b','Nothing — national certification is a licence',false,'It is evidence of competence, not permission to practise.'),
  opt('c','Only employer credentialing',false,'The state must license you as well.'),
  opt('d','Only a state licence',false,'The employer must still credential you.')],
 explanation_md:'This is the practical reason the three words are not interchangeable, and why the distinction is worth holding.',source_ref:STD}),
base({id:'itm-1.2.006',type:'mr',chapter:1,block:'1.2',objective:'obj-1.2.a',high_stakes:true,select_count:[2,3],
 stem:'Select every situation that puts you outside your scope of practice.',
 options:[opt('a','Performing a skill your licence level does not include',true,'That is the definition of exceeding scope.'),
  opt('b','Performing a skill after your licence has lapsed',true,'Without a current licence you have no scope at all.'),
  opt('c','Performing a skill a physician verbally asked you to do that is above your level',true,'A physician cannot extend a licence.'),
  opt('d','Performing a skill in your scope that your protocol omits',false,'That is a protocol violation, which is serious, but it is not outside scope.'),
  opt('e','Declining a skill within your scope',false,'Declining may be a clinical judgement. It does not exceed anything.')],
 explanation_md:'Scope violations and protocol violations are different failures with different consequences. Both matter; only one is practising without a licence.',source_ref:SOP}),
base({id:'itm-1.2.007',type:'mc',chapter:1,block:'1.2',objective:'obj-1.2.a',bloom:'analyze',high_stakes:true,
 stem:'Why is scope confusion the most common root of AEMT disciplinary action?',
 options:[opt('a','Because the boundary is invisible at the bedside and only becomes clear afterwards',true,'Nothing on scene stops you. The line is found in review, and by then the act is done.'),
  opt('b','Because AEMT scope changes frequently',false,'It is fairly stable. The problem is knowing where it sits, not tracking changes.'),
  opt('c','Because protocols are optional',false,'They are not optional.'),
  opt('d','Because states do not publish their scope',false,'They publish it. It has to be read.')],
 explanation_md:'This is why the boundary is worth knowing cold rather than looking up: on a bad call there is no time to look it up.',source_ref:SOP}),
base({id:'itm-1.2.008',type:'mc',chapter:1,block:'1.2',objective:'obj-1.2.a',bloom:'remember',
 stem:'What is the standard of care used to judge your actions after a call?',
 options:[opt('a','What a reasonable provider of the same level would have done in the same circumstances',true,'It is a comparison to a reasonable peer, not to an ideal or to hindsight.'),
  opt('b','What the best provider in the service would have done',false,'The comparison is to a reasonable provider, not the best one.'),
  opt('c','What the protocol says, word for word',false,'Protocol is evidence of the standard, not the whole of it.'),
  opt('d','What the outcome turned out to be',false,'A bad outcome does not by itself establish a breach.')],
 explanation_md:'Reasonable, same level, same circumstances. Protocol is strong evidence of what reasonable looks like, which is why deviating from it needs a reason you can state.',source_ref:STD}),
base({id:'itm-1.2.009',type:'mc',chapter:1,block:'1.2',objective:'obj-1.2.a',bloom:'understand',
 stem:'Where would you look to find what you may do on a given call today?',
 options:[opt('a','Your protocol, having confirmed the skill is within your state scope',true,'Protocol inside scope is the operative answer for today.'),
  opt('b','The national Scope of Practice Model alone',false,'It is a model states adapt. It is not your authority.'),
  opt('c','The national certification examination blueprint',false,'That describes what is tested, not what you may perform.'),
  opt('d','Whatever your partner did last shift',false,'Practice is not set by precedent on the truck.')],
 explanation_md:'The national model shapes state law; state law sets your ceiling; protocol tells you what to do beneath it.',source_ref:SOP}),

// ── 1.3 How the system is built ───────────────────────────────────────── 8
base({id:'itm-1.3.001',type:'build_list',chapter:1,block:'1.3',objective:'obj-1.3.a',
 stem:'Put the stages of a typical emergency call in order.',
 options:[opt('a','Public access — someone calls for help',true,'Nothing starts until the system is told.'),
  opt('b','Dispatch — the call is triaged and a resource is sent',true,'Dispatch decides what goes and gives pre-arrival instructions.'),
  opt('c','Prehospital assessment and treatment',true,'The crew arrives and care begins.'),
  opt('d','Transport to a capable destination',true,'Care continues to a facility able to take over.'),
  opt('e','Transfer of care and definitive treatment',true,'The handoff and what follows it.')],
 explanation_md:'Every component exists to move a patient from the moment of need to definitive care. A weak link anywhere costs the whole chain.',source_ref:STD}),
base({id:'itm-1.3.002',type:'mc',chapter:1,block:'1.3',objective:'obj-1.3.a',bloom:'understand',
 stem:'What is the purpose of emergency medical dispatch giving pre-arrival instructions?',
 options:[opt('a','Care begins before the ambulance arrives',true,'Compressions or bleeding control started by a caller can decide the outcome.'),
  opt('b','It keeps the caller occupied',false,'The instructions are clinical, not a distraction.'),
  opt('c','It replaces the need for a rapid response',false,'It supplements it and never replaces it.'),
  opt('d','It establishes legal consent',false,'Consent is a separate matter entirely.')],
 explanation_md:'Bystander compressions and early bleeding control are among the highest-value interventions in the whole system.',source_ref:STD}),
base({id:'itm-1.3.003',type:'mr',chapter:1,block:'1.3',objective:'obj-1.3.a',bloom:'remember',select_count:[2,3],
 stem:'Select every component that is part of an EMS system rather than an individual call.',
 options:[opt('a','Medical direction',true,'A system component, present on every call whether or not you speak to anyone.'),
  opt('b','Continuous quality improvement',true,'A system function that reviews care after the fact.'),
  opt('c','Public education and prevention',true,'Reducing the calls that happen at all is a system role.'),
  opt('d','The patient’s chief complaint',false,'That belongs to one call.'),
  opt('e','Your assessment findings',false,'Also specific to one patient.')],
 explanation_md:'The system is the thing that exists between calls. Recognising that is what makes CQI and prevention make sense.',source_ref:STD}),
base({id:'itm-1.3.004',type:'mc',chapter:1,block:'1.3',objective:'obj-1.3.a',
 stem:'A rural service has long transport times. Which system component most directly compensates?',
 options:[opt('a','Air medical and mutual aid arrangements built into the response plan',true,'Distance is answered by planning resources into the system in advance.'),
  opt('b','Increasing the number of protocols',false,'More paper does not shorten a transport.'),
  opt('c','More frequent recertification',false,'Valuable, but it does not address distance.'),
  opt('d','Reducing dispatch triage',false,'That would make matters worse.')],
 explanation_md:'System design is how geography is answered. It is decided long before the call comes in.',source_ref:STD}),
base({id:'itm-1.3.005',type:'mc',chapter:1,block:'1.3',objective:'obj-1.3.a',bloom:'remember',
 stem:'Which component of the system reviews care after the call to improve it?',
 options:[opt('a','Continuous quality improvement',true,'CQI closes the loop between what was done and what is taught next.'),
  opt('b','Medical direction',false,'It authorises care; review is a distinct function, though the medical director takes part.'),
  opt('c','Dispatch',false,'Dispatch sends resources.'),
  opt('d','Public access',false,'That is how a call reaches the system.')],
 explanation_md:'Without review, a system repeats its mistakes indefinitely and never learns from what went well.',source_ref:STD}),
base({id:'itm-1.3.006',type:'mc',chapter:1,block:'1.3',objective:'obj-1.3.a',bloom:'analyze',
 stem:'Why is an interfacility transfer still an EMS call rather than a taxi journey?',
 options:[opt('a','The patient is under your care throughout, at a level the sending facility specified',true,'The whole point is continuing a level of care in transit.'),
  opt('b','Because it is billed the same way',false,'Billing is not what makes it clinical.'),
  opt('c','Because it uses the same vehicle',false,'The vehicle is incidental.'),
  opt('d','Because the patient is on a stretcher',false,'A stretcher does not make a journey clinical either.')],
 explanation_md:'A transfer is an unbroken continuation of care. That is why the level of crew sent to one is a clinical decision.',source_ref:STD}),
base({id:'itm-1.3.007',type:'options_box',chapter:1,block:'1.3',objective:'obj-1.3.a',bloom:'remember',
 stem:'Which part of the system does each belong to?',
 columns:[{id:'access',label:'Access & dispatch'},{id:'care',label:'Clinical care'},{id:'over',label:'Oversight'}],
 rows:[{id:'r1',label:'Pre-arrival CPR instructions to a caller',answer:'access'},
  {id:'r2',label:'A standing order for nebulised albuterol',answer:'care'},
  {id:'r3',label:'A chart audit of every refusal last month',answer:'over'},
  {id:'r4',label:'Triaging a 911 call to the right resource',answer:'access'}],
 options:[],
 explanation_md:'Knowing which part of the system owns a problem tells you who can actually fix it.',source_ref:STD}),
base({id:'itm-1.3.008',type:'mc',chapter:1,block:'1.3',objective:'obj-1.3.a',
 stem:'Your service cannot get a crew to a rural address within a reasonable time, repeatedly. Whose problem is that?',
 options:[opt('a','The system’s — it is a resource deployment question, raised through the service',true,'Individual crews cannot solve coverage. It is designed, and it is changed by raising it.'),
  opt('b','The responding crew’s, for not driving faster',false,'Driving faster adds risk and saves very little time.'),
  opt('c','The caller’s, for living rurally',false,'Access to emergency care is not a personal failing.'),
  opt('d','Nobody’s — rural response is simply slow',false,'Treating it as inevitable is how it stays unexamined.')],
 explanation_md:'Recognising a system problem as a system problem is the first step to it being fixed rather than absorbed.',source_ref:STD}),

// ── 1.4 Medical direction ─────────────────────────────────────────────── 9
base({id:'itm-1.4.001',type:'mc',chapter:1,block:'1.4',objective:'obj-1.4.a',high_stakes:true,bloom:'understand',
 stem:'What is the difference between online and offline medical direction?',
 options:[opt('a','Online is contemporaneous contact with a physician; offline is written in advance',true,'Offline is your protocols and standing orders. Online is the call you make.'),
  opt('b','Online is by radio; offline is by telephone',false,'Both are contemporaneous contact. The channel is not the distinction.'),
  opt('c','Online applies to emergencies; offline to transfers',false,'Both apply everywhere.'),
  opt('d','Online is optional; offline is mandatory',false,'Both are binding when they apply.')],
 explanation_md:'Offline direction is the physician’s judgement written down before the call. Online is their judgement applied to the call in front of you.',source_ref:STD}),
base({id:'itm-1.4.002',type:'mc',chapter:1,block:'1.4',objective:'obj-1.4.a',high_stakes:true,
 stem:'A standing order covers your patient’s presentation exactly. What does that permit?',
 options:[opt('a','Acting immediately, without contacting a physician first',true,'That is what a standing order is for — the authorisation was given in advance.'),
  opt('b','Acting only after radio contact',false,'Requiring contact would defeat the purpose of the standing order.'),
  opt('c','Acting only with a paramedic present',false,'A standing order is written to your level.'),
  opt('d','Acting outside your scope if the order says so',false,'No order can exceed your licence.')],
 explanation_md:'Standing orders exist so time-critical care is not delayed by a phone call. Using one is not a shortcut.',source_ref:STD}),
base({id:'itm-1.4.003',type:'mr',chapter:1,block:'1.4',objective:'obj-1.4.a',high_stakes:true,select_count:[2,3],
 stem:'Select every situation that calls for contacting online medical direction.',
 options:[opt('a','The presentation does not fit any standing order you have',true,'An unanticipated situation is exactly what online direction is for.'),
  opt('b','You believe a deviation from protocol is in the patient’s interest',true,'Deviations need a physician’s agreement, contemporaneously.'),
  opt('c','A protocol explicitly requires physician contact before an intervention',true,'Where the protocol says call, calling is the protocol.'),
  opt('d','A standing order covers the presentation exactly',false,'Then the authorisation already exists.'),
  opt('e','You want a second opinion on a routine transport',false,'Not a clinical need, and it occupies a line others may need.')],
 explanation_md:'Call when the written direction runs out, when you want to depart from it, or when it tells you to.',source_ref:STD}),
base({id:'itm-1.4.004',type:'mc',chapter:1,block:'1.4',objective:'obj-1.4.a',high_stakes:true,
 cj_step:'take_action',
 stem:'Online medical direction gives you an order that is outside your scope of practice. What do you do?',
 options:[opt('a','Decline, state why, and offer what is within your scope',true,'A physician order cannot extend your licence. Saying so is part of the job.'),
  opt('b','Carry it out — a physician has assumed responsibility',false,'Responsibility does not transfer a licence. You would be practising outside scope.'),
  opt('c','Carry it out and document the physician’s name',false,'Documenting it does not make it lawful.'),
  opt('d','Carry it out only if the patient is critical',false,'Urgency does not widen scope.')],
 explanation_md:'This is rare, and it is worth rehearsing precisely because it is rare. The answer is the same as in 1.1: nobody can widen your scope on scene.',source_ref:SOP}),
base({id:'itm-1.4.005',type:'mc',chapter:1,block:'1.4',objective:'obj-1.4.a',bloom:'understand',
 stem:'What is the medical director’s role in the service?',
 options:[opt('a','A physician who authorises and oversees the clinical care the service provides',true,'Prehospital care is delivered under their licence and their oversight.'),
  opt('b','A supervisor of day-to-day operations',false,'That is an operational role, not the medical director’s.'),
  opt('c','An employee of the state EMS office',false,'They are appointed by or contracted to the service.'),
  opt('d','The author of the national scope model',false,'That is a national body.')],
 explanation_md:'Every protocol you work under is theirs. That is why departures from it are discussed with them and not decided alone.',source_ref:STD}),
base({id:'itm-1.4.006',type:'options_box',chapter:1,block:'1.4',objective:'obj-1.4.a',
 stem:'Does each situation need online direction, or is offline direction enough?',
 columns:[{id:'on',label:'Call medical control'},{id:'off',label:'Standing order is enough'}],
 rows:[{id:'r1',label:'Nebulised bronchodilator for wheezing covered by protocol',answer:'off'},
  {id:'r2',label:'A dose beyond the maximum the protocol states',answer:'on'},
  {id:'r3',label:'A presentation no protocol addresses',answer:'on'},
  {id:'r4',label:'Oxygen for a hypoxic patient',answer:'off'}],
 options:[],
 explanation_md:'The test is simple: does written direction already cover this, exactly? If yes, act. If not, call.',source_ref:STD}),
base({id:'itm-1.4.007',type:'mc',chapter:1,block:'1.4',objective:'obj-1.4.a',bloom:'analyze',
 stem:'Why does delaying a standing-order intervention to call medical control cause harm?',
 options:[opt('a','It costs time in a situation where the physician has already given the answer',true,'The order exists so the delay does not happen. Calling adds risk without adding information.'),
  opt('b','It annoys the physician',false,'Irrelevant to the patient.'),
  opt('c','It is a protocol violation',false,'Calling unnecessarily is not usually a violation. The harm is the delay.'),
  opt('d','It transfers liability to you',false,'Liability is not what makes this the wrong choice.')],
 explanation_md:'A standing order is a decision already made. Re-asking for it spends the minutes it was written to save.',source_ref:STD}),
base({id:'itm-1.4.008',type:'mc',chapter:1,block:'1.4',objective:'obj-1.4.a',high_stakes:true,
 stem:'You receive a radio order you did not hear clearly. What do you do before acting?',
 options:[opt('a','Repeat it back and have it confirmed',true,'Closed-loop confirmation is how a misheard order is caught before it is given.'),
  opt('b','Act on what you think you heard',false,'That is how wrong drugs and wrong doses happen.'),
  opt('c','Ask your partner what they heard',false,'Two people can mishear the same transmission the same way.'),
  opt('d','Record it and query afterwards',false,'Afterwards is too late if it was wrong.')],
 explanation_md:'Read back and confirm. It costs seconds and it is the only step that catches a misheard order.',source_ref:STD}),
base({id:'itm-1.4.009',type:'mc',chapter:1,block:'1.4',objective:'obj-1.4.a',
 stem:'Radio contact fails and your patient needs an intervention your standing orders cover. What governs?',
 options:[opt('a','The standing order — it is direction, given in advance, and still in force',true,'Offline direction does not depend on the radio working.'),
  opt('b','Nothing — you must wait until contact is restored',false,'Waiting would withhold care the physician already authorised.'),
  opt('c','Your own judgement, unconstrained',false,'You remain inside protocol and scope.'),
  opt('d','The receiving hospital’s instructions',false,'They are not your medical direction.')],
 explanation_md:'This is the practical reason offline direction exists: it works when nothing else does.',source_ref:STD}),

// ── 1.5 Where the patient goes ────────────────────────────────────────── 8
base({id:'itm-1.5.001',type:'mc',chapter:1,block:'1.5',objective:'obj-1.5.a',bloom:'understand',high_stakes:true,
 cj_step:'generate_solutions',
 stem:'What principle decides a destination when the nearest hospital cannot treat the problem?',
 options:[opt('a','Capability — go to a facility that can deliver the definitive treatment',true,'A short transport to a facility that must then transfer usually costs the patient time.'),
  opt('b','Proximity, always',false,'Nearest is right only when nearest is capable.'),
  opt('c','Whichever facility the family prefers',false,'Preference matters and is considered, but capability comes first in a time-critical case.'),
  opt('d','Whichever has the shortest wait',false,'Waiting time does not substitute for capability.')],
 explanation_md:'Specialty systems exist because some conditions need a capability that not every hospital has. Bypassing for capability is the point.',source_ref:STD}),
base({id:'itm-1.5.002',type:'drag_drop',chapter:1,block:'1.5',objective:'obj-1.5.a',high_stakes:true,
 stem:'Sort each presentation by the specialty capability it most needs.',
 categories:[{id:'trauma',label:'Trauma centre'},{id:'stroke',label:'Stroke centre'},{id:'cardiac',label:'Cardiac / PCI centre'}],
 options:[opt('a','Unilateral weakness with a clear time of onset',true,'Time-dependent stroke care needs imaging and a stroke pathway.'),
  opt('b','ST elevation on a transmitted 12-lead',true,'Definitive treatment is catheterisation.'),
  opt('c','Penetrating abdominal injury with hypotension',true,'That needs an operating theatre and a surgeon.'),
  opt('d','Fall from height with an open femur fracture',true,'Major trauma capability.')],
 answer_map:{a:'stroke',b:'cardiac',c:'trauma',d:'trauma'},
 explanation_md:'Each specialty system exists because its treatment is time-dependent and not universally available.',source_ref:STD}),
base({id:'itm-1.5.003',type:'mc',chapter:1,block:'1.5',objective:'obj-1.5.a',
 stem:'An interfacility transfer is requested at a level of care above your own. What should happen?',
 options:[opt('a','A crew at the required level is sent instead',true,'The sending clinician specifies the level; the service must meet it.'),
  opt('b','You take it and call for help if needed',false,'Accepting a transfer you cannot staff commits the patient to a gap.'),
  opt('c','You take it if the distance is short',false,'Distance does not change the level of care required.'),
  opt('d','The receiving facility decides',false,'The sending clinician specifies what the patient needs in transit.')],
 explanation_md:'Accepting a transfer above your level is a scope problem that begins before the wheels move.',source_ref:STD}),
base({id:'itm-1.5.004',type:'mr',chapter:1,block:'1.5',objective:'obj-1.5.a',bloom:'understand',select_count:[2,3],
 stem:'Select everything that should inform a destination decision.',
 options:[opt('a','What the patient needs and which facilities provide it',true,'Capability is the first question.'),
  opt('b','Transport time to each candidate facility',true,'Time is part of capability when treatment is time-dependent.'),
  opt('c','Any destination requirement in your protocol',true,'Protocol may direct or restrict destinations.'),
  opt('d','Which facility your crew prefers',false,'Crew preference is not a clinical input.'),
  opt('e','Which facility is least busy for you',false,'Convenience to the crew is not a patient consideration.')],
 explanation_md:'Capability, time, protocol — and the patient’s own preference where the case is not time-critical.',source_ref:STD}),
base({id:'itm-1.5.005',type:'mc',chapter:1,block:'1.5',objective:'obj-1.5.a',high_stakes:true,
 stem:'A stable patient asks to go to a hospital further away where their records are. Is that reasonable?',
 options:[opt('a','Yes, if the patient is stable and it does not conflict with protocol',true,'Continuity of care is a genuine benefit, and a stable patient may choose.'),
  opt('b','No — always transport to the nearest facility',false,'Nearest is not a rule; it is a default when time matters.'),
  opt('c','No — patients may not choose a destination',false,'They may, within clinical and protocol limits.'),
  opt('d','Only if the crew agrees it is convenient',false,'Convenience does not enter it.')],
 explanation_md:'The tighter the clinical time pressure, the less room there is for preference. In a stable patient there is usually room.',source_ref:STD}),
base({id:'itm-1.5.006',type:'mc',chapter:1,block:'1.5',objective:'obj-1.5.a',bloom:'analyze',high_stakes:true,
 stem:'Why can transporting a major trauma patient to a closer non-trauma hospital cost time overall?',
 options:[opt('a','The patient must then be stabilised and transferred again, adding a whole second journey',true,'Two transports and an interval of waiting usually exceed the longer first transport.'),
  opt('b','Non-trauma hospitals refuse trauma patients',false,'They do not refuse; they stabilise and transfer.'),
  opt('c','Ambulances are not permitted to bypass',false,'Bypass for capability is normal and protocol-directed.'),
  opt('d','It costs more to bill',false,'Not a clinical consideration.')],
 explanation_md:'The question is never "which is nearest" but "which route gets the definitive treatment soonest".',source_ref:STD}),
base({id:'itm-1.5.007',type:'options_box',chapter:1,block:'1.5',objective:'obj-1.5.a',
 stem:'Is proximity or capability the deciding factor?',
 columns:[{id:'near',label:'Nearest facility'},{id:'cap',label:'Capable facility'}],
 rows:[{id:'r1',label:'Uncontrolled airway you cannot manage',answer:'near'},
  {id:'r2',label:'Suspected large-vessel stroke within the treatment window',answer:'cap'},
  {id:'r3',label:'ST elevation on the 12-lead',answer:'cap'},
  {id:'r4',label:'Cardiac arrest you cannot resuscitate en route',answer:'near'}],
 options:[],
 explanation_md:'Capability wins for time-dependent definitive treatment. Proximity wins when the patient will not survive the extra distance.',source_ref:STD}),
base({id:'itm-1.5.008',type:'mc',chapter:1,block:'1.5',objective:'obj-1.5.a',
 stem:'Your protocol names a destination and the patient asks for a different one. What comes first?',
 options:[opt('a','Discuss it, and follow protocol where it is directive — contacting medical control if it is genuinely contested',true,'Protocol governs, but a contested destination is exactly what medical control is for.'),
  opt('b','The patient’s preference, always',false,'Preference does not override a directive protocol.'),
  opt('c','The crew’s decision, without discussion',false,'Deciding without discussing it is how complaints begin.'),
  opt('d','The nearest facility, regardless',false,'That answers neither the protocol nor the patient.')],
 explanation_md:'Most destination disputes dissolve once the reason is explained. The ones that do not are a medical control call.',source_ref:STD}),

// ── 1.6 Quality, safety and evidence ──────────────────────────────────── 8
base({id:'itm-1.6.001',type:'mc',chapter:1,block:'1.6',objective:'obj-1.6.a',bloom:'understand',
 stem:'What is continuous quality improvement meant to do?',
 options:[opt('a','Find and fix the system causes of recurring problems',true,'CQI looks for the pattern behind the incident, and changes the system.'),
  opt('b','Identify individuals to discipline',false,'A process that finds people to blame stops receiving honest reports, and then stops working.'),
  opt('c','Satisfy a documentation requirement',false,'It produces documentation; that is not its purpose.'),
  opt('d','Rank crews against each other',false,'Ranking does not identify causes.')],
 explanation_md:'A CQI process that people fear is a CQI process that stops being told anything, and it is then worse than none.',source_ref:STD}),
base({id:'itm-1.6.002',type:'mc',chapter:1,block:'1.6',objective:'obj-1.6.a',high_stakes:true,bloom:'analyze',
 stem:'A practice has been standard for thirty years. What does that establish about whether it works?',
 options:[opt('a','Very little — longevity is not evidence of benefit',true,'Several long-standing EMS practices have turned out to lack evidence of benefit, and some carried harm.'),
  opt('b','That it works, or it would have been abandoned',false,'Practices persist for many reasons other than efficacy.'),
  opt('c','That it is safe',false,'Duration says nothing about harm either.'),
  opt('d','That it is required by law',false,'Custom is not law.')],
 explanation_md:'This is worth holding onto. Later in this series you will meet two practices the textbook teaches and the current evidence does not support.',source_ref:STD}),
base({id:'itm-1.6.003',type:'mr',chapter:1,block:'1.6',objective:'obj-1.6.a',select_count:[2,3],
 stem:'Select every question worth asking about a claimed practice improvement.',
 options:[opt('a','What evidence supports it, and how strong is that evidence?',true,'The first question, and the one most often skipped.'),
  opt('b','What outcome was actually measured?',true,'A change in a surrogate measure is not a change in survival.'),
  opt('c','Who benefits if it is adopted?',true,'Worth knowing, particularly where a product is involved.'),
  opt('d','How long has it been taught?',false,'Longevity is not evidence, which is the point of this block.'),
  opt('e','Whether other services do it',false,'Common practice is not the same as supported practice.')],
 explanation_md:'Evidence, outcome, interest. Three questions that separate a real improvement from a confident one.',source_ref:STD}),
base({id:'itm-1.6.004',type:'mc',chapter:1,block:'1.6',objective:'obj-1.6.a',
 stem:'Your service changes a protocol because of a new study. What should the change rest on?',
 options:[opt('a','The medical director’s appraisal of the evidence against current practice',true,'A single study is an input to a judgement, not an instruction.'),
  opt('b','The study alone, immediately',false,'One study rarely overturns a practice by itself.'),
  opt('c','Whether the study agrees with existing practice',false,'That reasoning would prevent any change ever.'),
  opt('d','How widely the study was reported',false,'Coverage is not quality.')],
 explanation_md:'The medical director owns the protocol precisely so evidence is appraised rather than adopted on headline.',source_ref:STD}),
base({id:'itm-1.6.005',type:'options_box',chapter:1,block:'1.6',objective:'obj-1.6.a',bloom:'analyze',
 stem:'How much weight does each piece of support carry?',
 columns:[{id:'strong',label:'Strong'},{id:'weak',label:'Weak'}],
 rows:[{id:'r1',label:'Several randomised trials agreeing on a patient outcome',answer:'strong'},
  {id:'r2',label:'A manufacturer’s claim about their own device',answer:'weak'},
  {id:'r3',label:'"We have always done it this way"',answer:'weak'},
  {id:'r4',label:'A systematic review of many studies',answer:'strong'}],
 options:[],
 explanation_md:'Evidence literacy is a clinical skill. It is what lets you tell an improvement from a fashion.',source_ref:STD}),
base({id:'itm-1.6.006',type:'mc',chapter:1,block:'1.6',objective:'obj-1.6.a',high_stakes:true,
 stem:'You make an error on a call that causes no harm. What should you do?',
 options:[opt('a','Report it, so the system can find out why it was possible',true,'Near misses are the cheapest information a system ever gets.'),
  opt('b','Say nothing, since nobody was hurt',false,'The next occurrence may not be harmless, and nothing will have changed.'),
  opt('c','Tell your partner only',false,'It does not reach anyone who can change the system.'),
  opt('d','Correct the record to remove it',false,'Altering a record to conceal an error is a separate and far more serious problem.')],
 explanation_md:'A system only learns from what it is told. The error that harms nobody is the one you most want reported.',source_ref:STD}),
base({id:'itm-1.6.008',type:'mc',chapter:1,block:'1.6',objective:'obj-1.6.a',bloom:'analyze',
 stem:'A device is promoted on a study showing it improves a number on the monitor. What limits that evidence?',
 options:[opt('a','It measured a surrogate, not an outcome that matters to the patient',true,'A better waveform is not the same as a patient who survives or recovers function.'),
  opt('b','A single study is never worth reading',false,'One study is an input. The problem here is what it measured, not that there is one.'),
  opt('c','Monitors are unreliable',false,'The measurement may be perfectly accurate and still be the wrong thing to measure.'),
  opt('d','Devices cannot be studied properly',false,'They can be, and some are, against survival and function.')],
 explanation_md:'Surrogate outcomes are the most common way a weak claim looks strong. Ask what was measured before you ask how large the effect was.',source_ref:STD}),
base({id:'itm-1.6.007',type:'mc',chapter:1,block:'1.6',objective:'obj-1.6.a',bloom:'understand',
 stem:'What makes a chart audit useful to a service?',
 options:[opt('a','It shows patterns across many calls that no single crew could see',true,'Aggregate review finds what individual experience cannot.'),
  opt('b','It identifies the weakest provider',false,'That is not what aggregate data is good at, and chasing it poisons reporting.'),
  opt('c','It satisfies the billing department',false,'Billing review is a separate exercise.'),
  opt('d','It proves care was correct',false,'It examines care; it does not certify it.')],
 explanation_md:'One crew sees their own calls. The audit sees all of them, which is the only way a pattern becomes visible.',source_ref:STD}),

// ── 1.7 Professionalism and MIH ───────────────────────────────────────── 8
base({id:'itm-1.7.001',type:'mc',chapter:1,block:'1.7',objective:'obj-1.7.a',bloom:'understand',
 stem:'What is mobile integrated healthcare?',
 options:[opt('a','Using EMS resources to deliver planned care outside emergency response',true,'Follow-up visits, chronic disease support, navigation to the right service.'),
  opt('b','A faster form of emergency response',false,'It is not about response speed at all.'),
  opt('c','A transport service for non-emergency patients',false,'Transport is often exactly what MIH avoids.'),
  opt('d','A paramedic working in a hospital',false,'That is a different role.')],
 explanation_md:'MIH and community paramedicine treat EMS as a healthcare resource that happens to be mobile, rather than only a response system.',source_ref:STD}),
base({id:'itm-1.7.002',type:'mr',chapter:1,block:'1.7',objective:'obj-1.7.a',select_count:[2,3],bloom:'remember',
 stem:'Select the attributes most often named as professional conduct in EMS.',
 options:[opt('a','Integrity — recording what happened, including your own errors',true,'The record is only useful if it is true.'),
  opt('b','Respect — for patients, families and other services',true,'Named in every professional standard.'),
  opt('c','Self-motivation — maintaining competence without being told',true,'Skills decay whether or not anyone checks.'),
  opt('d','Deference — never questioning an order',false,'Questioning an unsafe order is part of the job, as 1.4 showed.'),
  opt('e','Speed above all',false,'Speed that adds risk is not professionalism.')],
 explanation_md:'These are what keeps a licence, and more importantly what makes a crew someone a patient can trust.',source_ref:STD}),
base({id:'itm-1.7.003',type:'mc',chapter:1,block:'1.7',objective:'obj-1.7.a',high_stakes:true,
 stem:'You realise mid-shift that you have forgotten part of a skill you rarely use. What is the professional response?',
 options:[opt('a','Say so, and arrange to refresh it',true,'Competence maintained honestly is what the attribute actually means.'),
  opt('b','Avoid calls where it might be needed',false,'You cannot choose your calls, and the gap remains.'),
  opt('c','Look it up if it comes up',false,'Reading a procedure for the first time at the bedside is not competence.'),
  opt('d','Assume it will return under pressure',false,'Skills degrade, and pressure is when they degrade most.')],
 explanation_md:'Rarely used skills decay fastest. Saying so is the professional act, not the embarrassing one.',source_ref:STD}),
base({id:'itm-1.7.004',type:'mc',chapter:1,block:'1.7',objective:'obj-1.7.a',bloom:'understand',
 stem:'A frequent caller uses the ambulance for problems better met elsewhere. What does an MIH approach offer?',
 options:[opt('a','A planned route to the service that actually addresses the underlying need',true,'MIH exists for exactly this pattern.'),
  opt('b','A way to refuse the calls',false,'Refusal is not a clinical solution and rarely lawful.'),
  opt('c','Transport to a different hospital',false,'A different door does not change the unmet need.'),
  opt('d','Nothing — it is a social problem',false,'Repeat use of emergency services is a healthcare problem with a healthcare answer.')],
 explanation_md:'Repeat callers are usually a signal that a need is unmet somewhere else in the system.',source_ref:STD}),
base({id:'itm-1.7.005',type:'options_box',chapter:1,block:'1.7',objective:'obj-1.7.a',
 stem:'Is each action consistent with professional conduct?',
 columns:[{id:'yes',label:'Professional'},{id:'no',label:'Not professional'}],
 rows:[{id:'r1',label:'Recording a vital sign you did not take',answer:'no'},
  {id:'r2',label:'Telling the receiving nurse about your own error',answer:'yes'},
  {id:'r3',label:'Discussing a recognisable patient on social media',answer:'no'},
  {id:'r4',label:'Refreshing a skill you have not used in a year',answer:'yes'}],
 options:[],
 explanation_md:'Two of these end careers. Both involve the record or the patient’s privacy, which Chapter 3 takes up in detail.',source_ref:STD}),
base({id:'itm-1.7.006',type:'mc',chapter:1,block:'1.7',objective:'obj-1.7.a',bloom:'analyze',
 stem:'Why is appearance and manner treated as a clinical matter rather than a cosmetic one?',
 options:[opt('a','A patient who does not trust you withholds information you need',true,'History is the bulk of your assessment, and it depends on being told the truth.'),
  opt('b','It is required by uniform policy',false,'Policy exists, but that is not the clinical reason.'),
  opt('c','It affects billing',false,'It does not.'),
  opt('d','It determines scope',false,'Scope is set by law.')],
 explanation_md:'Trust is an assessment tool. A frightened or unconvinced patient tells you less, and you decide with less.',source_ref:STD}),
base({id:'itm-1.7.008',type:'mc',chapter:1,block:'1.7',objective:'obj-1.7.a',bloom:'analyze',
 stem:'Your service starts an MIH programme. Which result would best show it is working?',
 options:[opt('a','Enrolled patients call 911 less because the underlying need is being met elsewhere',true,'Needs met rather than patients moved is the measure the model is built around.'),
  opt('b','The programme enrols more patients each month',false,'Enrolment is activity. It says nothing about whether anyone is better off.'),
  opt('c','Transports per shift increase',false,'MIH usually reduces transports; more of them is not the aim.'),
  opt('d','Response times fall',false,'A response-time change is not what this model sets out to produce.')],
 explanation_md:'This is 1.6 applied to your own service: ask what was actually measured, and whether it is the thing you care about.',source_ref:STD}),
base({id:'itm-1.7.007',type:'mc',chapter:1,block:'1.7',objective:'obj-1.7.a',bloom:'remember',
 stem:'Community paramedicine most often aims to do what?',
 options:[opt('a','Meet a patient’s need without an emergency department visit where that is appropriate',true,'Often through follow-up, assessment at home, or navigation to another service.'),
  opt('b','Increase ambulance transports',false,'It usually reduces them.'),
  opt('c','Replace primary care',false,'It connects to primary care rather than replacing it.'),
  opt('d','Expand paramedic scope of practice',false,'It is a deployment model, not a scope change.')],
 explanation_md:'The measure of success is usually a need met, not a patient moved.',source_ref:STD}),

// ── 1.INT Integration ─────────────────────────────────────────────────── 10
base({id:'itm-1.INT.000',type:'scenario',chapter:1,block:'1.INT',objective:'obj-1.INT.a',
 stimulus:{kind:'scenario',ref:null,
  text:'0410. You and your EMT partner are dispatched to a 58-year-old man with chest pain, thirty-five minutes from the nearest hospital. That hospital has an emergency department but no catheterisation laboratory. A PCI centre is fifty-five minutes away.\n\nHe is pale and sweating. Your 12-lead shows clear ST elevation. Your protocol has a standing order for aspirin, and directs transport to a PCI centre for ST elevation. Your partner says the closer hospital is safer because it is closer.'},
 children:['itm-1.INT.001','itm-1.INT.002','itm-1.INT.003','itm-1.INT.004',
  'itm-1.INT.005','itm-1.INT.006','itm-1.INT.007','itm-1.INT.008','itm-1.INT.009'],
 stem:'',options:[],explanation_md:'',source_ref:STD}),
base({id:'itm-1.INT.001',type:'mc',chapter:1,block:'1.INT',objective:'obj-1.INT.a',parent:'itm-1.INT.000',
 high_stakes:true,cj_step:'take_action',
 stem:'The standing order covers aspirin. What do you do about contacting medical control first?',
 options:[opt('a','Give it now — the authorisation was given in advance',true,'That is what a standing order is. Calling would spend time it exists to save.'),
  opt('b','Call for permission before giving it',false,'It is already permitted. The call adds delay and no information.'),
  opt('c','Wait until you have chosen a destination',false,'The two decisions are independent.'),
  opt('d','Ask the receiving hospital',false,'They are not your medical direction.')],
 explanation_md:'Offline direction is a decision already made. Acting on it is the correct use of it.',source_ref:STD}),
base({id:'itm-1.INT.002',type:'mc',chapter:1,block:'1.INT',objective:'obj-1.INT.a',parent:'itm-1.INT.000',
 high_stakes:true,cj_step:'generate_solutions',
 stem:'Your partner argues for the closer hospital. What is the strongest counter?',
 options:[opt('a','The closer hospital cannot deliver the definitive treatment, so he would be transferred again',true,'Two journeys and a wait between them usually exceed the extra twenty minutes.'),
  opt('b','Protocol says so, so there is nothing to discuss',false,'True, but it does not answer the clinical question and does not persuade.'),
  opt('c','The PCI centre is better staffed overall',false,'The relevant difference is the catheterisation laboratory, not general staffing.'),
  opt('d','The patient will prefer it',false,'You have not asked him, and this is time-critical.')],
 explanation_md:'The real question is which route reaches the definitive treatment soonest, not which door is nearest.',source_ref:STD}),
base({id:'itm-1.INT.003',type:'mc',chapter:1,block:'1.INT',objective:'obj-1.INT.a',parent:'itm-1.INT.000',
 stem:'Which type of medical direction is directing your destination here?',
 options:[opt('a','Offline — the protocol was written in advance',true,'A destination protocol is written direction.'),
  opt('b','Online — because you may radio the hospital',false,'Notifying a hospital is not the same as receiving direction from a physician.'),
  opt('c','Neither — destination is a crew decision',false,'Where protocol directs, it governs.'),
  opt('d','Both equally',false,'Only the written protocol is directing you at this point.')],
 explanation_md:'Most of what you do on a call runs on offline direction. Online is the exception, not the norm.',source_ref:STD}),
base({id:'itm-1.INT.004',type:'mr',chapter:1,block:'1.INT',objective:'obj-1.INT.a',parent:'itm-1.INT.000',
 select_count:[2,3],cj_step:'analyze_cues',
 stem:'Which facts here make this a capability decision rather than a proximity one?',
 options:[opt('a','ST elevation, whose definitive treatment is catheterisation',true,'The treatment he needs exists in only one of the two facilities.'),
  opt('b','The nearer hospital has no catheterisation laboratory',true,'That is the capability gap.'),
  opt('c','The protocol directs PCI centre transport for ST elevation',true,'The system has already made this decision.'),
  opt('d','It is 0410',false,'The hour does not change what he needs.'),
  opt('e','Your partner disagrees',false,'A disagreement to resolve, not a clinical fact.')],
 explanation_md:'Three facts, all pointing the same way. Recognising which facts are decisive is most of clinical judgement.',source_ref:STD}),
base({id:'itm-1.INT.005',type:'mc',chapter:1,block:'1.INT',objective:'obj-1.INT.a',parent:'itm-1.INT.000',
 high_stakes:true,
 stem:'En route he becomes unresponsive and you cannot manage his airway with what you carry. Does the destination change?',
 options:[opt('a','Yes — an airway you cannot manage makes the nearest facility the right one now',true,'Capability wins until the patient will not survive the distance. Then proximity wins.'),
  opt('b','No — the protocol named a PCI centre',false,'Protocol assumes a patient who survives the journey.'),
  opt('c','No — changing destination is never permitted',false,'It is, when the clinical picture changes.'),
  opt('d','Only if medical control agrees first',false,'Advise them, but do not withhold the diversion waiting for a reply.')],
 explanation_md:'The rule from 1.5 has both halves: capability for time-dependent treatment, proximity when the patient will not survive the extra distance.',source_ref:STD}),
base({id:'itm-1.INT.006',type:'mc',chapter:1,block:'1.INT',objective:'obj-1.INT.a',parent:'itm-1.INT.000',
 high_stakes:true,cj_step:'take_action',
 stem:'A physician on the radio orders a drug outside your AEMT scope. What do you do?',
 options:[opt('a','Decline, say why, and offer what is within your scope',true,'Nobody on a radio can extend your licence.'),
  opt('b','Give it — the physician has taken responsibility',false,'Responsibility does not transfer a licence to you.'),
  opt('c','Give it and document the order carefully',false,'Careful documentation of an unlawful act does not help.'),
  opt('d','Have your EMT partner give it',false,'It is further outside their scope than yours.')],
 explanation_md:'The same answer as 1.1 and 1.4, tested here under pressure, because that is where it is actually hard.',source_ref:SOP}),
base({id:'itm-1.INT.007',type:'mc',chapter:1,block:'1.INT',objective:'obj-1.INT.a',bloom:'understand',parent:'itm-1.INT.000',
 stem:'Which part of the system will examine this call afterwards, and to what end?',
 options:[opt('a','Continuous quality improvement, looking for what the system can change',true,'Aggregate review looks for causes, not culprits.'),
  opt('b','Medical direction, to decide discipline',false,'Discipline is a separate process, and a CQI system built on it stops being told anything.'),
  opt('c','Dispatch, to review the address',false,'Not the function.'),
  opt('d','Nobody — the call went well',false,'Calls that go well are exactly the ones worth understanding.')],
 explanation_md:'A long transport for capability is a system question: is the coverage right, and does the protocol still fit the geography?',source_ref:STD}),
base({id:'itm-1.INT.008',type:'mc',chapter:1,block:'1.INT',objective:'obj-1.INT.a',parent:'itm-1.INT.000',
 stem:'Which skills on this call were within your AEMT scope?',
 options:[opt('a','IV access and the aspirin your protocol authorises',true,'Both sit within the AEMT scope and within your protocol.'),
  opt('b','Interpreting the 12-lead as a basis for treatment decisions',false,'Rhythm and 12-lead interpretation is paramedic-level; transmitting it is different from acting on your own reading.'),
  opt('c','Needle decompression if his chest had been involved',false,'Paramedic-level.'),
  opt('d','Endotracheal intubation for the airway',false,'Above AEMT scope.')],
 explanation_md:'Acquiring and transmitting a 12-lead is a task; interpreting it as the basis for treatment is a scope question.',source_ref:SOP}),
base({id:'itm-1.INT.009',type:'mr',chapter:1,block:'1.INT',objective:'obj-1.INT.a',parent:'itm-1.INT.000',
 select_count:[2,3],cj_step:'evaluation',
 stem:'Reviewing this call, which decisions would you expect to defend and be able to?',
 options:[opt('a','Giving aspirin on the standing order without calling',true,'Written direction covered it exactly.'),
  opt('b','Bypassing the nearer hospital for the PCI centre',true,'Protocol-directed and clinically reasoned.'),
  opt('c','Diverting when the airway failed',true,'A change in the clinical picture changed the right answer.'),
  opt('d','Declining the out-of-scope order',true,'Correct, and the only lawful option.'),
  opt('e','Deferring to your partner’s preference for the closer hospital',false,'That would have been the one decision you could not defend.')],
 explanation_md:'Four defensible decisions and one that would not have been. Being able to say why afterwards is what the whole chapter is for.',source_ref:STD})
];

export const blocks=[
{id:'1.1',chapter:1,title:'What an AEMT actually is',learner_title:'What the letters mean',
 objectives:['obj-1.1.a'],est_minutes:7,
 cold_open:{text:'Your first shift. The crew chief says the truck is running "AEMT tonight, no medic". Your partner is an EMT. Somewhere between what the two of you can do and what a paramedic could do, there is a line, and by the end of the shift you will have stood on it at least once.',
  decision_point:'Where is that line?'},
 pretest_item:'itm-1.1.001',
 screens:[
  {id:'scr-1.1.1',body_md:'**Four levels, and each one contains the one below it.** Emergency Medical Responder, EMT, Advanced EMT, Paramedic.\n\nA paramedic has not stopped being able to do EMT things. The scopes are cumulative, which is why a mixed crew works and why the highest level present sets the ceiling for the call.',figure:null},
  {id:'scr-1.1.2',body_md:'**EMR** is designed for someone who arrives before an ambulance: compressions, an AED, bleeding control, an airway held open. Minimal equipment, immediate actions.\n\n**EMT** adds a fuller assessment, oxygen, a small set of medications mostly by simple routes, splinting and extrication.\n\nWhat the EMT level does not include is anything that enters a vein or breaks the skin, and that single boundary is where your own new scope begins.',figure:null},
  {id:'scr-1.1.3',body_md:'**AEMT is where access begins.** The defining additions are intravenous access, a wider set of medications and routes, and advanced airway adjuncts short of intubation.\n\nThe pattern is worth naming: AEMT adds *access and a limited drug set*. It does not add independent diagnosis, and it does not add invasive procedures.',figure:null},
  {id:'scr-1.1.4',body_md:'**Paramedic** adds rhythm interpretation and manual defibrillation, intubation, needle decompression, and a much larger formulary.\n\nThe clinical consequence for you is simple: when a patient needs one of those, the useful question is not whether you could attempt it, but how quickly someone who is licensed for it can get there.',figure:null},
  {id:'scr-1.1.5',body_md:'**Nobody on scene can move that line.** Not a paramedic partner, not a physician on the radio, not the urgency of the patient.\n\nThat sounds obvious written down. It is much less obvious at 0300 with a sick patient and a colleague telling you to get on with it — which is why it is worth deciding now, calmly, what you will say.',figure:null}],
 inline_checks:['itm-1.1.003','itm-1.1.006'],
 quiz:['itm-1.1.002','itm-1.1.004','itm-1.1.005','itm-1.1.007','itm-1.1.008'],
 callback_md:'The line runs between access and interpretation. You can start an IV and give what your protocol authorises through it; you cannot interpret a rhythm and shock on your own reading, and you cannot intubate.\n\n**And the line does not move.** Not for a partner, not for a physician, not for how sick the patient is. That last part is the whole of the answer.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'1.2',chapter:1,title:'Scope, protocol, licensure',learner_title:'Four words people use wrongly',
 objectives:['obj-1.2.a'],est_minutes:8,
 cold_open:{text:'A colleague at another service tells you they give a drug you have never been allowed to give. Same certification, same state, same national standard. Either one of you is doing something wrong, or the words you are both using do not mean quite what you think they mean.',
  decision_point:'Which is it?'},
 pretest_item:'itm-1.2.001',
 screens:[
  {id:'scr-1.2.1',body_md:'**Scope of practice is a legal ceiling**, set by your state. It is the complete list of things someone at your level may ever do there.\n\nIt is a ceiling and not a checklist. Being within scope means you *may*, not that you *should*, and not that you are authorised today.',figure:null},
  {id:'scr-1.2.2',body_md:'**Protocol is your medical director’s written instruction**, and it sits inside the scope.\n\nA protocol can be narrower than your scope and frequently is. It cannot be wider: no medical director can authorise a skill your licence does not include.\n\nYou practise in the overlap of the two, and the overlap is always the smaller circle.',figure:null},
  {id:'scr-1.2.3',body_md:'**Three words get confused constantly.**\n\n**Certification** says a national body examined you and you passed.\n**Licensure** says a state permits you to practise there.\n**Credentialing** says one employer permits you to practise for them.\n\nCertification travels with you. The other two do not. That is why moving states means starting two of the three again.',figure:null},
  {id:'scr-1.2.4',body_md:'**Standard of care is none of these.** It is how your conduct is judged afterwards: what a reasonable provider of the same level would have done, in the same circumstances.\n\nNot the best provider. Not with hindsight. Protocol is strong evidence of what reasonable looks like, which is why departing from it needs a reason you can state out loud.',figure:null},
  {id:'scr-1.2.5',body_md:'**This is the block worth knowing cold.** Scope confusion is the most common root of disciplinary action at this level, and the reason is structural: nothing on scene stops you.\n\nNo alarm sounds when you cross the line. It is found afterwards, in a review, by someone reading your chart — and by then the act is already done.',figure:null}],
 inline_checks:['itm-1.2.003','itm-1.2.005'],
 quiz:['itm-1.2.002','itm-1.2.004','itm-1.2.006','itm-1.2.007','itm-1.2.008','itm-1.2.009'],
 callback_md:'Neither of you is necessarily wrong. **Scope is set by the state; protocol is set by your medical director inside it.** Two services in one state can hold identical scope and different protocols, and both be practising correctly.\n\nWhat you cannot conclude is that because they may, you may. Your authority comes from your protocol, not from their practice.\n\n*Kansas AEMT scope and the AMR KC standing orders belong here as a local layer. They have not been added to this module yet.*',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'1.3',chapter:1,title:'How the system is built',learner_title:'What happens before you arrive',
 objectives:['obj-1.3.a'],est_minutes:7,
 cold_open:{text:'By the time you pull up, a neighbour has already called, a dispatcher has already triaged the call and talked someone through compressions, and a first responder has already put hands on the chest. Three things have gone right before you have done anything at all.',
  decision_point:'What else is holding this call up that you cannot see?'},
 pretest_item:'itm-1.3.005',
 screens:[
  {id:'scr-1.3.1',body_md:'**A system is what exists between calls.** Any single call runs through it: someone recognises an emergency and calls, dispatch triages and sends, a crew assesses and treats, the patient is transported, care is handed over.\n\nEvery one of those is a link, and the chain is only as good as its weakest.',figure:null},
  {id:'scr-1.3.2',body_md:'**Public access and dispatch do more than send a truck.** Emergency medical dispatch triages the call, sends the right resource, and gives pre-arrival instructions.\n\nBystander compressions and early bleeding control started on the phone are among the highest-value interventions in the entire system — higher than most of what happens after you arrive.',figure:null},
  {id:'scr-1.3.3',body_md:'**Medical direction is present on every call**, whether or not you speak to anybody. Your protocols are a physician’s judgement, written down in advance.\n\n**Transport and destination** are part of the system too. Which facilities exist, what they can do, and where a patient is taken were decided long before your shift started.',figure:null},
  {id:'scr-1.3.4',body_md:'**Two components look backward rather than forward.**\n\n**Continuous quality improvement** reviews what was done and feeds it into what is taught next. **Public education and prevention** reduces the number of calls that happen at all.\n\nNeither helps the patient in front of you. Both decide what the next hundred patients get.',figure:null},
  {id:'scr-1.3.5',body_md:'**Why this matters on a bad call:** when something is not going to plan, the useful question is which part of the system owns the problem.\n\nNo crew available is a deployment question. No capable hospital within reach is a system-design question. Neither is solved by the two of you driving faster, and both are solved by someone — if they are told.',figure:null}],
 inline_checks:['itm-1.3.002','itm-1.3.006'],
 quiz:['itm-1.3.001','itm-1.3.003','itm-1.3.004','itm-1.3.007','itm-1.3.008'],
 callback_md:'Medical direction, written before you arrived. A destination plan that decided which hospitals could take this patient. A deployment model that put your truck where it was. A CQI process that will look at this call next month.\n\nNone of it is visible on scene, and all of it is holding the call up. **When a call is failing for reasons you cannot fix with your hands, it is usually one of these — and they change only if someone says so.**',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'1.4',chapter:1,title:'Medical direction',learner_title:'Whose orders you are on',
 objectives:['obj-1.4.a'],est_minutes:8,
 cold_open:{text:'Wheezing, tight, frightened, and your protocol has a standing order for a nebulised bronchodilator that fits this patient exactly. Your partner reaches for the radio to ask medical control for permission. The drug is in your hand.',
  decision_point:'Do you wait for the radio?'},
 pretest_item:'itm-1.4.001',
 screens:[
  {id:'scr-1.4.1',body_md:'**Every prehospital intervention happens under a physician’s authority.** Yours comes in two forms.\n\n**Offline** direction is written in advance: your protocols and standing orders.\n**Online** direction is contemporaneous contact with a physician about this patient, now.\n\nMost of a shift runs on offline direction, and you may never use the other.',figure:null},
  {id:'scr-1.4.2',body_md:'**A standing order is a decision already made.** The physician considered this presentation in advance and wrote down what to do.\n\nWhen the presentation matches, you act. Calling to ask permission for something already permitted spends exactly the minutes the standing order was written to save, and returns no new information.\n\nThe physician who wrote it judged that the delay of a call would cost the patient more than it gained. Waiting anyway quietly overrides that judgement, without anyone deciding to.',figure:null},
  {id:'scr-1.4.3',body_md:'**Call when the written direction runs out.** Three occasions:\n\nThe presentation fits no standing order you hold. You believe a departure from protocol is in the patient’s interest. Or the protocol itself tells you to call.\n\nThat is the whole test: *does written direction already cover this, exactly?* If yes, act. If no, call.',figure:null},
  {id:'scr-1.4.4',body_md:'**An order you cannot lawfully perform is still an order you decline.** A physician cannot extend your licence, any more than a paramedic partner can.\n\nSay what you cannot do and offer what you can. It is uncomfortable once and defensible forever, and it is rare enough that it is worth rehearsing before it happens.',figure:null},
  {id:'scr-1.4.5',body_md:'**Read every radio order back.** Repeat it, have it confirmed, then act.\n\nA misheard drug or a misheard dose is caught at exactly one moment, and that moment is before you give it. The read-back costs about four seconds and it is the only step in the chain that catches the error.\n\nIt also puts the order in your partner’s hearing, which gives a wrong dose a second person who might notice it.',figure:null}],
 inline_checks:['itm-1.4.002','itm-1.4.008'],
 quiz:['itm-1.4.003','itm-1.4.004','itm-1.4.005','itm-1.4.006','itm-1.4.007','itm-1.4.009'],
 callback_md:'**No.** The standing order is medical direction, already given, for exactly this presentation. Give the drug.\n\nThe radio is for when the written direction runs out — when nothing covers the patient, when you want to depart from what does, or when the protocol tells you to call. None of those is true here, and the patient is short of breath while you wait.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'1.5',chapter:1,title:'Where the patient goes',learner_title:'Choosing a destination',
 objectives:['obj-1.5.a'],est_minutes:8,
 cold_open:{text:'Two hospitals. One is twenty minutes away and can admit almost anything. The other is fifty minutes away and is the only one within reach that can do the procedure your patient needs tonight. Your patient is stable enough to make the journey, and does not much want to.',
  decision_point:'Which way do you turn out of the driveway?'},
 pretest_item:'itm-1.5.001',
 screens:[
  {id:'scr-1.5.1',body_md:'**Nearest is a default, not a rule.** It is the right answer when the patient will not survive the extra distance, and only then.\n\nThe real question is never which door is closest. It is which route reaches the *definitive treatment* soonest — and for some conditions the nearest door cannot provide it at all.',figure:null},
  {id:'scr-1.5.2',body_md:'**Specialty systems exist because some treatments are time-dependent and not universal.** Trauma centres, stroke centres, cardiac and PCI centres, burn and paediatric centres.\n\nTaking a patient to a facility that must then stabilise and transfer them costs two journeys and the wait in between, which almost always exceeds the longer first transport.',figure:null},
  {id:'scr-1.5.3',body_md:'**Interfacility transfers are destination decisions made by someone else.** The sending clinician specifies the level of care the patient needs in transit, and the service must meet it.\n\nAccepting a transfer above your level is a scope problem that starts before the wheels move, and it is much harder to fix once you are on the road.',figure:null},
  {id:'scr-1.5.4',body_md:'**Patient preference is real and it has limits.** Continuity of care at a hospital that holds their records is a genuine clinical benefit.\n\nThe tighter the clinical time pressure, the less room there is. In a stable patient there is usually room; in a time-critical one there is often none, and saying so plainly is better than deciding silently.',figure:null},
  {id:'scr-1.5.5',body_md:'**Where protocol directs a destination, it governs.** Most disputes dissolve once someone explains the reason rather than asserting the rule.\n\nThe ones that do not are what medical control is for. A contested destination is a legitimate reason to pick up the radio.\n\nName the protocol, name the capability the patient needs, and offer the radio. That sequence settles most disputes before anybody has to be overruled.',figure:null}],
 inline_checks:['itm-1.5.003','itm-1.5.005'],
 quiz:['itm-1.5.002','itm-1.5.004','itm-1.5.006','itm-1.5.007','itm-1.5.008'],
 callback_md:'Toward the procedure — assuming your protocol directs it and he remains stable enough for the journey. The nearer hospital would have to stabilise and transfer him anyway, and that costs him more time than the extra thirty minutes does.\n\n**But tell him why.** A patient who understands that the closer hospital cannot do the thing he needs is usually no longer arguing, and a patient who is simply overruled complains later — reasonably.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'1.6',chapter:1,title:'Quality, safety and evidence',learner_title:'How practice changes',
 objectives:['obj-1.6.a'],est_minutes:7,
 cold_open:{text:'An instructor tells you a technique is standard because it has been taught that way for thirty years. Later the same week you read that a large review found no evidence it helps, and some evidence it harms. Both statements are true at once.',
  decision_point:'Which one should change what you do?'},
 pretest_item:'itm-1.6.002',
 screens:[
  {id:'scr-1.6.1',body_md:'**Continuous quality improvement looks for causes, not culprits.** It reviews care across many calls to find the pattern behind a problem, and then changes the system.\n\nA review process people are afraid of stops being told things. Once that happens it is worse than having none, because it produces reassuring reports about a service that is not actually safe.',figure:null},
  {id:'scr-1.6.2',body_md:'**The near miss is the cheapest information a system ever gets.** An error that harmed nobody tells you a hole exists, at no cost to a patient.\n\nReport it. The alternative is waiting for the same hole to be found by someone who is harmed by it, which is how most systems actually learn and is a terrible way to do it.',figure:null},
  {id:'scr-1.6.3',body_md:'**Longevity is not evidence.** A practice taught for thirty years has been taught for thirty years. That is all it establishes.\n\nSeveral long-standing EMS practices have turned out to lack evidence of benefit, and a few carried harm. They persisted because they were taught, not because they worked.',figure:null},
  {id:'scr-1.6.4',body_md:'**Three questions separate an improvement from a fashion.**\n\nWhat evidence supports it, and how strong is it? What outcome was actually measured — survival, or a number on a monitor? And who benefits if this is adopted?\n\nThe third is not cynicism. It is simply worth knowing when a product is involved.',figure:null},
  {id:'scr-1.6.5',body_md:'**You will meet this again in this series.** Two practices ahead of you are taught by the textbook and not supported by current evidence, and the module will show you the book position and the evidence side by side.\n\nThat is deliberate. Being able to say "here is what the book says, here is what the evidence says" is itself part of practising at this level.',figure:null}],
 inline_checks:['itm-1.6.006','itm-1.6.007'],
 quiz:['itm-1.6.001','itm-1.6.003','itm-1.6.004','itm-1.6.005','itm-1.6.008'],
 callback_md:'The review should — but through your medical director, not by you unilaterally on the next call. Protocol is theirs, and appraising evidence against current practice is exactly what that role is for.\n\n**What the thirty years establishes is that it has been taught for thirty years.** Nothing more. Holding both facts at once, without resolving them by deferring to whoever spoke last, is the skill this block is teaching.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'1.7',chapter:1,title:'Professionalism and MIH',learner_title:'Conduct, and the wider job',
 objectives:['obj-1.7.a'],est_minutes:6,
 cold_open:{text:'Same address, fourth time this month. Nothing is ever badly wrong. Your partner has stopped bothering to take a full history, and the patient has stopped expecting one. Everyone in the room has quietly agreed this call does not really count.',
  decision_point:'What has gone wrong here, and whose problem is it?'},
 pretest_item:'itm-1.7.001',
 screens:[
  {id:'scr-1.7.1',body_md:'**Professional attributes are not decoration.** Integrity, respect, self-motivation, appearance and manner, and careful communication appear in every professional standard, and each has a clinical reason.\n\nIntegrity is why the record can be relied on. Respect is why the patient tells you things. Self-motivation is why a rarely used skill still works when you need it.',figure:null},
  {id:'scr-1.7.2',body_md:'**Trust is an assessment tool.** History is the larger part of your assessment, and it depends entirely on being told the truth.\n\nA frightened or unconvinced patient tells you less, so you decide with less. That is why manner is treated as clinical rather than cosmetic — it changes the quality of your data.',figure:null},
  {id:'scr-1.7.3',body_md:'**Skills decay whether or not anyone checks.** The ones you rarely use decay fastest, and pressure is exactly when that shows.\n\nSaying "I have not done this in a year and I want to refresh it" is the professional act. Reading a procedure for the first time at a bedside is not competence, and everyone present can tell.',figure:null},
  {id:'scr-1.7.4',body_md:'**Mobile integrated healthcare treats EMS as a healthcare resource that happens to be mobile.** Follow-up visits, assessment at home, help navigating to the service that actually meets the need.\n\nMeasured by needs met rather than patients moved, and often the answer to a person who keeps calling because nothing else has worked.\n\nIt is not a scope change and not a new certification. It is the same providers, sent against a different question.',figure:null},
  {id:'scr-1.7.5',body_md:'**A frequent caller is usually a signal.** Repeated use of an emergency service is a healthcare problem with a healthcare answer, not a character defect and not something to be endured.\n\nIt is also the clearest example of why 1.3 mattered: the fix is almost never on the truck, and the people who can fix it only find out if somebody tells them.',figure:null}],
 inline_checks:['itm-1.7.003','itm-1.7.006'],
 quiz:['itm-1.7.002','itm-1.7.004','itm-1.7.005','itm-1.7.007','itm-1.7.008'],
 callback_md:'The assessment has quietly stopped happening, which means the day something *is* badly wrong, nobody will notice. Familiarity has become a clinical risk.\n\n**And the repeat calls themselves are the signal.** Four visits in a month is a need being met nowhere else — which is a system problem, with a system answer, that will keep recurring until somebody names it.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'1.INT',chapter:1,title:'Integration — scope, direction and destination',learner_title:'One call, all three',
 objectives:['obj-1.INT.a'],est_minutes:9,
 cold_open:{text:'Everything in this chapter arrives on the same call, usually in the wrong order and usually at night. Scope, medical direction and destination do not take turns. They land together, and each one changes what the others allow you to do.',
  decision_point:'Can you hold all three at once?'},
 pretest_item:null,
 screens:[
  {id:'scr-1.INT.1',body_md:'**Three questions, running at the same time.**\n\nWhat am I licensed and authorised to do? Who is directing this care, and does the written direction already cover it? And where does this patient need to end up?\n\nWhat follows is one call. Each question comes up more than once, and at least one of the answers changes partway through.',figure:null}],
 inline_checks:[],
 quiz:['itm-1.INT.000'],
 callback_md:'Aspirin on the standing order, without calling. The PCI centre, because the nearer hospital cannot do the thing he needs. A diversion when his airway failed, because capability stops winning the moment the patient will not survive the distance. And a declined order, because nobody on a radio can widen your licence.\n\nFour decisions, all defensible, and the reasons are different in each case. **That is what holding all three at once actually looks like.**',
 local_overlay:'ks-amr-kc',version:'1.0.0'}
];
