// Chapter 7 — The Human Body.
// Anatomy is instrumental here, never terminal: every objective has to name the
// decision it enables, and the block that cannot is a reference block rather
// than a memorization one. Two original figures carry the spatial content.
const STD='NHTSA National EMS Education Standards (2021) — Preparatory: Anatomy and Physiology.';
const AIR='NHTSA National EMS Education Standards (2021) — Airway Management, Respiration and Artificial Ventilation; pediatric airway anatomy.';
const FIG_CAV={kind:'image',ref:'aemt/fig-body-cavities.svg',
  alt:'Schematic front view of a head and trunk with four body cavities outlined: cranial, thoracic above the diaphragm, abdominal below it, and pelvic at the base.',
  asset_license:'Original schematic drawn for this module. AMR Kansas City, 2026. Not traced from any third-party illustration.'};
const FIG_AIR={kind:'image',ref:'aemt/fig-upper-airway.svg',
  alt:'Side-view schematic of the upper airway with five numbered pointers, from the nasal passage down to the windpipe.',
  asset_license:'Original schematic drawn for this module. AMR Kansas City, 2026. Not traced from any third-party illustration.'};

const opt=(id,text,correct,rationale)=>({id,text,correct,rationale});
const base=(o)=>({stimulus:{kind:'none',ref:null},bloom:'apply',nremt_domain:'ems_operations',
  cj_step:null,difficulty_seed:0.5,high_stakes:false,
  version:'1.0.0',...o});

export const objectives=[
 {id:'obj-7.1.a',chapter:7,tier:'core',text:'Use anatomical position and directional terms to describe a finding unambiguously',
  enables:'Describe where an injury is so the next clinician finds the same place'},
 {id:'obj-7.2.a',chapter:7,tier:'core',text:'Locate the body cavities and abdominal regions, and say what is inside each',
  enables:'Predict which organs a wound or a pain has reached'},
 {id:'obj-7.3.a',chapter:7,tier:'context',text:'Describe how cells, tissues, organs and systems relate — an orientation map for the rest',
  enables:'Orientation for the systems that follow; not a memorization target in itself'},
 {id:'obj-7.4.a',chapter:7,tier:'core',text:'Explain ventilation and respiration, and what changes each',
  enables:'Tell a ventilation problem from an oxygenation one at the bedside'},
 {id:'obj-7.5.a',chapter:7,tier:'core',text:'Explain perfusion in terms of pump, volume and vessels',
  enables:'Name which of the three has failed in a patient in shock'},
 {id:'obj-7.6.a',chapter:7,tier:'core',text:'Relate nervous and musculoskeletal structure to the findings you will assess',
  enables:'Read a deficit as information about where the problem is'},
 {id:'obj-7.7.a',chapter:7,tier:'core',text:'Identify upper airway structures and their clinical consequence',
  enables:'Size an adjunct, and know why a child’s airway occludes sooner than an adult’s'},
 {id:'obj-7.8.a',chapter:7,tier:'reference',text:'Recognize what belongs in a reference rather than in memory, and where to find it',
  enables:'Look a value up rather than carry it, and know which values those are'},
 {id:'obj-7.INT.a',chapter:7,tier:'core',text:'Use anatomy to predict injury and guide assessment on one call',
  enables:'Work out what is damaged from where the wound is and which way it went'}
];

export const items=[
// ── 7.1 Position and directional terms ───────────────────────────────── 8
base({id:'itm-7.1.001',type:'mc',chapter:7,block:'7.1',objective:'obj-7.1.a',bloom:'understand',
 stem:'Why is the anatomical position agreed before any directional term is used?',
 options:[opt('a','Terms like anterior and lateral only mean one thing if everyone assumes the same starting posture',true,'Otherwise "the front of the arm" depends on how the arm is turned.'),
  opt('b','It is the position patients are usually found in',false,'It is almost never the position they are found in.'),
  opt('c','It is the safest position for transport',false,'It is a descriptive convention, not a transport position.'),
  opt('d','It is required for consent',false,'Unrelated.')],
 explanation_md:'Standing, facing forward, arms at the sides with palms forward. Nobody lies like that; everybody describes from it.',source_ref:STD}),
base({id:'itm-7.1.002',type:'drag_drop',chapter:7,block:'7.1',objective:'obj-7.1.a',bloom:'remember',
 stem:'Match each pair of terms to what it describes.',
 categories:[{id:'ap',label:'Front and back'},{id:'ml',label:'Toward and away from the midline'},{id:'pd',label:'Nearer and further along a limb'},{id:'sup',label:'Above and below'}],
 options:[opt('a','Anterior and posterior',true,'Front and back of the body.'),
  opt('b','Medial and lateral',true,'Toward the midline and away from it.'),
  opt('c','Proximal and distal',true,'Nearer the trunk and further from it, along a limb.'),
  opt('d','Superior and inferior',true,'Above and below.')],
 answer_map:{a:'ap',b:'ml',c:'pd',d:'sup'},
 explanation_md:'Four pairs carry most of what you will need to write. Proximal and distal apply along a limb, which is why "distal pulse" means what it does.',source_ref:STD}),
base({id:'itm-7.1.003',type:'mc',chapter:7,block:'7.1',objective:'obj-7.1.a',high_stakes:true,
 stem:'How should you describe a wound on the thumb side of the left forearm, halfway along?',
 options:[opt('a','Lateral aspect of the left forearm, mid-shaft',true,'In anatomical position the thumb side is lateral, and left is the patient’s left.'),
  opt('b','Medial aspect of the left forearm',false,'The thumb side is lateral, not medial.'),
  opt('c','Right forearm, outer side',false,'Left and right are always the patient’s.'),
  opt('d','Upper forearm, outside',false,'Vague, and "upper" does not locate it along the limb.')],
 explanation_md:'Left and right are the patient’s, always. The commonest error in a handover is describing a limb as you are looking at it.',source_ref:STD}),
base({id:'itm-7.1.004',type:'mr',chapter:7,block:'7.1',objective:'obj-7.1.a',bloom:'remember',select_count:[3,4],
 stem:'Select the descriptions that would locate a finding unambiguously.',
 options:[opt('a','Anterior chest, right of midline, at the fourth rib',true,'Plane, side and level.'),
  opt('b','Distal to the elbow on the posterior left forearm',true,'Relative position along the limb and which surface.'),
  opt('c','Right upper quadrant of the abdomen',true,'A named region with agreed boundaries.'),
  opt('d','Two inches superior to the left iliac crest',true,'Measured from a landmark.'),
  opt('e','Over on the sore side',false,'Means nothing to anyone who was not there.')],
 explanation_md:'Landmark, side, plane, level. Any description that would survive being read aloud two years later is doing those four things.',source_ref:STD}),
base({id:'itm-7.1.005',type:'options_box',chapter:7,block:'7.1',objective:'obj-7.1.a',bloom:'analyze',
 stem:'Which plane divides the body this way?',
 columns:[{id:'sag',label:'Sagittal'},{id:'fro',label:'Frontal'},{id:'tra',label:'Transverse'}],
 rows:[{id:'r1',label:'Into left and right',answer:'sag'},
  {id:'r2',label:'Into front and back',answer:'fro'},
  {id:'r3',label:'Into upper and lower',answer:'tra'},
  {id:'r4',label:'Into equal left and right halves',answer:'sag'}],
 options:[],
 explanation_md:'Three planes. The midsagittal is the one through the midline, which is why "right of midline" is a usable phrase.',source_ref:STD}),
base({id:'itm-7.1.006',type:'mc',chapter:7,block:'7.1',objective:'obj-7.1.a',bloom:'analyze',
 stem:'Why does an ambiguous location in a handover matter clinically?',
 options:[opt('a','The next clinician examines the wrong place, or reassesses a different finding and calls it unchanged',true,'Both happen, and the second is harder to notice.'),
  opt('b','It looks unprofessional',false,'It does, and that is not the clinical harm.'),
  opt('c','It affects billing codes',false,'Not the concern here.'),
  opt('d','It slows the handover',false,'It usually speeds it up and costs accuracy.')],
 explanation_md:'"Unchanged since the ambulance" only means something if both people were looking at the same thing. Precision here is what makes serial assessment possible.',source_ref:STD}),
base({id:'itm-7.1.007',type:'mc',chapter:7,block:'7.1',objective:'obj-7.1.a',bloom:'remember',
 stem:'What do the terms prone and supine describe?',
 options:[opt('a','Lying face down and lying face up',true,'Prone is face down; supine is face up.'),
  opt('b','Lying on the left and on the right side',false,'Those are lateral recumbent positions.'),
  opt('c','Sitting and standing',false,'Neither.'),
  opt('d','Head down and head up',false,'Those describe tilt, not the two terms asked about.')],
 explanation_md:'Worth being automatic because both appear in the same sentence as an airway decision, and reversing them changes the meaning completely.',source_ref:STD}),
base({id:'itm-7.1.008',type:'mc',chapter:7,block:'7.1',objective:'obj-7.1.a',
 stem:'A colleague writes "wound to the inside of the right leg". What is the problem?',
 options:[opt('a','"Inside" is ambiguous — it could mean medial, or the inner surface of a wound',true,'Medial aspect of the right thigh or calf says it once, precisely.'),
  opt('b','Nothing — everyone understands it',false,'Different readers resolve it differently.'),
  opt('c','Leg should be lower limb',false,'A minor pedantry, not the problem.'),
  opt('d','The side should not be recorded',false,'Side is essential.')],
 explanation_md:'Plain words are good; ambiguous words are not. The test is whether a stranger reading it would go to the same place you did.',source_ref:STD}),
// ── 7.2 Body cavities and regions ─────────────────────────────────────── 8
base({id:'itm-7.2.001',type:'hotspot',chapter:7,block:'7.2',objective:'obj-7.2.a',high_stakes:true,
 stimulus:FIG_CAV,
 stem:'A stab wound just below the nipple line on the left. Which cavity is most likely entered?',
 regions:[{id:'cranial',label:'Region 1',polygon:[[38,3],[62,3],[62,20],[38,20]]},
  {id:'thoracic',label:'Region 2',polygon:[[29,30],[71,30],[71,49],[29,49]]},
  {id:'abdominal',label:'Region 3',polygon:[[29,52],[71,52],[71,74],[29,74]]},
  {id:'pelvic',label:'Region 4',polygon:[[32,76],[68,76],[68,89],[32,89]]}],
 answer_region:'thoracic',
 options:[],
 explanation_md:'The diaphragm rises to about the nipple line on expiration, so a wound there can enter the chest, the abdomen, or both. Assume thoracic and keep the abdomen on the list.',source_ref:STD}),
base({id:'itm-7.2.002',type:'drag_drop',chapter:7,block:'7.2',objective:'obj-7.2.a',high_stakes:true,
 stem:'Match each organ to the cavity that holds it.',
 categories:[{id:'th',label:'Thoracic'},{id:'ab',label:'Abdominal'},{id:'pe',label:'Pelvic'},{id:'cr',label:'Cranial'}],
 options:[opt('a','Heart and lungs',true,'Thoracic, above the diaphragm.'),
  opt('b','Liver, spleen, stomach',true,'Abdominal, immediately below it.'),
  opt('c','Bladder and rectum',true,'Pelvic.'),
  opt('d','Brain',true,'Cranial.')],
 answer_map:{a:'th',b:'ab',c:'pe',d:'cr'},
 explanation_md:'The liver and spleen sit high under the ribs, which is why lower rib fractures are an abdominal concern as well as a chest one.',source_ref:STD}),
base({id:'itm-7.2.003',type:'options_box',chapter:7,block:'7.2',objective:'obj-7.2.a',high_stakes:true,
 stem:'Which quadrant holds each organ?',
 columns:[{id:'ruq',label:'Right upper'},{id:'luq',label:'Left upper'},{id:'rlq',label:'Right lower'},{id:'llq',label:'Left lower'}],
 rows:[{id:'r1',label:'Liver and gallbladder',answer:'ruq'},
  {id:'r2',label:'Spleen and stomach',answer:'luq'},
  {id:'r3',label:'Appendix',answer:'rlq'},
  {id:'r4',label:'Sigmoid colon',answer:'llq'}],
 options:[],
 explanation_md:'Quadrants are named from the patient’s perspective. Chapter 5 drilled these as terminology; here they are a prediction about what is under the hand.',source_ref:STD}),
base({id:'itm-7.2.004',type:'mc',chapter:7,block:'7.2',objective:'obj-7.2.a',high_stakes:true,
 stem:'Why does the position of the diaphragm matter when assessing a penetrating wound to the lower chest?',
 options:[opt('a','It moves with breathing, so a wound at the same skin level can enter chest, abdomen, or both',true,'On expiration the diaphragm rises toward the nipple line.'),
  opt('b','It is fixed, so the level of the wound settles the question',false,'It is not fixed, which is the whole problem.'),
  opt('c','It has no relevance to penetrating injury',false,'It is the boundary the wound may have crossed.'),
  opt('d','It only matters for blunt injury',false,'It is most relevant in penetrating injury.')],
 explanation_md:'This is anatomy doing real work: the same entry point means different injuries depending on where the patient was in the breathing cycle.',source_ref:STD}),
base({id:'itm-7.2.005',type:'mc',chapter:7,block:'7.2',objective:'obj-7.2.a',
 stem:'A patient has left lower rib fractures. Which organ injury should you actively consider?',
 options:[opt('a','Splenic injury — the spleen sits high on the left, under those ribs',true,'And splenic bleeding can be occult for a while.'),
  opt('b','Appendicitis',false,'Wrong quadrant and not a traumatic concern here.'),
  opt('c','Bladder rupture',false,'Pelvic, and usually a different mechanism.'),
  opt('d','No abdominal concern — these are chest injuries',false,'The upper abdomen sits under the lower ribs.')],
 explanation_md:'Left lower ribs: spleen. Right lower ribs: liver. Two associations worth being automatic, because both bleed and neither shows on the skin.',source_ref:STD}),
base({id:'itm-7.2.006',type:'mr',chapter:7,block:'7.2',objective:'obj-7.2.a',bloom:'remember',select_count:[3,4],
 stem:'Select what is true about the abdominal cavity.',
 options:[opt('a','It extends upward under the lower ribs',true,'Which is why rib fractures are an abdominal question.'),
  opt('b','It is separated from the thorax by the diaphragm',true,'A moving boundary.'),
  opt('c','It is described in four quadrants around the umbilicus',true,'The convention used in handover and documentation.'),
  opt('d','It contains organs that can bleed heavily without external signs',true,'Liver and spleen in particular.'),
  opt('e','It is fully protected by the rib cage',false,'Only its upper portion is, and only partly.')],
 explanation_md:'The clinically important feature is that a great deal of blood can be lost into it with very little to see from the outside.',source_ref:STD}),
base({id:'itm-7.2.007',type:'mc',chapter:7,block:'7.2',objective:'obj-7.2.a',bloom:'analyze',
 stem:'How does knowing the cavities change your assessment of a penetrating wound?',
 options:[opt('a','It lets you predict which structures the track may have crossed, and look for those findings',true,'Anatomy converts a hole in the skin into a list of things to check.'),
  opt('b','It tells you the depth of the wound',false,'It does not; you cannot know that from the surface.'),
  opt('c','It determines whether to transport',false,'Penetrating torso injury is going regardless.'),
  opt('d','It replaces the physical examination',false,'It directs it.')],
 explanation_md:'You are not diagnosing. You are deciding what to look for and what to tell the receiving team to expect.',source_ref:STD}),
base({id:'itm-7.2.008',type:'mc',chapter:7,block:'7.2',objective:'obj-7.2.a',bloom:'remember',
 stem:'What separates the thoracic cavity from the abdominal cavity?',
 options:[opt('a','The diaphragm',true,'A muscular sheet that moves with every breath.'),
  opt('b','The peritoneum',false,'That lines the abdominal cavity; it is not the divider.'),
  opt('c','The pleura',false,'That lines the thoracic cavity and covers the lungs.'),
  opt('d','The mediastinum',false,'That is the space between the lungs.')],
 explanation_md:'And it is the only boundary in the body that changes position several thousand times an hour, which is what makes the lower chest so ambiguous.',source_ref:STD}),

// ── 7.3 From cell to system ───────────────────────────────────────────── 8
base({id:'itm-7.3.001',type:'mc',chapter:7,block:'7.3',objective:'obj-7.3.a',bloom:'understand',
 stem:'Why is this block marked as orientation rather than as something to memorize?',
 options:[opt('a','It is a map for the systems that follow — none of it changes a decision on its own',true,'Which is exactly what a context-tier objective means in this series.'),
  opt('b','Because it is unimportant',false,'It is needed; it is not independently actionable.'),
  opt('c','Because it is covered elsewhere',false,'It is covered here, at the level that is useful.'),
  opt('d','Because the terminology is in chapter 5',false,'Some of it is, and that is not why this is context.'),
  ],
 explanation_md:'The series only queues core material for spaced repetition. Orientation is read once and used, rather than drilled.',source_ref:STD}),
base({id:'itm-7.3.002',type:'build_list',chapter:7,block:'7.3',objective:'obj-7.3.a',bloom:'remember',
 stem:'Put these levels of organization in order, smallest first.',
 options:[opt('a','Cell',true,'The smallest living unit.'),
  opt('b','Tissue',true,'Cells of similar type working together.'),
  opt('c','Organ',true,'Several tissues with a shared function.'),
  opt('d','Organ system',true,'Organs working toward one outcome.'),
  opt('e','Organism',true,'All systems together.')],
 explanation_md:'The useful part is the direction: failure at a small scale shows up as a problem at a large one, which is the whole of chapter 8.',source_ref:STD}),
base({id:'itm-7.3.003',type:'mr',chapter:7,block:'7.3',objective:'obj-7.3.a',bloom:'remember',select_count:[3,4],
 stem:'Select what every cell needs continuously to stay alive.',
 options:[opt('a','Oxygen delivered by perfusion',true,'Delivery, not merely presence in the air.'),
  opt('b','Glucose or another usable fuel',true,'Substrate for energy production.'),
  opt('c','Removal of waste products',true,'Including carbon dioxide and acid.'),
  opt('d','A temperature and chemical environment within a narrow range',true,'Homeostasis, kept by several systems at once.'),
  opt('e','Direct nervous stimulation',false,'Most cells do not require it to stay alive.')],
 explanation_md:'Four requirements. Every emergency in this course is one of them failing, which is why this block is the map rather than the destination.',source_ref:STD}),
base({id:'itm-7.3.004',type:'mc',chapter:7,block:'7.3',objective:'obj-7.3.a',bloom:'understand',
 stem:'What does homeostasis describe?',
 options:[opt('a','The active maintenance of a stable internal environment against constant disturbance',true,'Active, not passive — it costs energy continuously.'),
  opt('b','The absence of disease',false,'A healthy person is constantly correcting, not undisturbed.'),
  opt('c','A fixed internal state that does not vary',false,'It varies within limits; the correction is the point.'),
  opt('d','The body’s response to injury only',false,'It runs all the time.')],
 explanation_md:'Compensation in a sick patient is homeostasis working hard and visibly. When it stops being visible, it has usually stopped working.',source_ref:STD}),
base({id:'itm-7.3.005',type:'mc',chapter:7,block:'7.3',objective:'obj-7.3.a',bloom:'understand',
 stem:'Which organ systems are most directly involved in delivering oxygen to a cell?',
 options:[opt('a','Respiratory and cardiovascular, working as one delivery chain',true,'One gets oxygen in; the other moves it.'),
  opt('b','Nervous and endocrine',false,'They regulate the chain rather than forming it.'),
  opt('c','Digestive and renal',false,'Fuel and waste, not oxygen delivery.'),
  opt('d','Musculoskeletal and integumentary',false,'Neither is part of the delivery chain.')],
 explanation_md:'Air in, blood around. Every failure of oxygenation is somewhere on that chain, and naming where is most of prehospital assessment.',source_ref:STD}),
base({id:'itm-7.3.006',type:'mc',chapter:7,block:'7.3',objective:'obj-7.3.a',bloom:'analyze',
 stem:'Why does cellular damage show up as an organ problem rather than a cell problem?',
 options:[opt('a','You cannot observe a cell — you observe the function that enough damaged cells stop performing',true,'The clinical signs are always at the organ or system level.'),
  opt('b','Cells are not affected in illness',false,'They are where illness starts.'),
  opt('c','Organs fail before their cells do',false,'It runs the other way.'),
  opt('d','Because cells repair instantly',false,'Repair is neither instant nor complete.')],
 explanation_md:'This is the link into pathophysiology: the injury is cellular, the presentation is systemic, and everything you can measure sits at the far end of that.',source_ref:STD}),
base({id:'itm-7.3.007',type:'mc',chapter:7,block:'7.3',objective:'obj-7.3.a',bloom:'remember',
 stem:'What defines a tissue?',
 options:[opt('a','A group of similar cells working together at one function',true,'Muscle, nerve, epithelial, connective.'),
  opt('b','Any structure with a blood supply',false,'Not the definition.'),
  opt('c','Two or more organs',false,'That is closer to a system.'),
  opt('d','The lining of a cavity only',false,'That describes one kind of epithelium.')],
 explanation_md:'Four broad types. Useful mainly because injuries and healing behave differently in each, which chapter 8 picks up.',source_ref:STD}),
base({id:'itm-7.3.008',type:'mc',chapter:7,block:'7.3',objective:'obj-7.3.a',bloom:'analyze',
 stem:'What is the practical value of holding this hierarchy in mind?',
 options:[opt('a','It lets you reason from a sign back toward the failure causing it, rather than treating signs in isolation',true,'Cold, mottled skin is a delivery failure, not a skin problem.'),
  opt('b','It allows you to diagnose at cellular level',false,'You cannot, and you do not need to.'),
  opt('c','It replaces the need for assessment',false,'It organizes assessment.'),
  opt('d','It determines drug dosing',false,'It does not.')],
 explanation_md:'That reasoning — sign, to organ, to what is failing — is the habit the rest of this chapter and all of chapter 8 are built to produce.',source_ref:STD}),
// ── 7.4 Ventilation and respiration ───────────────────────────────────── 8
base({id:'itm-7.4.001',type:'mc',chapter:7,block:'7.4',objective:'obj-7.4.a',bloom:'understand',high_stakes:true,
 stem:'What is the difference between ventilation and respiration?',
 options:[opt('a','Ventilation is air moving in and out; respiration is gas exchange across a membrane',true,'You can ventilate adequately and still fail to exchange.'),
  opt('b','They are two words for the same process',false,'Treating them as one is how oxygenation problems get missed.'),
  opt('c','Ventilation is at the cell, respiration at the lung',false,'That is the wrong way round.'),
  opt('d','Respiration means the respiratory rate',false,'The rate is a measurement of ventilation.')],
 explanation_md:'A patient can move air beautifully and be profoundly hypoxic. Keeping the two words separate is what lets you notice that.',source_ref:STD}),
base({id:'itm-7.4.002',type:'mc',chapter:7,block:'7.4',objective:'obj-7.4.a',high_stakes:true,
 stem:'What actually drives air into the chest during a normal breath?',
 options:[opt('a','The diaphragm and chest wall enlarge the thorax, dropping pressure inside it below atmospheric',true,'Air moves down a pressure gradient; nothing pulls it in.'),
  opt('b','The lungs actively expand and draw air in',false,'The lungs are passive; the chest wall and diaphragm do the work.'),
  opt('c','Air is pushed in by atmospheric pressure alone, without thoracic change',false,'The gradient has to be created.'),
  opt('d','Muscles in the airway pump air downward',false,'No such mechanism.')],
 explanation_md:'This is why an open chest wound breaks breathing: the seal that lets a negative pressure exist has gone, so enlarging the chest no longer moves air.',source_ref:STD}),
base({id:'itm-7.4.003',type:'options_box',chapter:7,block:'7.4',objective:'obj-7.4.a',high_stakes:true,bloom:'analyze',
 stem:'Is this primarily a ventilation problem or an oxygenation problem?',
 columns:[{id:'vent',label:'Ventilation'},{id:'ox',label:'Oxygenation'}],
 rows:[{id:'r1',label:'Opioid overdose, respiratory rate 4, good air entry when breaths occur',answer:'vent'},
  {id:'r2',label:'Pneumonia, rate 28, moving air well, saturations 84%',answer:'ox'},
  {id:'r3',label:'Chest wall injury, splinting, shallow ineffective breaths',answer:'vent'},
  {id:'r4',label:'Carbon monoxide exposure, breathing normally, confused',answer:'ox'}],
 options:[],
 explanation_md:'Two patients need air moved. Two need gas exchanged, and one of those has a normal saturation reading that means nothing at all.',source_ref:STD}),
base({id:'itm-7.4.004',type:'mr',chapter:7,block:'7.4',objective:'obj-7.4.a',bloom:'remember',select_count:[3,4],
 stem:'Select what is required for gas exchange to occur at the alveolus.',
 options:[opt('a','Air reaching the alveolus',true,'Ventilation has to deliver it there.'),
  opt('b','Blood reaching the capillary beside it',true,'Perfusion of the lung.'),
  opt('c','A membrane thin enough for gas to cross',true,'Fluid, pus or fibrosis thickens it.'),
  opt('d','A concentration gradient for the gas to move down',true,'Which is what supplemental oxygen increases.'),
  opt('e','Active transport of oxygen across the membrane',false,'It is diffusion, not active transport.')],
 explanation_md:'Air, blood, membrane, gradient. Every respiratory emergency you will meet is one of those four failing.',source_ref:STD}),
base({id:'itm-7.4.005',type:'mc',chapter:7,block:'7.4',objective:'obj-7.4.a',bloom:'analyze',
 stem:'Why does a rising carbon dioxide level usually indicate a ventilation problem rather than an oxygenation one?',
 options:[opt('a','Carbon dioxide clearance depends almost entirely on how much air is moved per minute',true,'It diffuses readily; what limits it is minute volume.'),
  opt('b','Carbon dioxide does not cross the alveolar membrane',false,'It crosses very readily.'),
  opt('c','Carbon dioxide is only produced during exercise',false,'It is produced continuously.'),
  opt('d','It indicates an oxygenation problem in most cases',false,'The relationship runs the other way.')],
 explanation_md:'Which is why a patient who is hypoxic with a normal carbon dioxide is telling you something different from one who is hypoxic and retaining it.',source_ref:STD}),
base({id:'itm-7.4.006',type:'mc',chapter:7,block:'7.4',objective:'obj-7.4.a',high_stakes:true,
 stem:'A patient is breathing 32 times a minute with very shallow breaths. What is the concern?',
 options:[opt('a','A high rate with a low tidal volume can move less usable air than a slower, deeper pattern',true,'Much of each shallow breath only fills airway that never exchanges.'),
  opt('b','A high rate always means adequate ventilation',false,'Rate alone tells you very little.'),
  opt('c','Shallow breathing is protective',false,'It is not.'),
  opt('d','Nothing — 32 is within normal limits for an adult',false,'It is well above normal, and depth is the greater concern.')],
 explanation_md:'Dead space is filled first on every breath. A rapid shallow pattern can ventilate almost nothing, which is why you count the rate and then watch the chest.',source_ref:STD}),
base({id:'itm-7.4.007',type:'mc',chapter:7,block:'7.4',objective:'obj-7.4.a',bloom:'remember',
 stem:'What normally stimulates you to take a breath?',
 options:[opt('a','A rising carbon dioxide level, sensed centrally',true,'Carbon dioxide is the primary drive in most people.'),
  opt('b','A falling oxygen level',false,'The hypoxic drive exists and is secondary in most people.'),
  opt('c','Stretch receptors in the chest wall',false,'They modify the pattern rather than initiating it.'),
  opt('d','A conscious decision',false,'Breathing continues without one.')],
 explanation_md:'Worth knowing because it explains why a patient who is not breathing enough builds up carbon dioxide long before their oxygen saturation falls.',source_ref:STD}),
base({id:'itm-7.4.008',type:'mc',chapter:7,block:'7.4',objective:'obj-7.4.a',bloom:'analyze',
 stem:'Why can a pulse oximeter read normally in a patient who is being poisoned by carbon monoxide?',
 options:[opt('a','It cannot distinguish carbon monoxide bound to hemoglobin from oxygen bound to it',true,'The molecule is saturated; it is saturated with the wrong thing.'),
  opt('b','Carbon monoxide raises the true oxygen saturation',false,'It lowers oxygen carriage.'),
  opt('c','The device fails in cold environments only',false,'Not the mechanism.'),
  opt('d','It reads normally because the patient is ventilating well',false,'Ventilation is not what the device measures.')],
 explanation_md:'An anatomy and physiology fact with an immediate operational consequence: in a suspected exposure, the normal number on the screen is not reassurance.',source_ref:STD}),

// ── 7.5 Perfusion ─────────────────────────────────────────────────────── 8
base({id:'itm-7.5.001',type:'mc',chapter:7,block:'7.5',objective:'obj-7.5.a',bloom:'understand',high_stakes:true,
 stem:'What does perfusion require?',
 options:[opt('a','A working pump, enough volume, and vessels of appropriate size',true,'Pump, volume, container. Every shock state is one of the three.'),
  opt('b','A normal blood pressure',false,'Pressure is a number that can be normal while perfusion fails.'),
  opt('c','A normal heart rate',false,'Same problem.'),
  opt('d','Adequate oxygen saturation alone',false,'Saturation says nothing about delivery.')],
 explanation_md:'Three components. Naming which one has failed is the most useful thing you can do with a patient in shock, and it is an anatomy question.',source_ref:STD}),
base({id:'itm-7.5.002',type:'drag_drop',chapter:7,block:'7.5',objective:'obj-7.5.a',high_stakes:true,
 stem:'Sort each cause of shock by which component has failed.',
 categories:[{id:'pump',label:'Pump'},{id:'vol',label:'Volume'},{id:'vess',label:'Vessels'}],
 options:[opt('a','Major hemorrhage',true,'Volume lost from the container.'),
  opt('b','Massive myocardial infarction with poor output',true,'The pump has failed.'),
  opt('c','Anaphylaxis with widespread vasodilation',true,'The container has enlarged beyond the volume in it.'),
  opt('d','Severe dehydration',true,'Volume again, lost more slowly.')],
 answer_map:{a:'vol',b:'pump',c:'vess',d:'vol'},
 explanation_md:'The treatment follows from the category. Fluid helps an empty container; it does very little for a failed pump.',source_ref:STD}),
base({id:'itm-7.5.003',type:'mc',chapter:7,block:'7.5',objective:'obj-7.5.a',high_stakes:true,bloom:'analyze',
 stem:'Why can a patient in early shock have a normal blood pressure?',
 options:[opt('a','Compensation raises heart rate and constricts vessels, holding pressure up until the loss is large',true,'Pressure is a late sign, particularly in the young.'),
  opt('b','Blood pressure is unaffected by blood loss',false,'It is affected — eventually.'),
  opt('c','Because the reading is inaccurate in shock',false,'The reading may be accurate and still reassuring wrongly.'),
  opt('d','Because shock does not involve the circulation',false,'It is a circulatory failure by definition.')],
 explanation_md:'Look at what compensation costs: tachycardia, cool peripheries, delayed capillary refill, anxiety. Those appear before the pressure moves.',source_ref:STD}),
base({id:'itm-7.5.004',type:'mr',chapter:7,block:'7.5',objective:'obj-7.5.a',select_count:[3,4],
 stem:'Select the findings that suggest compensation is already working hard.',
 options:[opt('a','Tachycardia at rest',true,'The first and cheapest compensation available.'),
  opt('b','Cool, pale or mottled peripheries',true,'Blood being diverted to the core.'),
  opt('c','Delayed capillary refill',true,'Peripheral perfusion falling.'),
  opt('d','Anxiety or restlessness',true,'Often the earliest change in cerebral perfusion.'),
  opt('e','A normal blood pressure',false,'Normal pressure is what compensation is producing, not evidence against it.')],
 explanation_md:'Four findings, none of which needs a monitor. The fifth is the number people look at instead of the other four.',source_ref:STD}),
base({id:'itm-7.5.005',type:'mc',chapter:7,block:'7.5',objective:'obj-7.5.a',bloom:'remember',
 stem:'What is the route of blood from the right side of the heart?',
 options:[opt('a','To the lungs, then back to the left side, then out to the body',true,'Pulmonary circuit first, then systemic.'),
  opt('b','Directly to the body',false,'That is the left side.'),
  opt('c','To the liver, then the lungs',false,'Not the circuit.'),
  opt('d','To the brain first',false,'The brain is supplied from the systemic circuit.')],
 explanation_md:'Two circuits in series. It explains why left-sided failure backs fluid into the lungs and right-sided failure backs it into the body.',source_ref:STD}),
base({id:'itm-7.5.006',type:'mc',chapter:7,block:'7.5',objective:'obj-7.5.a',bloom:'analyze',
 stem:'Why does hemoglobin matter as much as blood pressure in oxygen delivery?',
 options:[opt('a','Delivery depends on flow and on what the blood is carrying — a well-perfused patient with little hemoglobin still starves tissue',true,'Both halves of the product have to be adequate.'),
  opt('b','Hemoglobin determines blood pressure',false,'It does not directly.'),
  opt('c','Hemoglobin is not involved in oxygen transport',false,'It is the transport molecule.'),
  opt('d','Only saturation matters, not quantity',false,'Fully saturated but scarce hemoglobin carries very little.')],
 explanation_md:'Which is why saturation is a percentage rather than an amount, and why a bleeding patient with 100% saturation can still be hypoxic at the tissue.',source_ref:STD}),
base({id:'itm-7.5.007',type:'mc',chapter:7,block:'7.5',objective:'obj-7.5.a',bloom:'understand',
 stem:'What do arteries, capillaries and veins each contribute?',
 options:[opt('a','Arteries carry blood under pressure, capillaries exchange, veins return and hold volume in reserve',true,'Most of the circulating volume sits in the venous side at any moment.'),
  opt('b','All three exchange gas equally',false,'Exchange happens at the capillary.'),
  opt('c','Veins carry blood under the highest pressure',false,'Arteries do.'),
  opt('d','Capillaries carry blood away from the heart',false,'That is the arterial side.')],
 explanation_md:'The venous reservoir is why vasoconstriction can compensate for real volume loss for a while, and why vasodilation can cause shock with no blood lost at all.',source_ref:STD}),
base({id:'itm-7.5.008',type:'mc',chapter:7,block:'7.5',objective:'obj-7.5.a',high_stakes:true,bloom:'analyze',
 stem:'A patient is anxious, tachycardic and cool to the touch, with a blood pressure of 118/76. What is your reading?',
 options:[opt('a','Compensated shock until proved otherwise — the pressure is being held up, not preserved',true,'Three compensation findings and one number that has not moved yet.'),
  opt('b','A normal patient, since the pressure is normal',false,'That is the trap this whole block is built around.'),
  opt('c','An anxiety reaction',false,'Possible, and not the first thing to exclude.'),
  opt('d','Nothing can be said without a lactate',false,'Four findings at the bedside say a great deal.')],
 explanation_md:'Every finding except the blood pressure points the same way. The pressure is the last thing to go, so it is the last thing to trust.',source_ref:STD}),
// ── 7.6 Nervous and musculoskeletal ───────────────────────────────────── 8
base({id:'itm-7.6.001',type:'mc',chapter:7,block:'7.6',objective:'obj-7.6.a',bloom:'understand',
 stem:'What is the practical division of the nervous system for assessment?',
 options:[opt('a','Central — brain and spinal cord — and peripheral, everything running out from it',true,'Where the problem sits changes what the deficit looks like.'),
  opt('b','Voluntary and involuntary only',false,'A useful distinction and not the anatomical division.'),
  opt('c','Sensory and motor only',false,'Those are functions carried by both divisions.'),
  opt('d','Cranial and spinal only',false,'That divides the peripheral nerves, not the system.')],
 explanation_md:'A one-sided weakness with a facial droop points centrally. Numbness in one limb below an injury points peripherally or to the cord.',source_ref:STD}),
base({id:'itm-7.6.002',type:'mc',chapter:7,block:'7.6',objective:'obj-7.6.a',high_stakes:true,bloom:'analyze',
 stem:'A patient has weakness and numbness in both legs after a fall, with normal arms. What does the pattern suggest?',
 options:[opt('a','A cord problem at or below the level supplying the arms',true,'Bilateral and below a level is the pattern that points at the cord.'),
  opt('b','A peripheral nerve injury in one leg',false,'It would not be bilateral or symmetrical.'),
  opt('c','A stroke',false,'A stroke usually produces one-sided findings.'),
  opt('d','Nothing localizing can be said',false,'The pattern is highly localizing.')],
 explanation_md:'Bilateral, symmetrical, and everything below a line: that is the cord. This is anatomy telling you where to look rather than what to call it.',source_ref:STD}),
base({id:'itm-7.6.003',type:'mr',chapter:7,block:'7.6',objective:'obj-7.6.a',select_count:[3,4],
 stem:'Select what the autonomic nervous system controls that you will see at a bedside.',
 options:[opt('a','Heart rate and the force of contraction',true,'Sympathetic activation raises both.'),
  opt('b','Blood vessel diameter',true,'Which is why compensation makes people cool and pale.'),
  opt('c','Sweating',true,'The clammy patient is showing you sympathetic tone.'),
  opt('d','Pupil size',true,'Visible, fast, and useful.'),
  opt('e','Voluntary limb movement',false,'That is the somatic system.')],
 explanation_md:'Every one of these is something you can see without equipment, and together they are what "looks unwell" actually consists of.',source_ref:STD}),
base({id:'itm-7.6.004',type:'mc',chapter:7,block:'7.6',objective:'obj-7.6.a',bloom:'remember',
 stem:'What are the functions of the skeleton relevant to your assessment?',
 options:[opt('a','Support, movement, protection of organs, and blood cell production in marrow',true,'The protective function is what makes rib and skull injuries significant.'),
  opt('b','Support and movement only',false,'It omits the two that matter most clinically.'),
  opt('c','Protection only',false,'Incomplete.'),
  opt('d','Blood cell production only',false,'One function of several.')],
 explanation_md:'The protective function is the clinical one: a broken rib matters because of what is under it, and a long bone fracture matters partly because of what the marrow does.',source_ref:STD}),
base({id:'itm-7.6.005',type:'mc',chapter:7,block:'7.6',objective:'obj-7.6.a',high_stakes:true,
 stem:'Why does a femur fracture carry a risk of significant blood loss?',
 options:[opt('a','It is a large bone with a rich blood supply, and the thigh can hold a great deal of blood',true,'Loss is internal and often underestimated.'),
  opt('b','The femoral artery is always torn',false,'It usually is not, and the bleeding is still substantial.'),
  opt('c','Because the fracture is painful',false,'Pain is not the mechanism.'),
  opt('d','Only open femur fractures bleed significantly',false,'Closed ones bleed into the thigh.')],
 explanation_md:'Anatomy predicting an injury pattern again. Nothing is visible, and the volume is real, which is why a swollen thigh is a circulatory finding.',source_ref:STD}),
base({id:'itm-7.6.006',type:'options_box',chapter:7,block:'7.6',objective:'obj-7.6.a',bloom:'analyze',
 stem:'Where does this finding point?',
 columns:[{id:'cent',label:'Central'},{id:'per',label:'Peripheral or cord'}],
 rows:[{id:'r1',label:'One-sided facial droop with arm weakness on the same side',answer:'cent'},
  {id:'r2',label:'Numbness in both legs below the waist after a fall',answer:'per'},
  {id:'r3',label:'Slurred speech with confusion',answer:'cent'},
  {id:'r4',label:'Loss of sensation in one hand after a wrist laceration',answer:'per'}],
 options:[],
 explanation_md:'One-sided and involving speech or face points centrally. Below a level, or following one nerve, points away from the brain.',source_ref:STD}),
base({id:'itm-7.6.007',type:'mc',chapter:7,block:'7.6',objective:'obj-7.6.a',bloom:'understand',
 stem:'What is the difference between a ligament and a tendon?',
 options:[opt('a','Ligaments join bone to bone; tendons join muscle to bone',true,'Which is why one injury destabilizes a joint and the other stops a movement.'),
  opt('b','They are the same structure with different names',false,'Different structures with different jobs.'),
  opt('c','Tendons join bone to bone',false,'Reversed.'),
  opt('d','Ligaments contract to produce movement',false,'Muscle contracts; ligaments do not.')],
 explanation_md:'A torn ligament leaves a joint unstable. A torn tendon leaves a movement absent. The finding tells you which one you are dealing with.',source_ref:STD}),
base({id:'itm-7.6.008',type:'mc',chapter:7,block:'7.6',objective:'obj-7.6.a',bloom:'analyze',
 stem:'Why does checking distal pulse, movement and sensation matter after a limb injury?',
 options:[opt('a','The artery and nerve run close to the bone, so a fracture can compromise either — and the deficit is only findable if you look',true,'A baseline before splinting and a recheck after is the point.'),
  opt('b','It determines whether the limb is fractured',false,'It does not diagnose the fracture.'),
  opt('c','It is only necessary for open fractures',false,'It applies to all of them.'),
  opt('d','It replaces immobilization',false,'It accompanies it.')],
 explanation_md:'Before and after, every time, and written down. A deficit that appeared after splinting is a finding about the splint.',source_ref:STD}),

// ── 7.7 Upper airway anatomy ──────────────────────────────────────────── 8
base({id:'itm-7.7.001',type:'label_drag',chapter:7,block:'7.7',objective:'obj-7.7.a',high_stakes:true,
 stimulus:FIG_AIR,
 stem:'Label the upper airway structures at each pointer.',
 pointers:[{id:'p1',label:'1',x:32,y:20},{id:'p2',label:'2',x:40,y:40},
  {id:'p3',label:'3',x:46,y:55},{id:'p4',label:'4',x:48,y:66},{id:'p5',label:'5',x:50,y:84}],
 labels:[{id:'l-naso',text:'Nasopharynx'},{id:'l-oro',text:'Oropharynx'},
  {id:'l-epi',text:'Epiglottis'},{id:'l-lar',text:'Larynx'},{id:'l-tra',text:'Trachea'}],
 answer_map:{p1:'l-naso',p2:'l-oro',p3:'l-epi',p4:'l-lar',p5:'l-tra'},
 options:[],
 explanation_md:'Top to bottom: nose to nasopharynx, mouth to oropharynx, the epiglottis guarding the entrance, the larynx, then the trachea. An adjunct has to follow that path without catching on any of it.',source_ref:AIR}),
base({id:'itm-7.7.002',type:'mc',chapter:7,block:'7.7',objective:'obj-7.7.a',high_stakes:true,
 stem:'What is the most common cause of airway obstruction in an unresponsive patient?',
 options:[opt('a','The tongue falling back against the posterior pharynx',true,'Which is why a position change alone often clears it.'),
  opt('b','Swelling of the larynx',false,'A cause, and not the common one.'),
  opt('c','Foreign body',false,'Important and less common than the tongue.'),
  opt('d','Secretions',false,'Frequent contributor, not the leading cause.')],
 explanation_md:'The muscle tone that holds the tongue forward is lost with consciousness. Head tilt and chin lift, or a jaw thrust, addresses it before any device.',source_ref:AIR}),
base({id:'itm-7.7.003',type:'mr',chapter:7,block:'7.7',objective:'obj-7.7.a',select_count:[4,5],
 stem:'Select what makes a child’s airway occlude more easily than an adult’s.',
 options:[opt('a','A proportionally larger tongue in a smaller oral cavity',true,'More tissue, less room.'),
  opt('b','Narrower airways, where a given amount of swelling costs far more flow',true,'Resistance climbs steeply as the radius falls.'),
  opt('c','A large occiput that flexes the neck when supine',true,'Position alone can close it.'),
  opt('d','Softer, more compressible airway tissues',true,'Easily obstructed by pressure from outside.'),
  opt('e','A calcified rigid larynx',false,'The pediatric larynx is softer, not rigid.')],
 explanation_md:'Chapter 9 met these as handling problems. Here they are the anatomy underneath, and it is the same list.',source_ref:AIR}),
base({id:'itm-7.7.004',type:'mc',chapter:7,block:'7.7',objective:'obj-7.7.a',high_stakes:true,
 stem:'What does the epiglottis do?',
 options:[opt('a','Covers the laryngeal opening during swallowing so material passes to the esophagus',true,'A flap that redirects, rather than a valve that seals.'),
  opt('b','Produces the voice',false,'That is the vocal cords within the larynx.'),
  opt('c','Warms and humidifies air',false,'That is largely the nasal passages.'),
  opt('d','Separates the two lungs',false,'Not its function or location.')],
 explanation_md:'It fails when consciousness is lost, which is why an unprotected airway and vomiting is such a dangerous combination.',source_ref:AIR}),
base({id:'itm-7.7.005',type:'mc',chapter:7,block:'7.7',objective:'obj-7.7.a',high_stakes:true,
 stem:'How should an oropharyngeal airway be sized?',
 options:[opt('a','From the corner of the mouth to the angle of the jaw, or the earlobe',true,'Too short pushes the tongue back; too long can reach the larynx.'),
  opt('b','By the patient’s age alone',false,'Age is a poor proxy for this measurement.'),
  opt('c','The largest that will fit',false,'Too large is its own obstruction.'),
  opt('d','Sizing is not important if it is inserted correctly',false,'Size is most of whether it works.')],
 explanation_md:'Both errors make the airway worse rather than neutral, which is the reason to measure rather than estimate.',source_ref:AIR}),
base({id:'itm-7.7.006',type:'mc',chapter:7,block:'7.7',objective:'obj-7.7.a',
 stem:'Why is a nasopharyngeal airway sometimes tolerated when an oral one is not?',
 options:[opt('a','It does not touch the back of the tongue and pharynx in the same way, so it provokes less gagging',true,'Useful in a patient with a gag reflex who still needs the airway held open.'),
  opt('b','It is smaller in every dimension',false,'Not necessarily, and not the reason.'),
  opt('c','It requires no lubrication',false,'It needs lubrication.'),
  opt('d','It seals the airway completely',false,'Neither adjunct does.')],
 explanation_md:'Neither device protects against aspiration. Both hold a path open, and the choice between them turns on whether the patient will tolerate it.',source_ref:AIR}),
base({id:'itm-7.7.007',type:'mc',chapter:7,block:'7.7',objective:'obj-7.7.a',bloom:'analyze',
 stem:'Why does the shared path of air and food matter clinically?',
 options:[opt('a','Both cross the pharynx, so a failure of the protective mechanism sends stomach contents into the airway',true,'The design is why aspiration is possible at all.'),
  opt('b','It makes intubation easier',false,'Not a consequence of the anatomy in that direction.'),
  opt('c','It has no clinical consequence',false,'It is the anatomical basis of aspiration.'),
  opt('d','It only matters in children',false,'It matters at every age.')],
 explanation_md:'Position, suction, and readiness to roll a patient are all responses to one anatomical fact about a shared corridor.',source_ref:AIR}),
base({id:'itm-7.7.008',type:'mc',chapter:7,block:'7.7',objective:'obj-7.7.a',bloom:'understand',
 stem:'What do the nasal passages do for inspired air?',
 options:[opt('a','Warm, humidify and filter it before it reaches the lower airway',true,'Which is why bypassing them has consequences over time.'),
  opt('b','Nothing measurable',false,'The conditioning effect is substantial.'),
  opt('c','Add oxygen to it',false,'No gas is added.'),
  opt('d','Remove carbon dioxide',false,'That happens at the alveolus.')],
 explanation_md:'It also explains why infants tolerate a blocked nose so poorly, and why nasal obstruction is worth clearing rather than working around.',source_ref:AIR}),
// ── 7.8 What to look up rather than memorize ──────────────────────────── 8
base({id:'itm-7.8.001',type:'mc',chapter:7,block:'7.8',objective:'obj-7.8.a',bloom:'understand',
 stem:'What distinguishes something worth memorizing from something worth looking up?',
 options:[opt('a','Whether you will need it in the seconds before you act, with no time to reach for anything',true,'Time pressure, not importance, decides which list it goes on.'),
  opt('b','How important it is',false,'Plenty of important values are safer looked up than recalled.'),
  opt('c','How often it appears in a textbook',false,'Not a useful criterion.'),
  opt('d','How hard it is to remember',false,'Difficulty is not the test.')],
 explanation_md:'A drug dose you give under pressure belongs in memory and in a reference. An organ’s blood supply belongs in a reference alone.',source_ref:STD}),
base({id:'itm-7.8.002',type:'options_box',chapter:7,block:'7.8',objective:'obj-7.8.a',bloom:'analyze',
 stem:'Memorize, or look up?',
 columns:[{id:'mem',label:'Memorize'},{id:'ref',label:'Look up'}],
 rows:[{id:'r1',label:'Which cavity holds the liver and spleen',answer:'mem'},
  {id:'r2',label:'The precise arterial supply of the pancreas',answer:'ref'},
  {id:'r3',label:'The three components of perfusion',answer:'mem'},
  {id:'r4',label:'The names of every carpal bone',answer:'ref'}],
 options:[],
 explanation_md:'Two of these change what you do in the next sixty seconds. Two are anatomy you can and should look up on the rare occasion you need them.',source_ref:STD}),
base({id:'itm-7.8.003',type:'mr',chapter:7,block:'7.8',objective:'obj-7.8.a',bloom:'remember',select_count:[3,4],
 stem:'Select the anatomy from this chapter that genuinely belongs in memory.',
 options:[opt('a','Which organs sit in which quadrant',true,'It shapes the assessment of abdominal pain and penetrating trauma.'),
  opt('b','Pump, volume and vessels as the three components of perfusion',true,'It is the framework for every shock patient.'),
  opt('c','The upper airway structures in order',true,'You size and place an adjunct against it.'),
  opt('d','The difference between ventilation and respiration',true,'It decides what problem you are treating.'),
  opt('e','The origin and insertion of each muscle group',false,'Genuine anatomy, and nothing you will act on prehospital.')],
 explanation_md:'Four things that change an action, and one that does not. That is the whole filter this block is teaching.',source_ref:STD}),
base({id:'itm-7.8.004',type:'mc',chapter:7,block:'7.8',objective:'obj-7.8.a',bloom:'analyze',
 stem:'Why is carrying a reference not a sign of weak knowledge?',
 options:[opt('a','Reading a value under pressure is more reliable than recalling it, and the error you avoid is the patient’s',true,'Aviation and medicine both settled this some time ago.'),
  opt('b','Because nobody expects you to know anything',false,'Plenty is expected in memory.'),
  opt('c','Because references are always correct',false,'They need to be current, which is a real caveat.'),
  opt('d','Because it saves time',false,'It often costs a little time, and buys accuracy.')],
 explanation_md:'The professional act from chapter 1 in another form: saying you will check rather than guessing is competence, not its absence.',source_ref:STD}),
base({id:'itm-7.8.005',type:'mc',chapter:7,block:'7.8',objective:'obj-7.8.a',
 stem:'What is the risk of relying on a reference you have not checked recently?',
 options:[opt('a','It may be out of date — a superseded value read confidently is worse than none',true,'References need a version and a review date.'),
  opt('b','There is no risk if it is printed',false,'Print ages fastest of all.'),
  opt('c','Only digital references go out of date',false,'Both do.'),
  opt('d','References never change',false,'The whole of chapter 1 argues otherwise.')],
 explanation_md:'Know when your reference was last updated. That question is the difference between using a reference and trusting a laminated card from 2014.',source_ref:STD}),
base({id:'itm-7.8.006',type:'mc',chapter:7,block:'7.8',objective:'obj-7.8.a',bloom:'understand',
 stem:'Which systems in this chapter were deliberately treated as reference rather than drilled?',
 options:[opt('a','Endocrine, digestive, renal and integumentary detail beyond what perfusion and assessment require',true,'Present, used where relevant, and not queued for repetition.'),
  opt('b','The respiratory system',false,'Core: it changes what you do immediately.'),
  opt('c','The cardiovascular system',false,'Core, for the same reason.'),
  opt('d','The upper airway',false,'Core — you size equipment against it.')],
 explanation_md:'Not because those systems do not matter, but because the AEMT decisions that depend on them are few and the detail is large.',source_ref:STD}),
base({id:'itm-7.8.007',type:'mc',chapter:7,block:'7.8',objective:'obj-7.8.a',bloom:'analyze',
 stem:'What is lost when a course drills anatomy that never reaches a decision?',
 options:[opt('a','Study time that could have gone to the anatomy that does change what you do',true,'Attention is the scarce resource, not enthusiasm.'),
  opt('b','Nothing — more knowledge is always better',false,'Not when it displaces the knowledge you act on.'),
  opt('c','Only exam performance',false,'The cost lands on the bedside.'),
  opt('d','Accreditation',false,'Not the issue.')],
 explanation_md:'This series states the decision each objective enables for exactly this reason. An objective that cannot name one is reference material, and it is labeled that way.',source_ref:STD}),
base({id:'itm-7.8.008',type:'mc',chapter:7,block:'7.8',objective:'obj-7.8.a',
 stem:'You cannot recall which quadrant the appendix is in, mid-assessment. What do you do?',
 options:[opt('a','Check it — and then notice that this one belongs in memory, because it shapes the examination you are doing now',true,'Look it up today; drill it tonight.'),
  opt('b','Guess and move on',false,'A guess about where to examine is a guess about the finding.'),
  opt('c','Leave it out of the assessment',false,'The examination is what you are there for.'),
  opt('d','Ask the patient',false,'They do not know either.')],
 explanation_md:'The point of the block is knowing which list a fact belongs on. This one is a memory item, and needing to check it is information about your own revision.',source_ref:STD}),

// ── 7.INT Integration ─────────────────────────────────────────────────── 9
base({id:'itm-7.INT.000',type:'scenario',chapter:7,block:'7.INT',objective:'obj-7.INT.a',
 stimulus:{kind:'scenario',ref:null,
  text:'2340. A 26-year-old man, stabbed once in a fight. The wound is on the left side of the chest, about two finger-widths below the nipple, in the mid-clavicular line. The assailant is gone and the scene is secure.\n\nHe is alert and frightened. Respiratory rate 26, radial pulse 118 and thready, blood pressure 118/78, skin cool and pale. Air entry is reduced on the left. He says the knife came from below and to the side, angled upward.\n\nThe nearest hospital is eight minutes away and has an emergency department but no surgical service. The trauma center is twenty-two minutes away. Somebody on scene is holding a cervical collar.'},
 children:['itm-7.INT.001','itm-7.INT.002','itm-7.INT.003','itm-7.INT.004',
  'itm-7.INT.005','itm-7.INT.006','itm-7.INT.007','itm-7.INT.008'],
 stem:'',options:[],explanation_md:'',source_ref:STD}),
base({id:'itm-7.INT.001',type:'mc',chapter:7,block:'7.INT',objective:'obj-7.INT.a',parent:'itm-7.INT.000',high_stakes:true,
 stem:'Which cavities could this wound have entered?',
 options:[opt('a','Thoracic, abdominal, or both — the diaphragm moves through that level with every breath',true,'Below the nipple line is the ambiguous zone, and the upward angle widens it.'),
  opt('b','Thoracic only, because it is on the chest',false,'Skin level does not settle which side of the diaphragm the track reached.'),
  opt('c','Abdominal only, because it is below the nipple',false,'It can equally be above the diaphragm.'),
  opt('d','Neither — chest wounds at that level are superficial',false,'Nothing about the level makes it superficial.')],
 explanation_md:'This is 7.2 doing real work. One hole in the skin, two cavities, and a moving boundary you cannot see.',source_ref:STD}),
base({id:'itm-7.INT.002',type:'mr',chapter:7,block:'7.INT',objective:'obj-7.INT.a',parent:'itm-7.INT.000',select_count:[3,4],
 stem:'Given the location and the upward angle, which structures should you expect to be involved?',
 options:[opt('a','Left lung and pleural space',true,'Reduced air entry on the left already suggests it.'),
  opt('b','Spleen, which sits high on the left under the ribs',true,'And it bleeds substantially with nothing to see.'),
  opt('c','Diaphragm itself',true,'The track crosses it if it reached the abdomen.'),
  opt('d','Heart, given the left-sided and upward track',true,'It cannot be excluded from this trajectory.'),
  opt('e','Appendix',false,'Wrong quadrant entirely.')],
 explanation_md:'The angle is part of the history. "From below, angled upward" moves the heart and diaphragm onto the list and keeps them there.',source_ref:STD}),
base({id:'itm-7.INT.003',type:'mc',chapter:7,block:'7.INT',objective:'obj-7.INT.a',parent:'itm-7.INT.000',high_stakes:true,
 stem:'Blood pressure 118/78, pulse 118 and thready, cool and pale. How do you read that?',
 options:[opt('a','Compensated shock — pressure held up by tachycardia and vasoconstriction, which are both visible',true,'Three findings agree; only the pressure has not moved.'),
  opt('b','Adequately perfused, since the pressure is normal',false,'The exact error 7.5 is built around.'),
  opt('c','Anxiety alone',false,'He is frightened, and the skin and pulse are not explained by that.'),
  opt('d','No conclusion is possible without a lactate',false,'The bedside findings are conclusive enough to act on.')],
 explanation_md:'A 26-year-old compensates well and for a long time. When his pressure finally moves, it will move fast.',source_ref:STD}),
base({id:'itm-7.INT.004',type:'mc',chapter:7,block:'7.INT',objective:'obj-7.INT.a',parent:'itm-7.INT.000',
 stem:'Which component of perfusion has failed here?',
 options:[opt('a','Volume — he is bleeding, into the chest, the abdomen, or both',true,'Pump and vessels are intact; the container is emptying.'),
  opt('b','Pump — the heart is failing',false,'Possible if the heart is injured, and the presentation fits volume loss.'),
  opt('c','Vessels — widespread vasodilation',false,'His vessels are constricted, which is why he is cool and pale.'),
  opt('d','None — perfusion is adequate',false,'Three findings say otherwise.')],
 explanation_md:'Naming the component is what makes the next decision obvious: this patient needs the bleeding stopped by somebody with an operating room.',source_ref:STD}),
base({id:'itm-7.INT.005',type:'mc',chapter:7,block:'7.INT',objective:'obj-7.INT.a',parent:'itm-7.INT.000',high_stakes:true,
 stem:'Somebody hands you a cervical collar. What do you do with it?',
 options:[opt('a','Decline it — there is no role for spinal motion restriction in penetrating trauma',true,'Chapter 6 said it, and this is the call it was written for.'),
  opt('b','Apply it, since the wound is near the torso',false,'Not an indication, and it obscures the neck.'),
  opt('c','Apply it because he was in a fight and may have fallen',false,'He has no findings and the trauma is penetrating.'),
  opt('d','Apply it only for the transport',false,'The objection is the same either way.')],
 explanation_md:'It costs time he does not have and buys nothing. If somebody insists, say the reason: it is joint national guidance, not a preference.',source_ref:STD}),
base({id:'itm-7.INT.006',type:'mc',chapter:7,block:'7.INT',objective:'obj-7.INT.a',parent:'itm-7.INT.000',high_stakes:true,
 stem:'Eight minutes to an emergency department with no surgical service, or twenty-two to the trauma center. Which?',
 options:[opt('a','The trauma center, if protocol directs it — the nearer hospital would have to transfer him anyway',true,'Chapter 1: the nearest door is not the same as the definitive one.'),
  opt('b','The nearer hospital, because he is unstable',false,'Stabilize and transfer costs him more time than the extra fourteen minutes.'),
  opt('c','The nearer hospital, because it is closer',false,'Proximity is a default, not a rule.'),
  opt('d','Whichever the patient prefers',false,'Preference has little room in a time-critical bleeding patient.')],
 explanation_md:'His problem is bleeding into a body cavity. The only thing that fixes it is a surgeon, and one hospital has one.',source_ref:STD}),
base({id:'itm-7.INT.007',type:'mc',chapter:7,block:'7.INT',objective:'obj-7.INT.a',parent:'itm-7.INT.000',
 stem:'What should the receiving team be told about the wound itself?',
 options:[opt('a','Location by landmark and plane, and the reported angle of the track',true,'Left mid-clavicular line, two finger-widths below the nipple, angled upward from below.'),
  opt('b','That there is a stab wound to the chest',false,'True and it discards the two facts that predict the injury.'),
  opt('c','The size of the blade',false,'Rarely known and less useful than the track.'),
  opt('d','That the wound looks superficial',false,'You cannot know that, and saying it is actively misleading.')],
 explanation_md:'Chapter 7 and chapter 4 meet here. Precise location plus direction is a prediction the surgical team can act on before he arrives.',source_ref:STD}),
base({id:'itm-7.INT.008',type:'mc',chapter:7,block:'7.INT',objective:'obj-7.INT.a',parent:'itm-7.INT.000',bloom:'analyze',
 stem:'What did anatomy actually contribute to this call?',
 options:[opt('a','It turned one hole in the skin into a list of structures to expect and a reason to bypass the nearer hospital',true,'Cavity, organs, trajectory, and the perfusion component that is failing.'),
  opt('b','It provided a diagnosis',false,'You are not diagnosing; you are predicting.'),
  opt('c','It determined the drug therapy',false,'Not the contribution here.'),
  opt('d','Nothing — the decisions were protocol-driven',false,'The protocol tells you what to do once you know what you are looking at.')],
 explanation_md:'That is the case for this chapter. Anatomy is not decoration around the treatment; it is what tells you which treatment the patient is going to need.',source_ref:STD}),
];

export const blocks=[
{id:'7.1',chapter:7,title:'Position and directional terms',learner_title:'Saying where',
 objectives:['obj-7.1.a'],est_minutes:6,
 cold_open:{text:'Your chart says "wound to the inside of the right leg". Three hours later a nurse reassesses and writes that it is unchanged. Neither of you can be sure you were looking at the same thing, and the word doing all the damage is "inside".',
  decision_point:'What should it have said?'},
 pretest_item:'itm-7.1.001',
 screens:[
  {id:'scr-7.1.1',body_md:'**Everything is described from the anatomical position**: standing, facing forward, arms at the sides, palms forward.\n\nNobody is ever found like that. Everybody describes from it, because otherwise "the front of the arm" depends on which way the arm happens to be turned.\n\nIt is a convention, and its whole value is that everybody starts from the same one, every time.',figure:null},
  {id:'scr-7.1.2',body_md:'**Four pairs carry most of it.** Anterior and posterior — front and back. Medial and lateral — toward the midline and away from it. Proximal and distal — nearer the trunk and further along a limb. Superior and inferior — above and below.\n\nProximal and distal are limb terms, which is what "distal pulse" means — the one further out along the limb than the injury you are worried about.',figure:null},
  {id:'scr-7.1.3',body_md:'**Left and right are always the patient’s.** The commonest handover error is describing a limb as you are looking at it, from the front, and reversing it.\n\nAnd in the anatomical position the thumb side is lateral — so a wound on the thumb side of the left forearm is on its lateral aspect, whichever way the arm was lying when you found it.',figure:null},
  {id:'scr-7.1.4',body_md:'**Three planes.** Sagittal divides left from right, midsagittal into equal halves. Frontal divides front from back. Transverse divides upper from lower.\n\nThat is what lets "right of midline, at the fourth rib" mean one place rather than a general area of chest.',figure:null},
  {id:'scr-7.1.5',body_md:'**The test is whether a stranger would go to the same place.** Landmark, side, plane, level.\n\nFour things — landmark, side, plane, level. This is not pedantry. Serial assessment only works if two people examined the same thing, and "unchanged" is a dangerous word when they did not. Write it so a stranger could find it.',figure:null}],
 inline_checks:['itm-7.1.003','itm-7.1.007'],
 quiz:['itm-7.1.002','itm-7.1.004','itm-7.1.005','itm-7.1.006','itm-7.1.008'],
 callback_md:'"Medial aspect of the right thigh, mid-shaft" — or wherever it actually was.\n\n"Inside" could mean medial, or it could mean the inner surface of the wound itself, and two readers will resolve it two ways. **The nurse’s "unchanged" is only worth something if you were both looking at the same square inch of leg**, and nothing in that chart guaranteed it.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'7.2',chapter:7,title:'Cavities and regions',learner_title:'What is under the hole',
 objectives:['obj-7.2.a'],est_minutes:8,
 cold_open:{text:'A single stab wound, two finger-widths below the left nipple. Your partner says it is a chest injury. The patient says the blade came from below, angled upward. Both of those statements are about to matter more than the size of the wound.',
  decision_point:'What is under it?'},
 pretest_item:'itm-7.2.008',
 screens:[
  {id:'scr-7.2.1',body_md:'**Four cavities worth carrying.** Cranial holds the brain. Thoracic holds heart and lungs. Abdominal holds liver, spleen, stomach and bowel. Pelvic holds bladder and rectum.\n\nThe abdominal cavity extends upward under the lower ribs, which is why rib fractures are an abdominal question as well as a chest one, and why the lower chest is the hardest area to reason about.',figure:null},
  {id:'scr-7.2.2',body_md:'**The diaphragm is the only boundary in the body that moves several thousand times an hour.** On expiration it rises toward the nipple line.\n\nSo a wound at the same skin level can enter the chest, the abdomen, or both, depending on where in the breathing cycle the patient was. You cannot tell from outside.',figure:null},
  {id:'scr-7.2.3',body_md:'**Four quadrants, named from the patient’s perspective.** Liver and gallbladder right upper. Spleen and stomach left upper. Appendix right lower. Sigmoid colon left lower.\n\nChapter 5 drilled these as words. Here they are a prediction about what is under your hand.',figure:null},
  {id:'scr-7.2.4',body_md:'**Two rib associations to have automatic.** Left lower ribs: spleen. Right lower ribs: liver.\n\nBoth organs bleed heavily, both are high under the rib cage, and neither shows anything on the skin. A fractured lower rib is a circulatory finding waiting to be recognized, and it is usually recognized late, after the pressure has finally moved.',figure:null},
  {id:'scr-7.2.5',body_md:'**You are not diagnosing.** You are converting a hole in the skin into a list of structures the track may have crossed, and then looking for those findings.\n\nThat list is also what you hand over. "Left mid-clavicular, below the nipple, angled upward" tells a surgical team far more than "stab wound to the chest". The extra eight words are the whole prediction.',figure:null}],
 inline_checks:['itm-7.2.004','itm-7.2.005'],
 quiz:['itm-7.2.001','itm-7.2.002','itm-7.2.003','itm-7.2.006','itm-7.2.007'],
 callback_md:'Lung and pleural space. Spleen, sitting high on the left under those ribs. The diaphragm itself, if the track crossed it. And — given an upward angle from below on the left — the heart, which does not come off the list until somebody with imaging takes it off.\n\n**Your partner is not wrong, just incomplete.** It is a chest injury, and it may be an abdominal one, and the two facts that told you so were the level and the angle.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'7.3',chapter:7,title:'From cell to system',learner_title:'The orientation map',
 objectives:['obj-7.3.a'],est_minutes:6,
 cold_open:{text:'Cold, mottled skin. A capillary refill you count out to four seconds. Confusion that the family says started this afternoon. Three findings, in three different organ systems, and one cause underneath all of them that you cannot see, cannot measure with anything on the truck, and cannot treat directly.',
  decision_point:'What are those three findings actually telling you?'},
 pretest_item:'itm-7.3.001',
 screens:[
  {id:'scr-7.3.1',body_md:'**This block is orientation, and the series treats it that way.** It is tagged context rather than core, which means it is read and used rather than drilled in the review queue.\n\nNone of it changes a decision on its own. All of it makes the next four blocks make sense, and it is worth ten minutes once rather than ten minutes a week.',figure:null},
  {id:'scr-7.3.2',body_md:'**Cells, tissues, organs, systems, organism.** Each level is built from the one below it.\n\nThe direction is the useful part: injury happens at the small scale and presents at the large one. You will never observe a cell. You observe the function that enough damaged cells have stopped performing, which is always at organ level or higher.',figure:null},
  {id:'scr-7.3.3',body_md:'**Every cell needs four things continuously.** Oxygen delivered by perfusion. Fuel. Removal of waste. And an environment held within a narrow range.\n\nEvery emergency in this course is one of those four failing somewhere. That sentence is what this block exists to install, and it is the only thing from this block you will use daily.',figure:null},
  {id:'scr-7.3.4',body_md:'**Homeostasis is active, not passive.** It costs energy continuously, and in a sick patient you can watch it working: the tachycardia, the cool peripheries, the raised respiratory rate.\n\nWhen compensation stops being visible, it has usually stopped working rather than stopped being needed — which is the most dangerous moment on any of these calls.',figure:null},
  {id:'scr-7.3.5',body_md:'**Two systems form the delivery chain**: respiratory gets oxygen in, cardiovascular moves it. Everything else regulates, supplies or clears.\n\nSo any failure of oxygen delivery is somewhere on that chain, and naming where is most of what prehospital assessment consists of. Air in, blood around, and one of the two has failed.',figure:null}],
 inline_checks:['itm-7.3.004','itm-7.3.007'],
 quiz:['itm-7.3.002','itm-7.3.003','itm-7.3.005','itm-7.3.006','itm-7.3.008'],
 callback_md:'That delivery has failed — and the three findings are three organ systems reporting the same shortage.\n\nThe skin is being sacrificed to protect the core. The refill is the peripheral circulation giving up. The confusion is the brain running short. **One failure, three reports, and nothing you can see is the thing that is actually wrong.**\n\nThat is why this block is the map rather than the destination, and why chapter 8 starts exactly here.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'7.4',chapter:7,title:'Ventilation and respiration',learner_title:'Moving air is not the same as exchanging gas',
 objectives:['obj-7.4.a'],est_minutes:8,
 cold_open:{text:'Two patients. One is breathing four times a minute and moving good volumes when he does. The other is breathing twenty-eight times a minute, moving air beautifully, and saturating at 84 per cent. Both are in trouble and they do not have the same problem.',
  decision_point:'What is the difference?'},
 pretest_item:'itm-7.4.001',
 screens:[
  {id:'scr-7.4.1',body_md:'**Ventilation is air moving in and out. Respiration is gas crossing a membrane.** They are not the same word and they do not fail together.\n\nA patient can move air beautifully and remain profoundly hypoxic. Keeping the two separate is what lets you notice that rather than being reassured by chest movement.\n\nOne needs air moved for them. The other needs the gas to cross, and moving more air does not achieve it. Deciding which one you are looking at is the first move on every breathless patient.',figure:null},
  {id:'scr-7.4.2',body_md:'**Nothing pulls air in.** The diaphragm and chest wall enlarge the thorax, pressure inside drops below atmospheric, and air moves down the gradient. The lungs are passive.\n\nWhich is why an open chest wound breaks breathing: the seal that allowed a negative pressure has gone, and enlarging the chest no longer moves anything.',figure:null},
  {id:'scr-7.4.3',body_md:'**Gas exchange needs four things.** Air reaching the alveolus. Blood reaching the capillary beside it. A membrane thin enough to cross. And a gradient to cross down — which is what supplemental oxygen increases.\n\nEvery respiratory emergency is one of those four failing, and usually it is obvious which once you go looking.',figure:null},
  {id:'scr-7.4.4',body_md:'**Rate without depth moves very little.** Dead space fills first on every breath, so a rapid shallow pattern can ventilate almost nothing.\n\nCount the rate, then watch the chest. Carbon dioxide clearance in particular depends almost entirely on how much air moves per minute, not how often something happens.',figure:null},
  {id:'scr-7.4.5',body_md:'**Carbon dioxide is the primary drive to breathe** in most people, sensed centrally. Which is why someone who is not ventilating enough builds up carbon dioxide long before their saturation falls.\n\nAnd a pulse oximeter cannot tell oxygen from carbon monoxide on hemoglobin. In a suspected exposure, a normal number is not reassurance.',figure:null}],
 inline_checks:['itm-7.4.005','itm-7.4.007'],
 quiz:['itm-7.4.002','itm-7.4.003','itm-7.4.004','itm-7.4.006','itm-7.4.008'],
 callback_md:'The first is a ventilation problem: air is not moving, and the fix is to move it for him.\n\nThe second is an oxygenation problem: air is moving perfectly well and the gas is not crossing. Ventilating him harder achieves very little; the failure is at the membrane.\n\n**Two words, two entirely different interventions**, and the only thing that distinguishes them at the bedside is having kept them apart in your head.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'7.5',chapter:7,title:'Perfusion',learner_title:'Pump, volume, vessels',
 objectives:['obj-7.5.a'],est_minutes:8,
 cold_open:{text:'A 26-year-old, anxious and asking the same question twice, pulse 118 and thready, skin cool and pale, capillary refill slow. Then the cuff finishes and reads 118 over 76. Your partner says the number out loud, and you watch his shoulders come down about an inch.',
  decision_point:'Should he?'},
 pretest_item:'itm-7.5.001',
 screens:[
  {id:'scr-7.5.1',body_md:'**Perfusion needs three things**: a working pump, enough volume, and vessels of an appropriate size. Pump, volume, container.\n\nEvery shock state is one of those three failing, and naming which one is the most useful thing you can do with the patient in front of you.',figure:null},
  {id:'scr-7.5.2',body_md:'**The category decides the treatment.** Hemorrhage and dehydration empty the container. A failed heart is a pump problem. Anaphylaxis and sepsis enlarge the container beyond the volume in it.\n\nFluid helps an empty container. It does very little for a failed pump, and it is chasing a moving target in a dilated one. Name the category before you reach for anything.',figure:null},
  {id:'scr-7.5.3',body_md:'**Blood pressure is the last thing to go.** Compensation raises the heart rate and constricts vessels, holding pressure up until the loss is large — especially in the young.\n\nSo a normal pressure is not evidence of adequate perfusion. It is frequently evidence of successful compensation, which is a different thing entirely, and it has a limit you cannot see coming.',figure:null},
  {id:'scr-7.5.4',body_md:'**Watch what compensation costs instead.** Tachycardia at rest. Cool, pale or mottled peripheries. Delayed capillary refill. Anxiety or restlessness as cerebral perfusion falls.\n\nFour findings, none of which needs a monitor, and all of which appear before the pressure moves. Look for them deliberately rather than waiting for a number, because the number is the one that will reassure you wrongly.',figure:null},
  {id:'scr-7.5.5',body_md:'**Delivery is flow times carriage.** A patient with good flow and little hemoglobin still starves tissue, which is why saturation — a percentage — can read 100 per cent in someone who is bleeding to death.\n\nAnd most circulating volume sits on the venous side, which is why vasoconstriction can mask real loss for a while.',figure:null}],
 inline_checks:['itm-7.5.005','itm-7.5.007'],
 quiz:['itm-7.5.002','itm-7.5.003','itm-7.5.004','itm-7.5.006','itm-7.5.008'],
 callback_md:'No.\n\nEvery finding except the pressure points one way: the pump is racing, the container is being squeezed shut, and the brain is short. That is compensation working, and it works right up until it does not.\n\n**In a 26-year-old it can hold a normal pressure through a very large loss**, and when it finally fails the number will not drift down gently. Treat the four findings, not the one that has not moved yet.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'7.6',chapter:7,title:'Nervous and musculoskeletal',learner_title:'Reading a deficit',
 objectives:['obj-7.6.a'],est_minutes:7,
 cold_open:{text:'Two patients, both with weakness. One has a drooping face and a weak arm on the same side. The other has numb, weak legs after a fall and perfectly normal arms. Neither needs a scan for you to say something useful about where the problem is.',
  decision_point:'What can you say?'},
 pretest_item:'itm-7.6.001',
 screens:[
  {id:'scr-7.6.1',body_md:'**Central or peripheral.** Brain and spinal cord, or everything running out from them. Where the lesion sits determines what the deficit looks like, and the pattern is usually visible from the doorway.\n\nOne-sided findings involving the face or speech point centrally. Findings below a level, or following one nerve, point at the cord or a peripheral nerve.',figure:null},
  {id:'scr-7.6.2',body_md:'**Bilateral, symmetrical, and everything below a line is the cord.** Weak numb legs with normal arms locates the problem without any imaging at all.\n\nThat is anatomy telling you where to look — not what to call it. Naming the diagnosis is somebody else’s job; locating it is yours and it changes what you do — the destination most of all.',figure:null},
  {id:'scr-7.6.3',body_md:'**The autonomic system is what "looks unwell" consists of.** Heart rate and force, vessel diameter, sweating, pupil size.\n\nAll four are visible without equipment, and together they are the sympathetic response you met in chapter 2 and the compensation you met in 7.5, seen from the nervous side. One system, three chapters, three different names for it.',figure:null},
  {id:'scr-7.6.4',body_md:'**The skeleton supports, moves, protects and makes blood.** The protective function is the clinical one — a broken rib matters because of what is beneath it.\n\nAnd a femur fracture bleeds. It is a large bone with a rich supply, the thigh holds a great deal, and none of it is visible from outside.',figure:null},
  {id:'scr-7.6.5',body_md:'**Artery and nerve run close to the bone.** So check distal pulse, movement and sensation before splinting and again afterward, and write both down.\n\nA deficit that was not there before the splint is a finding about the splint. You cannot know that without the first check, which is why it is written down before anything is applied.',figure:null}],
 inline_checks:['itm-7.6.004','itm-7.6.007'],
 quiz:['itm-7.6.002','itm-7.6.003','itm-7.6.005','itm-7.6.006','itm-7.6.008'],
 callback_md:'A great deal.\n\nThe first is one-sided and involves the face — that is central, and it is a brain until proved otherwise. The second is bilateral, symmetrical and below a level, with normal arms above it — that is the cord, and the fall is the mechanism.\n\n**Neither needed a scan to be localized.** Both needed somebody to notice which pattern they were looking at, which is the only reason this block exists.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'7.7',chapter:7,title:'Upper airway anatomy',learner_title:'The path an adjunct has to follow',
 objectives:['obj-7.7.a'],est_minutes:8,
 cold_open:{text:'An unresponsive adult, snoring, with no chest injury and a clear scene. Your partner reaches for an oropharyngeal airway. You have not yet touched the patient’s head, and the sound is already telling you where the obstruction is.',
  decision_point:'What should happen first?'},
 pretest_item:'itm-7.7.002',
 screens:[
  {id:'scr-7.7.1',body_md:'**Top to bottom**: the nose leads to the nasopharynx, the mouth to the oropharynx, both meet in the pharynx, the epiglottis guards the entrance to the larynx, and the trachea descends from it.\n\nAny adjunct you place has to follow that path without catching on any of it. That is why the anatomy is worth having: it is the route your equipment travels, and you cannot see any of it.',figure:null},
  {id:'scr-7.7.2',body_md:'**The tongue is the commonest obstruction in an unresponsive patient**, because the muscle tone holding it forward is lost with consciousness.\n\nSo position comes before equipment: head tilt and chin lift, or a jaw thrust where that is indicated. Snoring is a positional sound, and position often fixes it before anything is opened or unwrapped.',figure:null},
  {id:'scr-7.7.3',body_md:'**Size the adjunct, do not estimate it.** An oropharyngeal airway is measured from the corner of the mouth to the angle of the jaw or the earlobe.\n\nToo short pushes the tongue back. Too long can reach the larynx. Both errors make the airway worse rather than leaving it unchanged.',figure:null},
  {id:'scr-7.7.4',body_md:'**A child’s airway occludes sooner for four anatomical reasons**: a proportionally larger tongue, narrower passages where swelling costs more flow, a large occiput that flexes the neck when supine, and softer tissues that compress.\n\nChapter 9 met these as handling problems. This is the same list from underneath.',figure:null},
  {id:'scr-7.7.5',body_md:'**Air and food share a corridor**, and the epiglottis is what normally keeps them separate. It fails when consciousness does.\n\nThat single fact is why aspiration is possible, why suction is kept within reach, and why neither adjunct protects the airway — they hold a path open, and nothing more. Suction and the ability to roll a patient are what address the rest.',figure:null}],
 inline_checks:['itm-7.7.004','itm-7.7.008'],
 quiz:['itm-7.7.001','itm-7.7.003','itm-7.7.005','itm-7.7.006','itm-7.7.007'],
 callback_md:'Open the airway with position first.\n\nSnoring is the sound of the tongue against the posterior pharynx, and in an unresponsive adult that is the commonest obstruction there is. A head tilt and chin lift may clear it entirely, and it takes no equipment and no sizing.\n\n**Then size an adjunct if it is still needed** — corner of the mouth to the angle of the jaw. Reaching for the device first is how a too-short airway ends up holding the tongue where it already was.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'7.8',chapter:7,title:'What to look up rather than memorize',learner_title:'Which list does this go on?',
 objectives:['obj-7.8.a'],est_minutes:6,
 cold_open:{text:'A course asks you to memorize every carpal bone and the arterial supply of the pancreas. Neither will ever change anything you do. Meanwhile a colleague cannot say which three things perfusion needs, and has a patient in shock in front of him.',
  decision_point:'Which list does a fact belong on?'},
 pretest_item:'itm-7.8.001',
 screens:[
  {id:'scr-7.8.1',body_md:'**The test is time pressure, not importance.** Will you need this in the seconds before you act, with nothing to reach for?\n\nPlenty of important anatomy fails that test. A drug dose given under pressure belongs in memory *and* in a reference. An organ’s blood supply belongs in a reference alone, however satisfying it is to know, and however often it appears in a textbook chapter.',figure:null},
  {id:'scr-7.8.2',body_md:'**From this chapter, four things belong in memory.** Which organs sit in which quadrant. Pump, volume and vessels. The upper airway structures in order. And the difference between ventilation and respiration.\n\nEach one changes an action within a minute of arriving at a patient, which is the only reason any of them is on the list.',figure:null},
  {id:'scr-7.8.3',body_md:'**This block is tagged reference for the same reason.** Endocrine, digestive, renal and integumentary detail beyond what perfusion and assessment require is present, used where relevant, and not queued for repetition.\n\nNot because those systems do not matter, but because the decisions depending on them are few and the detail is large.',figure:null},
  {id:'scr-7.8.4',body_md:'**Carrying a reference is not weak knowledge.** Reading a value under pressure is more reliable than recalling it, and the error you avoid belongs to the patient rather than to your pride.\n\nIt is chapter 1 in another form: saying you will check is the professional act, not the embarrassing one, and everyone in the room already knows which it is.',figure:null},
  {id:'scr-7.8.5',body_md:'**Know when your reference was last updated.** A superseded value read confidently is worse than no value at all, and print ages fastest.\n\nAnd notice when you have to look up something that belongs in memory. That is not a failure — it is information about tonight’s revision, and it is more useful than any score you will get on a practice test.',figure:null}],
 inline_checks:['itm-7.8.005','itm-7.8.006'],
 quiz:['itm-7.8.002','itm-7.8.003','itm-7.8.004','itm-7.8.007','itm-7.8.008'],
 callback_md:'On the memory list: anything that changes what your hands do in the next sixty seconds.\n\nOn the reference list: everything else, however respectable it looks in a textbook.\n\n**The carpal bones have never changed a prehospital decision. "Pump, volume, vessels" changes one on every shock patient** — and the colleague standing over that patient needed exactly one of those two lists.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'7.INT',chapter:7,title:'Integration — one hole in the skin',learner_title:'Anatomy doing the work',
 objectives:['obj-7.INT.a'],est_minutes:10,
 cold_open:{text:'A single stab wound tells you almost nothing on its own. A stab wound with a level, a side and a direction tells you which structures to expect, which component of perfusion is failing, and which hospital can actually fix it — before anyone has laid a hand on the patient.',
  decision_point:'How much can anatomy alone give you?'},
 pretest_item:null,
 screens:[
  {id:'scr-7.INT.1',body_md:'**Four questions, answered from anatomy.**\n\nWhich cavities could this have entered? Which structures lie along that track? Which component of perfusion is failing? And what does the receiving team need to be told to be ready?\n\nWhat follows is one call. Every answer comes from this chapter, and one of them decides which hospital he goes to.',figure:null}],
 inline_checks:[],
 quiz:['itm-7.INT.000'],
 callback_md:'A great deal, as it turns out.\n\nA moving diaphragm made it two cavities rather than one. An upward angle from the left put lung, spleen, diaphragm and heart on the list and kept them there. Four bedside findings against one unmoved blood pressure named the failing component as volume. And volume loss into a body cavity is fixed by a surgeon, which is what sent him past the nearer hospital.\n\n**None of that required a monitor, and all of it came from where the hole was and which way it went.**',
 local_overlay:'ks-amr-kc',version:'1.0.0'}
];
