// Chapter 9 — Life Span Development.
// The vital-range block, 9.6, carries the two sources recorded in
// aemt/src/DECISIONS.md and the disagreement between them: the Fleming centiles
// for heart and respiratory rate, the 2025 AHA/AAP thresholds for pressure, and
// an evidence flag on the gap between the measured centiles and the course
// tables that were in circulation when they were measured.
const STD='NHTSA National EMS Education Standards (2021) — Preparatory: Life Span Development.';
const FLEM='Fleming S, Thompson M, Stevens R, et al. Normal ranges of heart rate and respiratory rate in children from birth to 18 years of age: a systematic review of observational studies. Lancet 2011;377:1011–18.';
const PALS='Part 8: Pediatric Advanced Life Support: 2025 American Heart Association and American Academy of Pediatrics Guidelines for CPR and ECC. Circulation, October 2025.';
const BEERS='American Geriatrics Society Beers Criteria for potentially inappropriate medication use in older adults (2023 update).';
const DEV='Developmental stage theory as presented in the Education Standards (Erikson, Piaget), with the evidence status of the stage models noted where it matters.';

const opt=(id,text,correct,rationale)=>({id,text,correct,rationale});
const base=(o)=>({stimulus:{kind:'none',ref:null},bloom:'apply',nremt_domain:'ems_operations',
  cj_step:null,difficulty_seed:0.5,high_stakes:false,
  version:'1.0.0',...o});

export const objectives=[
 {id:'obj-9.1.a',chapter:9,tier:'core',text:'Describe the anatomy and physiology of infancy that changes how you assess and treat',
  enables:'Handle an airway and a temperature that behave nothing like an adult’s'},
 {id:'obj-9.2.a',chapter:9,tier:'core',text:'Adapt assessment for toddlers and preschool children',
  enables:'Get an examination out of a two-year-old who has decided against you'},
 {id:'obj-9.3.a',chapter:9,tier:'core',text:'Adapt assessment and communication for school-age children and adolescents',
  enables:'Ask a sixteen-year-old the question they will not answer in front of a parent'},
 {id:'obj-9.4.a',chapter:9,tier:'context',text:'Describe early and middle adulthood and the changes that begin there',
  enables:'Recognize the decade in which the silent risk factors accumulate'},
 {id:'obj-9.5.a',chapter:9,tier:'core',text:'Apply the physiology of late adulthood, including atypical presentation and polypharmacy',
  enables:'Catch the serious illness that arrives without the symptom you were taught to expect'},
 {id:'obj-9.6.a',chapter:9,tier:'core',text:'Use age-appropriate vital sign ranges, and state what a number in range does and does not establish',
  enables:'Know at a glance whether the number in front of you is the reason to worry'},
 {id:'obj-9.7.a',chapter:9,tier:'context',text:'Use psychosocial development to explain behavior you will meet, while stating the limits of the stage models',
  enables:'Read fear and regression as development rather than as difficulty'},
 {id:'obj-9.8.a',chapter:9,tier:'core',text:'Adapt approach, consent and examination sequence across the life span',
  enables:'Change your approach to fit the patient rather than repeating one that does not work'},
 {id:'obj-9.INT.a',chapter:9,tier:'core',text:'Integrate age-specific physiology, vital ranges and approach on one call',
  enables:'Assess a child and an older adult on the same shift without carrying the wrong template into either'}
];

export const items=[
// ── 9.1 Infancy ───────────────────────────────────────────────────────── 8
base({id:'itm-9.1.001',type:'mc',chapter:9,block:'9.1',objective:'obj-9.1.a',bloom:'understand',high_stakes:true,
 stem:'Why does an infant lose body heat so much faster than an adult?',
 options:[opt('a','A large surface area relative to body mass, thin skin, and little capacity to shiver',true,'All three work in the same direction, and a cold infant deteriorates fast.'),
  opt('b','A higher metabolic rate alone',false,'Metabolic rate is higher and it is not the mechanism of the heat loss.'),
  opt('c','Immature kidneys',false,'Renal immaturity affects fluid handling, not thermoregulation.'),
  opt('d','A slower heart rate',false,'Infant heart rates are faster, not slower.')],
 explanation_md:'Cover the head, close the doors, warm the compartment. Hypothermia in an infant is an injury you can cause during the assessment itself.',source_ref:STD}),
base({id:'itm-9.1.002',type:'mc',chapter:9,block:'9.1',objective:'obj-9.1.a',bloom:'understand',high_stakes:true,
 stem:'You lay a six-month-old flat on a firm surface and the airway sounds obstructed. What is the likely reason?',
 options:[opt('a','The large occiput flexes the neck when supine, closing the airway',true,'A folded towel under the shoulders restores a neutral position.'),
  opt('b','The tongue has fallen back because of the small mandible',false,'Tongue size matters and it is not what the flat surface changed.'),
  opt('c','Gastric distension',false,'Possible after ventilation, not from position alone.'),
  opt('d','Nasal congestion',false,'It would not appear at the moment you laid them down.')],
 explanation_md:'The head is proportionally large, so lying flat flexes the neck. Padding under the shoulders, not under the head, is the fix.',source_ref:STD}),
base({id:'itm-9.1.003',type:'mr',chapter:9,block:'9.1',objective:'obj-9.1.a',bloom:'remember',select_count:[3,4],
 stem:'Select the airway features that make an infant harder to manage than an adult.',
 options:[opt('a','A proportionally large tongue in a small oral cavity',true,'It obstructs easily and is the commonest cause of obstruction.'),
  opt('b','A large occiput that flexes the neck when supine',true,'Position is half of infant airway management.'),
  opt('c','Narrow airways in which small amounts of swelling matter a great deal',true,'Resistance rises steeply as the radius falls.'),
  opt('d','Nasal breathing that is strongly preferred, so a blocked nose is poorly tolerated',true,'Suctioning the nose can transform a distressed infant.'),
  opt('e','A calcified, rigid larynx',false,'The infant larynx is softer and more pliable, not rigid.')],
 explanation_md:'Tongue, position, diameter and nose. Three of the four are fixed by positioning and suction before anything else is reached for.',source_ref:STD}),
base({id:'itm-9.1.004',type:'mc',chapter:9,block:'9.1',objective:'obj-9.1.a',bloom:'analyze',
 stem:'Infants are often taught as obligate nasal breathers. How accurate is that?',
 options:[opt('a','Overstated — they strongly prefer nasal breathing, and most can breathe orally when the nose is blocked',true,'"Preferential" is the more accurate word; obstruction is still poorly tolerated.'),
  opt('b','Exactly right — an infant cannot breathe through the mouth at all',false,'Most can, which is why the absolute version is wrong.'),
  opt('c','Wrong — infants breathe orally by preference',false,'Nasal breathing is genuinely preferred.'),
  opt('d','Wrong — nasal obstruction is of no consequence in infants',false,'It matters clinically, which is why the teaching persists.')],
 explanation_md:'The clinical action is unchanged: clear the nose. The accurate word is preferential, and knowing the difference stops you assuming an infant with a blocked nose cannot compensate at all.',source_ref:STD}),
base({id:'itm-9.1.005',type:'options_box',chapter:9,block:'9.1',objective:'obj-9.1.a',bloom:'analyze',high_stakes:true,
 stem:'What does each fontanelle finding suggest in a quiet infant?',
 columns:[{id:'dry',label:'Suggests dehydration'},{id:'icp',label:'Suggests raised intracranial pressure'},{id:'norm',label:'Expected finding'}],
 rows:[{id:'r1',label:'Sunken anterior fontanelle',answer:'dry'},
  {id:'r2',label:'Bulging, tense fontanelle in an infant who is not crying',answer:'icp'},
  {id:'r3',label:'A soft, flat fontanelle that is open at four months',answer:'norm'},
  {id:'r4',label:'A posterior fontanelle already closed at four months',answer:'norm'}],
 options:[],
 explanation_md:'The posterior fontanelle closes at around two to three months and the anterior between roughly nine and eighteen. A bulge assessed while the infant is crying tells you nothing.',source_ref:STD}),
base({id:'itm-9.1.006',type:'mc',chapter:9,block:'9.1',objective:'obj-9.1.a',bloom:'remember',
 stem:'What happens to birth weight over the first year?',
 options:[opt('a','It roughly doubles by four to six months and triples by one year',true,'A useful check on whether growth has gone wrong.'),
  opt('b','It doubles by one year',false,'That understates normal growth considerably.'),
  opt('c','It quadruples by six months',false,'Far faster than normal growth.'),
  opt('d','It stays within ten per cent of birth weight for the first year',false,'That would be a serious failure to thrive.')],
 explanation_md:'Worth carrying because a parent can usually tell you the birth weight, and the comparison is sometimes the first sign that something has been wrong for months.',source_ref:STD}),
base({id:'itm-9.1.007',type:'mc',chapter:9,block:'9.1',objective:'obj-9.1.a',high_stakes:true,
 stem:'A four-month-old is breathing at 60 and drawing in below the ribs. The parents say she has been feeding poorly. What does the feeding history add?',
 options:[opt('a','Poor feeding is how an infant reports exhaustion — it suggests the work of breathing is already unsustainable',true,'Feeding is strenuous. An infant too tired to feed is too tired to keep breathing like that.'),
  opt('b','Nothing — feeding is a gastrointestinal matter',false,'In infants it is one of the most useful respiratory questions there is.'),
  opt('c','It suggests a viral gastrointestinal illness',false,'It could accompany one, and the respiratory findings are what dominate.'),
  opt('d','It indicates dehydration only',false,'Dehydration may follow; the exhaustion is the finding.')],
 explanation_md:'Ask about feeding and about wet diapers on every unwell infant. They are the two questions that turn "seems off" into a measurable history.',source_ref:STD}),
base({id:'itm-9.1.008',type:'mc',chapter:9,block:'9.1',objective:'obj-9.1.a',bloom:'analyze',
 stem:'Why does an infant compensate for hypoxia mainly by increasing rate rather than depth?',
 options:[opt('a','The chest wall is compliant and the diaphragm does most of the work, so depth cannot increase much',true,'Rate is the lever available, and it tires quickly.'),
  opt('b','The lungs are proportionally larger',false,'They are not, and it would not change the mechanism.'),
  opt('c','Because the airway is narrow',false,'Airway diameter affects resistance, not the compensation strategy.'),
  opt('d','Because oxygen demand is lower',false,'It is higher per kilogram, not lower.')],
 explanation_md:'That is why a rising rate in a tiring infant is ominous, and why a suddenly falling rate in the same infant is worse rather than better.',source_ref:STD}),
// ── 9.2 Toddler and preschool ─────────────────────────────────────────── 8
base({id:'itm-9.2.001',type:'mc',chapter:9,block:'9.2',objective:'obj-9.2.a',bloom:'understand',
 stem:'What is the most effective way to begin examining a frightened three-year-old?',
 options:[opt('a','Start at the feet and work upward, with the child on a parent’s lap',true,'Toe-to-head keeps the frightening part until last, and the parent is the safe place.'),
  opt('b','Head to toe, as with an adult',false,'Touching the face first is what ends the examination.'),
  opt('c','Separate the child from the parent so they concentrate',false,'It removes the only thing making this tolerable.'),
  opt('d','Complete the whole examination in the ambulance',false,'Moving them does not make them less frightened.')],
 explanation_md:'Reverse the order, keep the parent in contact, and show the equipment on the parent first. You get more examination in less time.',source_ref:STD}),
base({id:'itm-9.2.002',type:'mc',chapter:9,block:'9.2',objective:'obj-9.2.a',high_stakes:true,
 stem:'A two-year-old will not answer any of your questions. What does that tell you clinically?',
 options:[opt('a','Very little on its own — but a toddler who does not resist an examination at all is a concern',true,'The child who ignores you is normal. The one who does not object is often sick.'),
  opt('b','That the child has an altered mental status',false,'Not answering a stranger is age-appropriate.'),
  opt('c','That the parents should answer everything instead',false,'They corroborate; the child is still observed.'),
  opt('d','That the child is in severe pain',false,'It is not a pain indicator.')],
 explanation_md:'Toddlers are supposed to object. Compliance with a stranger prodding them is one of the more reliable soft signs of serious illness at that age.',source_ref:STD}),
base({id:'itm-9.2.003',type:'mr',chapter:9,block:'9.2',objective:'obj-9.2.a',select_count:[3,4],
 stem:'Select what genuinely helps when assessing a toddler.',
 options:[opt('a','Getting down to their eye level rather than standing over them',true,'Height is intimidating at that size.'),
  opt('b','Keeping a parent in physical contact throughout',true,'The parent is the equipment that makes the rest work.'),
  opt('c','Letting them handle the stethoscope before you use it',true,'Familiarity removes most of the fear of the object.'),
  opt('d','Offering real choices where there are any — which arm, which finger',true,'Autonomy is the developmental drive at this age; use it.'),
  opt('e','Telling them the procedure will not hurt when it will',false,'You spend all your credibility at once, and the next crew inherits the result.')],
 explanation_md:'Eye level, parent, familiarity, and a genuine choice. Offering a choice that is not real is worse than offering none.',source_ref:STD}),
base({id:'itm-9.2.004',type:'options_box',chapter:9,block:'9.2',objective:'obj-9.2.a',bloom:'analyze',
 stem:'Expected for a preschool child, or a reason for concern?',
 columns:[{id:'exp',label:'Expected'},{id:'con',label:'Concerning'}],
 rows:[{id:'r1',label:'Crying and pulling away from an unfamiliar person',answer:'exp'},
  {id:'r2',label:'Lying quietly and letting a stranger do anything',answer:'con'},
  {id:'r3',label:'Believing the illness is a punishment for something they did',answer:'exp'},
  {id:'r4',label:'Not consolable by the parent',answer:'con'}],
 options:[],
 explanation_md:'Two of these are development. Two are the child telling you something is wrong without any words, and inconsolability is among the most useful signs at this age.',source_ref:STD}),
base({id:'itm-9.2.005',type:'mc',chapter:9,block:'9.2',objective:'obj-9.2.a',bloom:'understand',
 stem:'A four-year-old asks whether they are sick because they were naughty. What is going on?',
 options:[opt('a','Magical thinking — at this age children commonly link illness to their own behavior',true,'Saying plainly that it is not their fault is a real intervention.'),
  opt('b','A sign of an underlying behavioral disorder',false,'It is developmentally ordinary.'),
  opt('c','Evidence that someone has told them so',false,'It arises without anyone saying it.'),
  opt('d','Confusion from hypoxia',false,'It is a normal cognitive pattern, not an acute change.')],
 explanation_md:'Tell them it is not their fault, in those words. It costs one sentence and it is often the part the parent thanks you for.',source_ref:DEV}),
base({id:'itm-9.2.006',type:'mc',chapter:9,block:'9.2',objective:'obj-9.2.a',bloom:'analyze',high_stakes:true,
 stem:'Why does an injury story that does not fit the child’s developmental stage matter?',
 options:[opt('a','A child who cannot yet perform the action described could not have injured themselves that way',true,'A six-week-old who "rolled off the couch" has not rolled anywhere.'),
  opt('b','Parents misremember timings, so stories rarely fit',false,'Imprecision about time is common; an impossible mechanism is different.'),
  opt('c','It only matters if the injury is severe',false,'Severity is not what makes the mismatch significant.'),
  opt('d','It matters for billing accuracy',false,'Not the reason.')],
 explanation_md:'This is where chapter 3 and this chapter meet: the developmental milestones are what let you recognize an account that cannot be true. Report on suspicion, not proof.',source_ref:STD}),
base({id:'itm-9.2.007',type:'mc',chapter:9,block:'9.2',objective:'obj-9.2.a',bloom:'remember',
 stem:'Roughly when do children begin to walk independently?',
 options:[opt('a','Around 12 months, with wide normal variation either side',true,'Most walk between about nine and fifteen months.'),
  opt('b','Around six months',false,'Sitting unsupported is nearer that age.'),
  opt('c','Around two years',false,'That is late enough to warrant assessment.'),
  opt('d','Around three years',false,'Well outside normal variation.')],
 explanation_md:'You do not need the full milestone chart. You need enough to notice when the story requires a skill the child does not have yet.',source_ref:STD}),
base({id:'itm-9.2.008',type:'mc',chapter:9,block:'9.2',objective:'obj-9.2.a',
 stem:'A toddler is quiet in the parent’s arms and becomes distressed only when moved. What does that suggest?',
 options:[opt('a','Pain that is worse on movement — the behavior is localizing information',true,'What settles and what provokes is how a preverbal child gives you a history.'),
  opt('b','Nothing useful, since the child cannot report pain',false,'This is exactly how they report it.'),
  opt('c','Separation anxiety alone',false,'It would not be movement-specific.'),
  opt('d','That the child is tired',false,'Tiredness does not produce movement-specific distress.')],
 explanation_md:'Watch what the child does rather than asking what they feel. Position of comfort, what provokes crying, and whether the parent can settle them are all history.',source_ref:STD}),

// ── 9.3 School age and adolescence ────────────────────────────────────── 8
base({id:'itm-9.3.001',type:'mc',chapter:9,block:'9.3',objective:'obj-9.3.a',bloom:'understand',high_stakes:true,
 stem:'A sixteen-year-old gives short answers with a parent in the room. What should you do?',
 options:[opt('a','Create a private moment and ask again — routinely, not only when you suspect something',true,'Doing it every time is what stops it signalling suspicion.'),
  opt('b','Accept the answers, since a parent is entitled to be present',false,'You will miss what adolescents systematically do not say in front of parents.'),
  opt('c','Ask the parent to leave permanently',false,'Blunt removal creates conflict; a routine private moment does not.'),
  opt('d','Ask the parent to answer instead',false,'It removes the patient from their own history.')],
 explanation_md:'Pregnancy, substance use, self-harm, sexual activity, violence at home. All of them are systematically underreported in front of a parent, and the private moment is how you find them.',source_ref:STD}),
base({id:'itm-9.3.002',type:'mc',chapter:9,block:'9.3',objective:'obj-9.3.a',bloom:'understand',
 stem:'What should you tell an adolescent about confidentiality before asking sensitive questions?',
 options:[opt('a','What you can keep private and what you cannot, before they answer rather than after',true,'Promising more than you can deliver is the way to lose them entirely.'),
  opt('b','That everything they say is completely confidential',false,'Untrue, and the moment it breaks they will never tell a clinician anything again.'),
  opt('c','Nothing — it will make them suspicious',false,'Being told the rules is what makes disclosure possible.'),
  opt('d','That their parent will be told everything',false,'Not generally true, and it guarantees silence.')],
 explanation_md:'The limits vary by state, which is a local-overlay question. Saying honestly that there are limits, before the answer, is what travels.',source_ref:STD}),
base({id:'itm-9.3.003',type:'mr',chapter:9,block:'9.3',objective:'obj-9.3.a',select_count:[3,4],
 stem:'Select what is developmentally characteristic of adolescence and relevant to your assessment.',
 options:[opt('a','Risk-taking that peaks in the presence of peers',true,'Peer presence changes the risk calculation measurably.'),
  opt('b','Strong concern about privacy and bodily exposure',true,'It shapes how and where you examine.'),
  opt('c','Identity and independence as the central developmental work',true,'Which is why being talked over lands so badly.'),
  opt('d','Reluctance to disclose in front of family',true,'The single most practical fact in this block.'),
  opt('e','An inability to understand explanations of risk',false,'They usually understand it perfectly well and weigh it differently.')],
 explanation_md:'Adolescents typically understand risk. What differs is how it is weighed, especially with an audience — so explaining it as though they cannot follow does not work.',source_ref:STD}),
base({id:'itm-9.3.004',type:'mc',chapter:9,block:'9.3',objective:'obj-9.3.a',high_stakes:true,
 stem:'A nine-year-old asks directly whether they are going to die. What do you say?',
 options:[opt('a','Answer honestly at their level, without promising an outcome you cannot guarantee',true,'School-age children detect evasion easily and trust it less than bad news.'),
  opt('b','Tell them everything will be fine',false,'If it is not, that sentence is the one they remember.'),
  opt('c','Change the subject',false,'They notice, and they conclude the answer is yes.'),
  opt('d','Tell them to ask their parents',false,'It hands the question to someone who is also frightened.')],
 explanation_md:'"I do not know yet. Here is what I am doing about it, and I will tell you what I find." True, reassuring in the only way that lasts, and it keeps them talking to you.',source_ref:STD}),
base({id:'itm-9.3.005',type:'options_box',chapter:9,block:'9.3',objective:'obj-9.3.a',bloom:'analyze',
 stem:'Which approach fits the age?',
 columns:[{id:'sch',label:'School age, 6–12'},{id:'ado',label:'Adolescent, 13–18'}],
 rows:[{id:'r1',label:'Explain each step before doing it and let them help where possible',answer:'sch'},
  {id:'r2',label:'Offer a private moment away from family as a matter of routine',answer:'ado'},
  {id:'r3',label:'Answer direct questions about outcome honestly and simply',answer:'sch'},
  {id:'r4',label:'Address them as the decision-maker about their own body',answer:'ado'}],
 options:[],
 explanation_md:'Both age groups want the truth. What changes is who else is allowed to be in the room while they hear it.',source_ref:STD}),
base({id:'itm-9.3.006',type:'mc',chapter:9,block:'9.3',objective:'obj-9.3.a',bloom:'analyze',
 stem:'Why does peer presence matter clinically at a scene involving adolescents?',
 options:[opt('a','Risk-taking and reluctance to appear frightened both increase with an audience, which changes what they report and accept',true,'Refusals and minimized symptoms both rise in front of friends.'),
  opt('b','It has no measurable effect',false,'The effect is consistent and well described.'),
  opt('c','Peers provide a more accurate history',false,'They may add information; they also change what the patient will say.'),
  opt('d','It only affects behavior after the incident',false,'It affects it during, which is when you are there.')],
 explanation_md:'Move the patient away from the audience before the serious conversation. It is the same maneuver as the private moment from a parent, for a different reason.',source_ref:STD}),
base({id:'itm-9.3.007',type:'mc',chapter:9,block:'9.3',objective:'obj-9.3.a',bloom:'remember',
 stem:'What is the central developmental task of adolescence as usually described?',
 options:[opt('a','Forming an identity and establishing independence',true,'It explains most of what you will meet on these calls.'),
  opt('b','Developing trust in caregivers',false,'That is the task described for infancy.'),
  opt('c','Establishing autonomy over the body’s basic functions',false,'That belongs to the toddler years.'),
  opt('d','Reviewing a life and finding it coherent',false,'That is described in late adulthood.')],
 explanation_md:'Which is why being spoken over, undressed in front of people, or treated as a child is not a minor irritation at this age.',source_ref:DEV}),
base({id:'itm-9.3.008',type:'mc',chapter:9,block:'9.3',objective:'obj-9.3.a',
 stem:'A twelve-year-old is embarrassed about exposure during a trauma assessment. How do you proceed?',
 options:[opt('a','Expose only what you need, when you need it, cover immediately, and say what you are doing first',true,'Modesty is a genuine clinical consideration, not a delay.'),
  opt('b','Expose fully and quickly to save time',false,'It costs cooperation for the rest of the call and is rarely necessary all at once.'),
  opt('c','Skip the areas they are embarrassed about',false,'That is a missed injury, not respect.'),
  opt('d','Wait until the hospital',false,'Some findings cannot wait, and the hospital is not more private.')],
 explanation_md:'Sequential exposure, narrated, with a blanket ready. You lose nothing clinically and keep a cooperative patient.',source_ref:STD}),
// ── 9.4 Early and middle adulthood ────────────────────────────────────── 8
base({id:'itm-9.4.001',type:'mc',chapter:9,block:'9.4',objective:'obj-9.4.a',bloom:'understand',
 stem:'When do most physiological systems reach peak function?',
 options:[opt('a','Around the late twenties to early thirties, with gradual decline afterward',true,'The decline is slow and begins earlier than most people expect.'),
  opt('b','At about age forty',false,'Decline is already under way by then.'),
  opt('c','At about age eighteen',false,'Several systems are still maturing.'),
  opt('d','Function is stable until age sixty',false,'That is not what the physiology does.')],
 explanation_md:'The point is not the number. It is that middle adulthood is where accumulated risk starts producing events, in people who still feel well.',source_ref:STD}),
base({id:'itm-9.4.002',type:'mc',chapter:9,block:'9.4',objective:'obj-9.4.a',high_stakes:true,
 stem:'A 46-year-old with no medical history has chest discomfort and says he is too young for a heart attack. How should that affect you?',
 options:[opt('a','Not at all — middle adulthood is exactly when coronary events begin appearing, often in people who feel well',true,'His reasoning is the commonest reason these patients delay calling.'),
  opt('b','It makes a cardiac cause unlikely at his age',false,'It does not, and agreeing with him is how this call goes wrong.'),
  opt('c','It means the symptom is probably muscular',false,'Age is not a rule-out.'),
  opt('d','It justifies a lower level of care',false,'Nothing here justifies that.')],
 explanation_md:'"Too young" is a belief, not a finding. The people most likely to hold it are the ones who have never been ill before, which is most of this age group.',source_ref:STD}),
base({id:'itm-9.4.003',type:'mr',chapter:9,block:'9.4',objective:'obj-9.4.a',bloom:'remember',select_count:[3,4],
 stem:'Select the changes that characterize middle adulthood.',
 options:[opt('a','Gradual decline in cardiac reserve and maximum heart rate',true,'Slow, and it limits the response to stress.'),
  opt('b','Reduced visual accommodation for near objects',true,'Which is why reading a medication bottle becomes difficult.'),
  opt('c','Accumulating risk factors — weight, blood pressure, glucose, lipids',true,'This is the decade they start producing events.'),
  opt('d','Menopause in women, typically in the late forties to early fifties',true,'With the loss of a cardiovascular risk differential that existed earlier.'),
  opt('e','Loss of the ability to form new memories',false,'Not a feature of normal aging at any age.')],
 explanation_md:'Nothing dramatic happens in this period. Things accumulate, and then one of them presents as an emergency in someone with no history.',source_ref:STD}),
base({id:'itm-9.4.004',type:'options_box',chapter:9,block:'9.4',objective:'obj-9.4.a',bloom:'analyze',
 stem:'Normal aging, or a finding to act on?',
 columns:[{id:'norm',label:'Normal aging'},{id:'find',label:'Act on it'}],
 rows:[{id:'r1',label:'Needing reading glasses at 45',answer:'norm'},
  {id:'r2',label:'New exertional chest discomfort at 45',answer:'find'},
  {id:'r3',label:'Slower recovery from a hard physical effort at 50',answer:'norm'},
  {id:'r4',label:'New confusion at 50',answer:'find'}],
 options:[],
 explanation_md:'Confusion is never normal aging, at any age in this chapter. That sentence is worth carrying into 9.5 intact.',source_ref:STD}),
base({id:'itm-9.4.005',type:'mc',chapter:9,block:'9.4',objective:'obj-9.4.a',bloom:'analyze',
 stem:'Why does a first presentation in middle adulthood often arrive late?',
 options:[opt('a','People with no history do not recognize symptoms as illness, and often reason themselves out of calling',true,'Never having been ill is a risk factor for delay.'),
  opt('b','Symptoms are genuinely milder at this age',false,'They are not reliably milder.'),
  opt('c','Access to care is worse in this group',false,'Access varies and it is not the mechanism.'),
  opt('d','The conditions themselves progress more slowly',false,'They do not.')],
 explanation_md:'It also explains the tone on scene: this person has no template for being a patient, and may be more frightened than they look.',source_ref:STD}),
base({id:'itm-9.4.006',type:'mc',chapter:9,block:'9.4',objective:'obj-9.4.a',bloom:'understand',
 stem:'How should the physiology of a healthy 30-year-old shape your interpretation of vital signs?',
 options:[opt('a','Compensation is efficient, so vital signs can stay normal until a large reserve is gone',true,'A normal blood pressure in a young trauma patient buys you nothing.'),
  opt('b','Vital signs change earlier than in older patients',false,'Younger patients compensate longer, not sooner.'),
  opt('c','Vital signs are unreliable at this age',false,'They are reliable; the issue is when they move.'),
  opt('d','Tachycardia is expected at rest',false,'It is not.')],
 explanation_md:'The young patient who has just become abnormal has usually been compensating for some time. That is the clinical meaning of good reserve.',source_ref:STD}),
base({id:'itm-9.4.007',type:'mc',chapter:9,block:'9.4',objective:'obj-9.4.a',bloom:'remember',
 stem:'What is generally described as the psychosocial work of middle adulthood?',
 options:[opt('a','Contributing to the next generation and to work that outlasts you',true,'Generativity, in the usual description.'),
  opt('b','Establishing identity',false,'That is adolescence.'),
  opt('c','Developing basic trust',false,'That is infancy.'),
  opt('d','Reviewing a life for coherence',false,'That is described in late adulthood.')],
 explanation_md:'Useful mainly for understanding what a patient is frightened of losing — which is frequently their role rather than their life.',source_ref:DEV}),
base({id:'itm-9.4.008',type:'mc',chapter:9,block:'9.4',objective:'obj-9.4.a',
 stem:'A 52-year-old refuses transport because she cannot leave her elderly mother alone. What is the useful response?',
 options:[opt('a','Treat the obstacle as solvable and work it — it is the actual reason for the refusal, not the stated one',true,'Middle adulthood is where people are responsible for two other generations at once.'),
  opt('b','Document the refusal and leave',false,'Chapter 3 asked for more than that, and the obstacle here is fixable.'),
  opt('c','Tell her the risks again, more firmly',false,'She has heard them. The barrier is not information.'),
  opt('d','Ask her to call a family member later',false,'Later is after you have gone.')],
 explanation_md:'A refusal built on a caregiving obligation is often solved by a phone call. Repeating the medical risk addresses a problem she does not have.',source_ref:STD}),

// ── 9.5 Late adulthood ────────────────────────────────────────────────── 8
base({id:'itm-9.5.001',type:'mc',chapter:9,block:'9.5',objective:'obj-9.5.a',bloom:'understand',high_stakes:true,
 stem:'An 84-year-old is weak and short of breath with no chest pain. Why does that not reduce your concern about a cardiac cause?',
 options:[opt('a','Older adults frequently present without chest pain — dyspnea, weakness, confusion or a fall may be the whole presentation',true,'Atypical presentation is common enough at this age to be the expectation rather than the exception.'),
  opt('b','Chest pain is always present but under-reported',false,'It is frequently genuinely absent, not merely unreported.'),
  opt('c','Age does not affect presentation',false,'It affects it substantially.'),
  opt('d','Weakness is a specific cardiac symptom',false,'It is not specific at all, which is the difficulty.')],
 explanation_md:'The textbook picture was drawn from younger patients. In the very old, the absence of the classic symptom carries almost no weight.',source_ref:STD}),
base({id:'itm-9.5.002',type:'mr',chapter:9,block:'9.5',objective:'obj-9.5.a',bloom:'remember',select_count:[4,5],
 stem:'Select the changes of late adulthood that change how you assess and treat.',
 options:[opt('a','Reduced renal and hepatic clearance, so drugs persist longer',true,'The basis of most age-related adverse drug effects.'),
  opt('b','Blunted baroreceptor response, so blood pressure compensates poorly on standing',true,'Which is why a fall may be the presentation of something else.'),
  opt('c','Reduced chest wall compliance and a weaker cough',true,'Secretions are cleared less well and pneumonia presents late.'),
  opt('d','Reduced thirst sensation, so dehydration develops quietly',true,'Frequently the reason for the call, and rarely the complaint.'),
  opt('e','A faster resting heart rate than a young adult',false,'Maximum rate falls with age; resting rate does not rise.')],
 explanation_md:'Every one of these turns a modest insult into a presentation. None of them is a disease, and all of them shorten the distance to one.',source_ref:STD}),
base({id:'itm-9.5.003',type:'mc',chapter:9,block:'9.5',objective:'obj-9.5.a',high_stakes:true,
 stem:'A family says their 79-year-old father is "confused". What is the first thing you need from them?',
 options:[opt('a','What he is normally like — confusion only means something against a known baseline',true,'New confusion is an emergency; long-standing confusion is a history.'),
  opt('b','His medication list',false,'Important, and second.'),
  opt('c','Whether he has dementia',false,'Part of the baseline question, not a substitute for it.'),
  opt('d','When he last ate',false,'Relevant later.')],
 explanation_md:'"Is this how he usually is?" is the highest-yield question on a geriatric call. Without it, an acute delirium and a chronic dementia look identical.',source_ref:STD}),
base({id:'itm-9.5.004',type:'mc',chapter:9,block:'9.5',objective:'obj-9.5.a',bloom:'understand',high_stakes:true,
 stem:'An 81-year-old takes eleven regular medications. Why does the number itself matter?',
 options:[opt('a','Risk of interactions and adverse effects rises with the count, and an adverse drug effect can be the whole reason for the call',true,'Polypharmacy is a presentation in its own right, not just a history to record.'),
  opt('b','It indicates poor medical care',false,'Often it indicates several conditions treated appropriately.'),
  opt('c','It only matters for the receiving hospital',false,'It may be the cause of what you are looking at now.'),
  opt('d','It has no clinical significance',false,'It is one of the most significant findings on the call.')],
 explanation_md:'Bring the medications, or photograph the labels. Published criteria list drugs that are potentially inappropriate in older adults precisely because this is so common.',source_ref:BEERS}),
base({id:'itm-9.5.005',type:'options_box',chapter:9,block:'9.5',objective:'obj-9.5.a',bloom:'analyze',high_stakes:true,
 stem:'Normal aging, or a finding that needs explaining?',
 columns:[{id:'norm',label:'Normal aging'},{id:'find',label:'Needs explaining'}],
 rows:[{id:'r1',label:'Gradual hearing loss over years',answer:'norm'},
  {id:'r2',label:'New confusion over two days',answer:'find'},
  {id:'r3',label:'Thinner, more fragile skin',answer:'norm'},
  {id:'r4',label:'A fall with no clear mechanism',answer:'find'}],
 options:[],
 explanation_md:'Confusion and unexplained falls are never normal aging. Treating either as "just age" is how a treatable cause gets left in the house.',source_ref:STD}),
base({id:'itm-9.5.006',type:'mc',chapter:9,block:'9.5',objective:'obj-9.5.a',bloom:'analyze',
 stem:'Why is a ground-level fall in an older adult treated as more than a mechanical event?',
 options:[opt('a','The fall is often the presentation of something else — infection, arrhythmia, drug effect, dehydration — and the injury may be significant at low energy',true,'Two separate problems arrive in the same call.'),
  opt('b','Because older patients exaggerate injury',false,'They more often minimize it.'),
  opt('c','Because head injury is impossible at low energy',false,'The opposite: it is more likely, not less.'),
  opt('d','Only because of anticoagulation',false,'Anticoagulation matters and is not the whole reason.')],
 explanation_md:'Ask what happened immediately before the fall. "I do not remember" changes the call entirely, and it is the question most often skipped.',source_ref:STD}),
base({id:'itm-9.5.007',type:'mc',chapter:9,block:'9.5',objective:'obj-9.5.a',
 stem:'An 88-year-old with a hip fracture reports pain as 3 out of 10. How should you read that?',
 options:[opt('a','Take it seriously but not as the whole picture — older adults frequently under-report pain, and undertreatment is well documented',true,'Watch the face, the guarding and the movement as well as the number.'),
  opt('b','Treat the number as definitive and withhold analgesia',false,'That is the mechanism by which these patients are undertreated.'),
  opt('c','Assume the fracture is minor',false,'The report does not tell you that.'),
  opt('d','Assume they are confused',false,'Under-reporting is not confusion.')],
 explanation_md:'Stoicism, not wanting to be a burden, and a fear of what admission means all suppress the number. The injury does not care what was reported.',source_ref:STD}),
base({id:'itm-9.5.008',type:'mc',chapter:9,block:'9.5',objective:'obj-9.5.a',bloom:'analyze',
 stem:'Why can an older patient in early shock have a blood pressure that looks acceptable?',
 options:[opt('a','A patient whose usual pressure is high may be profoundly hypotensive at a number that reads as normal',true,'Relative hypotension is invisible unless you ask what their usual pressure is.'),
  opt('b','Blood pressure is more accurate in older patients',false,'Accuracy is not the issue.'),
  opt('c','Shock does not lower blood pressure at this age',false,'It does, from a higher starting point.'),
  opt('d','Older patients compensate better than the young',false,'They compensate considerably worse.')],
 explanation_md:'Ask what their pressure normally runs. A systolic of 110 in someone who lives at 170 is a different number entirely.',source_ref:STD}),
// ── 9.6 Vital signs across the life span ──────────────────────────────── 10
base({id:'itm-9.6.001',type:'mc',chapter:9,block:'9.6',objective:'obj-9.6.a',bloom:'understand',high_stakes:true,
 stem:'A child’s heart rate is inside the normal range for their age. What does that establish?',
 options:[opt('a','Less than it appears — the ranges come from awake, healthy children at rest, and a rate inside them can still be abnormal for this child',true,'One finding, weighed with everything else.'),
  opt('b','That the child is not seriously ill',false,'A rate inside range is entirely compatible with serious illness.'),
  opt('c','That perfusion is adequate',false,'Rate says nothing directly about perfusion.'),
  opt('d','That no further assessment of the circulation is needed',false,'It is the start of that assessment, not the end.')],
 explanation_md:'The centiles describe healthy children at rest. A frightened, feverish or crying child is neither, and a number inside the range in a child who looks unwell is a reason to look harder.',source_ref:FLEM}),
base({id:'itm-9.6.002',type:'options_box',chapter:9,block:'9.6',objective:'obj-9.6.a',high_stakes:true,
 stem:'Classify each heart rate for a 2-year-old at rest. Normal range 92–128; 1st centile 76; 99th centile 142.',
 columns:[{id:'low',label:'Below the normal range'},{id:'norm',label:'Within the normal range'},{id:'high',label:'Above the normal range'}],
 rows:[{id:'r1',label:'70',answer:'low'},
  {id:'r2',label:'110',answer:'norm'},
  {id:'r3',label:'135',answer:'high'},
  {id:'r4',label:'190',answer:'high'}],
 options:[],
 explanation_md:'135 sits above the 90th centile but below the 99th — abnormal-ish, and explainable by crying or fever. 190 is far beyond the 99th centile of 142 and needs a cause.',source_ref:FLEM}),
base({id:'itm-9.6.003',type:'drag_drop',chapter:9,block:'9.6',objective:'obj-9.6.a',high_stakes:true,
 stem:'Match each age to its normal resting heart rate range.',
 categories:[{id:'a',label:'123–164'},{id:'b',label:'98–135'},{id:'c',label:'74–111'},{id:'d',label:'58–92'}],
 options:[opt('o1','0 to 3 months',true,'The highest range of childhood, 123 to 164.'),
  opt('o2','18 to 24 months',true,'98 to 135.'),
  opt('o3','6 to 8 years',true,'74 to 111.'),
  opt('o4','15 to 18 years',true,'58 to 92, approaching adult values.')],
 answer_map:{o1:'a',o2:'b',o3:'c',o4:'d'},
 explanation_md:'Heart rate falls steadily from infancy to adolescence. You do not need every band memorized — you need to know roughly where the patient in front of you should sit.',source_ref:FLEM}),
base({id:'itm-9.6.004',type:'mc',chapter:9,block:'9.6',objective:'obj-9.6.a',bloom:'remember',high_stakes:true,
 stem:'What systolic pressure defines hypotension in a 6-year-old?',
 options:[opt('a','Below 82 mmHg — 70 plus twice the age in years',true,'70 + (2 × 6) = 82.'),
  opt('b','Below 70 mmHg',false,'That is the threshold for an infant aged 1 to 12 months.'),
  opt('c','Below 90 mmHg',false,'That applies over 10 years of age.'),
  opt('d','Below 60 mmHg',false,'That is the term neonate threshold.')],
 explanation_md:'Four thresholds: under 60 for a term neonate, under 70 for an infant, 70 + twice the age for 1 to 10 years, under 90 over 10. The formula is the one worth knowing cold.',source_ref:PALS}),
base({id:'itm-9.6.005',type:'mr',chapter:9,block:'9.6',objective:'obj-9.6.a',select_count:[3,4],
 stem:'Select what is true about the pediatric rate ranges you are using.',
 options:[opt('a','They describe awake, healthy children at rest',true,'Which most of your patients are not.'),
  opt('b','A number inside the range can still be abnormal for that child',true,'Stated explicitly in the source.'),
  opt('c','A number outside the range may have an innocent explanation — crying, fever, fear, pain',true,'Context decides what the number means.'),
  opt('d','The respiratory rate ranges rest on far less data than the heart rate ranges',true,'A few thousand children against well over a hundred thousand.'),
  opt('e','They are diagnostic thresholds',false,'They are reference centiles, and that is a different thing.')],
 explanation_md:'Reference ranges describe a population. They do not diagnose the individual in front of you, and using them as if they did is the error this block is written against.',source_ref:FLEM}),
base({id:'itm-9.6.006',type:'build_list',chapter:9,block:'9.6',objective:'obj-9.6.a',bloom:'remember',
 stem:'Put these ages in order of normal resting heart rate, highest first.',
 options:[opt('a','0 to 3 months',true,'The highest of these, 123 to 164.'),
  opt('b','12 to 18 months',true,'103 to 140.'),
  opt('c','3 to 4 years',true,'86 to 123.'),
  opt('d','8 to 12 years',true,'67 to 103.'),
  opt('e','15 to 18 years',true,'58 to 92, the lowest of these.')],
 explanation_md:'The direction is the part to internalize: heart rate and respiratory rate both fall steadily with age, and neither jumps at any particular birthday.',source_ref:FLEM}),
base({id:'itm-9.6.007',type:'mc',chapter:9,block:'9.6',objective:'obj-9.6.a',bloom:'analyze',
 stem:'Why should the respiratory rate ranges be quoted with more caution than the heart rate ranges?',
 options:[opt('a','They come from a far smaller pool of children — a few thousand against well over a hundred thousand',true,'Same systematic review, much weaker half.'),
  opt('b','Respiratory rate is not clinically useful',false,'It is one of the most useful signs there is.'),
  opt('c','They were derived from unwell children',false,'Both arms describe healthy children.'),
  opt('d','They come from a different, unrelated study',false,'They come from the same review.')],
 explanation_md:'This is the habit from 1.6 applied to your own reference card: know what the number rests on before you treat it as settled.',source_ref:FLEM}),
base({id:'itm-9.6.008',type:'mc',chapter:9,block:'9.6',objective:'obj-9.6.a',bloom:'remember',
 stem:'What happens to heart rate and respiratory rate as a child grows?',
 options:[opt('a','Both fall steadily from infancy to adolescence',true,'Steadily and without sharp steps.'),
  opt('b','Both rise steadily',false,'The opposite.'),
  opt('c','Heart rate falls while respiratory rate rises',false,'Both fall.'),
  opt('d','Both stay stable until puberty',false,'They change continuously from birth.')],
 explanation_md:'Which is why the bands in any table are a convenience. A child does not change physiology on a birthday, and a value at the edge of a band should be read that way.',source_ref:FLEM}),
base({id:'itm-9.6.009',type:'mc',chapter:9,block:'9.6',objective:'obj-9.6.a',high_stakes:true,bloom:'analyze',
 stem:'A distressed nine-month-old has a heart rate of 190 that falls to 100 over a few minutes, with no treatment given. How do you read that?',
 options:[opt('a','As deterioration until proved otherwise — a falling rate in a tiring infant usually precedes arrest',true,'100 is inside the normal band and this is the most dangerous number on the call.'),
  opt('b','As improvement, since the rate is now within the normal range',false,'This is the misreading the block exists to prevent.'),
  opt('c','As an artifact of the monitor',false,'Confirm it, and do not assume it.'),
  opt('d','As a normal response to being comforted',false,'Not over that range, in an infant who is tiring.')],
 explanation_md:'Bradycardia in a hypoxic infant is a pre-arrest sign. The number moving into the normal range is exactly what makes it easy to miss.',source_ref:PALS}),
base({id:'itm-9.6.010',type:'options_box',chapter:9,block:'9.6',objective:'obj-9.6.a',bloom:'analyze',
 stem:'Classify each respiratory rate. Normal ranges: 0–3 months 34–57; 2–3 years 22–34; 8–12 years 16–22.',
 columns:[{id:'low',label:'Below range'},{id:'norm',label:'Within range'},{id:'high',label:'Above range'}],
 rows:[{id:'r1',label:'A 2-month-old at 40',answer:'norm'},
  {id:'r2',label:'A 2-year-old at 44',answer:'high'},
  {id:'r3',label:'A 10-year-old at 18',answer:'norm'},
  {id:'r4',label:'A 10-year-old at 34',answer:'high'}],
 options:[],
 explanation_md:'A rate of 40 is unremarkable in a two-month-old and would be alarming in a ten-year-old. The number alone means nothing without the age beside it.',source_ref:FLEM}),

// ── 9.7 Psychosocial development ──────────────────────────────────────── 8
base({id:'itm-9.7.001',type:'mc',chapter:9,block:'9.7',objective:'obj-9.7.a',bloom:'understand',
 stem:'What is the honest status of the psychosocial stage models you will be taught?',
 options:[opt('a','Useful vocabulary for reactions you will meet; not validated as a fixed sequence everyone passes through',true,'The same caution the five stages of grief needed in chapter 2.'),
  opt('b','Experimentally verified and predictive for individuals',false,'They are theoretical frameworks, not validated predictive models.'),
  opt('c','Discredited and of no use',false,'They describe real patterns usefully; the claim to be a fixed sequence is what does not hold.'),
  opt('d','Legally binding on how you assess capacity',false,'Capacity is assessed as chapter 3 described, not from a stage.')],
 explanation_md:'Use the stages to anticipate what a patient may be frightened of. Do not use them to predict what an individual must be feeling, or to decide they are behaving wrongly.',source_ref:DEV}),
base({id:'itm-9.7.002',type:'drag_drop',chapter:9,block:'9.7',objective:'obj-9.7.a',bloom:'remember',
 stem:'Match each developmental concern to the age it is usually described in.',
 categories:[{id:'inf',label:'Infancy'},{id:'tod',label:'Toddler'},{id:'ado',label:'Adolescence'},{id:'late',label:'Late adulthood'}],
 options:[opt('a','Trust built through consistent caregiving',true,'The first year, in the usual description.'),
  opt('b','Autonomy, and objecting to being controlled',true,'The toddler years, and it explains most of the resistance you meet.'),
  opt('c','Identity and independence',true,'Adolescence.'),
  opt('d','Reviewing a life and finding it coherent',true,'Late adulthood.')],
 answer_map:{a:'inf',b:'tod',c:'ado',d:'late'},
 explanation_md:'Worth knowing because each one tells you what the patient is defending. A toddler resisting you is defending autonomy, not being difficult.',source_ref:DEV}),
base({id:'itm-9.7.003',type:'mc',chapter:9,block:'9.7',objective:'obj-9.7.a',bloom:'understand',high_stakes:true,
 stem:'A five-year-old who was toilet trained starts wetting the bed after a serious illness in the family. What is this?',
 options:[opt('a','Regression — a common and usually temporary response to stress at this age',true,'It is a stress response, not a behavioral problem or a new illness.'),
  opt('b','A new neurological problem requiring urgent investigation',false,'It would be an unusual presentation for one.'),
  opt('c','Deliberate misbehavior',false,'It is not volitional in any useful sense.'),
  opt('d','Evidence of neglect',false,'Not on this information, and assuming so does harm.')],
 explanation_md:'Recognizing regression matters because the alternative readings both lead somewhere damaging: an unnecessary workup, or an accusation.',source_ref:DEV}),
base({id:'itm-9.7.004',type:'options_box',chapter:9,block:'9.7',objective:'obj-9.7.a',bloom:'analyze',
 stem:'Is this behavior developmentally expected in the circumstances?',
 columns:[{id:'exp',label:'Expected'},{id:'con',label:'Concerning'}],
 rows:[{id:'r1',label:'An 8-month-old distressed by a stranger approaching',answer:'exp'},
  {id:'r2',label:'A 3-year-old insisting on doing everything themselves',answer:'exp'},
  {id:'r3',label:'A 7-year-old showing no reaction to a painful injury',answer:'con'},
  {id:'r4',label:'A 15-year-old refusing to undress in front of their father',answer:'exp'}],
 options:[],
 explanation_md:'Stranger anxiety from around six months, toddler autonomy, and adolescent modesty are all development. Absent reaction to pain is the one that is not.',source_ref:DEV}),
base({id:'itm-9.7.005',type:'mc',chapter:9,block:'9.7',objective:'obj-9.7.a',bloom:'analyze',
 stem:'Why does a stage model become harmful when treated as a schedule rather than a vocabulary?',
 options:[opt('a','It turns ordinary variation into a deficiency, and invites you to decide what a patient must be feeling',true,'Exactly what went wrong with the five stages of grief in chapter 2.'),
  opt('b','Because the stages are in the wrong order',false,'Order is not the problem.'),
  opt('c','Because it takes too long to apply',false,'Not the objection.'),
  opt('d','Because it only applies to children',false,'The models cover the whole life span.')],
 explanation_md:'The same failure, twice in one series: a useful description of common patterns, taken as a rule about individuals, stops you seeing the person in front of you.',source_ref:DEV}),
base({id:'itm-9.7.006',type:'mc',chapter:9,block:'9.7',objective:'obj-9.7.a',
 stem:'From roughly what age does an unfamiliar face reliably distress an infant?',
 options:[opt('a','Around six months, and it intensifies over the following months',true,'Which is precisely when you start needing the parent in contact.'),
  opt('b','From birth',false,'Newborns do not discriminate strangers that way.'),
  opt('c','From about two years',false,'It is well established before then.'),
  opt('d','It does not occur in infancy',false,'It is one of the defining features of the second half of the first year.')],
 explanation_md:'Below six months you can usually examine an infant anywhere. After it, the examination happens on the parent or it does not happen well.',source_ref:DEV}),
base({id:'itm-9.7.007',type:'mc',chapter:9,block:'9.7',objective:'obj-9.7.a',
 stem:'An older adult keeps returning to stories about their working life while you assess them. How should you treat that?',
 options:[opt('a','As ordinary life review, and as a way in — let it run briefly while you work',true,'It is not confusion, and fighting it costs more time than allowing it.'),
  opt('b','As evidence of cognitive impairment',false,'Reminiscence is not impairment.'),
  opt('c','As avoidance of the medical question',false,'Rarely, and it is not the first reading.'),
  opt('d','As a reason to direct questions to a relative',false,'They are answering you; the content is just not what you asked for.')],
 explanation_md:'Assess while they talk. Interrupting to get back on script usually loses more time than it saves, and it costs the rapport you need for the difficult parts.',source_ref:DEV}),
base({id:'itm-9.7.008',type:'mc',chapter:9,block:'9.7',objective:'obj-9.7.a',bloom:'analyze',
 stem:'How should development change what you actually do, as distinct from what you know?',
 options:[opt('a','It changes the approach — who is present, what order you examine in, what you explain and to whom',true,'The physiology changes the treatment; the development changes the approach.'),
  opt('b','It changes the drug doses only',false,'Weight and physiology drive dosing, not psychosocial stage.'),
  opt('c','It changes nothing operationally',false,'It changes almost everything about how the call runs.'),
  opt('d','It determines the destination',false,'Capability and protocol do that.')],
 explanation_md:'That distinction is the whole chapter. Physiology tells you what to do; development tells you how to get near enough to do it.',source_ref:STD}),
// ── 9.8 Approach across the life span ─────────────────────────────────── 8
base({id:'itm-9.8.001',type:'mc',chapter:9,block:'9.8',objective:'obj-9.8.a',bloom:'understand',
 stem:'Which part of your assessment changes most across the life span?',
 options:[opt('a','The approach — order, position, who is present, and who you address',true,'The findings you are looking for change far less than how you get at them.'),
  opt('b','The conditions you are looking for',false,'They vary by age and that is not the largest change in what you do.'),
  opt('c','The equipment carried',false,'Sizes change; the approach changes more.'),
  opt('d','Nothing — assessment is standardized',false,'A standardized approach fails at both ends of the life span.')],
 explanation_md:'A rigid head-to-toe sequence delivered identically to a three-year-old and an eighty-year-old will fail with both, for opposite reasons.',source_ref:STD}),
base({id:'itm-9.8.002',type:'drag_drop',chapter:9,block:'9.8',objective:'obj-9.8.a',high_stakes:true,
 stem:'Match each adaptation to the patient it is for.',
 categories:[{id:'inf',label:'Infant'},{id:'pre',label:'Preschool child'},{id:'ado',label:'Adolescent'},{id:'old',label:'Older adult'}],
 options:[opt('a','Pad under the shoulders to keep the airway neutral',true,'The large occiput flexes the neck when supine.'),
  opt('b','Examine toe to head, on the parent’s lap',true,'Keeps the frightening part until last.'),
  opt('c','Create a private moment away from family before the sensitive questions',true,'Routine, not suspicion-driven.'),
  opt('d','Establish the baseline before interpreting any mental status',true,'Confusion only means something against what is usual for them.')],
 answer_map:{a:'inf',b:'pre',c:'ado',d:'old'},
 explanation_md:'Four patients, four different first moves, none of which is in the standard sequence. That is what age-appropriate assessment means in practice.',source_ref:STD}),
base({id:'itm-9.8.003',type:'mr',chapter:9,block:'9.8',objective:'obj-9.8.a',bloom:'remember',select_count:[3,4],
 stem:'Select what should change when the patient is an older adult living alone.',
 options:[opt('a','Ask what they are normally like, from someone who knows',true,'The baseline question, and it needs a source.'),
  opt('b','Look at the home — food, heating, stairs, whether the medications have been taken',true,'The scene is clinical information on these calls.'),
  opt('c','Bring the medications or photograph the labels',true,'Polypharmacy may be the reason for the call.'),
  opt('d','Consider whether going back alone is safe, and say so if it is not',true,'The disposition is part of the assessment, not an afterthought.'),
  opt('e','Assume a reduced level of care is appropriate because of age',false,'Age is not a reason to assess or treat less.')],
 explanation_md:'On a geriatric call the house tells you things the patient will not. Cold rooms, untouched food and a full pill organizer are all findings.',source_ref:STD}),
base({id:'itm-9.8.004',type:'options_box',chapter:9,block:'9.8',objective:'obj-9.8.a',bloom:'analyze',
 stem:'Who should you be addressing?',
 columns:[{id:'pt',label:'The patient'},{id:'both',label:'Patient and caregiver together'}],
 rows:[{id:'r1',label:'A 15-year-old with abdominal pain',answer:'pt'},
  {id:'r2',label:'An 8-month-old with a fever',answer:'both'},
  {id:'r3',label:'An 88-year-old with hearing loss and a daughter present',answer:'pt'},
  {id:'r4',label:'A 3-year-old with a laceration',answer:'both'}],
 options:[],
 explanation_md:'Hearing loss is not a reason to talk past someone to their daughter. Face them, quieten the room, and address the patient — chapter 4 covered how.',source_ref:STD}),
base({id:'itm-9.8.005',type:'mc',chapter:9,block:'9.8',objective:'obj-9.8.a',high_stakes:true,
 stem:'Who consents for a 14-year-old brought in by a school coach after a collision?',
 options:[opt('a','Generally a parent or guardian — treat the emergency meanwhile, and check your state’s rules, which vary',true,'Emergency care is not withheld while you find a parent, and the consent rules are state law.'),
  opt('b','The coach, as the responsible adult present',false,'Not unless a specific arrangement exists in writing.'),
  opt('c','The patient, in all circumstances',false,'Minor consent provisions vary and are not a general rule.'),
  opt('d','Nobody — care must wait',false,'That is never the answer to an emergency.')],
 explanation_md:'Chapter 3 covered the framework and said the ages are state law. This is the same answer arriving on a call, and the local layer is where the age goes.',source_ref:STD}),
base({id:'itm-9.8.006',type:'mc',chapter:9,block:'9.8',objective:'obj-9.8.a',bloom:'analyze',
 stem:'Why is a single standardized assessment sequence a poor fit at both ends of the life span?',
 options:[opt('a','At one end it destroys cooperation before you start; at the other it misses findings that only appear against a baseline',true,'Two different failures, same rigid sequence.'),
  opt('b','Because the sequence is too long',false,'Length is not the issue.'),
  opt('c','Because equipment sizes differ',false,'True and not what breaks the sequence.'),
  opt('d','Because older patients refuse examination more often',false,'Not generally so.')],
 explanation_md:'The sequence is a default for a cooperative adult with no baseline problem. Neither end of this chapter is that patient.',source_ref:STD}),
base({id:'itm-9.8.007',type:'mc',chapter:9,block:'9.8',objective:'obj-9.8.a',
 stem:'A caregiver answers every question for a competent older adult. What do you do?',
 options:[opt('a','Thank them, then put the questions back to the patient directly',true,'Politely, and every time, because the patient is the source.'),
  opt('b','Accept it — the caregiver knows the history better',false,'They know some of it; the patient owns all of it.'),
  opt('c','Ask the caregiver to leave',false,'Heavy-handed, and you lose corroboration you want.'),
  opt('d','Record the history as reported by the caregiver only',false,'It makes the chart less useful and the patient invisible.')],
 explanation_md:'"I want to hear it from him, then I will come to you." It takes one sentence and it changes who the assessment is actually of.',source_ref:STD}),
base({id:'itm-9.8.008',type:'mc',chapter:9,block:'9.8',objective:'obj-9.8.a',bloom:'analyze',
 stem:'What is the single most useful habit this chapter asks for?',
 options:[opt('a','Asking what is normal for this patient before deciding what is abnormal',true,'It works for the infant’s feeding, the child’s behavior and the older adult’s mental status alike.'),
  opt('b','Memorizing every vital sign range',false,'Useful, and it does not carry the whole chapter.'),
  opt('c','Applying the same sequence to everyone for consistency',false,'The opposite of what the chapter argues.'),
  opt('d','Deferring to the family on all questions',false,'They corroborate; they do not replace the patient.')],
 explanation_md:'Every high-yield question in this chapter is a version of the same one. Is this how they usually are? Is this how they usually feed, behave, walk, think?',source_ref:STD}),

// ── 9.INT Integration ─────────────────────────────────────────────────── 9
base({id:'itm-9.INT.000',type:'scenario',chapter:9,block:'9.INT',objective:'obj-9.INT.a',
 stimulus:{kind:'scenario',ref:null,
  text:'One shift, two calls.\n\n**0910.** A 9-month-old, unwell for two days. She is irritable in her mother’s arms, has fed poorly since yesterday and has had two wet diapers in twenty-four hours. Respiratory rate 62 with subcostal recession, heart rate 188, temperature 38.9°C. The anterior fontanelle is sunken. Twenty minutes later, undisturbed, her heart rate is 104 and she has stopped crying.\n\n**1640.** An 84-year-old man, found on the kitchen floor by his daughter, who visits weekly. He is oriented to name only. She says he was "completely sharp" last Sunday. He takes nine regular medications, none of which she can name. Blood pressure 118/70, heart rate 96, temperature 37.8°C. He does not remember falling. The kitchen is cold and there is uneaten food on the counter.'},
 children:['itm-9.INT.001','itm-9.INT.002','itm-9.INT.003','itm-9.INT.004',
  'itm-9.INT.005','itm-9.INT.006','itm-9.INT.007','itm-9.INT.008'],
 stem:'',options:[],explanation_md:'',source_ref:STD}),
base({id:'itm-9.INT.001',type:'mc',chapter:9,block:'9.INT',objective:'obj-9.INT.a',parent:'itm-9.INT.000',high_stakes:true,
 stem:'The infant’s heart rate falls from 188 to 104 with no treatment. What is that?',
 options:[opt('a','Deterioration until proved otherwise — a falling rate in a tiring infant precedes arrest',true,'104 is inside the normal band of 109 to 145 only by falling through it.'),
  opt('b','Improvement, since 104 is close to normal for her age',false,'This is the misreading the block was written against.'),
  opt('c','A normal response to being comforted',false,'Not across that range, in an infant working this hard.'),
  opt('d','Evidence the fever has broken',false,'Nothing here indicates that.')],
 explanation_md:'She was at 188 because she was compensating. She is at 104 because she is running out of the ability to. The number looks better and the child is worse.',source_ref:PALS}),
base({id:'itm-9.INT.002',type:'mr',chapter:9,block:'9.INT',objective:'obj-9.INT.a',parent:'itm-9.INT.000',select_count:[4,5],
 stem:'Which findings in the infant point to significant illness?',
 options:[opt('a','Respiratory rate 62 against a normal range of 30 to 50 for her age',true,'Above the 99th centile of 58.'),
  opt('b','Subcostal recession',true,'Work of breathing, not just rate.'),
  opt('c','Poor feeding since yesterday',true,'How an infant reports exhaustion.'),
  opt('d','Two wet diapers in twenty-four hours',true,'Reduced output — a dehydration finding she cannot report any other way.'),
  opt('e','Irritability in her mother’s arms',false,'Consolable irritability in a febrile infant is expected; inconsolability would not be.')],
 explanation_md:'Rate, effort, feeding and output. The fontanelle adds a fifth. None of these needed a monitor.',source_ref:FLEM}),
base({id:'itm-9.INT.003',type:'mc',chapter:9,block:'9.INT',objective:'obj-9.INT.a',parent:'itm-9.INT.000',
 stem:'What does the sunken anterior fontanelle add?',
 options:[opt('a','Support for significant dehydration, consistent with the poor feeding and reduced wet diapers',true,'Three findings pointing the same way.'),
  opt('b','Evidence of raised intracranial pressure',false,'A bulging fontanelle would suggest that; a sunken one is the opposite.'),
  opt('c','Nothing — it should be closed by nine months',false,'The anterior fontanelle closes between roughly nine and eighteen months, and is commonly still open.'),
  opt('d','Evidence of head injury',false,'Not on this presentation.')],
 explanation_md:'Sunken points to volume depletion, bulging to pressure. Assess it in a quiet infant, because crying will mislead you in one direction.',source_ref:STD}),
base({id:'itm-9.INT.004',type:'mc',chapter:9,block:'9.INT',objective:'obj-9.INT.a',parent:'itm-9.INT.000',high_stakes:true,
 stem:'What is the single most useful question to ask the daughter about her father?',
 options:[opt('a','What he is normally like — she has already answered it, and "completely sharp last Sunday" makes this acute',true,'Oriented to name only, from sharp, in a week. That is a change, not a baseline.'),
  opt('b','Whether he has dementia',false,'Part of the baseline question, and it does not replace it.'),
  opt('c','How often she visits',false,'Useful context, not the key question.'),
  opt('d','Whether he has fallen before',false,'Relevant, and secondary to whether this is new.')],
 explanation_md:'Without the baseline, "oriented to name only" is just a number on a chart. With it, this is an acute change over days and the call is a different one entirely.',source_ref:STD}),
base({id:'itm-9.INT.005',type:'mr',chapter:9,block:'9.INT',objective:'obj-9.INT.a',parent:'itm-9.INT.000',select_count:[4,5],
 stem:'What in the second call needs explaining rather than attributing to age?',
 options:[opt('a','New confusion over about a week',true,'Never normal aging, at any age.'),
  opt('b','A fall he cannot remember',true,'The question is what happened immediately before it.'),
  opt('c','Nine medications nobody can name',true,'An adverse drug effect can be the whole presentation.'),
  opt('d','A temperature of 37.8°C in an older adult',true,'A modest rise can accompany significant infection at this age.'),
  opt('e','Gradual hearing loss over several years',false,'That one genuinely is expected.')],
 explanation_md:'Four findings, each of which could be the cause and any of which could be missed by writing "confused, elderly" and moving on.',source_ref:STD}),
base({id:'itm-9.INT.006',type:'mc',chapter:9,block:'9.INT',objective:'obj-9.INT.a',parent:'itm-9.INT.000',high_stakes:true,
 stem:'His blood pressure is 118/70. Why is that not reassuring on its own?',
 options:[opt('a','It may be low for him — a patient who usually runs at 170 can be significantly hypotensive at 118',true,'Relative hypotension is invisible unless you ask what is usual.'),
  opt('b','118 systolic is hypotensive at any age',false,'It is not, in absolute terms.'),
  opt('c','Blood pressure is unreliable in older patients',false,'The measurement is fine; the interpretation needs a baseline.'),
  opt('d','It is reassuring — no further thought is needed',false,'That is the conclusion this item exists to prevent.')],
 explanation_md:'Ask the daughter, or look for a reading in the house. The same question as the mental status: what is normal for this person?',source_ref:STD}),
base({id:'itm-9.INT.007',type:'mc',chapter:9,block:'9.INT',objective:'obj-9.INT.a',parent:'itm-9.INT.000',
 stem:'What should you do about the medications and the state of the kitchen?',
 options:[opt('a','Bring the medications or photograph the labels, and report the cold room and uneaten food as findings',true,'Both are clinical information, and only you will see them.'),
  opt('b','Leave the medications — the hospital will have a list',false,'Their list may be out of date and will not show what he has actually been taking.'),
  opt('c','Note the kitchen only if abuse is suspected',false,'It is relevant to this illness regardless.'),
  opt('d','Neither is EMS business',false,'Nobody else on the pathway will ever see that room.')],
 explanation_md:'The house is the part of the assessment that exists only while you are standing in it. Write what you saw, not an impression of it.',source_ref:STD}),
base({id:'itm-9.INT.008',type:'mc',chapter:9,block:'9.INT',objective:'obj-9.INT.a',parent:'itm-9.INT.000',bloom:'analyze',
 stem:'What do these two calls have in common?',
 options:[opt('a','In both, the most dangerous finding was a number that looked acceptable in isolation',true,'A heart rate of 104 and a pressure of 118 over 70.'),
  opt('b','Both patients had an infection',false,'Possible in both, and not what links them.'),
  opt('c','Both needed the same treatment',false,'They needed very different treatment.'),
  opt('d','In both, the vital signs were clearly abnormal',false,'The critical ones read as normal, which is the point.')],
 explanation_md:'Both numbers were only interpretable against something else: the direction it came from, and what is usual for this person. That is the chapter, twice, in one shift.',source_ref:FLEM}),
];

export const blocks=[
{id:'9.1',chapter:9,title:'Infancy',learner_title:'The first year',
 objectives:['obj-9.1.a'],est_minutes:7,
 cold_open:{text:'You lay a six-month-old flat on the cot to get a better look at her, and her breathing immediately sounds worse. Nothing has changed except the surface she is on, and your partner is already reaching for the airway bag.',
  decision_point:'What did you just do?'},
 pretest_item:'itm-9.1.001',
 screens:[
  {id:'scr-9.1.1',body_md:'**An infant is not a small adult**, and the differences are mostly mechanical.\n\nThe head is proportionally large, so lying flat flexes the neck and closes the airway. The fix is a folded towel under the *shoulders*, not under the head — and it is the first thing to try when an infant’s breathing worsens on a flat surface.',figure:null},
  {id:'scr-9.1.2',body_md:'**The rest of the airway is working against you too.** A large tongue in a small mouth, narrow passages where a little swelling costs a lot of flow, and a strong preference for breathing through the nose.\n\nTaught as "obligate nasal breathers", which overstates it — most infants can breathe orally. But a blocked nose is poorly tolerated, so suction it.',figure:null},
  {id:'scr-9.1.3',body_md:'**Infants lose heat fast**: large surface area against small mass, thin skin, and little capacity to shiver.\n\nA cold infant deteriorates, and the cooling frequently happens during your assessment, in a draughty room with the doors open and the clothes off. Cover the head, close the doors, warm the compartment.\n\nAnd check the temperature rather than assuming it. A cold infant is easy to miss in a warm room and obvious in the numbers.',figure:null},
  {id:'scr-9.1.4',body_md:'**Compensation runs on rate, not depth.** The chest wall is compliant and the diaphragm does the work, so an infant in trouble breathes faster rather than deeper.\n\nThat is tiring. A rising rate is the warning; a rate that suddenly falls in a tiring infant is not recovery, and 9.6 comes back to exactly that.',figure:null},
  {id:'scr-9.1.5',body_md:'**Two questions get you a history from someone with no words.** How has she been feeding? How many wet diapers?\n\nFeeding is strenuous, so an infant too tired to feed is too tired to keep breathing like this. Wet diapers are urine output. Both turn "seems off" into something you can write down and hand over.',figure:null}],
 inline_checks:['itm-9.1.002','itm-9.1.006'],
 quiz:['itm-9.1.003','itm-9.1.004','itm-9.1.005','itm-9.1.007','itm-9.1.008'],
 callback_md:'You closed her airway. The occiput is large enough that a flat surface flexes the neck, and the sound changed the moment she went down.\n\n**Pad under the shoulders, not the head.** It takes a folded towel and about four seconds, and it comes before the airway bag — which is the point of knowing this rather than reaching for equipment.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'9.2',chapter:9,title:'Toddler and preschool',learner_title:'The age that says no',
 objectives:['obj-9.2.a'],est_minutes:7,
 cold_open:{text:'A two-year-old with a fever. He watches you cross the room, screams when you get within a meter, and clamps onto his mother. Your usual sequence starts at the head, and you are not getting anywhere near it.',
  decision_point:'Where do you start instead?'},
 pretest_item:'itm-9.2.001',
 screens:[
  {id:'scr-9.2.1',body_md:'**Reverse the sequence.** Toe to head, on the parent’s lap, with the frightening parts last.\n\nGet to eye level — height is intimidating at that size. Let them hold the stethoscope first. Listen to the parent’s chest before theirs. Every one of those buys you more examination than insisting does.\n\nNone of it is indulgence. It is the fastest route to a chest you can actually listen to.',figure:null},
  {id:'scr-9.2.2',body_md:'**Autonomy is the developmental drive at this age**, which is why being controlled produces such resistance. Use it: offer real choices. Which arm? Which finger?\n\nOffer only real ones. A choice that is not a choice is worse than none, and "this will not hurt" when it does spends all the credibility you have, permanently.',figure:null},
  {id:'scr-9.2.3',body_md:'**The child who does not object is the one to worry about.** Toddlers are supposed to resist a stranger prodding them.\n\nLying still and letting you do anything is one of the more reliable soft signs of serious illness at this age, and so is being inconsolable by the parent. Both are findings, and neither needs equipment.',figure:null},
  {id:'scr-9.2.4',body_md:'**Watch what they do rather than asking what they feel.** A preverbal child gives a history through behavior: the position they hold, what provokes crying, whether the parent can settle them.\n\nQuiet in mother’s arms and distressed only on movement is a localizing finding. That is a history, and you obtained it without a question.',figure:null},
  {id:'scr-9.2.5',body_md:'**Milestones matter for one reason here.** They let you notice a story that requires a skill the child does not have — a six-week-old who rolled off a couch has not rolled anywhere yet.\n\nMost walk around twelve months, with wide variation. You need enough to recognize an account that cannot be true, and the threshold for reporting is suspicion.\n\nYou are not investigating. You are noticing that the story needs a child who can do something this one cannot yet do.',figure:null}],
 inline_checks:['itm-9.2.005','itm-9.2.007'],
 quiz:['itm-9.2.002','itm-9.2.003','itm-9.2.004','itm-9.2.006','itm-9.2.008'],
 callback_md:'At his feet, on his mother’s lap, with the stethoscope in his hands before it is on his chest.\n\nYou will get most of the examination and lose almost no time. **And note what he is doing while you work** — a two-year-old who screams at you from a meter away is behaving normally. The one who lets you do whatever you like is the one to worry about.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'9.3',chapter:9,title:'School age and adolescence',learner_title:'Who else is in the room',
 objectives:['obj-9.3.a'],est_minutes:8,
 cold_open:{text:'A sixteen-year-old with abdominal pain, answering in single words with her mother two feet away. Everything she has told you so far is true and none of it is the thing that is wrong. Her mother is not going to leave on her own.',
  decision_point:'How do you get the rest of it?'},
 pretest_item:'itm-9.3.001',
 screens:[
  {id:'scr-9.3.1',body_md:'**Create a private moment, and do it every time.** Moving the patient to the ambulance is usually enough: "I ask everyone this on their own."\n\nDoing it routinely is what matters. A private moment created only when you are suspicious announces the suspicion, and the patient hears it before you have asked anything.',figure:null},
  {id:'scr-9.3.2',body_md:'**Say what is confidential before they answer, not after.** Never promise that everything stays between you — the limits vary by state, and a promise you break once means that patient tells no clinician anything again.\n\n"Most of this stays with me. Some things I have to pass on, and I will tell you if we get there."',figure:null},
  {id:'scr-9.3.3',body_md:'**Identity and independence are the work of this age**, so being spoken over, undressed in front of people, or addressed through a parent lands much harder than it would at thirty.\n\nExpose sequentially, narrate first, cover immediately. You lose nothing clinically and keep a cooperative patient for the rest of the call.',figure:null},
  {id:'scr-9.3.4',body_md:'**Peers change the reading.** Risk-taking and reluctance to appear frightened both rise with an audience, so symptoms get minimized and refusals go up in front of friends.\n\nMove the patient away from the audience before the serious conversation. Same maneuver as the private moment from a parent, for a different reason.',figure:null},
  {id:'scr-9.3.5',body_md:'**School-age children detect evasion and trust it less than bad news.** Asked directly whether they are going to die, answer honestly at their level.\n\n"I do not know yet. Here is what I am doing about it, and I will tell you what I find." Changing the subject answers the question, and the answer they hear is yes.',figure:null}],
 inline_checks:['itm-9.3.004','itm-9.3.007'],
 quiz:['itm-9.3.002','itm-9.3.003','itm-9.3.005','itm-9.3.006','itm-9.3.008'],
 callback_md:'You move her to the ambulance, alone, and you say the sentence you say to everybody: "I ask everyone these on their own."\n\nThen you tell her what stays private before you ask, rather than after. **Pregnancy, substance use, self-harm, violence at home** — all of them are systematically not said in front of a parent, and the private moment is the only thing that reliably finds them.\n\n*What must be disclosed, and at what age, is state law. It belongs in the local layer.*',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'9.4',chapter:9,title:'Early and middle adulthood',learner_title:'The decade nothing shows',
 objectives:['obj-9.4.a'],est_minutes:6,
 cold_open:{text:'Forty-six, no medical history, no medications, runs a business and has not seen a doctor in nine years. Chest discomfort for forty minutes, and he has spent thirty-five of them explaining to his wife that he is too young for this.',
  decision_point:'Is he?'},
 pretest_item:'itm-9.4.001',
 screens:[
  {id:'scr-9.4.1',body_md:'**Peak function arrives around the late twenties, and the decline afterward is slow.** Nothing dramatic happens in early or middle adulthood.\n\nWhat happens is accumulation — weight, blood pressure, glucose, lipids — quietly, in people who still feel well and have no reason to think of themselves as patients.\n\nNothing on this list produces a symptom until the day one of them produces an emergency.',figure:null},
  {id:'scr-9.4.2',body_md:'**Good reserve cuts both ways.** A healthy adult compensates efficiently, so vital signs can stay normal until a large amount of reserve is gone.\n\nA normal blood pressure in a young trauma patient buys you nothing. When the numbers finally move in this group, they have usually been compensating for a while.',figure:null},
  {id:'scr-9.4.3',body_md:'**"Too young" is a belief, not a finding.** Middle adulthood is exactly when coronary events start appearing, and the people most likely to reason themselves out of calling are the ones who have never been ill.\n\nNever having been a patient is a risk factor for delay. Agreeing with them is how these calls go wrong.',figure:null},
  {id:'scr-9.4.4',body_md:'**Mid-life patients are frequently responsible for two other generations at once.** That is where refusals in this group come from.\n\n"I cannot leave my mother" is the actual reason, not the stated risk calculation. Treat the obstacle as solvable and work it — a phone call often does what repeating the medical risk will not.\n\nRepeating the risk addresses a problem she does not have. She has understood you perfectly.',figure:null},
  {id:'scr-9.4.5',body_md:'**One line to carry forward into 9.5.** New confusion is not normal aging at forty, at sixty, or at ninety.\n\nReading glasses at forty-five are aging. Slower recovery from effort at fifty is aging. New confusion at any age in this chapter is a finding, and it is the one most often waved away.',figure:null}],
 inline_checks:['itm-9.4.002','itm-9.4.007'],
 quiz:['itm-9.4.003','itm-9.4.004','itm-9.4.005','itm-9.4.006','itm-9.4.008'],
 callback_md:'No. Forty-six with no history is precisely the profile that presents late, because he has no template for being a patient and thirty-five minutes of arguing was him building one.\n\n**His reasoning is a symptom of the epidemiology, not evidence against it.** And his vital signs may look unremarkable for a while yet, which is what good reserve does for you right up until it stops.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'9.5',chapter:9,title:'Late adulthood',learner_title:'When the classic picture does not arrive',
 objectives:['obj-9.5.a'],est_minutes:8,
 cold_open:{text:'Eighty-four, weak for two days, a little short of breath, no chest pain at all. His blood pressure is 118 over 70, which reads as unremarkable, and his daughter says he is "a bit confused, but he is eighty-four".',
  decision_point:'How many things in that sentence are wrong?'},
 pretest_item:'itm-9.5.001',
 screens:[
  {id:'scr-9.5.1',body_md:'**The classic presentations were drawn from younger patients.** In the very old, a myocardial infarction may arrive as dyspnea, weakness, confusion or a fall, with no chest pain whatever.\n\nSo the absence of the textbook symptom carries almost no weight at this age. Atypical is the expectation, not the exception.\n\nSo the question is not whether the picture fits. It is what else could produce weakness in an eighty-four-year-old, and how many of those are dangerous.',figure:null},
  {id:'scr-9.5.2',body_md:'**Four changes do most of the work.** Renal and hepatic clearance fall, so drugs persist. Baroreceptor response blunts, so pressure compensates poorly. Chest wall compliance and cough weaken, so pneumonia presents late. Thirst sensation drops, so dehydration builds silently.\n\nNone is a disease. All shorten the distance to one.',figure:null},
  {id:'scr-9.5.3',body_md:'**The highest-yield question on a geriatric call is about the baseline.** Is this how he usually is?\n\nWithout it, acute delirium and long-standing dementia look identical, and "confused, elderly" gets written in a chart. New confusion over days is an emergency. The same finding for three years is a history.',figure:null},
  {id:'scr-9.5.4',body_md:'**Numbers need the same treatment.** A systolic of 118 in someone who lives at 170 is relative hypotension, and it is invisible unless you ask what their pressure normally runs.\n\nPain is under-reported too — stoicism, not wanting to be a burden, fear of what admission means. Watch the face and the guarding, not only the number.',figure:null},
  {id:'scr-9.5.5',body_md:'**A ground-level fall is two problems.** The injury, which can be significant at low energy, and whatever caused the fall — infection, arrhythmia, drug effect, dehydration.\n\nAsk what happened immediately before. "I do not remember" changes the call. And count the medications: an adverse drug effect can be the entire reason you were called.',figure:null}],
 inline_checks:['itm-9.5.003','itm-9.5.006'],
 quiz:['itm-9.5.002','itm-9.5.004','itm-9.5.005','itm-9.5.007','itm-9.5.008'],
 callback_md:'Three.\n\n**No chest pain** does not lower the probability of a cardiac cause at eighty-four. **118 over 70** may be profoundly low for a man who lives at 170, and you cannot know until you ask. And **"he is eighty-four"** is doing the work of an explanation without being one — new confusion is never normal aging.\n\nThe daughter has handed you the baseline without meaning to: *a bit* confused implies she knows what he is usually like. Ask her.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'9.6',chapter:9,title:'Vital signs across the life span',learner_title:'Numbers by age',
 objectives:['obj-9.6.a'],est_minutes:9,
 cold_open:{text:'A two-year-old, heart rate 190, and nobody on scene can remember whether that is high. Somebody produces a laminated card from a pocket. Somebody else says their card has different numbers on it, and both of them are holding real cards.',
  decision_point:'Which card is right?'},
 pretest_item:'itm-9.6.001',
 evidence_flag:{topic:'Pediatric heart and respiratory rate reference ranges',
  textbook_position:'Age-banded "normal" ranges from resuscitation-course tables and textbooks, presented as settled values to be memorized and applied.',
  current_evidence:'A systematic review pooled 69 studies — heart rate in 143,346 children, respiratory rate in 3,881 — and produced centile charts from measurement rather than convention. It found **striking disagreement** with the reference ranges then in circulation: published limits frequently fell outside the 1st and 99th centiles, and in places crossed the observed median. The centiles in this block are those measured values.',
  uncertainty:'Two things to hold. The respiratory-rate arm rests on a few thousand children against well over a hundred thousand for heart rate, so it is the weaker half of the same paper and should not be quoted with equal confidence. And every value describes **awake, healthy children at rest** — which is not the child in front of you. A number inside the range can still be abnormal for that child, and a number outside it may be fear, fever, pain or crying.',
  source_ref:'Fleming S, Thompson M, Stevens R, et al. Lancet 2011;377:1011–18',
  teach_as:'divergence'},
 screens:[
  {id:'scr-9.6.1',body_md:'**Heart rate and respiratory rate both fall steadily from birth to adolescence.** No step changes, no birthdays where the physiology shifts.\n\nSo the bands in any table are a convenience for printing, not a description of the child. A value sitting at the edge of a band should be read as being at an edge, not as being in or out.',figure:null},
  {id:'scr-9.6.2',body_md:'**Anchors worth carrying, rather than the whole table.**\n\nHeart rate: **0–3 months, 123–164** · **18–24 months, 98–135** · **6–8 years, 74–111** · **15–18 years, 58–92**.\n\nRespiratory rate: **0–3 months, 34–57** · **2–3 years, 22–34** · **8–12 years, 16–22**.\n\nFour and three. Interpolate between them and you will not be far wrong.',figure:null},
  {id:'scr-9.6.3',body_md:'**Blood pressure comes from a different source and is a formula, not a table.**\n\nTerm neonate: systolic under **60**. Infant 1–12 months: under **70**. Child 1–10 years: under **70 + (2 × age in years)**. Over 10 years: under **90**.\n\nSo a 6-year-old is hypotensive below 82. That formula is the thing to know cold.',figure:null},
  {id:'scr-9.6.4',body_md:'**Hypotension in a child is a late sign.** Children compensate by raising heart rate and clamping down peripherally, and they hold a normal pressure until they are close to running out.\n\nWhich means a low blood pressure in a child is not the beginning of shock. It is a long way into it.',figure:null},
  {id:'scr-9.6.5',body_md:'**The dangerous number is the one that looks fine.** A heart rate of 190 in a distressed infant that falls to 104 with no treatment has not improved — it has fallen *through* the normal band because the child is tiring.\n\nBradycardia in a hypoxic infant is a pre-arrest sign, and it reads as a number getting better.',figure:null}],
 inline_checks:['itm-9.6.008','itm-9.6.009'],
 quiz:['itm-9.6.002','itm-9.6.003','itm-9.6.004','itm-9.6.005','itm-9.6.006','itm-9.6.007','itm-9.6.010'],
 callback_md:'Both cards are real, and they disagree because one set of numbers was measured and the other was conventional.\n\nThis block uses the measured centiles. A 2-year-old sits at **92–128**, with a 99th centile of **142** — so 190 is not borderline, it is far outside, and it needs a cause.\n\n**But do not let the card do your thinking.** The ranges describe awake, healthy children at rest, and a number inside them in a child who looks unwell is a reason to look harder rather than to relax.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'9.7',chapter:9,title:'Psychosocial development',learner_title:'What the patient is defending',
 objectives:['obj-9.7.a'],est_minutes:6,
 cold_open:{text:'A five-year-old who has been dry for two years starts wetting the bed, three weeks after his mother was taken to hospital in the night. His father wants to know what is wrong with him, and is braced for the answer.',
  decision_point:'What is wrong with him?'},
 pretest_item:'itm-9.7.001',
 screens:[
  {id:'scr-9.7.1',body_md:'**The stage models are vocabulary, not a schedule.** Trust in infancy, autonomy in the toddler years, identity in adolescence, life review in late adulthood.\n\nThey describe patterns usefully. They are not validated as a fixed sequence everyone passes through — the same caution the five stages of grief needed in chapter 2, and for the same reason.',figure:null},
  {id:'scr-9.7.2',body_md:'**Used properly, they tell you what the patient is defending.** A toddler resisting you is defending autonomy. An adolescent bristling at being spoken over is defending identity. Neither is being difficult.\n\nUsed as a schedule, they turn ordinary variation into a deficiency and invite you to decide what someone must be feeling.',figure:null},
  {id:'scr-9.7.3',body_md:'**Stranger anxiety appears around six months** and intensifies afterward. Below that you can usually examine an infant anywhere; after it, the examination happens on the parent or it does not happen well.\n\nAnd magical thinking at four or five means a child may believe the illness is a punishment. Saying plainly that it is not their fault is a real intervention.',figure:null},
  {id:'scr-9.7.4',body_md:'**Regression under stress is common and usually temporary.** A toilet-trained child who starts wetting the bed after a frightening event is showing a stress response, not a new disease and not misbehavior.\n\nBoth of the alternative readings do harm: an unnecessary workup, or an accusation aimed at a family already under strain.\n\nNaming it correctly is often the most useful thing anybody says to that parent all week.',figure:null},
  {id:'scr-9.7.5',body_md:'**In late adulthood, reminiscence is not impairment.** A patient returning to their working life while you assess them is doing something ordinary, and interrupting to get back on script costs more time than it saves.\n\nAssess while they talk. The physiology tells you what to do; development tells you how to get near enough to do it.',figure:null}],
 inline_checks:['itm-9.7.003','itm-9.7.006'],
 quiz:['itm-9.7.002','itm-9.7.004','itm-9.7.005','itm-9.7.007','itm-9.7.008'],
 callback_md:'Nothing is wrong with him. This is regression — a common, usually temporary response to exactly the kind of stress his household has been under.\n\n**Say that to his father plainly**, because the two readings he is braced for are that his son is ill or that his son is being difficult, and both of those do damage. Tell him what it is, tell him it usually settles, and tell him who to speak to if it does not.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'9.8',chapter:9,title:'Approach across the life span',learner_title:'Changing how, not what',
 objectives:['obj-9.8.a'],est_minutes:7,
 cold_open:{text:'The same standardized head-to-toe, delivered identically to a three-year-old and to an eighty-eight-year-old with hearing loss and a daughter who answers for her. It fails with both, in opposite directions, and in neither case because anybody got the anatomy wrong or missed a step of the sequence.',
  decision_point:'What actually needed to change?'},
 pretest_item:'itm-9.8.001',
 screens:[
  {id:'scr-9.8.1',body_md:'**The findings you look for change far less than how you get at them.** Physiology decides what to do; development decides how to get near enough to do it.\n\nThat distinction is the whole chapter, and it is why the standard sequence is a default for a cooperative adult rather than a method.\n\nChange the order, the position, the audience and who you speak to. Do not change what you are looking for.',figure:null},
  {id:'scr-9.8.2',body_md:'**Four patients, four different first moves.** Infant: pad under the shoulders. Preschool child: start at the feet, on the parent’s lap. Adolescent: create a private moment, as a matter of routine.\n\nOlder adult: establish the baseline before interpreting anything. None of the four is in the standard sequence.\n\nEach takes seconds, and each one decides whether the rest of the assessment is possible at all.',figure:null},
  {id:'scr-9.8.3',body_md:'**Address the patient.** Hearing loss is not a reason to talk past someone to their daughter — face them, quieten the room, and ask them.\n\nWhen a caregiver answers for a competent adult: "I want to hear it from him, then I will come to you." One sentence, and it changes whose assessment this is.',figure:null},
  {id:'scr-9.8.4',body_md:'**On a geriatric call the house is part of the assessment.** Cold rooms, uneaten food, a full pill organizer, stairs that cannot be managed.\n\nNobody else on the pathway will ever see that room. Write what you observed rather than an impression of it, and consider whether going back there alone is safe.',figure:null},
  {id:'scr-9.8.5',body_md:'**Consent moves with age and it is state law.** Who may consent for a minor, at what age, and in what circumstances varies — chapter 3 said so, and it arrives here as a real call.\n\nTreat the emergency while you find a parent. Nobody goes untreated because a phone is not being answered.',figure:null}],
 inline_checks:['itm-9.8.005','itm-9.8.007'],
 quiz:['itm-9.8.002','itm-9.8.003','itm-9.8.004','itm-9.8.006','itm-9.8.008'],
 callback_md:'The order, the position, who was present, and who you addressed.\n\nWith the three-year-old the sequence destroyed cooperation before you started. With the eighty-eight-year-old it collected findings you could not interpret, because you never asked what was normal for her.\n\n**Both failures have the same repair**, and it is the habit this chapter is really asking for: ask what is usual for this patient before deciding what is abnormal.',
 local_overlay:'ks-amr-kc',version:'1.0.0'},

{id:'9.INT',chapter:9,title:'Integration — two calls, one shift',learner_title:'Both ends of the life span',
 objectives:['obj-9.INT.a'],est_minutes:10,
 cold_open:{text:'The two hardest patients in this chapter can turn up on the same shift, seven hours apart, and the template that works for one is actively wrong for the other. Both will hand you a number that looks acceptable, and in both cases that number is the reason to worry.',
  decision_point:'Can you switch between them?'},
 pretest_item:null,
 screens:[
  {id:'scr-9.INT.1',body_md:'**One question, asked twice, in two different forms.**\n\nFor the infant: what is normal for a child this age, and which direction is this one moving? For the older adult: what is normal for *this person*, and how long has it been different?\n\nWhat follows is one shift. In both calls the most dangerous finding reads as unremarkable, and in both the reason is the same.',figure:null}],
 inline_checks:[],
 quiz:['itm-9.INT.000'],
 callback_md:'A heart rate of 104 in a nine-month-old and a blood pressure of 118 over 70 in an eighty-four-year-old. On paper, two unremarkable numbers.\n\nThe first is unremarkable only because it fell *through* the normal band from 188, in an infant who is running out. The second is unremarkable only if he does not normally live at 170 — and nobody has asked.\n\n**Neither number means anything on its own.** One needs a direction, the other needs a baseline, and everything else in this chapter is a way of getting one or the other.',
 local_overlay:'ks-amr-kc',version:'1.0.0'}
];
